use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};
use tera::{Context, Tera};

/// Marker comment emitted at the top of every generated per-crate README so
/// editors and reviewers can see the file is machine-managed.
const GENERATED_MARKER: &str =
    "<!-- AUTO-GENERATED by `cargo xtask gen-docs` — do not edit manually -->";

/// Generate the JSON Schema for `Config` as a pretty-printed JSON string.
fn generate_schema_json() -> Result<String, String> {
    let schema = anodizer_core::config::config_schema();
    serde_json::to_string_pretty(&schema).map_err(|e| format!("cannot serialize schema: {e}"))
}

/// Compare `generated` against `existing` file; record staleness to `stale`.
/// Prints the first differing line and line-count mismatch for debuggability.
fn check_file_freshness(path: &Path, generated: &str, stale: &mut bool) -> Result<(), String> {
    let existing =
        fs::read_to_string(path).map_err(|e| format!("cannot read {}: {e}", path.display()))?;
    if existing != generated {
        eprintln!("STALE: {}", path.display());
        for (i, (a, b)) in existing.lines().zip(generated.lines()).enumerate() {
            if a != b {
                eprintln!("  line {}: committed: {}", i + 1, a);
                eprintln!("  line {}: generated: {}", i + 1, b);
                break;
            }
        }
        if existing.lines().count() != generated.lines().count() {
            eprintln!(
                "  line count: committed={}, generated={}",
                existing.lines().count(),
                generated.lines().count()
            );
        }
        *stale = true;
    }
    Ok(())
}

/// Run doc generation. If `check` is true, compare output against existing files
/// and return an error if they differ.
pub fn run(check: bool) -> Result<(), String> {
    let project_root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|p| p.parent())
        .ok_or("cannot find project root")?;

    let docs_dir = project_root.join("docs/site/content/docs");
    let templates_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("templates");

    // tera 2.0 dropped the glob-loading constructor; loading is a separate
    // step (feature `glob_fs`). No custom filters/functions are used by the
    // xtask templates, so nothing needs registering before the load.
    let mut tera = Tera::default();
    tera.load_from_glob(
        templates_dir
            .join("*.tera")
            .to_str()
            .ok_or("invalid template path")?,
    )
    .map_err(|e| format!("failed to load templates: {e}"))?;
    let tera = tera;

    let cli_content = generate_cli_reference(&tera)?;
    let config_content = generate_config_reference(&tera)?;
    let crate_readmes = generate_per_crate_readmes(project_root, &tera)?;
    let schema_content = generate_schema_json()?;

    let cli_path = docs_dir.join("reference/cli.md");
    let config_path = docs_dir.join("reference/configuration.md");
    let schema_path = project_root.join("docs/site/static/schema.json");

    if check {
        let mut stale = false;
        check_file_freshness(&cli_path, &cli_content, &mut stale)?;
        check_file_freshness(&config_path, &config_content, &mut stale)?;
        check_file_freshness(&schema_path, &schema_content, &mut stale)?;
        for (path, content) in &crate_readmes {
            check_file_freshness(path, content, &mut stale)?;
        }

        if stale {
            return Err("generated docs are out of date — run `cargo xtask gen-docs`".into());
        }
        eprintln!("docs are up to date");
        return Ok(());
    }

    fs::write(&cli_path, &cli_content)
        .map_err(|e| format!("cannot write {}: {e}", cli_path.display()))?;
    eprintln!("wrote {}", cli_path.display());

    fs::write(&config_path, &config_content)
        .map_err(|e| format!("cannot write {}: {e}", config_path.display()))?;
    eprintln!("wrote {}", config_path.display());

    fs::write(&schema_path, &schema_content)
        .map_err(|e| format!("cannot write {}: {e}", schema_path.display()))?;
    eprintln!("wrote {}", schema_path.display());

    for (path, content) in &crate_readmes {
        fs::write(path, content).map_err(|e| format!("cannot write {}: {e}", path.display()))?;
        eprintln!("wrote {}", path.display());
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Per-crate README generation
// ---------------------------------------------------------------------------

/// Walk `crates/*` and produce `(path, content)` pairs for every publishable
/// crate's `README.md`.
///
/// The `anodizer` binary crate (`crates/cli`) reuses the workspace root README
/// verbatim (with a generated-marker prepended) so its crates.io page is the
/// full user-facing landing page. Every other publishable crate gets a brief
/// generated stub rendered from `crate-readme.md.tera` that points users back
/// to the main repository.
///
/// Crates with `publish = false` (e.g. `xtask`) are skipped.
fn generate_per_crate_readmes(
    project_root: &Path,
    tera: &Tera,
) -> Result<Vec<(PathBuf, String)>, String> {
    let crates_dir = project_root.join("crates");
    let workspace_readme = fs::read_to_string(project_root.join("README.md"))
        .map_err(|e| format!("cannot read workspace README.md: {e}"))?;

    let mut entries: Vec<PathBuf> = fs::read_dir(&crates_dir)
        .map_err(|e| format!("cannot read {}: {e}", crates_dir.display()))?
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.is_dir())
        .collect();
    entries.sort();

    let mut out: Vec<(PathBuf, String)> = Vec::with_capacity(entries.len());

    for crate_dir in entries {
        let cargo_toml = crate_dir.join("Cargo.toml");
        if !cargo_toml.exists() {
            continue;
        }

        let manifest_text = fs::read_to_string(&cargo_toml)
            .map_err(|e| format!("cannot read {}: {e}", cargo_toml.display()))?;
        let manifest: toml::Value = toml::from_str(&manifest_text)
            .map_err(|e| format!("cannot parse {}: {e}", cargo_toml.display()))?;

        let pkg = match manifest.get("package").and_then(|p| p.as_table()) {
            Some(p) => p,
            None => continue,
        };

        // Skip crates with publish = false (e.g. xtask).
        if matches!(pkg.get("publish"), Some(toml::Value::Boolean(false))) {
            continue;
        }

        let name = pkg
            .get("name")
            .and_then(|v| v.as_str())
            .ok_or_else(|| format!("{} has no [package].name", cargo_toml.display()))?
            .to_string();
        let description = pkg
            .get("description")
            .and_then(|v| v.as_str())
            .ok_or_else(|| format!("{} has no [package].description", cargo_toml.display()))?
            .to_string();

        let readme_path = crate_dir.join("README.md");
        let content = if name == "anodizer" {
            format!("{GENERATED_MARKER}\n\n{workspace_readme}")
        } else {
            let mut ctx = Context::new();
            ctx.insert("name", &name);
            ctx.insert("description", &description);
            tera.render("crate-readme.md.tera", &ctx)
                .map_err(|e| format!("failed to render crate-readme.md.tera for {name}: {e}"))?
        };

        out.push((readme_path, content));
    }

    Ok(out)
}

#[derive(serde::Serialize)]
struct ArgInfo {
    long: String,
    short: String,
    default: String,
    help: String,
}

#[derive(serde::Serialize)]
struct CmdInfo {
    name: String,
    about: String,
    args: Vec<ArgInfo>,
}

/// Build an `ArgInfo` for a single non-global, visible flag. Emits a warning
/// to stderr when the flag has no help text (caught by `gen-docs --check`).
fn arg_info(a: &clap::Arg, owner_label: &str) -> ArgInfo {
    if a.get_help().is_none() {
        let flag = a.get_long().unwrap_or_else(|| a.get_id().as_str());
        eprintln!("warning: {owner_label}.--{flag} has no help text");
    }
    ArgInfo {
        long: a
            .get_long()
            .map(|l| format!("`--{l}`"))
            .unwrap_or_else(|| format!("`<{}>`", a.get_id())),
        short: a
            .get_short()
            .map(|s| format!("`-{s}`"))
            .unwrap_or_else(|| "\u{2014}".into()),
        default: a
            .get_default_values()
            .first()
            .map(|d| format!("`{}`", d.to_string_lossy()))
            .unwrap_or_else(|| "\u{2014}".into()),
        help: a.get_help().map(|h| h.to_string()).unwrap_or_default(),
    }
}

/// Recursively collect this command and all of its visible subcommands into a
/// flat list of `CmdInfo`. `parent_path` carries the names of ancestors so the
/// rendered `CmdInfo.name` becomes e.g. `"check determinism"` for nested
/// subcommands.
///
/// Hidden args (`Arg::hide(true)`) and hidden subcommands (`Command::hide(true)`)
/// are filtered out so test-harness plumbing like `--simulate-failure` and
/// `--inject-drift` doesn't leak into user-facing docs.
fn collect_command(cmd: &clap::Command, parent_path: &[&str]) -> Vec<CmdInfo> {
    let mut path: Vec<&str> = parent_path.to_vec();
    path.push(cmd.get_name());
    let full_name = path.join(" ");

    let args: Vec<ArgInfo> = cmd
        .get_arguments()
        .filter(|a| {
            !a.is_global_set()
                && a.get_id() != "help"
                && a.get_id() != "version"
                && !a.is_hide_set()
        })
        .map(|a| arg_info(a, &full_name))
        .collect();

    let mut result = vec![CmdInfo {
        name: full_name,
        about: cmd.get_about().map(|a| a.to_string()).unwrap_or_default(),
        args,
    }];

    for sub in cmd.get_subcommands() {
        if sub.is_hide_set() {
            continue;
        }
        result.extend(collect_command(sub, &path));
    }

    result
}

fn generate_cli_reference(tera: &Tera) -> Result<String, String> {
    let cmd = anodizer_cli::build_cli();

    let about = cmd.get_about().map(|a| a.to_string()).unwrap_or_default();

    let global_args: Vec<ArgInfo> = cmd
        .get_arguments()
        .filter(|a| a.is_global_set() && !a.is_hide_set())
        .map(|a| {
            if a.get_help().is_none()
                && let Some(long) = a.get_long()
            {
                eprintln!("warning: global flag --{long} has no help text");
            }
            ArgInfo {
                long: a.get_long().map(|l| format!("`--{l}`")).unwrap_or_default(),
                short: a
                    .get_short()
                    .map(|s| format!("`-{s}`"))
                    .unwrap_or_else(|| "\u{2014}".into()),
                default: "\u{2014}".into(),
                help: a.get_help().map(|h| h.to_string()).unwrap_or_default(),
            }
        })
        .collect();

    let commands: Vec<CmdInfo> = cmd
        .get_subcommands()
        .filter(|s| !s.is_hide_set())
        .flat_map(|sub| collect_command(sub, &[]))
        .collect();

    let mut ctx = Context::new();
    ctx.insert("about", &about);
    ctx.insert("global_args", &global_args);
    ctx.insert("commands", &commands);

    tera.render("cli.md.tera", &ctx)
        .map_err(|e| format!("failed to render cli.md: {e}"))
}

// ---------------------------------------------------------------------------
// Config reference generation — schema-driven
// ---------------------------------------------------------------------------

use serde_json::{Map, Value};

#[derive(serde::Serialize)]
struct ConfigField {
    name: String,
    field_type: String,
    default: String,
    description: String,
}

#[derive(serde::Serialize)]
struct NestedSection {
    name: String,
    /// The heading's explicit anchor attribute, pre-rendered as `{#anchor}`.
    /// Built here rather than in the template because `{#` opens a Tera
    /// comment — the template cannot spell the attribute literally.
    anchor_attr: String,
    description: String,
    fields: Vec<ConfigField>,
}

/// The explicit heading anchor for a section named `name`, emitted as
/// `## `name` {#anchor}`.
///
/// Written into the heading rather than left to zola's slugifier: `zola build`
/// does not validate bare `#fragment` targets, so a generated link that
/// disagreed with the slug would be a dead link nothing reports. Section names
/// carry `[]` and `.` (`crates[].dockers_v2`), which is exactly where a
/// slugifier's rules are easiest to guess wrong.
fn section_anchor(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    for c in name.chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c.to_ascii_lowercase());
        } else if !out.ends_with('-') {
            out.push('-');
        }
    }
    out.trim_matches('-').to_string()
}

/// Map a JSON Schema instance-type keyword to anodizer's human-readable type
/// name as it appears in the config reference (`bool` for `boolean`, `list` for
/// `array`, `map` for `object`).
fn format_instance_type(t: &str) -> String {
    match t {
        "string" => "string".into(),
        "integer" => "integer".into(),
        "number" => "number".into(),
        "boolean" => "bool".into(),
        "array" => "list".into(),
        "object" => "map".into(),
        "null" => "null".into(),
        other => other.into(),
    }
}

/// Format a schema `default` value for markdown (em-dash for absent/null/empty,
/// backtick-wrapped otherwise).
///
/// A composite default too wide to inline links to the section documenting its
/// type instead. `McpConfig`'s default serializes to 239 characters of JSON,
/// which widens the Default column past the point where the Description column
/// is readable — and every byte of it restates the per-field defaults the `mcp`
/// section lists one screen below.
///
/// Width is the whole criterion, so a narrow composite stays literal:
/// `preflight`'s `{"strict":false}` answers the reader's question in place, and
/// replacing it with a link would cost a page jump to learn less. Same for the
/// empty composites `[]` / `{}` — "no entries" is the answer, not a pointer to
/// field defaults that do not apply until the reader adds one.
fn format_default(val: Option<&Value>, section: Option<&str>) -> String {
    match val {
        None | Some(Value::Null) => "\u{2014}".into(),
        Some(Value::String(s)) if s.is_empty() => "\u{2014}".into(),
        Some(Value::String(s)) => format!("`{s}`"),
        Some(v) => {
            let inline = format!("`{v}`");
            match section {
                Some(anchor) if inline.len() > MAX_INLINE_DEFAULT => {
                    format!("[per field](#{anchor})")
                }
                _ => inline,
            }
        }
    }
}

/// Longest Default cell rendered literally before it is replaced by a link to
/// the type's section. Sized against the columns beside it: field names and type
/// names both run to roughly 20 characters, so a default past this width is the
/// column that decides the table's total width, and the Description column pays
/// for it.
const MAX_INLINE_DEFAULT: usize = 48;

/// The definition name a `#/definitions/<Name>` `$ref` string targets.
fn ref_name(reference: &str) -> Option<String> {
    reference
        .strip_prefix("#/definitions/")
        .map(|s| s.to_string())
}

/// The `$ref` string carried directly on a schema object, if any.
fn direct_ref(schema: &Value) -> Option<&str> {
    schema.as_object()?.get("$ref")?.as_str()
}

/// The non-null members of an `anyOf`/`oneOf` subschema list, treating
/// `{ "type": "null" }` as the null variant schemars emits for an `Option<T>`.
fn non_null_variants(variants: &[Value]) -> Vec<&Value> {
    variants
        .iter()
        .filter(|s| {
            !matches!(
                s.as_object().and_then(|o| o.get("type")),
                Some(Value::String(t)) if t == "null"
            )
        })
        .collect()
}

/// Resolve a property schema to a human-readable type name, matching the config
/// reference's vocabulary.
///
/// Handles:
/// - direct `$ref` → definition name;
/// - `anyOf`/`oneOf` (the `Option<T>` pattern: `[T, {"type":"null"}]`) → the
///   single non-null variant's type, or a `T | U` join for a true union;
/// - `allOf` (the `#[serde(default)]`-wrapper pattern) → the first entry's type;
/// - array → `list of <inner>` (or bare `list` when the element type is
///   inexpressible);
/// - a `type` keyword (string or `[T, "null"]` union) → the mapped scalar name.
fn resolve_type_name(prop: &Value, defs: &Map<String, Value>) -> String {
    let Some(obj) = prop.as_object() else {
        return "object".into();
    };

    if let Some(r) = direct_ref(prop) {
        let Some(name) = ref_name(r) else {
            return r.to_string();
        };
        // A `#[serde(transparent)]` newtype over a scalar (e.g. `StringOrU32`
        // wrapping a `u32`) is a named definition that is just a scalar type;
        // inline its underlying type so the field shows `integer` rather than
        // the wrapper's name. Definitions with structure (`properties`, an enum
        // `oneOf`/`anyOf`, …) keep their name and get their own section.
        if let Some(scalar) = defs.get(&name).and_then(scalar_def_type) {
            return scalar;
        }
        return name;
    }

    // Only `anyOf` participates in type naming — it is how an `Option<T>`/
    // nullable field renders (`[T, {"type":"null"}]`), so the field shows `T`.
    // A `oneOf` (e.g. the `"auto"`-or-bool tri-state schemas) has no single
    // representative type and renders as the generic `object`, matching the
    // reference's long-standing treatment of those fields.
    if let Some(Value::Array(variants)) = obj.get("anyOf") {
        let non_null = non_null_variants(variants);
        if let [single] = non_null.as_slice() {
            return resolve_type_name(single, defs);
        }
        let names: Vec<String> = non_null
            .iter()
            .map(|s| resolve_type_name(s, defs))
            .collect();
        if !names.is_empty() {
            return names.join(" | ");
        }
    }

    if let Some(Value::Array(all_of)) = obj.get("allOf")
        && let Some(first) = all_of.first()
    {
        return resolve_type_name(first, defs);
    }

    // `Option<Vec<T>>` renders as `type: ["array", "null"]`, while `Vec<T>`
    // renders as the bare `type: "array"`; both must resolve their `items` type
    // so the field shows `list of <inner>` rather than a bare `list`.
    if schema_has_type(prop, "array") {
        if let Some(item) = array_item(prop) {
            return format!("list of {}", resolve_type_name(item, defs));
        }
        return "list".into();
    }

    match obj.get("type") {
        Some(Value::String(t)) => format_instance_type(t),
        Some(Value::Array(types)) => {
            let non_null: Vec<String> = types
                .iter()
                .filter_map(Value::as_str)
                .filter(|t| *t != "null")
                .map(format_instance_type)
                .collect();
            if non_null.is_empty() {
                "object".into()
            } else {
                non_null.join(" | ")
            }
        }
        _ => "object".into(),
    }
}

/// Whether a schema's `type` keyword names `ty`, accepting both the single form
/// (`"type": "array"`) and the nullable union form (`"type": ["array", "null"]`)
/// schemars emits for an `Option<…>`.
fn schema_has_type(schema: &Value, ty: &str) -> bool {
    match schema.as_object().and_then(|o| o.get("type")) {
        Some(Value::String(t)) => t == ty,
        Some(Value::Array(types)) => types.iter().any(|t| t.as_str() == Some(ty)),
        _ => false,
    }
}

/// The mapped scalar type name of a definition that is a bare scalar — a `type`
/// keyword and nothing structural (`properties`, `oneOf`, `anyOf`, `allOf`,
/// `enum`). `None` for a structured definition (which keeps its own name and
/// section). Underpins inlining a `#[serde(transparent)]` scalar newtype to the
/// type it wraps.
fn scalar_def_type(def: &Value) -> Option<String> {
    let obj = def.as_object()?;
    let structural = ["properties", "oneOf", "anyOf", "allOf", "enum"];
    if structural.iter().any(|k| obj.contains_key(*k)) {
        return None;
    }
    match obj.get("type")?.as_str()? {
        // Only true scalars inline; a map (`object` + `additionalProperties`) or
        // list newtype keeps its definition name and its own section.
        t @ ("string" | "integer" | "number" | "boolean") => Some(format_instance_type(t)),
        _ => None,
    }
}

/// The element schema of an array schema's `items`, handling both the single-
/// schema form (`"items": {…}`) and the tuple form (`"items": [{…}, …]`).
fn array_item(schema: &Value) -> Option<&Value> {
    match schema.as_object()?.get("items")? {
        Value::Array(items) => items.first(),
        other => Some(other),
    }
}

/// If a property schema directly or indirectly references a definition, the
/// definition name. Handles a direct `$ref`, a `$ref` inside `anyOf`/`oneOf`/
/// `allOf`, and a `$ref` on array `items`.
///
/// `allOf` coverage matters because schemars emits the
/// `#[serde(default = "...")]` + `#[serde(rename = "use")]` pattern (used by
/// `mcp:` among others) as a wrapper object with a default and a single-entry
/// `allOf: [{ $ref: ... }]`. Without this branch the field shows up in the
/// top-level table but never gets a `## <name>` schema section.
fn resolve_ref_type_name(schema: &Value) -> Option<String> {
    let obj = schema.as_object()?;

    if let Some(r) = direct_ref(schema) {
        return ref_name(r);
    }

    for key in ["anyOf", "oneOf", "allOf"] {
        if let Some(Value::Array(variants)) = obj.get(key) {
            for s in variants {
                if let Some(r) = direct_ref(s) {
                    return ref_name(r);
                }
            }
        }
    }

    if schema_has_type(schema, "array")
        && let Some(item) = array_item(schema)
        && let Some(r) = direct_ref(item)
    {
        return ref_name(r);
    }

    None
}

/// Normalize a schema `description` for rendering, then unwrap the rustdoc
/// link syntax this markdown pipeline cannot resolve.
///
/// The normalization itself is [`anodizer_core::config::collapse_description`] —
/// the same function that normalizes the published `schema.json`, so the
/// generated config reference and the editor tooltips cannot drift apart on how
/// a doc comment's wrapping, paragraphs, or fenced examples are treated.
fn collapse_description(s: &str) -> String {
    unwrap_rustdoc_links(&anodizer_core::config::collapse_description(s))
}

/// Unwrap rustdoc intra-doc links — `` [`Path::to::item`] `` and
/// `` [`item`](rust::path) `` — to plain inline code.
///
/// schemars copies rustdoc verbatim into schema descriptions, but this
/// markdown pipeline has no rustdoc link resolver, so the bracket syntax
/// would render literally (e.g. ``[`Self::upload_concurrency`]``) or, for
/// the explicit-target form, as a link whose href is a rust path — broken
/// either way. A leading `Self::` is dropped — the reference tables already
/// scope fields to their section. Markdown links with a real URL / relative
/// / anchor target (``[`x`](https://…)``) and reference-style links
/// (``[`x`][ref]``) are left untouched: those render as real links.
fn unwrap_rustdoc_links(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut rest = s;
    while let Some(start) = rest.find("[`") {
        let Some(end_rel) = rest[start + 2..].find("`]") else {
            break;
        };
        let end = start + 2 + end_rel;
        let mut after = end + 2;
        let mut unwrap_to_code = true;
        match rest.as_bytes().get(after) {
            // Explicit target: unwrap only when the target is a rust path,
            // and consume it; a real URL/relative/anchor target stays a link.
            Some(b'(') => {
                if let Some(close_rel) = rest[after..].find(')') {
                    let target = &rest[after + 1..after + close_rel];
                    if is_rust_path_target(target) {
                        after += close_rel + 1;
                    } else {
                        unwrap_to_code = false;
                    }
                } else {
                    unwrap_to_code = false;
                }
            }
            // Reference-style link — leave for the renderer.
            Some(b'[') => unwrap_to_code = false,
            _ => {}
        }
        out.push_str(&rest[..start]);
        if unwrap_to_code {
            let code = &rest[start + 2..end];
            out.push('`');
            out.push_str(code.strip_prefix("Self::").unwrap_or(code));
            out.push('`');
        } else {
            out.push_str(&rest[start..after]);
        }
        rest = &rest[after..];
    }
    out.push_str(rest);
    out
}

/// True when a markdown link target is a rustdoc item path (`crate::x`,
/// `super::super::y`, `Self::z`, or a bare identifier) rather than a real
/// URL, relative file path, or `#anchor` — i.e. when the "link" only means
/// something to rustdoc and must be unwrapped to inline code.
fn is_rust_path_target(target: &str) -> bool {
    !target.is_empty()
        && target.split("::").all(|seg| {
            !seg.is_empty() && seg.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')
        })
}

/// The `description` keyword on a schema, normalized via [`collapse_description`]
/// and flattened for a markdown-table cell: paragraph breaks become
/// `<br><br>` and any residual newline a space (a bare newline inside a cell
/// terminates the table row), with `|` escaped so a description containing a
/// pipe does not break the markdown table column.
///
/// A fenced code block cannot survive in a table cell — markdown ends the row
/// at the first newline. Its lines become one `<code>` span each, joined by
/// `<br>`, so a YAML example stays line-per-line instead of collapsing into an
/// unreadable single run.
fn schema_description(schema: &Value) -> String {
    schema
        .as_object()
        .and_then(|o| o.get("description"))
        .and_then(Value::as_str)
        .map(collapse_description)
        .map(|d| flatten_fences_for_cell(&d))
        .unwrap_or_default()
        .replace("\n\n", "<br><br>")
        .replace('\n', " ")
        .replace('|', "\\|")
}

/// Rewrite every fenced code block into `<br>`-joined `<code>` spans, leaving
/// prose untouched. Runs before the newline flattening in [`schema_description`]
/// so the fence's own line structure survives into the cell.
fn flatten_fences_for_cell(s: &str) -> String {
    let mut out: Vec<String> = Vec::new();
    let mut cell: Vec<String> = Vec::new();
    let mut in_fence = false;

    for line in s.split('\n') {
        if line.trim_start().starts_with("```") {
            if in_fence {
                out.push(cell.join("<br>"));
                cell.clear();
            }
            in_fence = !in_fence;
            continue;
        }
        if in_fence {
            if !line.trim().is_empty() {
                cell.push(format!("<code>{}</code>", html_escape_cell(line)));
            }
        } else {
            out.push(line.to_string());
        }
    }
    if !cell.is_empty() {
        out.push(cell.join("<br>"));
    }
    out.join("\n")
}

/// Escape the characters that would be read as markup inside a `<code>` span in
/// a table cell. `<` alone is enough to swallow the rest of the row when a doc
/// example contains something like `Name <email>`.
fn html_escape_cell(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

/// Extract `ConfigField` entries from a properties map, sorted by field name.
/// `defs` is the schema's definitions map, consulted to inline scalar newtype
/// `$ref`s to their underlying type. `section_anchors` maps a definition name to
/// the anchor of the section documenting it, so a composite default can point at
/// that section instead of inlining its serialization.
///
/// The map is keyed by DEFINITION name, not field name: a nested `repository`
/// field resolves to `McpRepository`, which has no section, while a top-level
/// `changelog` field resolves to `ChangelogConfig`, which does. Keying by field
/// name would link any same-named nested field to an unrelated top-level
/// section.
fn extract_fields(
    props: &Map<String, Value>,
    defs: &Map<String, Value>,
    section_anchors: &HashMap<String, String>,
) -> Vec<ConfigField> {
    let mut fields: Vec<ConfigField> = props
        .iter()
        .map(|(name, schema)| {
            if schema.as_bool().is_some() {
                return ConfigField {
                    name: name.clone(),
                    field_type: "any".into(),
                    default: "\u{2014}".into(),
                    description: String::new(),
                };
            }
            let anchor = resolve_ref_type_name(schema)
                .and_then(|def| section_anchors.get(&def))
                .map(String::as_str);
            ConfigField {
                name: name.clone(),
                field_type: resolve_type_name(schema, defs),
                default: format_default(schema.as_object().and_then(|o| o.get("default")), anchor),
                description: schema_description(schema),
            }
        })
        .collect();
    fields.sort_by(|a, b| a.name.cmp(&b.name));
    fields
}

/// Inner types (typically per-crate fields or per-crate `publish.*` entries)
/// that warrant their own `## <qualified-name>` schema section even though
/// they are not top-level `Config` fields. Each entry is
/// `(qualified_section_name, parent_definition, field_name)`.
///
/// Without this list, a consumer reading the configuration reference cannot
/// see the field shape for the canonical Docker API (`crates[].dockers_v2`),
/// the per-crate publishers (`crates[].publish.<name>`), and similar
/// per-crate publisher / packager sub-structs — they show up only as a type
/// name in the parent table.
const SECOND_LEVEL_SECTIONS: &[(&str, &str, &str)] = &[
    ("crates[].dockers_v2", "CrateConfig", "dockers_v2"),
    (
        "crates[].docker_manifests",
        "CrateConfig",
        "docker_manifests",
    ),
    ("crates[].docker_digest", "CrateConfig", "docker_digest"),
    ("crates[].nfpms", "CrateConfig", "nfpms"),
    ("crates[].publish", "CrateConfig", "publish"),
    ("crates[].publish.cargo", "PublishConfig", "cargo"),
    ("crates[].publish.homebrew", "PublishConfig", "homebrew"),
    (
        "crates[].publish.homebrew_cask",
        "PublishConfig",
        "homebrew_cask",
    ),
    ("crates[].publish.scoop", "PublishConfig", "scoop"),
    ("crates[].publish.chocolatey", "PublishConfig", "chocolatey"),
    ("crates[].publish.winget", "PublishConfig", "winget"),
    ("crates[].publish.aur", "PublishConfig", "aur"),
    ("crates[].publish.aur_source", "PublishConfig", "aur_source"),
    ("crates[].publish.krew", "PublishConfig", "krew"),
    ("crates[].publish.nix", "PublishConfig", "nix"),
];

/// Build a [`NestedSection`] for the schema definition `def_name`, titled
/// `section_name`. Returns `None` when the definition is missing or has no
/// documentable properties. Shared by the top-level and second-level
/// section passes so both resolve description + fields identically.
fn build_nested_section(
    defs: &Map<String, Value>,
    def_name: &str,
    section_name: &str,
    section_anchors: &HashMap<String, String>,
) -> Option<NestedSection> {
    let def_schema = defs.get(def_name)?.as_object()?;
    let def_props = match def_schema.get("properties").and_then(Value::as_object) {
        Some(o) if !o.is_empty() => o,
        _ => return None,
    };
    let description = def_schema
        .get("description")
        .and_then(Value::as_str)
        .map(collapse_description)
        .unwrap_or_default();
    Some(NestedSection {
        name: section_name.to_string(),
        anchor_attr: format!("{{#{}}}", section_anchor(section_name)),
        description,
        fields: extract_fields(def_props, defs, section_anchors),
    })
}

/// Definition name → anchor of the section that documents it, for every section
/// the reference will emit.
///
/// Resolved in its own pass before any field is rendered: a field's Default cell
/// links to the section for its type, and sections are themselves built from
/// fields, so the mapping cannot be a by-product of building them. Mirrors the
/// two section passes in `generate_config_reference` exactly — auto-discovered
/// top-level sections first, then [`SECOND_LEVEL_SECTIONS`] — so a definition
/// reachable both ways resolves to the same anchor the heading gets.
fn collect_section_anchors(
    root_props: &Map<String, Value>,
    defs: &Map<String, Value>,
) -> HashMap<String, String> {
    let mut anchors: HashMap<String, String> = HashMap::new();

    let documentable = |def_name: &str| {
        defs.get(def_name)
            .and_then(Value::as_object)
            .and_then(|d| d.get("properties"))
            .and_then(Value::as_object)
            .is_some_and(|p| !p.is_empty())
    };

    let mut sorted_props: Vec<(&String, &Value)> = root_props.iter().collect();
    sorted_props.sort_by(|a, b| a.0.cmp(b.0));
    for (field_name, schema) in sorted_props {
        if schema.as_bool().is_some() {
            continue;
        }
        let Some(def_name) = resolve_ref_type_name(schema) else {
            continue;
        };
        if documentable(&def_name) {
            anchors
                .entry(def_name)
                .or_insert_with(|| section_anchor(field_name));
        }
    }

    for (section_name, parent_def, field_name) in SECOND_LEVEL_SECTIONS {
        let Some(def_name) = defs
            .get(*parent_def)
            .and_then(Value::as_object)
            .and_then(|o| o.get("properties"))
            .and_then(Value::as_object)
            .and_then(|p| p.get(*field_name))
            .and_then(resolve_ref_type_name)
        else {
            continue;
        };
        if documentable(&def_name) {
            anchors
                .entry(def_name)
                .or_insert_with(|| section_anchor(section_name));
        }
    }

    anchors
}

/// The `properties` map of an object schema, or an error if absent.
fn object_properties<'a>(schema: &'a Value, what: &str) -> Result<&'a Map<String, Value>, String> {
    schema
        .as_object()
        .and_then(|o| o.get("properties"))
        .and_then(Value::as_object)
        .ok_or_else(|| format!("{what} is not an object schema"))
}

fn generate_config_reference(tera: &Tera) -> Result<String, String> {
    let root = anodizer_core::config::config_schema();
    let empty = Map::new();
    let defs = root
        .as_object()
        .and_then(|o| o.get("definitions"))
        .and_then(Value::as_object)
        .unwrap_or(&empty);

    let root_props = object_properties(&root, "Config schema")?;

    // Resolve every section's anchor first: a field's Default cell links to the
    // section documenting its type, so the mapping has to exist before any field
    // is rendered.
    let section_anchors = collect_section_anchors(root_props, defs);

    // Build top-level field list
    let top_level_fields = extract_fields(root_props, defs, &section_anchors);

    // Build nested sections: for every top-level field that references a
    // definition, expand that definition's properties into a section. Iterate
    // the root properties in sorted key order so the emitted sections are
    // alphabetical (schemars emits `properties` in struct-declaration order; the
    // reference orders auto-discovered sections by field name).
    let mut nested_sections: Vec<NestedSection> = Vec::new();

    let mut sorted_props: Vec<(&String, &Value)> = root_props.iter().collect();
    sorted_props.sort_by(|a, b| a.0.cmp(b.0));

    for (field_name, schema) in sorted_props {
        if schema.as_bool().is_some() {
            continue;
        }
        let Some(def_name) = resolve_ref_type_name(schema) else {
            continue;
        };
        if let Some(section) = build_nested_section(defs, &def_name, field_name, &section_anchors) {
            nested_sections.push(section);
        }
    }

    // Append second-level sections (per-crate / per-publisher sub-structs).
    for (section_name, parent_def, field_name) in SECOND_LEVEL_SECTIONS {
        let Some(parent_props) = defs
            .get(*parent_def)
            .and_then(|s| s.as_object())
            .and_then(|o| o.get("properties"))
            .and_then(Value::as_object)
        else {
            continue;
        };
        let Some(field_obj) = parent_props.get(*field_name) else {
            continue;
        };
        let Some(def_name) = resolve_ref_type_name(field_obj) else {
            continue;
        };
        if let Some(section) = build_nested_section(defs, &def_name, section_name, &section_anchors)
        {
            nested_sections.push(section);
        }
    }

    let mut ctx = Context::new();
    ctx.insert("top_level_fields", &top_level_fields);
    ctx.insert("nested_sections", &nested_sections);

    tera.render("configuration.md.tera", &ctx)
        .map_err(|e| format!("failed to render configuration.md: {e}"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::{Arg, Command};

    /// Convenience: collect all visible commands rooted at `cmd` (excluding
    /// `cmd` itself), mirroring what `generate_cli_reference` puts into the
    /// `commands` Tera context.
    fn collect_all_commands(cmd: &clap::Command) -> Vec<CmdInfo> {
        cmd.get_subcommands()
            .filter(|s| !s.is_hide_set())
            .flat_map(|sub| collect_command(sub, &[]))
            .collect()
    }

    /// Load the xtask templates the same way `run` does, so a test renders
    /// through the real template rather than a stand-in.
    fn load_templates() -> Tera {
        let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("templates");
        let mut tera = Tera::default();
        tera.load_from_glob(dir.join("*.tera").to_str().unwrap())
            .expect("templates load");
        tera
    }

    #[test]
    fn section_anchor_slugifies_qualified_section_names() {
        assert_eq!(section_anchor("mcp"), "mcp");
        assert_eq!(section_anchor("verify_release"), "verify-release");
        assert_eq!(
            section_anchor("crates[].publish.homebrew_cask"),
            "crates-publish-homebrew-cask"
        );
    }

    #[test]
    fn format_default_inlines_a_narrow_composite_even_with_a_section() {
        let v = serde_json::json!({"strict": false});
        assert_eq!(
            format_default(Some(&v), Some("preflight")),
            "`{\"strict\":false}`"
        );
    }

    #[test]
    fn format_default_links_a_wide_composite_to_its_section() {
        let v = serde_json::json!({
            "enabled": false, "assert_assets": true,
            "assert_landing": true, "install_smoke": null
        });
        assert!(format!("`{v}`").len() > MAX_INLINE_DEFAULT);
        assert_eq!(
            format_default(Some(&v), Some("verify-release")),
            "[per field](#verify-release)"
        );
    }

    #[test]
    fn format_default_inlines_a_wide_composite_with_no_section_to_link() {
        // Nothing to point at, so the serialization is still the best answer
        // available — never an empty cell.
        let v = serde_json::json!({
            "enabled": false, "assert_assets": true,
            "assert_landing": true, "install_smoke": null
        });
        assert_eq!(format_default(Some(&v), None), format!("`{v}`"));
    }

    #[test]
    fn format_default_keeps_empty_composites_literal() {
        assert_eq!(
            format_default(Some(&serde_json::json!([])), Some("x")),
            "`[]`"
        );
        assert_eq!(
            format_default(Some(&serde_json::json!({})), Some("x")),
            "`{}`"
        );
    }

    #[test]
    fn every_generated_default_link_resolves_to_an_emitted_anchor() {
        // The whole point of emitting explicit `{#anchor}` attributes: zola
        // does not validate bare `#fragment` targets, so a link that missed
        // would be dead with nothing reporting it.
        let md = generate_config_reference(&load_templates()).expect("render");
        let anchors: std::collections::HashSet<&str> = md
            .lines()
            .filter(|l| l.starts_with("## "))
            .filter_map(|l| l.rsplit_once("{#"))
            .filter_map(|(_, rest)| rest.strip_suffix('}'))
            .collect();
        assert!(!anchors.is_empty(), "no section anchors were emitted");

        let mut linked = 0;
        for rest in md.split_terminator("[per field](#").skip(1) {
            let target = rest.split(')').next().expect("link target");
            assert!(
                anchors.contains(target),
                "dead Default-column link to #{target}"
            );
            linked += 1;
        }
        assert!(linked > 0, "no composite default was linked to a section");
    }

    #[test]
    fn unwrap_rustdoc_links_strips_brackets_and_self_prefix() {
        assert_eq!(
            unwrap_rustdoc_links("layered on top of [`Self::upload_concurrency`] (the cap)"),
            "layered on top of `upload_concurrency` (the cap)"
        );
        assert_eq!(
            unwrap_rustdoc_links("[`AttestationMode::Subjects`] emits a manifest"),
            "`AttestationMode::Subjects` emits a manifest"
        );
        // Multiple links in one description.
        assert_eq!(
            unwrap_rustdoc_links("see [`Self::a`] and [`b::c`]"),
            "see `a` and `b::c`"
        );
        // A non-`Self::` path keeps its full form.
        assert_eq!(unwrap_rustdoc_links("[`b::c`]"), "`b::c`");
        // Explicit rust-path target: the href means nothing outside rustdoc,
        // so the link collapses to its code text.
        assert_eq!(
            unwrap_rustdoc_links("see [`apply_legacy`](super::super::apply_legacy) for details"),
            "see `apply_legacy` for details"
        );
    }

    #[test]
    fn unwrap_rustdoc_links_leaves_real_markdown_links_alone() {
        assert_eq!(
            unwrap_rustdoc_links("[`docs`](https://example.com) and [`x`][ref]"),
            "[`docs`](https://example.com) and [`x`][ref]"
        );
        // No link syntax at all: pass through unchanged.
        assert_eq!(
            unwrap_rustdoc_links("plain `code` text"),
            "plain `code` text"
        );
        // Unterminated bracket: pass through unchanged.
        assert_eq!(unwrap_rustdoc_links("broken [`link"), "broken [`link");
    }

    #[test]
    fn collapse_description_unwraps_links_after_joining_wrapped_lines() {
        // A rustdoc link split across a hard wrap must still unwrap after
        // the paragraph joins.
        assert_eq!(
            collapse_description("layered on top of [`Self::upload_concurrency`]\n(the cap)"),
            "layered on top of `upload_concurrency` (the cap)"
        );
    }

    #[test]
    fn schema_description_flattens_paragraphs_for_table_cells() {
        // A two-paragraph rustdoc description must render as ONE table-cell
        // line: paragraph break -> <br><br>, no bare newline survives.
        let schema = serde_json::json!({
            "description": "First paragraph\nhard-wrapped here.\n\nSecond paragraph with a | pipe."
        });
        let cell = schema_description(&schema);
        assert_eq!(
            cell,
            "First paragraph hard-wrapped here.<br><br>Second paragraph with a \\| pipe."
        );
        assert!(!cell.contains('\n'));
    }

    #[test]
    fn gen_docs_filters_hidden_flags() {
        let cmd = Command::new("root").subcommand(
            Command::new("leaf")
                .arg(Arg::new("visible").long("visible").help("visible flag"))
                .arg(
                    Arg::new("hidden")
                        .long("hidden-flag")
                        .help("hidden flag")
                        .hide(true),
                ),
        );

        let commands = collect_all_commands(&cmd);
        let leaf = commands
            .iter()
            .find(|c| c.name == "leaf")
            .expect("leaf command present");
        let longs: Vec<&str> = leaf.args.iter().map(|a| a.long.as_str()).collect();
        assert!(
            longs.iter().any(|l| l.contains("visible")),
            "visible flag should be rendered: {longs:?}"
        );
        assert!(
            !longs.iter().any(|l| l.contains("hidden-flag")),
            "hidden flag must be filtered: {longs:?}"
        );
    }

    #[test]
    fn gen_docs_recurses_into_nested_subcommands() {
        let cmd = Command::new("root").subcommand(
            Command::new("parent")
                .subcommand(Command::new("child-a"))
                .subcommand(Command::new("child-b")),
        );

        let commands = collect_all_commands(&cmd);
        let names: Vec<&str> = commands.iter().map(|c| c.name.as_str()).collect();
        assert!(names.contains(&"parent"), "parent must appear: {names:?}");
        assert!(
            names.contains(&"parent child-a"),
            "nested child-a must appear: {names:?}"
        );
        assert!(
            names.contains(&"parent child-b"),
            "nested child-b must appear: {names:?}"
        );
    }

    #[test]
    fn gen_docs_excludes_hidden_subcommands() {
        let cmd = Command::new("root").subcommand(
            Command::new("parent")
                .subcommand(Command::new("visible-child"))
                .subcommand(Command::new("hidden-child").hide(true)),
        );

        let commands = collect_all_commands(&cmd);
        let names: Vec<&str> = commands.iter().map(|c| c.name.as_str()).collect();
        assert!(
            names.contains(&"parent visible-child"),
            "visible nested subcommand must appear: {names:?}"
        );
        assert!(
            !names.iter().any(|n| n.contains("hidden-child")),
            "hidden nested subcommand must be filtered: {names:?}"
        );
    }

    #[test]
    fn gen_docs_excludes_hidden_global_flags() {
        // Mirror the production filter used in `generate_cli_reference` for
        // global args.
        let cmd = Command::new("root")
            .arg(
                Arg::new("g-visible")
                    .long("g-visible")
                    .global(true)
                    .help("visible global"),
            )
            .arg(
                Arg::new("g-hidden")
                    .long("g-hidden")
                    .global(true)
                    .hide(true)
                    .help("hidden global"),
            )
            .subcommand(Command::new("leaf"));

        let global_longs: Vec<String> = cmd
            .get_arguments()
            .filter(|a| a.is_global_set() && !a.is_hide_set())
            .filter_map(|a| a.get_long().map(|l| l.to_string()))
            .collect();

        assert!(
            global_longs.iter().any(|l| l == "g-visible"),
            "visible global should appear: {global_longs:?}"
        );
        assert!(
            !global_longs.iter().any(|l| l == "g-hidden"),
            "hidden global must be filtered: {global_longs:?}"
        );
    }

    // ---------------------------------------------------------------------
    // Integration tests against the real `anodizer_cli::build_cli()` output.
    // These pin the audit-I18 closures: `check config` / `check determinism`
    // must be documented, and `--simulate-failure` / `--inject-drift` must
    // not leak into rendered docs.
    // ---------------------------------------------------------------------

    #[test]
    fn gen_docs_includes_check_config_subcommand() {
        let cmd = anodizer_cli::build_cli();
        let commands = collect_all_commands(&cmd);
        let names: Vec<&str> = commands.iter().map(|c| c.name.as_str()).collect();
        assert!(
            names.contains(&"check config"),
            "`check config` must be documented: {names:?}"
        );
        assert!(
            names.contains(&"check determinism"),
            "`check determinism` must be documented: {names:?}"
        );
    }

    #[test]
    fn gen_docs_omits_simulate_failure_flag() {
        let cmd = anodizer_cli::build_cli();
        let commands = collect_all_commands(&cmd);
        let release_cmd = commands
            .iter()
            .find(|c| c.name == "release")
            .unwrap_or_else(|| panic!("release subcommand must exist"));
        let flag_names: Vec<&str> = release_cmd.args.iter().map(|a| a.long.as_str()).collect();
        assert!(
            !flag_names.iter().any(|f| f.contains("simulate-failure")),
            "--simulate-failure must not appear in rendered docs: {flag_names:?}"
        );
    }

    #[test]
    fn gen_docs_omits_inject_drift_flag() {
        let cmd = anodizer_cli::build_cli();
        let commands = collect_all_commands(&cmd);
        let check_det_cmd = commands
            .iter()
            .find(|c| c.name == "check determinism")
            .unwrap_or_else(|| panic!("`check determinism` must be documented"));
        let flag_names: Vec<&str> = check_det_cmd.args.iter().map(|a| a.long.as_str()).collect();
        assert!(
            !flag_names.iter().any(|f| f.contains("inject-drift")),
            "--inject-drift must not appear in rendered docs: {flag_names:?}"
        );
    }

    #[test]
    fn test_schema_has_all_config_fields() {
        let schema = anodizer_core::config::config_schema();
        let props = object_properties(&schema, "Config schema").unwrap_or_else(|e| panic!("{e}"));
        let field_names: Vec<&String> = props.keys().collect();

        for expected in &[
            "version",
            "project_name",
            "dist",
            "includes",
            "env_files",
            "defaults",
            "before",
            "after",
            "crates",
            "changelog",
            "signs",
            "binary_signs",
            "docker_signs",
            "upx",
            "snapshot",
            "nightly",
            "announce",
            "report_sizes",
            "env",
            "variables",
            "publishers",
            "tag",
            "git",
            "partial",
            "workspaces",
            "source",
            "sboms",
            "release",
            "notarize",
            "metadata",
        ] {
            assert!(
                field_names.contains(&&expected.to_string()),
                "schema missing top-level field: {expected}"
            );
        }
    }

    #[test]
    fn test_all_config_fields_resolve_to_non_empty_type() {
        let root = anodizer_core::config::config_schema();
        let empty = Map::new();
        let defs = root
            .as_object()
            .and_then(|o| o.get("definitions"))
            .and_then(Value::as_object)
            .unwrap_or(&empty);
        let props = object_properties(&root, "Config schema").unwrap_or_else(|e| panic!("{e}"));

        for (name, schema) in props {
            if schema.as_bool().is_some() {
                continue;
            }
            let type_str = super::resolve_type_name(schema, defs);
            assert!(
                !type_str.is_empty(),
                "field `{name}` resolved to an empty type string"
            );
        }
    }
}
