use std::fs;
use std::path::{Path, PathBuf};
use tera::{Context, Tera};

/// Marker comment emitted at the top of every generated per-crate README so
/// editors and reviewers can see the file is machine-managed.
const GENERATED_MARKER: &str =
    "<!-- AUTO-GENERATED by `cargo xtask gen-docs` — do not edit manually -->";

/// Generate the JSON Schema for `Config` as a pretty-printed JSON string.
fn generate_schema_json() -> Result<String, String> {
    let schema = schemars::schema_for!(anodizer_core::config::Config);
    serde_json::to_string_pretty(&schema).map_err(|e| format!("cannot serialize schema: {e}"))
}

/// Compare `generated` against `existing` file; record staleness to `stale`.
/// Prints the first differing line and line-count mismatch for debuggability.
fn check_file_freshness(path: &Path, generated: &str, stale: &mut bool) -> Result<(), String> {
    let existing =
        fs::read_to_string(path).map_err(|e| format!("cannot read {}: {e}", path.display()))?;
    if existing != generated {
        eprintln!("STALE: {}", path.display());
        for (i, (a, b)) in existing.lines().zip(generated.lines()).enumerate() {
            if a != b {
                eprintln!("  line {}: committed: {}", i + 1, a);
                eprintln!("  line {}: generated: {}", i + 1, b);
                break;
            }
        }
        if existing.lines().count() != generated.lines().count() {
            eprintln!(
                "  line count: committed={}, generated={}",
                existing.lines().count(),
                generated.lines().count()
            );
        }
        *stale = true;
    }
    Ok(())
}

/// Run doc generation. If `check` is true, compare output against existing files
/// and return an error if they differ.
pub fn run(check: bool) -> Result<(), String> {
    let project_root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|p| p.parent())
        .ok_or("cannot find project root")?;

    let docs_dir = project_root.join("docs/site/content/docs");
    let templates_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("templates");

    let tera = Tera::new(
        templates_dir
            .join("*.tera")
            .to_str()
            .ok_or("invalid template path")?,
    )
    .map_err(|e| format!("failed to load templates: {e}"))?;

    let cli_content = generate_cli_reference(&tera)?;
    let config_content = generate_config_reference(&tera)?;
    let crate_readmes = generate_per_crate_readmes(project_root, &tera)?;
    let schema_content = generate_schema_json()?;

    let cli_path = docs_dir.join("reference/cli.md");
    let config_path = docs_dir.join("reference/configuration.md");
    let schema_path = project_root.join("docs/site/static/schema.json");

    if check {
        let mut stale = false;
        check_file_freshness(&cli_path, &cli_content, &mut stale)?;
        check_file_freshness(&config_path, &config_content, &mut stale)?;
        check_file_freshness(&schema_path, &schema_content, &mut stale)?;
        for (path, content) in &crate_readmes {
            check_file_freshness(path, content, &mut stale)?;
        }

        if stale {
            return Err("generated docs are out of date — run `cargo xtask gen-docs`".into());
        }
        eprintln!("docs are up to date");
        return Ok(());
    }

    fs::write(&cli_path, &cli_content)
        .map_err(|e| format!("cannot write {}: {e}", cli_path.display()))?;
    eprintln!("wrote {}", cli_path.display());

    fs::write(&config_path, &config_content)
        .map_err(|e| format!("cannot write {}: {e}", config_path.display()))?;
    eprintln!("wrote {}", config_path.display());

    fs::write(&schema_path, &schema_content)
        .map_err(|e| format!("cannot write {}: {e}", schema_path.display()))?;
    eprintln!("wrote {}", schema_path.display());

    for (path, content) in &crate_readmes {
        fs::write(path, content).map_err(|e| format!("cannot write {}: {e}", path.display()))?;
        eprintln!("wrote {}", path.display());
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Per-crate README generation
// ---------------------------------------------------------------------------

/// Walk `crates/*` and produce `(path, content)` pairs for every publishable
/// crate's `README.md`.
///
/// The `anodizer` binary crate (`crates/cli`) reuses the workspace root README
/// verbatim (with a generated-marker prepended) so its crates.io page is the
/// full user-facing landing page. Every other publishable crate gets a brief
/// generated stub rendered from `crate-readme.md.tera` that points users back
/// to the main repository.
///
/// Crates with `publish = false` (e.g. `xtask`) are skipped.
fn generate_per_crate_readmes(
    project_root: &Path,
    tera: &Tera,
) -> Result<Vec<(PathBuf, String)>, String> {
    let crates_dir = project_root.join("crates");
    let workspace_readme = fs::read_to_string(project_root.join("README.md"))
        .map_err(|e| format!("cannot read workspace README.md: {e}"))?;

    let mut entries: Vec<PathBuf> = fs::read_dir(&crates_dir)
        .map_err(|e| format!("cannot read {}: {e}", crates_dir.display()))?
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.is_dir())
        .collect();
    entries.sort();

    let mut out: Vec<(PathBuf, String)> = Vec::with_capacity(entries.len());

    for crate_dir in entries {
        let cargo_toml = crate_dir.join("Cargo.toml");
        if !cargo_toml.exists() {
            continue;
        }

        let manifest_text = fs::read_to_string(&cargo_toml)
            .map_err(|e| format!("cannot read {}: {e}", cargo_toml.display()))?;
        let manifest: toml::Value = toml::from_str(&manifest_text)
            .map_err(|e| format!("cannot parse {}: {e}", cargo_toml.display()))?;

        let pkg = match manifest.get("package").and_then(|p| p.as_table()) {
            Some(p) => p,
            None => continue,
        };

        // Skip crates with publish = false (e.g. xtask).
        if matches!(pkg.get("publish"), Some(toml::Value::Boolean(false))) {
            continue;
        }

        let name = pkg
            .get("name")
            .and_then(|v| v.as_str())
            .ok_or_else(|| format!("{} has no [package].name", cargo_toml.display()))?
            .to_string();
        let description = pkg
            .get("description")
            .and_then(|v| v.as_str())
            .ok_or_else(|| format!("{} has no [package].description", cargo_toml.display()))?
            .to_string();

        let readme_path = crate_dir.join("README.md");
        let content = if name == "anodizer" {
            format!("{GENERATED_MARKER}\n\n{workspace_readme}")
        } else {
            let mut ctx = Context::new();
            ctx.insert("name", &name);
            ctx.insert("description", &description);
            tera.render("crate-readme.md.tera", &ctx)
                .map_err(|e| format!("failed to render crate-readme.md.tera for {name}: {e}"))?
        };

        out.push((readme_path, content));
    }

    Ok(out)
}

#[derive(serde::Serialize)]
struct ArgInfo {
    long: String,
    short: String,
    default: String,
    help: String,
}

#[derive(serde::Serialize)]
struct CmdInfo {
    name: String,
    about: String,
    args: Vec<ArgInfo>,
}

/// Build an `ArgInfo` for a single non-global, visible flag. Emits a warning
/// to stderr when the flag has no help text (caught by `gen-docs --check`).
fn arg_info(a: &clap::Arg, owner_label: &str) -> ArgInfo {
    if a.get_help().is_none() {
        let flag = a.get_long().unwrap_or_else(|| a.get_id().as_str());
        eprintln!("warning: {owner_label}.--{flag} has no help text");
    }
    ArgInfo {
        long: a
            .get_long()
            .map(|l| format!("`--{l}`"))
            .unwrap_or_else(|| format!("`<{}>`", a.get_id())),
        short: a
            .get_short()
            .map(|s| format!("`-{s}`"))
            .unwrap_or_else(|| "\u{2014}".into()),
        default: a
            .get_default_values()
            .first()
            .map(|d| format!("`{}`", d.to_string_lossy()))
            .unwrap_or_else(|| "\u{2014}".into()),
        help: a.get_help().map(|h| h.to_string()).unwrap_or_default(),
    }
}

/// Recursively collect this command and all of its visible subcommands into a
/// flat list of `CmdInfo`. `parent_path` carries the names of ancestors so the
/// rendered `CmdInfo.name` becomes e.g. `"check determinism"` for nested
/// subcommands.
///
/// Hidden args (`Arg::hide(true)`) and hidden subcommands (`Command::hide(true)`)
/// are filtered out so test-harness plumbing like `--simulate-failure` and
/// `--inject-drift` doesn't leak into user-facing docs.
fn collect_command(cmd: &clap::Command, parent_path: &[&str]) -> Vec<CmdInfo> {
    let mut path: Vec<&str> = parent_path.to_vec();
    path.push(cmd.get_name());
    let full_name = path.join(" ");

    let args: Vec<ArgInfo> = cmd
        .get_arguments()
        .filter(|a| {
            !a.is_global_set()
                && a.get_id() != "help"
                && a.get_id() != "version"
                && !a.is_hide_set()
        })
        .map(|a| arg_info(a, &full_name))
        .collect();

    let mut result = vec![CmdInfo {
        name: full_name,
        about: cmd.get_about().map(|a| a.to_string()).unwrap_or_default(),
        args,
    }];

    for sub in cmd.get_subcommands() {
        if sub.is_hide_set() {
            continue;
        }
        result.extend(collect_command(sub, &path));
    }

    result
}

fn generate_cli_reference(tera: &Tera) -> Result<String, String> {
    let cmd = anodizer_cli::build_cli();

    let about = cmd.get_about().map(|a| a.to_string()).unwrap_or_default();

    let global_args: Vec<ArgInfo> = cmd
        .get_arguments()
        .filter(|a| a.is_global_set() && !a.is_hide_set())
        .map(|a| {
            if a.get_help().is_none()
                && let Some(long) = a.get_long()
            {
                eprintln!("warning: global flag --{long} has no help text");
            }
            ArgInfo {
                long: a.get_long().map(|l| format!("`--{l}`")).unwrap_or_default(),
                short: a
                    .get_short()
                    .map(|s| format!("`-{s}`"))
                    .unwrap_or_else(|| "\u{2014}".into()),
                default: "\u{2014}".into(),
                help: a.get_help().map(|h| h.to_string()).unwrap_or_default(),
            }
        })
        .collect();

    let commands: Vec<CmdInfo> = cmd
        .get_subcommands()
        .filter(|s| !s.is_hide_set())
        .flat_map(|sub| collect_command(sub, &[]))
        .collect();

    let mut ctx = Context::new();
    ctx.insert("about", &about);
    ctx.insert("global_args", &global_args);
    ctx.insert("commands", &commands);

    tera.render("cli.md.tera", &ctx)
        .map_err(|e| format!("failed to render cli.md: {e}"))
}

// ---------------------------------------------------------------------------
// Config reference generation — schema-driven
// ---------------------------------------------------------------------------

use schemars::Map;
use schemars::schema::{InstanceType, Schema, SchemaObject, SingleOrVec};

#[derive(serde::Serialize)]
struct ConfigField {
    name: String,
    field_type: String,
    default: String,
    description: String,
}

#[derive(serde::Serialize)]
struct NestedSection {
    name: String,
    description: String,
    fields: Vec<ConfigField>,
}

/// Map an `InstanceType` variant to a human-readable string.
fn format_instance_type(t: &InstanceType) -> String {
    match t {
        InstanceType::String => "string".into(),
        InstanceType::Integer => "integer".into(),
        InstanceType::Number => "number".into(),
        InstanceType::Boolean => "bool".into(),
        InstanceType::Array => "list".into(),
        InstanceType::Object => "map".into(),
        InstanceType::Null => "null".into(),
    }
}

/// Format a `serde_json::Value` default for markdown (em-dash for absent/null,
/// backtick-wrapped otherwise).
fn format_default(val: &Option<serde_json::Value>) -> String {
    match val {
        None => "\u{2014}".into(),
        Some(serde_json::Value::Null) => "\u{2014}".into(),
        Some(serde_json::Value::String(s)) if s.is_empty() => "\u{2014}".into(),
        Some(serde_json::Value::String(s)) => format!("`{s}`"),
        Some(v) => format!("`{v}`"),
    }
}

/// Given a schema object that may be a `$ref`, extract the definition name
/// (i.e. the fragment after `#/definitions/`).
fn ref_name(reference: &str) -> Option<String> {
    reference
        .strip_prefix("#/definitions/")
        .map(|s| s.to_string())
}

/// Resolve a schema object to a human-readable type name.
///
/// Handles:
/// - Direct `instance_type`
/// - `$ref`
/// - `anyOf` (Option<T> pattern: `[T, null]`)
/// - `allOf` (#[serde(flatten)] pattern)
/// - Array with items `$ref`
fn resolve_type_name(prop: &SchemaObject) -> String {
    // Direct $ref
    if let Some(ref r) = prop.reference {
        return ref_name(r).unwrap_or_else(|| r.clone());
    }

    // anyOf — Option<T> is represented as anyOf: [T, {type: null}]
    if let Some(ref sub) = prop.subschemas {
        if let Some(ref any_of) = sub.any_of {
            // Collect non-null variants
            let non_null: Vec<&Schema> = any_of
                .iter()
                .filter(|s| {
                    if let Schema::Object(o) = s {
                        if let Some(SingleOrVec::Single(ref t)) = o.instance_type {
                            return **t != InstanceType::Null;
                        }
                        // Keep if it has a $ref or subschemas (not a bare null)
                        return o.reference.is_some() || o.subschemas.is_some();
                    }
                    true
                })
                .collect();

            if non_null.len() == 1
                && let Schema::Object(inner) = non_null[0]
            {
                return resolve_type_name(inner);
            }
            // Multiple non-null variants — join them
            let names: Vec<String> = non_null
                .iter()
                .filter_map(|s| {
                    if let Schema::Object(o) = s {
                        Some(resolve_type_name(o))
                    } else {
                        None
                    }
                })
                .collect();
            if !names.is_empty() {
                return names.join(" | ");
            }
        }

        // allOf — flatten pattern; use first entry's type
        if let Some(ref all_of) = sub.all_of
            && let Some(Schema::Object(first)) = all_of.first()
        {
            return resolve_type_name(first);
        }
    }

    // Array with items
    if let Some(ref arr) = prop.array {
        if let Some(SingleOrVec::Single(ref item_schema)) = arr.items
            && let Schema::Object(ref item_obj) = **item_schema
        {
            let inner = resolve_type_name(item_obj);
            return format!("list of {inner}");
        }
        return "list".into();
    }

    // Direct instance_type
    if let Some(ref t) = prop.instance_type {
        return match t {
            SingleOrVec::Single(it) => format_instance_type(it),
            SingleOrVec::Vec(its) => {
                let non_null: Vec<String> = its
                    .iter()
                    .filter(|it| **it != InstanceType::Null)
                    .map(format_instance_type)
                    .collect();
                if non_null.len() == 1 {
                    non_null
                        .into_iter()
                        .next()
                        .unwrap_or_else(|| panic!("filtered to exactly one non-null type"))
                } else {
                    non_null.join(" | ")
                }
            }
        };
    }

    "object".into()
}

/// Given a schema object, if it directly or indirectly references a definition,
/// return that definition name. Handles `$ref`, `anyOf`/`allOf` with `$ref`,
/// and array items `$ref`.
///
/// `allOf` coverage matters because schemars emits the
/// `#[serde(default = "...")]` + `#[serde(rename = "use")]` pattern (used by
/// `mcp:` among others) as a wrapper object with a default and a single-entry
/// `allOf: [{ $ref: ... }]`. Without this branch the field shows up in the
/// top-level table but never gets a `## <name>` schema section.
fn resolve_ref_type_name(obj: &SchemaObject) -> Option<String> {
    // Direct $ref
    if let Some(ref r) = obj.reference {
        return ref_name(r);
    }

    if let Some(ref sub) = obj.subschemas {
        // anyOf — look for non-null $ref variant
        if let Some(ref any_of) = sub.any_of {
            for s in any_of {
                if let Schema::Object(inner) = s
                    && let Some(ref r) = inner.reference
                {
                    return ref_name(r);
                }
            }
        }
        // allOf — wrapper for `#[serde(default)]` on a struct field
        if let Some(ref all_of) = sub.all_of {
            for s in all_of {
                if let Schema::Object(inner) = s
                    && let Some(ref r) = inner.reference
                {
                    return ref_name(r);
                }
            }
        }
    }

    // Array with items $ref (e.g. signs, upx)
    if let Some(ref arr) = obj.array
        && let Some(SingleOrVec::Single(ref item_schema)) = arr.items
        && let Schema::Object(ref item_obj) = **item_schema
        && let Some(ref r) = item_obj.reference
    {
        return ref_name(r);
    }

    None
}

/// Extract `ConfigField` entries from a properties map.
fn extract_fields(props: &Map<String, Schema>) -> Vec<ConfigField> {
    props
        .iter()
        .map(|(name, schema)| {
            let obj = match schema {
                Schema::Object(o) => o,
                Schema::Bool(_) => {
                    return ConfigField {
                        name: name.clone(),
                        field_type: "any".into(),
                        default: "\u{2014}".into(),
                        description: String::new(),
                    };
                }
            };

            let description = obj
                .metadata
                .as_ref()
                .and_then(|m| m.description.clone())
                .unwrap_or_default()
                .replace('|', "\\|");

            let default = obj.metadata.as_ref().and_then(|m| m.default.clone());

            let field_type = resolve_type_name(obj);

            ConfigField {
                name: name.clone(),
                field_type,
                default: format_default(&default),
                description,
            }
        })
        .collect()
}

/// Inner types (typically per-crate fields or per-crate `publish.*` entries)
/// that warrant their own `## <qualified-name>` schema section even though
/// they are not top-level `Config` fields. Each entry is
/// `(qualified_section_name, parent_definition, field_name)`.
///
/// Without this list, a consumer reading the configuration reference cannot
/// see the field shape for the canonical Docker API (`crates[].docker_v2`),
/// the Krew publisher (`crates[].publish.krew`), and similar per-crate
/// publisher / packager sub-structs — they show up only as a type name in
/// the parent table.
const SECOND_LEVEL_SECTIONS: &[(&str, &str, &str)] = &[
    ("crates[].docker_v2", "CrateConfig", "docker_v2"),
    (
        "crates[].docker_manifests",
        "CrateConfig",
        "docker_manifests",
    ),
    ("crates[].docker_digest", "CrateConfig", "docker_digest"),
    ("crates[].publish", "CrateConfig", "publish"),
    ("crates[].publish.krew", "PublishConfig", "krew"),
];

fn generate_config_reference(tera: &Tera) -> Result<String, String> {
    let root_schema = schemars::schema_for!(anodizer_core::config::Config);
    let defs = &root_schema.definitions;
    let root = &root_schema.schema;

    let root_props = root
        .object
        .as_ref()
        .map(|o| &o.properties)
        .ok_or("Config schema is not an object schema")?;

    // Build top-level field list
    let top_level_fields = extract_fields(root_props);

    // Build nested sections: for every top-level field that references a
    // definition, expand that definition's properties into a section.
    let mut nested_sections: Vec<NestedSection> = Vec::new();

    for (field_name, schema) in root_props.iter() {
        let obj = match schema {
            Schema::Object(o) => o,
            Schema::Bool(_) => continue,
        };

        let def_name = match resolve_ref_type_name(obj) {
            Some(n) => n,
            None => continue,
        };

        let def_schema = match defs.get(&def_name) {
            Some(Schema::Object(s)) => s,
            _ => continue,
        };

        let def_props = match def_schema.object.as_ref() {
            Some(o) if !o.properties.is_empty() => &o.properties,
            _ => continue,
        };

        let description = def_schema
            .metadata
            .as_ref()
            .and_then(|m| m.description.clone())
            .unwrap_or_default();

        let fields = extract_fields(def_props);

        nested_sections.push(NestedSection {
            name: field_name.clone(),
            description,
            fields,
        });
    }

    // Append second-level sections (per-crate / per-publisher sub-structs).
    for (section_name, parent_def, field_name) in SECOND_LEVEL_SECTIONS {
        let parent_schema = match defs.get(*parent_def) {
            Some(Schema::Object(s)) => s,
            _ => continue,
        };
        let parent_props = match parent_schema.object.as_ref() {
            Some(o) => &o.properties,
            None => continue,
        };
        let field_obj = match parent_props.get(*field_name) {
            Some(Schema::Object(o)) => o,
            _ => continue,
        };
        let def_name = match resolve_ref_type_name(field_obj) {
            Some(n) => n,
            None => continue,
        };
        let def_schema = match defs.get(&def_name) {
            Some(Schema::Object(s)) => s,
            _ => continue,
        };
        let def_props = match def_schema.object.as_ref() {
            Some(o) if !o.properties.is_empty() => &o.properties,
            _ => continue,
        };
        let description = def_schema
            .metadata
            .as_ref()
            .and_then(|m| m.description.clone())
            .unwrap_or_default();
        let fields = extract_fields(def_props);
        nested_sections.push(NestedSection {
            name: (*section_name).to_string(),
            description,
            fields,
        });
    }

    let mut ctx = Context::new();
    ctx.insert("top_level_fields", &top_level_fields);
    ctx.insert("nested_sections", &nested_sections);

    tera.render("configuration.md.tera", &ctx)
        .map_err(|e| format!("failed to render configuration.md: {e}"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::{Arg, Command};

    /// Convenience: collect all visible commands rooted at `cmd` (excluding
    /// `cmd` itself), mirroring what `generate_cli_reference` puts into the
    /// `commands` Tera context.
    fn collect_all_commands(cmd: &clap::Command) -> Vec<CmdInfo> {
        cmd.get_subcommands()
            .filter(|s| !s.is_hide_set())
            .flat_map(|sub| collect_command(sub, &[]))
            .collect()
    }

    #[test]
    fn gen_docs_filters_hidden_flags() {
        let cmd = Command::new("root").subcommand(
            Command::new("leaf")
                .arg(Arg::new("visible").long("visible").help("visible flag"))
                .arg(
                    Arg::new("hidden")
                        .long("hidden-flag")
                        .help("hidden flag")
                        .hide(true),
                ),
        );

        let commands = collect_all_commands(&cmd);
        let leaf = commands
            .iter()
            .find(|c| c.name == "leaf")
            .expect("leaf command present");
        let longs: Vec<&str> = leaf.args.iter().map(|a| a.long.as_str()).collect();
        assert!(
            longs.iter().any(|l| l.contains("visible")),
            "visible flag should be rendered: {longs:?}"
        );
        assert!(
            !longs.iter().any(|l| l.contains("hidden-flag")),
            "hidden flag must be filtered: {longs:?}"
        );
    }

    #[test]
    fn gen_docs_recurses_into_nested_subcommands() {
        let cmd = Command::new("root").subcommand(
            Command::new("parent")
                .subcommand(Command::new("child-a"))
                .subcommand(Command::new("child-b")),
        );

        let commands = collect_all_commands(&cmd);
        let names: Vec<&str> = commands.iter().map(|c| c.name.as_str()).collect();
        assert!(names.contains(&"parent"), "parent must appear: {names:?}");
        assert!(
            names.contains(&"parent child-a"),
            "nested child-a must appear: {names:?}"
        );
        assert!(
            names.contains(&"parent child-b"),
            "nested child-b must appear: {names:?}"
        );
    }

    #[test]
    fn gen_docs_excludes_hidden_subcommands() {
        let cmd = Command::new("root").subcommand(
            Command::new("parent")
                .subcommand(Command::new("visible-child"))
                .subcommand(Command::new("hidden-child").hide(true)),
        );

        let commands = collect_all_commands(&cmd);
        let names: Vec<&str> = commands.iter().map(|c| c.name.as_str()).collect();
        assert!(
            names.contains(&"parent visible-child"),
            "visible nested subcommand must appear: {names:?}"
        );
        assert!(
            !names.iter().any(|n| n.contains("hidden-child")),
            "hidden nested subcommand must be filtered: {names:?}"
        );
    }

    #[test]
    fn gen_docs_excludes_hidden_global_flags() {
        // Mirror the production filter used in `generate_cli_reference` for
        // global args.
        let cmd = Command::new("root")
            .arg(
                Arg::new("g-visible")
                    .long("g-visible")
                    .global(true)
                    .help("visible global"),
            )
            .arg(
                Arg::new("g-hidden")
                    .long("g-hidden")
                    .global(true)
                    .hide(true)
                    .help("hidden global"),
            )
            .subcommand(Command::new("leaf"));

        let global_longs: Vec<String> = cmd
            .get_arguments()
            .filter(|a| a.is_global_set() && !a.is_hide_set())
            .filter_map(|a| a.get_long().map(|l| l.to_string()))
            .collect();

        assert!(
            global_longs.iter().any(|l| l == "g-visible"),
            "visible global should appear: {global_longs:?}"
        );
        assert!(
            !global_longs.iter().any(|l| l == "g-hidden"),
            "hidden global must be filtered: {global_longs:?}"
        );
    }

    // ---------------------------------------------------------------------
    // Integration tests against the real `anodizer_cli::build_cli()` output.
    // These pin the audit-I18 closures: `check config` / `check determinism`
    // must be documented, and `--simulate-failure` / `--inject-drift` must
    // not leak into rendered docs.
    // ---------------------------------------------------------------------

    #[test]
    fn gen_docs_includes_check_config_subcommand() {
        let cmd = anodizer_cli::build_cli();
        let commands = collect_all_commands(&cmd);
        let names: Vec<&str> = commands.iter().map(|c| c.name.as_str()).collect();
        assert!(
            names.contains(&"check config"),
            "`check config` must be documented: {names:?}"
        );
        assert!(
            names.contains(&"check determinism"),
            "`check determinism` must be documented: {names:?}"
        );
    }

    #[test]
    fn gen_docs_omits_simulate_failure_flag() {
        let cmd = anodizer_cli::build_cli();
        let commands = collect_all_commands(&cmd);
        let release_cmd = commands
            .iter()
            .find(|c| c.name == "release")
            .unwrap_or_else(|| panic!("release subcommand must exist"));
        let flag_names: Vec<&str> = release_cmd.args.iter().map(|a| a.long.as_str()).collect();
        assert!(
            !flag_names.iter().any(|f| f.contains("simulate-failure")),
            "--simulate-failure must not appear in rendered docs: {flag_names:?}"
        );
    }

    #[test]
    fn gen_docs_omits_inject_drift_flag() {
        let cmd = anodizer_cli::build_cli();
        let commands = collect_all_commands(&cmd);
        let check_det_cmd = commands
            .iter()
            .find(|c| c.name == "check determinism")
            .unwrap_or_else(|| panic!("`check determinism` must be documented"));
        let flag_names: Vec<&str> = check_det_cmd.args.iter().map(|a| a.long.as_str()).collect();
        assert!(
            !flag_names.iter().any(|f| f.contains("inject-drift")),
            "--inject-drift must not appear in rendered docs: {flag_names:?}"
        );
    }

    #[test]
    fn test_schema_has_all_config_fields() {
        let schema = schemars::schema_for!(anodizer_core::config::Config);
        let root = schema.schema;
        let props = root
            .object
            .as_ref()
            .unwrap_or_else(|| panic!("Config should be an object schema"));
        let field_names: Vec<&String> = props.properties.keys().collect();

        for expected in &[
            "version",
            "project_name",
            "dist",
            "includes",
            "env_files",
            "defaults",
            "before",
            "after",
            "crates",
            "changelog",
            "signs",
            "binary_signs",
            "docker_signs",
            "upx",
            "snapshot",
            "nightly",
            "announce",
            "report_sizes",
            "env",
            "variables",
            "publishers",
            "tag",
            "git",
            "partial",
            "workspaces",
            "source",
            "sboms",
            "release",
            "notarize",
            "metadata",
        ] {
            assert!(
                field_names.contains(&&expected.to_string()),
                "schema missing top-level field: {expected}"
            );
        }
    }

    #[test]
    fn test_all_config_fields_resolve_to_non_empty_type() {
        use schemars::schema::Schema;
        let schema = schemars::schema_for!(anodizer_core::config::Config);
        let root = schema.schema;
        let props = root
            .object
            .as_ref()
            .unwrap_or_else(|| panic!("Config should be an object schema"));

        for (name, schema) in &props.properties {
            if let Schema::Object(obj) = schema {
                let type_str = super::resolve_type_name(obj);
                assert!(
                    !type_str.is_empty(),
                    "field `{name}` resolved to an empty type string"
                );
            }
        }
    }
}
