//! Attribution strings for published content.
//!
//! Every consumer-facing artifact anodizer authors on the user's behalf — a
//! submission PR body, a generated formula/manifest header — credits the tool
//! with a pointer back to the project, so a maintainer reading the artifact
//! in an index repo can find out what produced it without guessing.

/// Canonical project URL used in published-content attributions.
#[cfg(test)]
pub(crate) const ANODIZER_URL: &str = "https://github.com/tj-smith47/anodizer";

/// Markdown footer sentence for auto-generated submission PR bodies
/// (homebrew / scoop / winget / krew / nix / schemastore). Rendered by the
/// forge, so the mention links.
pub(crate) const SUBMITTED_BY_FOOTER: &str =
    "Automatically submitted by [anodizer](https://github.com/tj-smith47/anodizer).";

/// `#`-comment header line stamped at the top of generated files (formula,
/// cask, krew/winget manifests). A comment cannot carry markdown, so the
/// bare URL rides along (auto-linked by most viewers).
pub(crate) const GENERATED_FILE_HEADER: &str =
    "# This file was generated by anodizer (https://github.com/tj-smith47/anodizer). DO NOT EDIT.";

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn attributions_agree_on_the_canonical_url() {
        assert!(SUBMITTED_BY_FOOTER.contains(ANODIZER_URL));
        assert!(GENERATED_FILE_HEADER.contains(ANODIZER_URL));
    }
}
