//! Homebrew cask generation: template, params struct, and the per-context
//! cask body builder used by both per-crate and top-level publishers.
use super::formula::build_uninstall_directives;
use anodizer_core::context::Context;
use anyhow::{Context as _, Result};
const CASK_TEMPLATE: &str = r#"# This file was generated by anodizer. DO NOT EDIT.
cask "{{ name }}" do
  version "{{ version }}"
{% if not has_platforms %}  sha256 "{{ sha256 }}"

  url "{{ url }}"
{% endif %}{% if custom_block %}{{ custom_block }}
{% endif %}{% if homepage %}  homepage "{{ homepage }}"
{% endif %}  name "{{ display_name }}"
{% for alt in alternative_names %}  name "{{ alt }}"
{% endfor %}{% if description %}  desc "{{ description }}"
{% endif %}
  livecheck do
    skip "Auto-generated on release."
  end

{% if has_platforms %}{% for plat in platforms %}  on_{{ plat.os_block }} do
{% for arch_entry in plat.arches %}    on_{{ arch_entry.arch_block }} do
      url "{{ arch_entry.url }}"
      sha256 "{{ arch_entry.sha256 }}"
    end
{% endfor %}  end

{% endfor %}{% endif %}{% if has_depends %}{% for dep in depends_on %}  depends_on {{ dep }}
{% endfor %}{% endif %}{% if has_conflicts %}  conflicts_with {% for c in conflicts_with %}{% if not loop.first %}                  {% endif %}{{ c }}{% if not loop.last %},
{% endif %}{% endfor %}

{% endif %}{% if app %}  app "{{ app }}"
{% endif %}{% for binary in binaries %}  binary "{{ binary }}"
{% endfor %}{% for manpage in manpages %}  manpage "{{ manpage }}"
{% endfor %}{% if has_completions_bash %}  bash_completion "{{ completions_bash }}"
{% endif %}{% if has_completions_zsh %}  zsh_completion "{{ completions_zsh }}"
{% endif %}{% if has_completions_fish %}  fish_completion "{{ completions_fish }}"
{% endif %}{% if has_service %}  service do
{{ service }}
  end
{% endif %}{% if has_preflight %}  preflight do
{{ preflight }}
  end
{% endif %}{% if has_postflight %}  postflight do
{{ postflight }}
  end
{% endif %}{% if has_uninstall_preflight %}  uninstall_preflight do
{{ uninstall_preflight }}
  end
{% endif %}{% if has_uninstall_postflight %}  uninstall_postflight do
{{ uninstall_postflight }}
  end
{% endif %}{% if has_caveats %}
  caveats <<~EOS
    {{ caveats }}
  EOS
{% endif %}{% if has_uninstall %}  uninstall {% for u in uninstall_items %}{% if not loop.first %}            {% endif %}{{ u }}{% if not loop.last %},
{% endif %}{% endfor %}

{% endif %}{% if has_zap %}  zap trash: [
{% for z in zap %}    "{{ z }}",
{% endfor %}  ]
{% endif %}end
"#;

// ---------------------------------------------------------------------------
// generate_cask
// ---------------------------------------------------------------------------

/// Multi-platform cask architecture entry (within an OS block).
/// Multi-platform cask architecture entry (within an OS block).
#[derive(serde::Serialize, Clone)]
pub struct CaskArchEntry {
    arch_block: String, // "intel" or "arm"
    url: String,
    sha256: String,
}

/// Multi-platform cask OS block (on_macos / on_linux).
#[derive(serde::Serialize, Clone)]
pub struct CaskPlatformBlock {
    os_block: String, // "macos" or "linux"
    arches: Vec<CaskArchEntry>,
}

/// Parameters for cask generation.
pub struct CaskParams<'a> {
    /// Cask token (lowercase hyphenated name used as `cask "name"`).
    pub name: &'a str,
    /// Display name shown in `name` stanza.
    pub display_name: &'a str,
    /// Alternative display names.
    pub alternative_names: &'a [String],
    /// Release version string.
    pub version: &'a str,
    /// SHA-256 hex digest of the download artifact.
    pub sha256: &'a str,
    /// Download URL for the .dmg/.zip/.app archive.
    pub url: &'a str,
    /// Project homepage URL.
    pub homepage: Option<&'a str>,
    /// One-line description.
    pub description: Option<&'a str>,
    /// macOS .app bundle name (e.g. "MyApp.app").
    pub app: Option<&'a str>,
    /// Binary stubs to create in /usr/local/bin (inside the .app).
    pub binaries: &'a [String],
    /// Post-install user-facing notes.
    pub caveats: Option<&'a str>,
    /// Zap stanza paths for complete uninstall cleanup.
    pub zap: &'a [String],
    /// Uninstall stanza directives (e.g. `quit: "com.example.App"`).
    pub uninstall: &'a [String],
    /// Custom Ruby code block.
    pub custom_block: Option<&'a str>,
    /// Service block content.
    pub service: Option<&'a str>,
    /// Manpage file paths.
    pub manpages: &'a [String],
    /// Bash completion file path.
    pub completions_bash: Option<&'a str>,
    /// Zsh completion file path.
    pub completions_zsh: Option<&'a str>,
    /// Fish completion file path.
    pub completions_fish: Option<&'a str>,
    /// depends_on directives (e.g. `cask: "other-app"`).
    pub depends_on: &'a [String],
    /// conflicts_with directives (e.g. `cask: "other-app"`).
    pub conflicts_with: &'a [String],
    /// Preflight hook Ruby code.
    pub preflight: Option<&'a str>,
    /// Postflight hook Ruby code.
    pub postflight: Option<&'a str>,
    /// Uninstall preflight hook Ruby code.
    pub uninstall_preflight: Option<&'a str>,
    /// Uninstall postflight hook Ruby code.
    pub uninstall_postflight: Option<&'a str>,
    /// Multi-platform entries (when set, replaces top-level url/sha256).
    pub platforms: Vec<CaskPlatformBlock>,
}

/// Generate a Homebrew Cask Ruby file string from the given parameters.
pub fn generate_cask(params: &CaskParams<'_>) -> Result<String> {
    let tera = anodizer_core::template::parse_static("cask", CASK_TEMPLATE)
        .context("homebrew: parse cask template")?;

    let mut ctx = tera::Context::new();
    ctx.insert("name", params.name);
    ctx.insert("display_name", params.display_name);
    ctx.insert("alternative_names", params.alternative_names);
    ctx.insert("version", params.version);
    ctx.insert("sha256", params.sha256);
    ctx.insert("url", params.url);

    // Multi-platform support
    let has_platforms = !params.platforms.is_empty();
    ctx.insert("has_platforms", &has_platforms);
    ctx.insert("platforms", &params.platforms);
    ctx.insert("homepage", &params.homepage.unwrap_or(""));
    ctx.insert("description", &params.description.unwrap_or(""));
    ctx.insert("app", &params.app.unwrap_or(""));
    ctx.insert("binaries", params.binaries);

    let has_caveats = params.caveats.is_some();
    ctx.insert("has_caveats", &has_caveats);
    ctx.insert("caveats", params.caveats.unwrap_or(""));

    let has_zap = !params.zap.is_empty();
    ctx.insert("has_zap", &has_zap);
    ctx.insert("zap", params.zap);

    let has_uninstall = !params.uninstall.is_empty();
    ctx.insert("has_uninstall", &has_uninstall);
    ctx.insert("uninstall_items", params.uninstall);

    // Custom block
    ctx.insert("custom_block", &params.custom_block.unwrap_or(""));

    // Service
    let has_service = params.service.is_some();
    ctx.insert("has_service", &has_service);
    ctx.insert("service", params.service.unwrap_or(""));

    // Manpages
    ctx.insert("manpages", params.manpages);

    // Completions
    let has_completions_bash = params.completions_bash.is_some();
    let has_completions_zsh = params.completions_zsh.is_some();
    let has_completions_fish = params.completions_fish.is_some();
    ctx.insert("has_completions_bash", &has_completions_bash);
    ctx.insert("completions_bash", params.completions_bash.unwrap_or(""));
    ctx.insert("has_completions_zsh", &has_completions_zsh);
    ctx.insert("completions_zsh", params.completions_zsh.unwrap_or(""));
    ctx.insert("has_completions_fish", &has_completions_fish);
    ctx.insert("completions_fish", params.completions_fish.unwrap_or(""));

    // Dependencies
    let has_depends = !params.depends_on.is_empty();
    ctx.insert("has_depends", &has_depends);
    ctx.insert("depends_on", params.depends_on);

    // Conflicts
    let has_conflicts = !params.conflicts_with.is_empty();
    ctx.insert("has_conflicts", &has_conflicts);
    ctx.insert("conflicts_with", params.conflicts_with);

    // Hooks
    let has_preflight = params.preflight.is_some();
    let has_postflight = params.postflight.is_some();
    let has_uninstall_preflight = params.uninstall_preflight.is_some();
    let has_uninstall_postflight = params.uninstall_postflight.is_some();
    ctx.insert("has_preflight", &has_preflight);
    ctx.insert("preflight", params.preflight.unwrap_or(""));
    ctx.insert("has_postflight", &has_postflight);
    ctx.insert("postflight", params.postflight.unwrap_or(""));
    ctx.insert("has_uninstall_preflight", &has_uninstall_preflight);
    ctx.insert(
        "uninstall_preflight",
        params.uninstall_preflight.unwrap_or(""),
    );
    ctx.insert("has_uninstall_postflight", &has_uninstall_postflight);
    ctx.insert(
        "uninstall_postflight",
        params.uninstall_postflight.unwrap_or(""),
    );

    anodizer_core::template::render_static(&tera, "cask", &ctx, "homebrew")
}

// ---------------------------------------------------------------------------
// generate_cask_content – shared helper for cask file generation
// ---------------------------------------------------------------------------

/// Intermediate result from cask content generation: the rendered cask file
/// string plus the cask name used as the filename stem.
pub(super) struct CaskGenResult {
    pub(super) content: String,
    pub(super) cask_name: String,
}

/// Generate a Homebrew Cask `.rb` file string from the project context.
///
/// This is the shared logic used by both [`publish_to_homebrew`] (when formula
/// and cask share a tap repo) and [`publish_cask`] (standalone).
pub(super) fn generate_cask_from_context(
    ctx: &Context,
    crate_name: &str,
    hb_cfg: &anodizer_core::config::HomebrewConfig,
    cask_cfg: &anodizer_core::config::HomebrewCaskConfig,
) -> Result<CaskGenResult> {
    let version = ctx.version();
    let cask_name = cask_cfg.name.as_deref().unwrap_or(crate_name);

    // Collect all platform artifacts: DiskImage and Archive types for macOS/Linux.
    // multi-platform casks with on_macos/on_linux + on_intel/on_arm nesting.
    let url_template = cask_cfg
        .url_template
        .as_deref()
        .or(hb_cfg.url_template.as_deref());

    let mut platform_artifacts: Vec<(&anodizer_core::artifact::Artifact, String, String)> =
        Vec::new();
    let kinds = [
        anodizer_core::artifact::ArtifactKind::DiskImage,
        anodizer_core::artifact::ArtifactKind::Archive,
        anodizer_core::artifact::ArtifactKind::UploadableBinary,
    ];
    for kind in &kinds {
        for art in ctx.artifacts.by_kind_and_crate(*kind, crate_name) {
            if !art.only_replacing_unibins() {
                continue;
            }
            let target = art.target.as_deref().unwrap_or("");
            let is_macos =
                target.contains("darwin") || target.contains("macos") || target.contains("apple");
            let is_linux = target.contains("linux");
            if !is_macos && !is_linux && !target.is_empty() {
                continue; // Skip Windows and other platforms for casks
            }
            // Skip if this OS+arch combo is already covered by a higher-priority kind
            let (os, arch) = anodizer_core::target::map_target(target);
            let key = format!("{}_{}", os, arch);
            if platform_artifacts.iter().any(|(_, k, _)| *k == key) {
                continue;
            }
            let url = if let Some(tmpl) = url_template {
                crate::util::render_url_template(tmpl, art.name(), &version, &arch, &os)
            } else if let Some(u) = art.metadata.get("url") {
                u.clone()
            } else {
                continue;
            };
            let url = url.replace(&version, "#{version}");
            let sha256 = art.metadata.get("sha256").cloned().unwrap_or_default();
            platform_artifacts.push((art, key, format!("{}|{}|{}", os, arch, url)));
            let _ = sha256; // used below
        }
    }

    // Build platform blocks for multi-platform cask support.
    // Re-collect with proper url/sha256 pairs.
    let mut platform_blocks: Vec<CaskPlatformBlock> = Vec::new();
    {
        use std::collections::BTreeMap;
        let mut os_map: BTreeMap<String, Vec<CaskArchEntry>> = BTreeMap::new();
        for kind in &kinds {
            for art in ctx.artifacts.by_kind_and_crate(*kind, crate_name) {
                if !art.only_replacing_unibins() {
                    continue;
                }
                let target = art.target.as_deref().unwrap_or("");
                let (os, arch) = anodizer_core::target::map_target(target);
                let os_block = if os == "darwin" {
                    "macos"
                } else if os == "linux" {
                    "linux"
                } else {
                    continue;
                };
                let arch_block = if arch == "amd64" || arch == "386" {
                    "intel"
                } else if arch == "arm64" {
                    "arm"
                } else {
                    continue;
                };
                let key = format!("{}_{}", os_block, arch_block);
                if os_map
                    .values()
                    .flatten()
                    .any(|e: &CaskArchEntry| format!("{}_{}", os_block, e.arch_block) == key)
                {
                    continue;
                }
                let url = if let Some(tmpl) = url_template {
                    crate::util::render_url_template(tmpl, art.name(), &version, &arch, &os)
                } else if let Some(u) = art.metadata.get("url") {
                    u.clone()
                } else {
                    continue;
                };
                let url = url.replace(&version, "#{version}");
                let sha256 = art.metadata.get("sha256").cloned().unwrap_or_default();
                os_map
                    .entry(os_block.to_string())
                    .or_default()
                    .push(CaskArchEntry {
                        arch_block: arch_block.to_string(),
                        url,
                        sha256,
                    });
            }
        }
        for (os_block, arches) in os_map {
            platform_blocks.push(CaskPlatformBlock { os_block, arches });
        }
    }

    // Find primary artifact for fallback single-platform behavior
    let primary_artifact = ctx
        .artifacts
        .by_kind_and_crate(anodizer_core::artifact::ArtifactKind::DiskImage, crate_name)
        .into_iter()
        .filter(|a| a.only_replacing_unibins())
        .find(|a| {
            a.target
                .as_deref()
                .map(|t| t.contains("darwin") || t.contains("macos"))
                .unwrap_or(true)
        })
        .or_else(|| {
            ctx.artifacts
                .by_kind_and_crate(anodizer_core::artifact::ArtifactKind::Archive, crate_name)
                .into_iter()
                .filter(|a| a.only_replacing_unibins())
                .find(|a| {
                    a.target
                        .as_deref()
                        .map(|t| t.contains("darwin") || t.contains("macos"))
                        .unwrap_or(false)
                })
        })
        .ok_or_else(|| {
            anyhow::anyhow!(
                "homebrew cask: no macOS artifact (DiskImage or Archive) found for '{}'",
                crate_name
            )
        })?;

    // Single-platform URL/SHA for backwards compatibility (used when no multi-platform blocks)
    let url = if let Some(tmpl) = url_template {
        let target = primary_artifact.target.as_deref().unwrap_or("");
        let (os, arch) = anodizer_core::target::map_target(target);
        crate::util::render_url_template(tmpl, primary_artifact.name(), &version, &arch, &os)
    } else {
        primary_artifact.metadata.get("url").cloned().ok_or_else(|| {
            anyhow::anyhow!(
                "homebrew cask: artifact for '{}' has no 'url' metadata; set url_template or ensure release uploads set artifact URLs",
                crate_name
            )
        })?
    };
    let url = url.replace(&version, "#{version}");

    let sha256 = primary_artifact
        .metadata
        .get("sha256")
        .cloned()
        .ok_or_else(|| {
            anyhow::anyhow!(
                "homebrew cask: artifact for '{}' has no 'sha256' metadata",
                crate_name
            )
        })?;

    // Use multi-platform blocks when there's more than one platform entry
    let use_platforms = platform_blocks
        .iter()
        .map(|p| p.arches.len())
        .sum::<usize>()
        > 1;

    let display_name = cask_cfg.name.as_deref().unwrap_or(crate_name);
    let empty_vec: Vec<String> = Vec::new();

    // Build dependency and conflict directive strings for the template
    let cask_depends: Vec<String> = cask_cfg
        .dependencies
        .as_deref()
        .unwrap_or(&[])
        .iter()
        .map(|d| {
            if let Some(ref c) = d.cask {
                format!("cask: \"{}\"", c)
            } else if let Some(ref f) = d.formula {
                format!("formula: \"{}\"", f)
            } else {
                String::new()
            }
        })
        .filter(|s| !s.is_empty())
        .collect();
    let cask_conflicts: Vec<String> = cask_cfg
        .conflicts
        .as_deref()
        .unwrap_or(&[])
        .iter()
        .map(|c| {
            if let Some(ref cask) = c.cask {
                format!("cask: \"{}\"", cask)
            } else if let Some(ref formula) = c.formula {
                format!("formula: \"{}\"", formula)
            } else {
                String::new()
            }
        })
        .filter(|s| !s.is_empty())
        .collect();

    // Convert structured uninstall/zap config to directive strings for template rendering.
    let uninstall_directives = build_uninstall_directives(cask_cfg.uninstall.as_ref());
    let zap_directives = build_uninstall_directives(cask_cfg.zap.as_ref());

    let params = CaskParams {
        name: cask_name,
        display_name,
        alternative_names: cask_cfg.alternative_names.as_deref().unwrap_or(&empty_vec),
        version: &version,
        sha256: &sha256,
        url: &url,
        homepage: cask_cfg.homepage.as_deref().or(hb_cfg.homepage.as_deref()),
        description: cask_cfg
            .description
            .as_deref()
            .or(hb_cfg.description.as_deref()),
        app: cask_cfg.app.as_deref(),
        binaries: cask_cfg.binaries.as_deref().unwrap_or(&empty_vec),
        caveats: cask_cfg.caveats.as_deref(),
        zap: &zap_directives,
        uninstall: &uninstall_directives,
        custom_block: cask_cfg.custom_block.as_deref(),
        service: cask_cfg.service.as_deref(),
        manpages: cask_cfg.manpages.as_deref().unwrap_or(&empty_vec),
        completions_bash: cask_cfg
            .completions
            .as_ref()
            .and_then(|c| c.bash.as_deref()),
        completions_zsh: cask_cfg.completions.as_ref().and_then(|c| c.zsh.as_deref()),
        completions_fish: cask_cfg
            .completions
            .as_ref()
            .and_then(|c| c.fish.as_deref()),
        platforms: if use_platforms {
            platform_blocks
        } else {
            Vec::new()
        },
        depends_on: &cask_depends,
        conflicts_with: &cask_conflicts,
        preflight: cask_cfg
            .hooks
            .as_ref()
            .and_then(|h| h.pre.as_ref())
            .and_then(|p| p.install.as_deref()),
        postflight: cask_cfg
            .hooks
            .as_ref()
            .and_then(|h| h.post.as_ref())
            .and_then(|p| p.install.as_deref()),
        uninstall_preflight: cask_cfg
            .hooks
            .as_ref()
            .and_then(|h| h.pre.as_ref())
            .and_then(|p| p.uninstall.as_deref()),
        uninstall_postflight: cask_cfg
            .hooks
            .as_ref()
            .and_then(|h| h.post.as_ref())
            .and_then(|p| p.uninstall.as_deref()),
    };

    Ok(CaskGenResult {
        content: generate_cask(&params)?,
        cask_name: cask_name.to_string(),
    })
}
/// Find a macOS artifact for top-level cask config.
/// Searches all artifacts (not per-crate) with optional ID filtering.
pub(super) fn find_top_level_cask_artifact<'a>(
    ctx: &'a Context,
    ids: Option<&[String]>,
) -> Option<&'a anodizer_core::artifact::Artifact> {
    let filter = |a: &&anodizer_core::artifact::Artifact| {
        if !anodizer_core::artifact::matches_id_filter(a, ids) {
            return false;
        }
        a.target
            .as_deref()
            .map(|t| t.contains("darwin") || t.contains("macos") || t.contains("apple"))
            .unwrap_or(false)
    };

    // Prefer DiskImage (with OnlyReplacingUnibins filter)
    ctx.artifacts
        .by_kind(anodizer_core::artifact::ArtifactKind::DiskImage)
        .into_iter()
        .filter(|a| a.only_replacing_unibins())
        .find(|a| filter(a))
        .or_else(|| {
            // Fall back to Archive
            ctx.artifacts
                .by_kind(anodizer_core::artifact::ArtifactKind::Archive)
                .into_iter()
                .filter(|a| a.only_replacing_unibins())
                .find(|a| filter(a))
        })
        .or_else(|| {
            // Fall back to UploadableBinary
            ctx.artifacts
                .by_kind(anodizer_core::artifact::ArtifactKind::UploadableBinary)
                .into_iter()
                .filter(|a| a.only_replacing_unibins())
                .find(|a| filter(a))
        })
}
