//! Homebrew cask generation: template, params struct, and the per-context
//! cask body builder used by both per-crate and top-level publishers.
use anodizer_core::context::Context;
use anyhow::{Context as _, Result};
const CASK_TEMPLATE: &str = r#"# This file was generated by anodizer. DO NOT EDIT.
cask "{{ name }}" do
  version "{{ version }}"
{% if not has_platforms %}  sha256 "{{ sha256 }}"

  url "{{ url }}"{{ url_extras }}
{% endif %}{% if custom_block %}{{ custom_block }}
{% endif %}{% if homepage %}  homepage "{{ homepage }}"
{% endif %}  name "{{ display_name }}"
{% for alt in alternative_names %}  name "{{ alt }}"
{% endfor %}{% if description %}  desc "{{ description }}"
{% endif %}
  livecheck do
    skip "Auto-generated on release."
  end

{% if has_platforms %}{% for plat in platforms %}  on_{{ plat.os_block }} do
{% for arch_entry in plat.arches %}    on_{{ arch_entry.arch_block }} do
      sha256 "{{ arch_entry.sha256 }}"
      url "{{ arch_entry.url }}"{{ url_extras_indented }}
    end
{% endfor %}  end

{% endfor %}{% endif %}{% if has_depends %}{% for dep in depends_on %}  depends_on {{ dep }}
{% endfor %}{% endif %}{% if has_conflicts %}  conflicts_with {% for c in conflicts_with %}{% if not loop.first %}                  {% endif %}{{ c }}{% if not loop.last %},
{% endif %}{% endfor %}

{% endif %}{% if app %}  app "{{ app }}"
{% endif %}{% for binary in binaries %}  binary "{{ binary.name }}"{% if binary.target %}, target: "{{ binary.target }}"{% endif %}
{% endfor %}{% for manpage in manpages %}  manpage "{{ manpage }}"
{% endfor %}{% if has_completions_bash %}  bash_completion "{{ completions_bash }}"
{% endif %}{% if has_completions_zsh %}  zsh_completion "{{ completions_zsh }}"
{% endif %}{% if has_completions_fish %}  fish_completion "{{ completions_fish }}"
{% endif %}{% if has_service %}  service do
{{ service }}
  end
{% endif %}{% if has_preflight %}  preflight do
{{ preflight }}
  end
{% endif %}{% if has_postflight %}  postflight do
{{ postflight }}
  end
{% endif %}{% if has_generate_completions %}
  {{ generate_completions }}
{% endif %}{% if has_uninstall_preflight %}  uninstall_preflight do
{{ uninstall_preflight }}
  end
{% endif %}{% if has_uninstall_postflight %}  uninstall_postflight do
{{ uninstall_postflight }}
  end
{% endif %}{% if has_caveats %}
  caveats <<~EOS
    {{ caveats }}
  EOS
{% endif %}{% if has_uninstall %}  {{ uninstall_block }}
{% endif %}{% if has_zap %}  {{ zap_block }}
{% endif %}end
"#;

// ---------------------------------------------------------------------------
// generate_cask
// ---------------------------------------------------------------------------

/// Cask `binary` template entry.
///
/// The bare-string YAML form `"my-cli"` deserialises to `name = "my-cli",
/// target = None`, which renders `binary "my-cli"`. The structured form
/// `{ name, target }` preserves the rename so the template emits
/// `binary "my-cli", target: "mycli"`.
#[derive(serde::Serialize, Clone)]
pub struct CaskBinaryEntry {
    /// Path inside the .app bundle.
    pub name: String,
    /// Optional rename target — symlink name in `/usr/local/bin`.
    pub target: Option<String>,
}

/// Multi-platform cask architecture entry (within an OS block).
#[derive(serde::Serialize, Clone)]
pub struct CaskArchEntry {
    pub(super) arch_block: String, // "intel" or "arm"
    pub(super) url: String,
    pub(super) sha256: String,
}

/// Multi-platform cask OS block (on_macos / on_linux).
#[derive(serde::Serialize, Clone)]
pub struct CaskPlatformBlock {
    pub(super) os_block: String, // "macos" or "linux"
    pub(super) arches: Vec<CaskArchEntry>,
}

/// Parameters for cask generation.
pub struct CaskParams<'a> {
    /// Cask token (lowercase hyphenated name used as `cask "name"`).
    pub name: &'a str,
    /// Display name shown in `name` stanza.
    pub display_name: &'a str,
    /// Alternative display names.
    pub alternative_names: &'a [String],
    /// Release version string.
    pub version: &'a str,
    /// SHA-256 hex digest of the download artifact.
    pub sha256: &'a str,
    /// Download URL for the .dmg/.zip/.app archive.
    pub url: &'a str,
    /// Project homepage URL.
    pub homepage: Option<&'a str>,
    /// One-line description.
    pub description: Option<&'a str>,
    /// macOS .app bundle name (e.g. "MyApp.app").
    pub app: Option<&'a str>,
    /// Binary stubs to create in /usr/local/bin (inside the .app).
    /// Each entry carries `{ name, target: Option<String> }` so the
    /// template can emit `binary "<n>"` (bare) or `binary "<n>", target: "<t>"`
    /// (rename form).
    pub binaries: &'a [CaskBinaryEntry],
    /// Post-install user-facing notes.
    pub caveats: Option<&'a str>,
    /// Pre-rendered `zap` stanza Ruby (full `zap launchctl: [...], quit: [...]`
    /// block) — empty string when no `zap` config is present.  Built via
    /// [`render_zap_block`].
    pub zap_block: &'a str,
    /// Pre-rendered `uninstall` stanza Ruby (full `uninstall launchctl: [...]`
    /// block) — empty string when no `uninstall` config is present.  Built
    /// via [`render_uninstall_block`].
    pub uninstall_block: &'a str,
    /// Custom Ruby code block.
    pub custom_block: Option<&'a str>,
    /// Service block content.
    pub service: Option<&'a str>,
    /// Manpage file paths.
    pub manpages: &'a [String],
    /// Bash completion file path.
    pub completions_bash: Option<&'a str>,
    /// Zsh completion file path.
    pub completions_zsh: Option<&'a str>,
    /// Fish completion file path.
    pub completions_fish: Option<&'a str>,
    /// depends_on directives (e.g. `cask: "other-app"`).
    pub depends_on: &'a [String],
    /// conflicts_with directives (e.g. `cask: "other-app"`).
    pub conflicts_with: &'a [String],
    /// Preflight hook Ruby code.
    pub preflight: Option<&'a str>,
    /// Postflight hook Ruby code.
    pub postflight: Option<&'a str>,
    /// Uninstall preflight hook Ruby code.
    pub uninstall_preflight: Option<&'a str>,
    /// Uninstall postflight hook Ruby code.
    pub uninstall_postflight: Option<&'a str>,
    /// Pre-rendered Ruby continuation for the `url` line — empty string when
    /// no [`HomebrewCaskURL`] sub-fields (`verified`, `using`, `cookies`,
    /// `referer`, `headers`, `user_agent`, `data`) are configured. When
    /// non-empty, starts with `,\n      verified: "..."` so it splices
    /// directly after the closing `"` of `url "..."`.
    pub url_extras: &'a str,
    /// Same payload as [`Self::url_extras`] but indented two extra spaces so
    /// it can splice into the per-arch `on_{intel,arm}` blocks (which are
    /// nested an extra level inside `on_macos do … end`).
    pub url_extras_indented: &'a str,
    /// Multi-platform entries (when set, replaces top-level url/sha256).
    pub platforms: Vec<CaskPlatformBlock>,
    /// Pre-rendered `generate_completions_from_executable` line (without the
    /// trailing newline). When `Some`, the cask emits an empty line + the
    /// directive after the `postflight` stanza. Build via
    /// [`render_generate_completions`] from a `HomebrewCaskGeneratedCompletions`.
    pub generate_completions: Option<String>,
}

/// Recognised `shell_parameter_format` values. Unknown values fall back
/// to a quoted string so user input round-trips without surprise.
const KNOWN_SHELL_PARAMETER_FORMATS: &[&str] =
    &["arg", "clap", "click", "cobra", "flag", "none", "typer"];

/// Render a `generate_completions_from_executable` directive from config.
///
/// Returns `None` when no executable is configured. The returned string
/// has no trailing newline and is intended to be injected directly into
/// the cask template.
///
/// Output shape:
///
/// ```ruby
/// generate_completions_from_executable "bin/myapp", "completions",
///     base_name: "myapp",
///     shell_parameter_format: :cobra,
///     shells: [:bash, :zsh, :fish, :pwsh]
/// ```
pub fn render_generate_completions(
    g: &anodizer_core::config::HomebrewCaskGeneratedCompletions,
) -> Option<String> {
    let exec = g.executable.as_deref().filter(|s| !s.is_empty())?;

    let mut args: Vec<String> = Vec::with_capacity(1 + g.args.as_deref().map_or(0, |a| a.len()));
    args.push(format!("\"{}\"", exec));
    if let Some(extra) = g.args.as_deref() {
        for a in extra {
            args.push(format!("\"{}\"", a));
        }
    }

    let mut kwargs: Vec<String> = Vec::new();
    if let Some(name) = g.base_name.as_deref().filter(|s| !s.is_empty()) {
        kwargs.push(format!("base_name: \"{}\"", name));
    }
    if let Some(fmt) = g
        .shell_parameter_format
        .as_deref()
        .filter(|s| !s.is_empty())
    {
        if KNOWN_SHELL_PARAMETER_FORMATS.contains(&fmt) {
            kwargs.push(format!("shell_parameter_format: :{}", fmt));
        } else {
            kwargs.push(format!("shell_parameter_format: \"{}\"", fmt));
        }
    }
    if let Some(shells) = g.shells.as_deref().filter(|s| !s.is_empty()) {
        let joined = shells
            .iter()
            .map(|s| format!(":{}", s))
            .collect::<Vec<_>>()
            .join(", ");
        kwargs.push(format!("shells: [{}]", joined));
    }

    let mut out = String::from("generate_completions_from_executable ");
    out.push_str(&args.join(", "));
    if !kwargs.is_empty() {
        out.push_str(",\n    ");
        out.push_str(&kwargs.join(",\n    "));
    }
    Some(out)
}

// ---------------------------------------------------------------------------
// uninstall / zap block rendering.
// ---------------------------------------------------------------------------

/// Helper: render one keyed group of items as a Ruby array literal.
///
/// ```ruby
/// launchctl: [
///       "com.example.daemon",
///     ]
/// ```
fn group_to_ruby_array(name: &str, lines: &[String]) -> String {
    let mut sb = String::new();
    sb.push_str(name);
    sb.push_str(": [\n");
    for l in lines {
        sb.push_str("      ");
        // Use Rust's `Debug` formatting for `&str` to get Ruby-compatible
        // double-quoted, backslash-escaped output for ASCII-safe strings.
        sb.push_str(&format!("{:?}", l));
        sb.push_str(",\n");
    }
    sb.push_str("    ]");
    sb
}

/// Helper: join the per-key groups into a single `<stanza> ...` Ruby block.
fn join_groups(stanza: &str, groups: &[String]) -> String {
    if groups.is_empty() {
        return String::new();
    }
    let mut sb = String::new();
    sb.push_str(stanza);
    sb.push(' ');
    for (i, group) in groups.iter().enumerate() {
        if i > 0 {
            sb.push_str("    ");
        }
        sb.push_str(group);
        if i < groups.len() - 1 {
            sb.push(',');
        }
        sb.push('\n');
    }
    // Drop the trailing newline so the template can decide spacing.
    if sb.ends_with('\n') {
        sb.pop();
    }
    sb
}

fn make_uninstall_like_groups(u: &anodizer_core::config::HomebrewCaskUninstall) -> Vec<String> {
    let mut groups = Vec::new();
    if let Some(ref items) = u.launchctl
        && !items.is_empty()
    {
        groups.push(group_to_ruby_array("launchctl", items));
    }
    if let Some(ref items) = u.quit
        && !items.is_empty()
    {
        groups.push(group_to_ruby_array("quit", items));
    }
    if let Some(ref items) = u.login_item
        && !items.is_empty()
    {
        groups.push(group_to_ruby_array("login_item", items));
    }
    if let Some(ref items) = u.delete
        && !items.is_empty()
    {
        groups.push(group_to_ruby_array("delete", items));
    }
    if let Some(ref items) = u.trash
        && !items.is_empty()
    {
        groups.push(group_to_ruby_array("trash", items));
    }
    groups
}

/// Render the full `uninstall <key>: [...], <key>: [...]` Ruby block from
/// structured uninstall config. Returns `""` when no uninstall config is
/// configured.
pub(super) fn render_uninstall_block(
    uninstall: Option<&anodizer_core::config::HomebrewCaskUninstall>,
) -> String {
    let Some(u) = uninstall else {
        return String::new();
    };
    let groups = make_uninstall_like_groups(u);
    join_groups("uninstall", &groups)
}

/// Render the full `zap <key>: [...], <key>: [...]` Ruby block from
/// structured zap config. Unlike `uninstall`, an empty config still
/// emits a `# No zap stanza required` comment so the cask file shape
/// stays identical whether or not a zap stanza is configured.
pub(super) fn render_zap_block(
    zap: Option<&anodizer_core::config::HomebrewCaskUninstall>,
) -> String {
    let Some(u) = zap else {
        return String::new();
    };
    let groups = make_uninstall_like_groups(u);
    if groups.is_empty() {
        return String::new();
    }
    join_groups("zap", &groups)
}

// ---------------------------------------------------------------------------
// additional_url_params
// ---------------------------------------------------------------------------

/// Render Ruby kwargs for the `url "<url>"` line: `verified`, `using`,
/// `cookies`, `referer`, `header`, `user_agent`, `data`. Returns `""` when
/// every sub-field is unset.
///
/// `indent` is the leading whitespace placed before each kwarg (6 spaces
/// at top level, 8 spaces when the call site is inside an
/// `on_<arch> do ... end` block). The returned string starts with `,\n`
/// + indent so it splices directly after the closing `"` of `url "..."`.
pub(super) fn render_additional_url_params(
    u: &anodizer_core::config::HomebrewCaskURL,
    indent: &str,
) -> String {
    let mut parts: Vec<String> = Vec::new();
    if let Some(ref v) = u.verified
        && !v.is_empty()
    {
        parts.push(format!("verified: \"{}\"", v));
    }
    if let Some(ref v) = u.using
        && !v.is_empty()
    {
        // `using:` accepts either a Ruby symbol (`:homebrew_curl`) or a
        // class name (no quotes). Pass through verbatim without quoting.
        parts.push(format!("using: {}", v));
    }
    if let Some(ref cookies) = u.cookies
        && !cookies.is_empty()
    {
        let mut hash = String::from("cookies: {\n");
        // Sort keys so output is deterministic across runs (HashMap iter
        // order would otherwise produce noisy diffs in committed cask
        // files).
        let mut keys: Vec<_> = cookies.keys().collect();
        keys.sort();
        for k in keys {
            let v = &cookies[k];
            hash.push_str(indent);
            hash.push_str(&format!("  \"{}\" => \"{}\",\n", k, v));
        }
        hash.push_str(indent);
        hash.push('}');
        parts.push(hash);
    }
    if let Some(ref v) = u.referer
        && !v.is_empty()
    {
        parts.push(format!("referer: \"{}\"", v));
    }
    if let Some(ref headers) = u.headers
        && !headers.is_empty()
    {
        let mut arr = String::from("header: [\n");
        for h in headers {
            arr.push_str(indent);
            arr.push_str(&format!("  \"{}\",\n", h));
        }
        arr.push_str(indent);
        arr.push(']');
        parts.push(arr);
    }
    if let Some(ref v) = u.user_agent
        && !v.is_empty()
    {
        parts.push(format!("user_agent: \"{}\"", v));
    }
    if let Some(ref data) = u.data
        && !data.is_empty()
    {
        let mut hash = String::from("data: {\n");
        let mut keys: Vec<_> = data.keys().collect();
        keys.sort();
        for k in keys {
            let v = &data[k];
            hash.push_str(indent);
            hash.push_str(&format!("  \"{}\" => \"{}\",\n", k, v));
        }
        hash.push_str(indent);
        hash.push('}');
        parts.push(hash);
    }

    if parts.is_empty() {
        return String::new();
    }
    let mut out = String::new();
    for p in &parts {
        out.push_str(",\n");
        out.push_str(indent);
        out.push_str(p);
    }
    out
}

/// Split rendered `alternative_names` into two groups:
///
/// - **Aliases**: pure-string alternative names that Homebrew treats as
///   aliases — they render as additional `name "..."` directives INSIDE
///   the primary cask file.
/// - **Versioned files**: alternative names that contain an `@` — these
///   emit a SECOND `.rb` file named after the alt entry (e.g.
///   `myapp@1.2.3.rb`) so users can `brew install myapp@1.2.3` for a
///   downgrade path.
///
/// The split follows `alternative_names:` semantics: the example
/// `myproject@{{ .Version }}` only makes sense as a separate file, since
/// using it as an alias would mean every release overwrites the previous
/// version's record.
pub(super) fn split_alternative_names(
    rendered: &[String],
    cask_name: &str,
) -> (Vec<String>, Vec<String>) {
    let mut aliases: Vec<String> = Vec::new();
    let mut versioned: Vec<String> = Vec::new();
    for entry in rendered {
        let trimmed = entry.trim();
        if trimmed.is_empty() || trimmed == cask_name {
            continue;
        }
        if trimmed.contains('@') {
            versioned.push(trimmed.to_string());
        } else {
            aliases.push(trimmed.to_string());
        }
    }
    (aliases, versioned)
}

/// Pre-render every `alternative_names` entry through the user's template
/// engine. A failure surfaces as `Err` so a typo in the template doesn't
/// silently degrade the rendered cask body.
pub(super) fn render_alternative_names(ctx: &Context, raw: &[String]) -> Result<Vec<String>> {
    let mut out: Vec<String> = Vec::with_capacity(raw.len());
    for entry in raw {
        let rendered = ctx.render_template(entry).with_context(|| {
            format!("homebrew cask: render alternative_names entry '{}'", entry)
        })?;
        out.push(rendered);
    }
    Ok(out)
}

/// Generate a Homebrew Cask Ruby file string from the given parameters.
pub fn generate_cask(params: &CaskParams<'_>) -> Result<String> {
    let tera = anodizer_core::template::parse_static("cask", CASK_TEMPLATE)
        .context("homebrew: parse cask template")?;

    let mut ctx = tera::Context::new();
    ctx.insert("name", params.name);
    ctx.insert("display_name", params.display_name);
    ctx.insert("alternative_names", params.alternative_names);
    ctx.insert("version", params.version);
    ctx.insert("sha256", params.sha256);
    ctx.insert("url", params.url);
    ctx.insert("url_extras", params.url_extras);
    ctx.insert("url_extras_indented", params.url_extras_indented);

    // Multi-platform support
    let has_platforms = !params.platforms.is_empty();
    ctx.insert("has_platforms", &has_platforms);
    ctx.insert("platforms", &params.platforms);
    // Optional cask stanzas — every `unwrap_or("")` below pairs with either a
    // `{% if foo %}` truthy-guard or a sibling `has_<foo>` boolean in
    // CASK_TEMPLATE (see top of file). Empty values render as no-stanza in the
    // Ruby output. Homebrew Cask DSL accepts cask blocks without homepage,
    // desc, caveats, service, hooks, etc. — none are required by `brew style`.
    ctx.insert("homepage", &params.homepage.unwrap_or(""));
    ctx.insert("description", &params.description.unwrap_or(""));
    ctx.insert("app", &params.app.unwrap_or(""));
    ctx.insert("binaries", params.binaries);

    let has_caveats = params.caveats.is_some();
    ctx.insert("has_caveats", &has_caveats);
    ctx.insert("caveats", params.caveats.unwrap_or(""));

    let has_zap = !params.zap_block.is_empty();
    ctx.insert("has_zap", &has_zap);
    ctx.insert("zap_block", params.zap_block);

    let has_uninstall = !params.uninstall_block.is_empty();
    ctx.insert("has_uninstall", &has_uninstall);
    ctx.insert("uninstall_block", params.uninstall_block);

    // Custom block
    ctx.insert("custom_block", &params.custom_block.unwrap_or(""));

    // Service
    let has_service = params.service.is_some();
    ctx.insert("has_service", &has_service);
    ctx.insert("service", params.service.unwrap_or(""));

    // Manpages
    ctx.insert("manpages", params.manpages);

    // Completions
    let has_completions_bash = params.completions_bash.is_some();
    let has_completions_zsh = params.completions_zsh.is_some();
    let has_completions_fish = params.completions_fish.is_some();
    ctx.insert("has_completions_bash", &has_completions_bash);
    ctx.insert("completions_bash", params.completions_bash.unwrap_or(""));
    ctx.insert("has_completions_zsh", &has_completions_zsh);
    ctx.insert("completions_zsh", params.completions_zsh.unwrap_or(""));
    ctx.insert("has_completions_fish", &has_completions_fish);
    ctx.insert("completions_fish", params.completions_fish.unwrap_or(""));

    // Dependencies
    let has_depends = !params.depends_on.is_empty();
    ctx.insert("has_depends", &has_depends);
    ctx.insert("depends_on", params.depends_on);

    // Conflicts
    let has_conflicts = !params.conflicts_with.is_empty();
    ctx.insert("has_conflicts", &has_conflicts);
    ctx.insert("conflicts_with", params.conflicts_with);

    // Hooks
    let has_preflight = params.preflight.is_some();
    let has_postflight = params.postflight.is_some();
    let has_uninstall_preflight = params.uninstall_preflight.is_some();
    let has_uninstall_postflight = params.uninstall_postflight.is_some();
    ctx.insert("has_preflight", &has_preflight);
    ctx.insert("preflight", params.preflight.unwrap_or(""));
    ctx.insert("has_postflight", &has_postflight);
    ctx.insert("postflight", params.postflight.unwrap_or(""));
    ctx.insert("has_uninstall_preflight", &has_uninstall_preflight);
    ctx.insert(
        "uninstall_preflight",
        params.uninstall_preflight.unwrap_or(""),
    );
    ctx.insert("has_uninstall_postflight", &has_uninstall_postflight);
    ctx.insert(
        "uninstall_postflight",
        params.uninstall_postflight.unwrap_or(""),
    );

    // generate_completions_from_executable (rendered after postflight:
    // postflight may strip the macOS quarantine attribute, which must run
    // before Homebrew executes the binary to generate completions).
    let has_generate_completions = params.generate_completions.is_some();
    ctx.insert("has_generate_completions", &has_generate_completions);
    ctx.insert(
        "generate_completions",
        params.generate_completions.as_deref().unwrap_or(""),
    );

    anodizer_core::template::render_static(&tera, "cask", &ctx, "homebrew")
}

// ---------------------------------------------------------------------------
// generate_cask_content – shared helper for cask file generation
// ---------------------------------------------------------------------------

/// Intermediate result from cask content generation: the rendered cask file
/// string, the cask name used as the filename stem, and any versioned
/// alternative-name files to emit alongside (one extra `.rb` per entry).
pub(super) struct CaskGenResult {
    pub(super) content: String,
    pub(super) cask_name: String,
    /// Tuples of (filename-stem, file-body) for each versioned alt-name
    /// (e.g. `myapp@1.2.3`). Empty when no alt-name templated to a
    /// versioned form. Each body is the same as `content` but with the
    /// `cask "<name>"` header re-keyed to the alt-name so
    /// `brew install <alt>` resolves to the version-pinned cask.
    pub(super) versioned_files: Vec<(String, String)>,
}

/// Generate a Homebrew Cask `.rb` file string from the project context.
///
/// This is the shared logic used by both [`publish_to_homebrew`] (when formula
/// and cask share a tap repo) and [`publish_cask`] (standalone).
pub(super) fn generate_cask_from_context(
    ctx: &Context,
    crate_name: &str,
    hb_cfg: &anodizer_core::config::HomebrewConfig,
    cask_cfg: &anodizer_core::config::HomebrewCaskConfig,
) -> Result<CaskGenResult> {
    let version = ctx.version();
    let cask_name = cask_cfg.name.as_deref().unwrap_or(crate_name);

    // Collect all platform artifacts: DiskImage and Archive types for macOS/Linux.
    // multi-platform casks with on_macos/on_linux + on_intel/on_arm nesting.
    let url_template = cask_cfg
        .url_template
        .as_deref()
        .or(hb_cfg.url_template.as_deref());

    let mut platform_artifacts: Vec<(&anodizer_core::artifact::Artifact, String, String)> =
        Vec::new();
    let kinds = [
        anodizer_core::artifact::ArtifactKind::DiskImage,
        anodizer_core::artifact::ArtifactKind::Archive,
        anodizer_core::artifact::ArtifactKind::UploadableBinary,
    ];
    for kind in &kinds {
        for art in ctx.artifacts.by_kind_and_crate(*kind, crate_name) {
            if !art.only_replacing_unibins() {
                continue;
            }
            let target = art.target.as_deref().unwrap_or("");
            let is_macos =
                target.contains("darwin") || target.contains("macos") || target.contains("apple");
            let is_linux = target.contains("linux");
            if !is_macos && !is_linux && !target.is_empty() {
                continue; // Skip Windows and other platforms for casks
            }
            // Skip if this OS+arch combo is already covered by a higher-priority kind
            let (os, arch) = anodizer_core::target::map_target(target);
            let key = format!("{}_{}", os, arch);
            if platform_artifacts.iter().any(|(_, k, _)| *k == key) {
                continue;
            }
            let url = if let Some(tmpl) = url_template {
                crate::util::render_url_template_with_ctx(
                    ctx,
                    tmpl,
                    art.name(),
                    &version,
                    &arch,
                    &os,
                )
            } else if let Some(u) = art.metadata.get("url") {
                u.clone()
            } else {
                continue;
            };
            let url = url.replace(&version, "#{version}");
            // sha256 is fetched again in the second collection pass below
            // (the one that actually populates CaskArchEntry); both lookups
            // are bail-on-missing there, so any artifact reaching this loop
            // is already known to carry sha256 metadata. Discard locally.
            platform_artifacts.push((art, key, format!("{}|{}|{}", os, arch, url)));
        }
    }

    // Build platform blocks for multi-platform cask support.
    // Re-collect with proper url/sha256 pairs.
    let mut platform_blocks: Vec<CaskPlatformBlock> = Vec::new();
    {
        use std::collections::BTreeMap;
        let mut os_map: BTreeMap<String, Vec<CaskArchEntry>> = BTreeMap::new();
        for kind in &kinds {
            for art in ctx.artifacts.by_kind_and_crate(*kind, crate_name) {
                if !art.only_replacing_unibins() {
                    continue;
                }
                let target = art.target.as_deref().unwrap_or("");
                let (os, arch) = anodizer_core::target::map_target(target);
                let os_block = if os == "darwin" {
                    "macos"
                } else if os == "linux" {
                    "linux"
                } else {
                    continue;
                };
                let arch_block = if arch == "amd64" || arch == "386" {
                    "intel"
                } else if arch == "arm64" {
                    "arm"
                } else {
                    continue;
                };
                let key = format!("{}_{}", os_block, arch_block);
                if os_map
                    .values()
                    .flatten()
                    .any(|e: &CaskArchEntry| format!("{}_{}", os_block, e.arch_block) == key)
                {
                    continue;
                }
                let url = if let Some(tmpl) = url_template {
                    crate::util::render_url_template_with_ctx(
                        ctx,
                        tmpl,
                        art.name(),
                        &version,
                        &arch,
                        &os,
                    )
                } else if let Some(u) = art.metadata.get("url") {
                    u.clone()
                } else {
                    continue;
                };
                let url = url.replace(&version, "#{version}");
                let sha256 = art
                    .metadata
                    .get("sha256")
                    .cloned()
                    .filter(|s| !s.is_empty())
                    .ok_or_else(|| {
                        anyhow::anyhow!(
                            "homebrew cask: artifact '{}' (os={}, arch={}) for crate '{}' \
                             is missing required sha256 metadata. A multi-platform cask \
                             block with an empty `sha256 \"\"` line fails `brew style` and \
                             aborts `brew install` (Homebrew verifies the SHA before \
                             extracting). This indicates the artifacts.json catalog dropped \
                             the entry's sha256 before the publish stage. Re-run with \
                             `task release` from a clean dist/ and verify dist/artifacts.json \
                             carries metadata.sha256 for every macOS/Linux artifact.",
                            art.name(),
                            os_block,
                            arch_block,
                            crate_name,
                        )
                    })?;
                os_map
                    .entry(os_block.to_string())
                    .or_default()
                    .push(CaskArchEntry {
                        arch_block: arch_block.to_string(),
                        url,
                        sha256,
                    });
            }
        }
        for (os_block, arches) in os_map {
            platform_blocks.push(CaskPlatformBlock { os_block, arches });
        }
    }

    // Find primary artifact for fallback single-platform behavior
    let primary_artifact = ctx
        .artifacts
        .by_kind_and_crate(anodizer_core::artifact::ArtifactKind::DiskImage, crate_name)
        .into_iter()
        .filter(|a| a.only_replacing_unibins())
        .find(|a| {
            a.target
                .as_deref()
                .map(|t| t.contains("darwin") || t.contains("macos"))
                .unwrap_or(true)
        })
        .or_else(|| {
            ctx.artifacts
                .by_kind_and_crate(anodizer_core::artifact::ArtifactKind::Archive, crate_name)
                .into_iter()
                .filter(|a| a.only_replacing_unibins())
                .find(|a| {
                    a.target
                        .as_deref()
                        .map(|t| t.contains("darwin") || t.contains("macos"))
                        .unwrap_or(false)
                })
        })
        .ok_or_else(|| {
            anyhow::anyhow!(
                "homebrew cask: no macOS artifact (DiskImage or Archive) found for '{}'",
                crate_name
            )
        })?;

    // Single-platform URL/SHA for backwards compatibility (used when no multi-platform blocks)
    let url = if let Some(tmpl) = url_template {
        let target = primary_artifact.target.as_deref().unwrap_or("");
        let (os, arch) = anodizer_core::target::map_target(target);
        crate::util::render_url_template_with_ctx(
            ctx,
            tmpl,
            primary_artifact.name(),
            &version,
            &arch,
            &os,
        )
    } else {
        primary_artifact.metadata.get("url").cloned().ok_or_else(|| {
            anyhow::anyhow!(
                "homebrew cask: artifact for '{}' has no 'url' metadata; set url_template or ensure release uploads set artifact URLs",
                crate_name
            )
        })?
    };
    let url = url.replace(&version, "#{version}");

    let sha256 = primary_artifact
        .metadata
        .get("sha256")
        .cloned()
        .ok_or_else(|| {
            anyhow::anyhow!(
                "homebrew cask: artifact for '{}' has no 'sha256' metadata",
                crate_name
            )
        })?;

    // Use multi-platform blocks when there's more than one platform entry
    let use_platforms = platform_blocks
        .iter()
        .map(|p| p.arches.len())
        .sum::<usize>()
        > 1;

    let display_name = cask_cfg.name.as_deref().unwrap_or(crate_name);
    let empty_vec: Vec<String> = Vec::new();

    // Map config-side `HomebrewCaskBinary` entries (untagged enum: bare string
    // OR `{ name, target }`) into the template-side `CaskBinaryEntry` shape so
    // the template renders `binary "<n>"` for the bare form and
    // `binary "<n>", target: "<t>"` when the rename target is set.
    let cask_binaries: Vec<CaskBinaryEntry> = cask_cfg
        .binaries
        .as_deref()
        .unwrap_or(&[])
        .iter()
        .map(|b| CaskBinaryEntry {
            name: b.name().to_string(),
            target: b.target().map(str::to_string),
        })
        .collect();

    // Build dependency and conflict directive strings for the template
    let cask_depends: Vec<String> = cask_cfg
        .dependencies
        .as_deref()
        .unwrap_or(&[])
        .iter()
        .map(|d| {
            if let Some(ref c) = d.cask {
                format!("cask: \"{}\"", c)
            } else if let Some(ref f) = d.formula {
                format!("formula: \"{}\"", f)
            } else {
                String::new()
            }
        })
        .filter(|s| !s.is_empty())
        .collect();
    let cask_conflicts: Vec<String> = cask_cfg
        .conflicts
        .as_deref()
        .unwrap_or(&[])
        .iter()
        .map(|c| {
            if let Some(ref cask) = c.cask {
                format!("cask: \"{}\"", cask)
            } else if let Some(ref formula) = c.formula {
                format!("formula: \"{}\"", formula)
            } else {
                String::new()
            }
        })
        .filter(|s| !s.is_empty())
        .collect();

    // Each `uninstall` / `zap` sub-key (`launchctl`, `quit`, `login_item`,
    // `delete`, `trash`) renders as its own keyed Ruby array. The prior
    // shape hard-coded `zap trash: [...]` and shoved every sub-directive
    // into that array, producing broken Ruby for non-trash directives.
    let uninstall_block = render_uninstall_block(cask_cfg.uninstall.as_ref());
    let zap_block = render_zap_block(cask_cfg.zap.as_ref());

    // Pre-rendered Ruby kwargs continuation for the `url` line. When the
    // cask config does not set `url:` (a `url_template` was used instead),
    // there are no kwargs to splice — empty string emits `url "..."` with
    // no trailing kwargs, which is valid Cask DSL.
    let url_extras_top = cask_cfg
        .url
        .as_ref()
        .map(|u| render_additional_url_params(u, "      "))
        .unwrap_or_default();
    let url_extras_arch = cask_cfg
        .url
        .as_ref()
        .map(|u| render_additional_url_params(u, "        "))
        .unwrap_or_default();

    // Pre-render every `alternative_names` entry through the user's
    // template engine. Entries like `myproject@{{ .Version }}` are
    // templated, not literal. Without this pass the rendered Ruby would
    // carry the unresolved `{{ .Version }}` substring and `brew style`
    // would reject it.
    let rendered_alts = render_alternative_names(
        ctx,
        cask_cfg.alternative_names.as_deref().unwrap_or(&empty_vec),
    )?;
    let (alias_alts, versioned_alts) = split_alternative_names(&rendered_alts, cask_name);

    let params = CaskParams {
        name: cask_name,
        display_name,
        alternative_names: &alias_alts,
        version: &version,
        sha256: &sha256,
        url: &url,
        url_extras: &url_extras_top,
        url_extras_indented: &url_extras_arch,
        // Fallback chain: per-cask homepage → per-formula homepage →
        // project metadata.homepage. Lets a monorepo declare project
        // metadata once and have every cask inherit it.
        homepage: cask_cfg
            .homepage
            .as_deref()
            .or(hb_cfg.homepage.as_deref())
            .or_else(|| ctx.config.meta_homepage_for(crate_name)),
        description: cask_cfg
            .description
            .as_deref()
            .or(hb_cfg.description.as_deref())
            .or_else(|| ctx.config.meta_description_for(crate_name)),
        app: cask_cfg.app.as_deref(),
        binaries: &cask_binaries,
        caveats: cask_cfg.caveats.as_deref(),
        zap_block: &zap_block,
        uninstall_block: &uninstall_block,
        custom_block: cask_cfg.custom_block.as_deref(),
        service: cask_cfg.service.as_deref(),
        manpages: cask_cfg.manpages.as_deref().unwrap_or(&empty_vec),
        completions_bash: cask_cfg
            .completions
            .as_ref()
            .and_then(|c| c.bash.as_deref()),
        completions_zsh: cask_cfg.completions.as_ref().and_then(|c| c.zsh.as_deref()),
        completions_fish: cask_cfg
            .completions
            .as_ref()
            .and_then(|c| c.fish.as_deref()),
        platforms: if use_platforms {
            platform_blocks
        } else {
            Vec::new()
        },
        depends_on: &cask_depends,
        conflicts_with: &cask_conflicts,
        preflight: cask_cfg
            .hooks
            .as_ref()
            .and_then(|h| h.pre.as_ref())
            .and_then(|p| p.install.as_deref()),
        postflight: cask_cfg
            .hooks
            .as_ref()
            .and_then(|h| h.post.as_ref())
            .and_then(|p| p.install.as_deref()),
        uninstall_preflight: cask_cfg
            .hooks
            .as_ref()
            .and_then(|h| h.pre.as_ref())
            .and_then(|p| p.uninstall.as_deref()),
        uninstall_postflight: cask_cfg
            .hooks
            .as_ref()
            .and_then(|h| h.post.as_ref())
            .and_then(|p| p.uninstall.as_deref()),
        generate_completions: cask_cfg
            .generate_completions_from_executable
            .as_ref()
            .and_then(render_generate_completions),
    };

    let content = generate_cask(&params)?;

    // For each versioned alt-name, emit a second .rb whose body re-keys
    // the `cask "<name>" do` header to the alt-name and drops the
    // (cosmetic) `alternative_names` aliases — the alt-name's own file
    // does not need to advertise the others. The versioned cask is the
    // pin: it points at the same URL/sha256 as the primary cask body, so
    // a user who pinned to `myapp@1.2.3` can downgrade and stay there.
    let mut versioned_files: Vec<(String, String)> = Vec::with_capacity(versioned_alts.len());
    for alt in &versioned_alts {
        let alt_params = CaskParams {
            name: alt,
            display_name: alt,
            // Inside the versioned cask file, don't carry the alias list;
            // the file's identity IS the alt-name.
            alternative_names: &[],
            ..clone_cask_params(&params)
        };
        let body = generate_cask(&alt_params)?;
        versioned_files.push((alt.clone(), body));
    }

    Ok(CaskGenResult {
        content,
        cask_name: cask_name.to_string(),
        versioned_files,
    })
}

/// Borrow-shaped clone of [`CaskParams`] used when re-rendering the same
/// cask body under a different `name` / `display_name` (the versioned
/// alt-name path). All references re-bind to the source struct's
/// lifetime so the alt-name's own slices stay independent.
pub(super) fn clone_cask_params<'a>(p: &'a CaskParams<'a>) -> CaskParams<'a> {
    CaskParams {
        name: p.name,
        display_name: p.display_name,
        alternative_names: p.alternative_names,
        version: p.version,
        sha256: p.sha256,
        url: p.url,
        url_extras: p.url_extras,
        url_extras_indented: p.url_extras_indented,
        homepage: p.homepage,
        description: p.description,
        app: p.app,
        binaries: p.binaries,
        caveats: p.caveats,
        zap_block: p.zap_block,
        uninstall_block: p.uninstall_block,
        custom_block: p.custom_block,
        service: p.service,
        manpages: p.manpages,
        completions_bash: p.completions_bash,
        completions_zsh: p.completions_zsh,
        completions_fish: p.completions_fish,
        platforms: p.platforms.clone(),
        depends_on: p.depends_on,
        conflicts_with: p.conflicts_with,
        preflight: p.preflight,
        postflight: p.postflight,
        uninstall_preflight: p.uninstall_preflight,
        uninstall_postflight: p.uninstall_postflight,
        generate_completions: p.generate_completions.clone(),
    }
}
/// Find a macOS artifact for top-level cask config.
/// Searches all artifacts (not per-crate) with optional ID filtering.
pub(super) fn find_top_level_cask_artifact<'a>(
    ctx: &'a Context,
    ids: Option<&[String]>,
) -> Option<&'a anodizer_core::artifact::Artifact> {
    let filter = |a: &&anodizer_core::artifact::Artifact| {
        if !anodizer_core::artifact::matches_id_filter(a, ids) {
            return false;
        }
        a.target
            .as_deref()
            .map(|t| t.contains("darwin") || t.contains("macos") || t.contains("apple"))
            .unwrap_or(false)
    };

    // Prefer DiskImage (with OnlyReplacingUnibins filter)
    ctx.artifacts
        .by_kind(anodizer_core::artifact::ArtifactKind::DiskImage)
        .into_iter()
        .filter(|a| a.only_replacing_unibins())
        .find(|a| filter(a))
        .or_else(|| {
            // Fall back to Archive
            ctx.artifacts
                .by_kind(anodizer_core::artifact::ArtifactKind::Archive)
                .into_iter()
                .filter(|a| a.only_replacing_unibins())
                .find(|a| filter(a))
        })
        .or_else(|| {
            // Fall back to UploadableBinary
            ctx.artifacts
                .by_kind(anodizer_core::artifact::ArtifactKind::UploadableBinary)
                .into_iter()
                .filter(|a| a.only_replacing_unibins())
                .find(|a| filter(a))
        })
}
