//! Homebrew formula generation: template, options, and dependency directive
//! helpers.
use anodizer_core::template::ruby_escape_str;
use anyhow::{Context as _, Result};

// ---------------------------------------------------------------------------
// Homebrew formula Tera template
// ---------------------------------------------------------------------------
const FORMULA_TEMPLATE: &str = r#"# This file was generated by anodizer. DO NOT EDIT.
# typed: false
# frozen_string_literal: true
{% if custom_require %}
require_relative "{{ custom_require | ruby_escape }}"
{% endif %}
class {{ class_name }} < Formula
  desc "{{ description | ruby_escape }}"
  homepage "{{ homepage | ruby_escape }}"
{% if license_stanza %}  {{ license_stanza }}
{% elif license %}  license "{{ license | ruby_escape }}"
{% endif %}
  version "{{ version | ruby_escape }}"

{% if single_archive %}  url "{{ single_url | ruby_escape }}"{% if download_strategy %}, using: {{ download_strategy }}{% endif %}{% if url_headers %},
    headers: [
{% for header in url_headers %}      "{{ header | ruby_escape }}",
{% endfor %}    ]{% endif %}

  sha256 "{{ single_sha256 | ruby_escape }}"
{% endif %}{% for entry in unknown_entries %}  # platform: {{ entry.platform }}
  url "{{ entry.url | ruby_escape }}"{% if download_strategy %}, using: {{ download_strategy }}{% endif %}{% if url_headers %},
    headers: [
{% for header in url_headers %}      "{{ header | ruby_escape }}",
{% endfor %}    ]{% endif %}

  sha256 "{{ entry.sha256 | ruby_escape }}"
{% endfor %}{% if depends_on_macos %}  depends_on :macos
{% endif %}{% if depends_on_linux %}  depends_on :linux
{% endif %}{% if has_macos %}  on_macos do
{% if has_only_amd64_macos %}    url "{{ macos_entries.0.url | ruby_escape }}"{% if download_strategy %}, using: {{ download_strategy }}{% endif %}{% if url_headers %},
      headers: [
{% for header in url_headers %}        "{{ header | ruby_escape }}",
{% endfor %}      ]{% endif %}

    sha256 "{{ macos_entries.0.sha256 | ruby_escape }}"

    def install
{% for line in install_lines %}      {{ line }}
{% endfor %}{% for line in extra_install_lines %}      {{ line }}
{% endfor %}    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the {{ name }}
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
{% elif macos_has_arch %}{% for entry in macos_entries %}    {{ entry.arch_block }} do
      url "{{ entry.url | ruby_escape }}"{% if download_strategy %}, using: {{ download_strategy }}{% endif %}{% if url_headers %},
        headers: [
{% for header in url_headers %}          "{{ header | ruby_escape }}",
{% endfor %}        ]{% endif %}

      sha256 "{{ entry.sha256 | ruby_escape }}"

      def install
{% for line in install_lines %}        {{ line }}
{% endfor %}{% for line in extra_install_lines %}        {{ line }}
{% endfor %}      end
    end
{% endfor %}{% else %}{% for entry in macos_entries %}    url "{{ entry.url | ruby_escape }}"{% if download_strategy %}, using: {{ download_strategy }}{% endif %}{% if url_headers %},
      headers: [
{% for header in url_headers %}        "{{ header | ruby_escape }}",
{% endfor %}      ]{% endif %}

    sha256 "{{ entry.sha256 | ruby_escape }}"

    def install
{% for line in install_lines %}      {{ line }}
{% endfor %}{% for line in extra_install_lines %}      {{ line }}
{% endfor %}    end
{% endfor %}{% endif %}  end
{% endif %}{% if has_linux %}  on_linux do
{% if linux_has_arch %}{% for entry in linux_entries %}    {{ entry.arch_block }}
      url "{{ entry.url | ruby_escape }}"{% if download_strategy %}, using: {{ download_strategy }}{% endif %}{% if url_headers %},
        headers: [
{% for header in url_headers %}          "{{ header | ruby_escape }}",
{% endfor %}        ]{% endif %}

      sha256 "{{ entry.sha256 | ruby_escape }}"

      def install
{% for line in install_lines %}        {{ line }}
{% endfor %}{% for line in extra_install_lines %}        {{ line }}
{% endfor %}      end
    end
{% endfor %}{% else %}{% for entry in linux_entries %}    url "{{ entry.url | ruby_escape }}"{% if download_strategy %}, using: {{ download_strategy }}{% endif %}{% if url_headers %},
      headers: [
{% for header in url_headers %}        "{{ header | ruby_escape }}",
{% endfor %}      ]{% endif %}

    sha256 "{{ entry.sha256 | ruby_escape }}"

    def install
{% for line in install_lines %}      {{ line }}
{% endfor %}{% for line in extra_install_lines %}      {{ line }}
{% endfor %}    end
{% endfor %}{% endif %}  end
{% endif %}{% for dep in global_deps %}
  depends_on "{{ dep.name | ruby_escape }}"{% if dep.version %} => "{{ dep.version | ruby_escape }}"{% elif dep.optional %} => :optional{% endif %}
{% endfor %}{% for dep in macos_deps %}
  on_macos do
    depends_on "{{ dep.name | ruby_escape }}"{% if dep.version %} => "{{ dep.version | ruby_escape }}"{% elif dep.optional %} => :optional{% endif %}
  end
{% endfor %}{% for dep in linux_deps %}
  on_linux do
    depends_on "{{ dep.name | ruby_escape }}"{% if dep.version %} => "{{ dep.version | ruby_escape }}"{% elif dep.optional %} => :optional{% endif %}
  end
{% endfor %}{% for c in conflicts %}
  conflicts_with "{{ c.name | ruby_escape }}"{% if c.because %}, because: "{{ c.because | ruby_escape }}"{% endif %}
{% endfor %}{% if custom_block %}
{{ custom_block }}
{% endif %}{% if single_archive or not has_platform_blocks %}
  def install
{% for line in install_lines %}    {{ line }}
{% endfor %}{% for line in extra_install_lines %}    {{ line }}
{% endfor %}  end
{% endif %}{% if has_post_install %}
  def post_install
{% for line in post_install_lines %}    {{ line }}
{% endfor %}  end
{% endif %}
{% if has_livecheck %}  livecheck do
{% for line in livecheck_lines %}    {{ line }}
{% endfor %}  end

{% endif %}  test do
{% for line in test_lines %}    {{ line }}
{% endfor %}  end
{% if has_caveats %}
  def caveats
    <<~EOS
      {{ caveats }}
    EOS
  end
{% endif %}{% if has_plist %}
  plist_options startup: true

  def plist
    <<~EOS
{{ plist }}
    EOS
  end
{% endif %}{% if has_service %}
  service do
{{ service }}
  end
{% endif %}end
"#;

// ---------------------------------------------------------------------------
// Homebrew Cask Tera template
// ---------------------------------------------------------------------------
/// Optional extended fields for formula generation.
#[derive(Default)]
pub struct FormulaOptions<'a> {
    /// Explicit homepage URL.  Falls back to the GitHub release URL when available.
    pub homepage: Option<&'a str>,
    /// GitHub owner/name for default homepage fallback (e.g. "owner/repo").
    pub github_slug: Option<String>,
    /// Package dependencies.
    pub dependencies: Option<&'a [anodizer_core::config::HomebrewDependency]>,
    /// Conflicting formula names (with optional reason).
    pub conflicts: Option<&'a [anodizer_core::config::HomebrewConflict]>,
    /// Post-install user-facing notes.
    pub caveats: Option<&'a str>,
    /// Additional install commands appended after main install block.
    pub extra_install: Option<&'a str>,
    /// Post-install method body (separate from install).
    pub post_install: Option<&'a str>,
    /// Custom download strategy class name.
    pub download_strategy: Option<&'a str>,
    /// URL headers for download requests.
    pub url_headers: Option<&'a [String]>,
    /// Custom `require` statement for download strategies.
    pub custom_require: Option<&'a str>,
    /// Custom Ruby code block in the formula body.
    pub custom_block: Option<&'a str>,
    /// Launchd plist content.
    pub plist: Option<&'a str>,
    /// Homebrew service block content.
    pub service: Option<&'a str>,
    /// Pre-rendered `livecheck do … end` block body (the lines *between*
    /// `livecheck do` and `end`, already indented). `None` ⇒ no livecheck
    /// stanza. Build via [`render_formula_livecheck`].
    pub livecheck: Option<String>,
    /// License stanza override. When `Some`, this raw Ruby replaces the
    /// `license "<id>"` form so dual-license SPDX expressions can render as
    /// `license any_of: [...]` / `license all_of: [...]`. When `None`, the
    /// renderer falls back to `license "<FormulaCore.license>"` (single id).
    /// Build via [`render_formula_license`].
    pub license_stanza: Option<String>,
}

/// Package identity — name, version, description, license. The fields
/// emitted as plain template variables (`{{ name }}` etc.) by every
/// formula renderer.
#[derive(Clone, Copy)]
pub struct FormulaCore<'a> {
    pub name: &'a str,
    pub version: &'a str,
    pub description: &'a str,
    pub license: &'a str,
}

/// Ruby code blocks emitted into the formula body — `install do … end` and
/// `test do … end`. Pre-rendered before reaching the renderer so that
/// templating decisions stay outside this module.
#[derive(Clone, Copy)]
pub struct FormulaCode<'a> {
    pub install: &'a str,
    pub test: &'a str,
}

/// Generate a Homebrew Ruby formula string.
///
/// `archives` is a slice of `(platform_tag, url, sha256)` tuples.
/// When there is a single archive entry (no `on_` OS block needed) the formula
/// uses a flat `url`/`sha256` pair; otherwise it emits an `on_macos`/`on_linux`
/// block per entry.
pub fn generate_formula(
    core: &FormulaCore<'_>,
    archives: &[(&str, &str, &str)],
    code: &FormulaCode<'_>,
) -> Result<String> {
    generate_formula_with_opts(core, archives, code, &FormulaOptions::default())
}

/// Generate a Homebrew Ruby formula string with extended options.
pub fn generate_formula_with_opts(
    core: &FormulaCore<'_>,
    archives: &[(&str, &str, &str)],
    code: &FormulaCode<'_>,
    opts: &FormulaOptions<'_>,
) -> Result<String> {
    let FormulaCore {
        name,
        version,
        description,
        license,
    } = *core;
    let FormulaCode { install, test } = *code;
    // Ruby class name conversion.
    //
    // Rules:
    // - Lowercase the entire name first
    // - `+` is replaced with `x`
    // - `@` is replaced with `AT` only when followed by a digit
    // - Split on `-`, `_`, and `.` (all are word separators)
    // - Each segment is Title-cased and joined
    let class_name: String = {
        let name_lower = name.to_lowercase();
        let s = name_lower.replace('+', "x");
        // Replace `@` with `AT` only when followed by a digit (e.g., foo@2 -> fooAT2,
        // but foo@bar stays as foo@bar).
        let mut at_replaced = String::new();
        let chars: Vec<char> = s.chars().collect();
        let mut skip_next = false;
        for (i, ch) in chars.iter().enumerate() {
            if skip_next {
                skip_next = false;
                continue;
            }
            if *ch == '@' && i + 1 < chars.len() && chars[i + 1].is_ascii_digit() {
                at_replaced.push_str("AT");
                // The digit after '@' is consumed as part of the "AT<digit>"
                // replacement — push it now and skip it in the next iteration
                // (advance `i` past the digit).
                at_replaced.push(chars[i + 1]);
                skip_next = true;
            } else {
                at_replaced.push(*ch);
            }
        }
        // Split on `-`, `_`, `.`, and ` ` as word boundaries.
        at_replaced
            .split(['-', '_', '.', ' '])
            .map(|seg| {
                let mut c = seg.chars();
                match c.next() {
                    None => String::new(),
                    Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
                }
            })
            .collect::<Vec<_>>()
            .join("")
    };

    let tera = anodizer_core::template::parse_static("formula", FORMULA_TEMPLATE)
        .context("homebrew: parse formula template")?;

    let mut ctx = tera::Context::new();
    ctx.insert("class_name", &class_name);
    ctx.insert("name", name);
    ctx.insert("version", version);
    ctx.insert("description", description);
    ctx.insert("license", license);

    // Homepage: explicit > GitHub owner/repo > empty string.
    // When no github_slug is available we leave homepage blank rather than
    // producing a broken URL from the bare crate name.
    let default_homepage = opts
        .github_slug
        .as_deref()
        .map(|slug| format!("https://github.com/{}", slug))
        .unwrap_or_default();
    let homepage = opts.homepage.unwrap_or(&default_homepage);
    ctx.insert("homepage", homepage);

    // Determine archive layout
    let single_archive = archives.len() == 1;
    ctx.insert("single_archive", &single_archive);

    if single_archive {
        ctx.insert("single_url", archives[0].1);
        ctx.insert("single_sha256", archives[0].2);
    } else {
        ctx.insert("single_url", "");
        ctx.insert("single_sha256", "");
    }

    // Build per-OS entry lists only for multi-archive layout
    let empty_vec: Vec<std::collections::HashMap<&str, &str>> = Vec::new();
    let (unknown_vals, macos_vals, linux_vals, macos_has_arch, linux_has_arch) = if single_archive {
        (
            empty_vec.clone(),
            empty_vec.clone(),
            empty_vec,
            false,
            false,
        )
    } else {
        let has_arch = |entries: &[(&str, &str, &str)]| -> bool {
            entries.iter().any(|(p, _, _)| {
                p.contains("arm64")
                    || p.contains("aarch64")
                    || p.contains("amd64")
                    || p.contains("x86_64")
            })
        };

        let unknown: Vec<_> = archives
            .iter()
            .filter(|(p, _, _)| {
                !p.contains("darwin") && !p.contains("macos") && !p.contains("linux")
            })
            .map(|(platform, url, sha256)| {
                let mut m = std::collections::HashMap::new();
                m.insert("platform", *platform);
                m.insert("url", *url);
                m.insert("sha256", *sha256);
                m
            })
            .collect();

        let macos_archives: Vec<_> = archives
            .iter()
            .filter(|(p, _, _)| p.contains("darwin") || p.contains("macos"))
            .copied()
            .collect();
        let macos_has = !macos_archives.is_empty() && has_arch(&macos_archives);
        let macos: Vec<_> = macos_archives
            .iter()
            .map(|(platform, url, sha256)| {
                let arch_block = if platform.contains("arm64") || platform.contains("aarch64") {
                    "on_arm"
                } else {
                    "on_intel"
                };
                let mut m = std::collections::HashMap::new();
                m.insert("url", *url);
                m.insert("sha256", *sha256);
                m.insert("arch_block", arch_block);
                m
            })
            .collect();

        let linux_archives: Vec<_> = archives
            .iter()
            .filter(|(p, _, _)| p.contains("linux"))
            .copied()
            .collect();
        let linux_has = !linux_archives.is_empty()
            && linux_archives.iter().any(|(p, _, _)| {
                p.contains("arm64")
                    || p.contains("aarch64")
                    || p.contains("amd64")
                    || p.contains("x86_64")
                    || p.contains("armv6")
                    || p.contains("armv7")
                    || {
                        let l = p.to_lowercase();
                        (l.contains("-arm") || l.contains("_arm"))
                            && !l.contains("arm64")
                            && !l.contains("aarch64")
                    }
            });
        let linux: Vec<_> = linux_archives
            .iter()
            .map(|(platform, url, sha256)| {
                let arch_block = if platform.contains("arm64") || platform.contains("aarch64") {
                    "if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?"
                } else if platform.contains("amd64") || platform.contains("x86_64") {
                    "if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?"
                } else if platform.contains("armv6") || platform.contains("armv7") || {
                    let l = platform.to_lowercase();
                    (l.contains("-arm") || l.contains("_arm"))
                        && !l.contains("arm64")
                        && !l.contains("aarch64")
                } {
                    "if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?"
                } else {
                    "if Hardware::CPU.intel?"
                };
                let mut m = std::collections::HashMap::new();
                m.insert("url", *url);
                m.insert("sha256", *sha256);
                m.insert("arch_block", arch_block);
                m
            })
            .collect();

        (unknown, macos, linux, macos_has, linux_has)
    };

    let has_macos = !macos_vals.is_empty();
    let has_linux = !linux_vals.is_empty();
    let depends_on_macos = has_macos && !has_linux;
    let depends_on_linux = has_linux && !has_macos;
    let has_only_amd64_macos = has_macos
        && macos_vals.len() == 1
        && macos_vals
            .first()
            .and_then(|m| m.get("arch_block"))
            .map(|a| *a == "on_intel")
            .unwrap_or(false);
    let has_platform_blocks = has_macos || has_linux;

    ctx.insert("unknown_entries", &unknown_vals);
    ctx.insert("has_macos", &has_macos);
    ctx.insert("macos_has_arch", &macos_has_arch);
    ctx.insert("macos_entries", &macos_vals);
    ctx.insert("has_linux", &has_linux);
    ctx.insert("linux_has_arch", &linux_has_arch);
    ctx.insert("linux_entries", &linux_vals);
    ctx.insert("depends_on_macos", &depends_on_macos);
    ctx.insert("depends_on_linux", &depends_on_linux);
    ctx.insert("has_only_amd64_macos", &has_only_amd64_macos);
    ctx.insert("has_platform_blocks", &has_platform_blocks);

    // Dependencies: split into global (no OS), macos-only, and linux-only.
    #[derive(serde::Serialize)]
    struct DepEntry {
        name: String,
        optional: bool,
        version: Option<String>,
    }

    let (global_deps, macos_deps, linux_deps) = if let Some(deps) = opts.dependencies {
        let mut global = Vec::new();
        let mut mac = Vec::new();
        let mut linux = Vec::new();
        for d in deps {
            let entry = DepEntry {
                name: d.name.clone(),
                optional: d.dep_type.as_deref() == Some("optional"),
                version: d.version.clone(),
            };
            match d.os.as_deref() {
                Some("mac") | Some("macos") => mac.push(entry),
                Some("linux") => linux.push(entry),
                _ => global.push(entry),
            }
        }
        // Dependencies are sorted alphabetically in the formula output.
        global.sort_by(|a, b| a.name.cmp(&b.name));
        mac.sort_by(|a, b| a.name.cmp(&b.name));
        linux.sort_by(|a, b| a.name.cmp(&b.name));
        (global, mac, linux)
    } else {
        (Vec::new(), Vec::new(), Vec::new())
    };
    ctx.insert("global_deps", &global_deps);
    ctx.insert("macos_deps", &macos_deps);
    ctx.insert("linux_deps", &linux_deps);

    // Conflicts — build serializable entries with name + optional because
    #[derive(serde::Serialize)]
    struct ConflictEntry {
        name: String,
        because: Option<String>,
    }
    let conflict_entries: Vec<ConflictEntry> = opts
        .conflicts
        .unwrap_or(&[])
        .iter()
        .map(|c| ConflictEntry {
            name: c.name().to_string(),
            because: c.because().map(|s| s.to_string()),
        })
        .collect();
    ctx.insert("conflicts", &conflict_entries);

    // Optional formula stanzas — each `unwrap_or("")` below pairs with either
    // a `{% if foo %}` truthy-guard or a sibling `has_<foo>` boolean in
    // FORMULA_TEMPLATE. Empty values render as no-stanza; Homebrew formulae
    // accept omitting caveats, plist, service, post_install, download_strategy,
    // custom_require, and custom_block — none are required by `brew style`.
    // The `license` field at line ~293 is likewise guarded by `{% if license %}`.
    let has_caveats = opts.caveats.is_some();
    ctx.insert("has_caveats", &has_caveats);
    ctx.insert("caveats", opts.caveats.unwrap_or(""));

    let install_lines: Vec<&str> = install.lines().collect();
    let test_lines: Vec<&str> = test.lines().collect();
    ctx.insert("install_lines", &install_lines);
    ctx.insert("test_lines", &test_lines);

    // Extra install lines (appended after main install block)
    let extra_install_lines: Vec<&str> = opts
        .extra_install
        .map(|s| s.lines().collect())
        .unwrap_or_default();
    ctx.insert("extra_install_lines", &extra_install_lines);

    // Post-install method
    let has_post_install = opts.post_install.is_some();
    ctx.insert("has_post_install", &has_post_install);
    let post_install_lines: Vec<&str> = opts
        .post_install
        .map(|s| s.lines().collect())
        .unwrap_or_default();
    ctx.insert("post_install_lines", &post_install_lines);

    // Download strategy
    ctx.insert("download_strategy", &opts.download_strategy.unwrap_or(""));

    // URL headers
    let url_headers: Vec<&str> = opts
        .url_headers
        .map(|h| h.iter().map(|s| s.as_str()).collect())
        .unwrap_or_default();
    ctx.insert("url_headers", &url_headers);

    // Custom require
    ctx.insert("custom_require", &opts.custom_require.unwrap_or(""));

    // Custom block
    ctx.insert("custom_block", &opts.custom_block.unwrap_or(""));

    // Plist
    let has_plist = opts.plist.is_some();
    ctx.insert("has_plist", &has_plist);
    ctx.insert("plist", &opts.plist.unwrap_or(""));

    // Service
    let has_service = opts.service.is_some();
    ctx.insert("has_service", &has_service);
    ctx.insert("service", &opts.service.unwrap_or(""));

    // Livecheck stanza (lines between `livecheck do` and `end`).
    let has_livecheck = opts.livecheck.is_some();
    ctx.insert("has_livecheck", &has_livecheck);
    let livecheck_lines: Vec<&str> = opts
        .livecheck
        .as_deref()
        .map(|s| s.lines().collect())
        .unwrap_or_default();
    ctx.insert("livecheck_lines", &livecheck_lines);

    // License stanza override (dual-license `any_of:`/`all_of:` form).
    let has_license_stanza = opts.license_stanza.is_some();
    ctx.insert(
        "license_stanza",
        opts.license_stanza.as_deref().unwrap_or(""),
    );
    // When a structured stanza is present, blank the plain-string `license`
    // var so the template's `{% elif license %}` branch never double-emits.
    if has_license_stanza {
        ctx.insert("license", "");
    }

    anodizer_core::template::render_static(&tera, "formula", &ctx, "homebrew")
}
/// Build depends_on directives from structured cask dependency config.
pub(super) fn build_depends_directives(
    deps: Option<&[anodizer_core::config::HomebrewCaskDependencyEntry]>,
) -> Vec<String> {
    let d = match deps {
        Some(d) if !d.is_empty() => d,
        _ => return Vec::new(),
    };
    let mut directives = Vec::new();
    for dep in d {
        if let Some(ref cask) = dep.cask {
            directives.push(format!("cask: \"{}\"", ruby_escape_str(cask)));
        }
        if let Some(ref formula) = dep.formula {
            directives.push(format!("formula: \"{}\"", ruby_escape_str(formula)));
        }
    }
    directives
}

/// Build conflicts_with directives from structured cask conflict config.
pub(super) fn build_conflicts_directives(
    conflicts: Option<&[anodizer_core::config::HomebrewCaskConflictEntry]>,
) -> Vec<String> {
    let c = match conflicts {
        Some(c) if !c.is_empty() => c,
        _ => return Vec::new(),
    };
    let mut directives = Vec::new();
    for conflict in c {
        if let Some(ref cask) = conflict.cask {
            directives.push(format!("cask: \"{}\"", ruby_escape_str(cask)));
        } else if let Some(ref formula) = conflict.formula {
            directives.push(format!("formula: \"{}\"", ruby_escape_str(formula)));
        }
    }
    directives
}

// `build_uninstall_directives` was removed when the cask renderer switched
// to multi-key Ruby array rendering — see
// `cask::{render_zap_block, render_uninstall_block}`.

/// Render the formula's `license` stanza from a parsed SPDX expression.
///
/// - single id → `license "MIT"`
/// - `A OR B` → `license any_of: ["A", "B"]`
/// - `A AND B` → `license all_of: ["A", "B"]`
///
/// A dual-license literal like `Apache-2.0 OR MIT` is an *invalid* argument to
/// brew's `license` stanza — Homebrew requires the structured `any_of:` form —
/// so this is the difference between a formula that passes `brew audit` and one
/// that does not. Returns `None` for an empty license so the caller omits the
/// stanza entirely.
pub fn render_formula_license(license: &str) -> Option<String> {
    use anodizer_core::license::{SpdxExpr, parse_spdx_expression};
    if license.trim().is_empty() {
        return None;
    }
    let stanza = match parse_spdx_expression(license) {
        SpdxExpr::Single(id) => format!("license \"{}\"", ruby_escape_str(&id)),
        SpdxExpr::AnyOf(ids) => format!("license any_of: [{}]", ruby_string_array(&ids)),
        SpdxExpr::AllOf(ids) => format!("license all_of: [{}]", ruby_string_array(&ids)),
    };
    Some(stanza)
}

/// Join license ids into a Ruby string-array body: `"A", "B", "C"`.
fn ruby_string_array(ids: &[String]) -> String {
    ids.iter()
        .map(|id| format!("\"{}\"", ruby_escape_str(id)))
        .collect::<Vec<_>>()
        .join(", ")
}

/// Render the body of a formula `livecheck do … end` block from config.
///
/// Returns `None` when no livecheck should be emitted. The returned string is
/// the inner lines (already trimmed of the `do`/`end` wrapper, no leading
/// indent — the template indents each line). Behavior:
///
/// - config absent OR `skip` truthy OR (no `strategy`/`url`/`regex` set) ⇒
///   `skip "<reason>"` (default reason `Auto-generated on release.`), matching
///   the cask. A binary tap's archive URL/sha change every release, so an
///   active livecheck has nothing stable to poll.
/// - `skip: false` + a `strategy`/`url`/`regex` ⇒ an active block
///   (`url :stable` / `strategy :github_latest` / `regex(...)`).
///
/// When the user explicitly sets `skip: false` but supplies none of
/// `strategy`/`url`/`regex`, an active block would render an empty (invalid)
/// `livecheck do … end`, so the renderer falls back to `skip` and emits a
/// `log.warn` so the ignored opt-in is visible rather than silently dropped.
pub fn render_formula_livecheck(
    cfg: Option<&anodizer_core::config::HomebrewLivecheck>,
    log: &anodizer_core::log::StageLogger,
) -> Option<String> {
    let cfg = cfg.cloned().unwrap_or_default();
    let has_active = cfg.strategy.as_deref().is_some_and(|s| !s.is_empty())
        || cfg.url.as_deref().is_some_and(|s| !s.is_empty())
        || cfg.regex.as_deref().is_some_and(|s| !s.is_empty());
    // Skip is the default unless the user explicitly opts into an active check
    // (skip == Some(false) AND at least one active field present).
    let skip = match cfg.skip {
        Some(s) => s,
        None => !has_active,
    };
    if skip || !has_active {
        // Surface a requested-but-ignored active livecheck: the user asked for
        // `skip: false` yet gave nothing to poll, so we fall back to `skip`.
        if cfg.skip == Some(false) && !has_active {
            log.warn(
                "homebrew livecheck: `skip: false` was set but no \
                 `strategy`/`url`/`regex` was provided — an active livecheck \
                 needs at least one. Falling back to `skip`.",
            );
        }
        let reason = cfg
            .skip_reason
            .as_deref()
            .filter(|s| !s.is_empty())
            .unwrap_or("Auto-generated on release.");
        return Some(format!("skip \"{}\"", ruby_escape_str(reason)));
    }

    let mut lines: Vec<String> = Vec::new();
    // `url`: a bare symbol shorthand (`stable`/`head`/`homepage`) renders as a
    // Ruby symbol; anything containing `:` or `/` is treated as a literal URL.
    let url_val = cfg
        .url
        .as_deref()
        .filter(|s| !s.is_empty())
        .unwrap_or("stable");
    if let Some(sym) = livecheck_url_symbol(url_val) {
        lines.push(format!("url :{}", sym));
    } else {
        lines.push(format!("url \"{}\"", ruby_escape_str(url_val)));
    }
    if let Some(strategy) = cfg.strategy.as_deref().filter(|s| !s.is_empty()) {
        // `strategy` is a Ruby symbol; strip a user-supplied leading `:`.
        lines.push(format!("strategy :{}", strategy.trim_start_matches(':')));
    }
    if let Some(regex) = cfg.regex.as_deref().filter(|s| !s.is_empty()) {
        // `regex` is raw Ruby (a `%r{...}` or `/.../ ` literal), emitted verbatim.
        lines.push(format!("regex({})", regex));
    }
    Some(lines.join("\n"))
}

/// Map a livecheck `url` config value to its Ruby symbol when it is one of the
/// recognised shorthands (`stable`/`head`/`homepage`). Returns `None` for a
/// literal URL (which the caller renders as a quoted string).
fn livecheck_url_symbol(url: &str) -> Option<&str> {
    let u = url.trim().trim_start_matches(':');
    matches!(u, "stable" | "head" | "homepage").then_some(u)
}

/// Build the extra install-block lines for prebuilt completion files and
/// manpages: `bash_completion.install "<path>"`, `man1.install "<path>"`, etc.
///
/// `completions` carries explicit prebuilt completion file paths (one per
/// shell). `manpages` carries manpage file paths; each is routed to the
/// matching `manN` section by its `.N` suffix (defaulting to `man1`).
/// Returns the lines in a stable order (completions then manpages) so the
/// rendered formula is byte-deterministic across runs.
pub fn build_completion_and_manpage_install_lines(
    completions: Option<&anodizer_core::config::HomebrewCaskCompletions>,
    manpages: Option<&[String]>,
) -> Vec<String> {
    let mut lines = Vec::new();
    if let Some(c) = completions {
        if let Some(p) = c.bash.as_deref().filter(|s| !s.is_empty()) {
            lines.push(format!(
                "bash_completion.install \"{}\"",
                ruby_escape_str(p)
            ));
        }
        if let Some(p) = c.zsh.as_deref().filter(|s| !s.is_empty()) {
            lines.push(format!("zsh_completion.install \"{}\"", ruby_escape_str(p)));
        }
        if let Some(p) = c.fish.as_deref().filter(|s| !s.is_empty()) {
            lines.push(format!(
                "fish_completion.install \"{}\"",
                ruby_escape_str(p)
            ));
        }
    }
    for path in manpages.unwrap_or(&[]) {
        if path.is_empty() {
            continue;
        }
        let section = manpage_section(path);
        lines.push(format!(
            "man{}.install \"{}\"",
            section,
            ruby_escape_str(path)
        ));
    }
    lines
}

/// Determine the `manN` section a manpage path installs into, from its numeric
/// extension (`foo.1` → 1, `foo.8` → 8). Defaults to section 1 — the
/// overwhelmingly common case for a CLI's primary manpage — when the path has
/// no recognised `.1`–`.8` suffix.
fn manpage_section(path: &str) -> u8 {
    path.rsplit('.')
        .next()
        .and_then(|ext| ext.parse::<u8>().ok())
        .filter(|n| (1..=8).contains(n))
        .unwrap_or(1)
}
