//! `Stage` impl for `ChangelogStage` — the pipeline entry point.
//!
//! Orchestrates per-crate changelog generation: resolves config, fetches
//! commits via the configured backend (`use: git` / `github` / `gitlab` /
//! `gitea` / `github-native`), filters / sorts / groups, renders Markdown,
//! and writes `dist/CHANGELOG.md`.

use std::path::PathBuf;

use anodizer_core::config::{ChangelogConfig, ChangelogGroup, ContentSource};
use anodizer_core::context::Context;
use anodizer_core::git::find_latest_tag_matching_with_prefix;
use anodizer_core::log::StageLogger;
use anodizer_core::stage::Stage;
use anyhow::{Context as _, Result};

use crate::fetch::build_login_enricher;
use crate::github_native::{handle_github_native_changelog, handle_release_notes_override};
use crate::group::exclude_filters_with_version_sync;
use crate::render::{render_crate_changelog, render_group_titles, wrap_with_header_footer};

/// Resolved options for the native changelog pipeline (everything not
/// touched by the `release-notes` / `github-native` early returns).
pub(crate) struct ChangelogOpts {
    pub(crate) sort_order: String,
    pub(crate) exclude_filters: Vec<String>,
    pub(crate) include_filters: Vec<String>,
    pub(crate) groups: Vec<ChangelogGroup>,
    pub(crate) header: Option<String>,
    pub(crate) footer: Option<String>,
    pub(crate) abbrev: i32,
    pub(crate) format_template: Option<String>,
    pub(crate) paths: Vec<String>,
    pub(crate) title: Option<String>,
    pub(crate) divider: Option<String>,
}

impl Stage for super::ChangelogStage {
    fn name(&self) -> &str {
        "changelog"
    }

    fn run(&self, ctx: &mut Context) -> Result<()> {
        let log = ctx.logger("changelog");

        let changelog_cfg = ctx.config.changelog.clone();

        // Snapshot-mode opt-in (`if snapshot { skip }`
        // default; user opts back in via `changelog.snapshot: true` for local
        // preview / draft generation). The standalone `changelog --format
        // release-notes` preview bypasses the config gate entirely: it is an
        // explicit inspection request, so it must render even when the config
        // hasn't opted into snapshot rendering (the release pipeline never sets
        // `changelog_preview`, so its gate stays intact).
        if ctx.is_snapshot() && !ctx.options.changelog_preview {
            let snapshot_opt_in = changelog_cfg
                .as_ref()
                .map(|c| c.resolved_snapshot())
                .unwrap_or(false);
            if !snapshot_opt_in {
                log.skip_line(
                    ctx.options.show_skipped,
                    "skipped changelog — snapshot mode (set `changelog.snapshot: true` to render)",
                );
                return Ok(());
            }
        }

        if handle_release_notes_override(ctx, &log)? {
            return Ok(());
        }

        // If skipped, skip the stage entirely (supports template-conditional skip).
        if let Some(d) = changelog_cfg.as_ref().and_then(|c| c.skip.as_ref()) {
            let off = d
                .try_evaluates_to_true(|s| ctx.render_template(s))
                .with_context(|| "changelog: render skip template")?;
            if off {
                log.status("skipped changelog — `skip` condition evaluated truthy");
                return Ok(());
            }
        }

        // If `use: github-native`, skip changelog generation and store empty
        // bodies so the release stage can delegate to GitHub's auto-generated
        // release notes.
        let mut use_source = changelog_cfg
            .as_ref()
            .map(|c| c.resolved_use_source().to_string())
            .unwrap_or_else(|| {
                anodizer_core::config::ChangelogConfig::DEFAULT_USE_SOURCE.to_string()
            });

        // The standalone `changelog --format release-notes` preview cannot
        // delegate to GitHub: the published body is generated by GitHub at
        // release time and there is no release here to query (and no token
        // should be required for a local preview). Render from local git
        // instead — the same source kac/json fall back to — by demoting the
        // use-source to the scm default. This both skips the github-native
        // branch below AND passes the VALID_USE_SOURCE validation that would
        // otherwise bail on a now-unhandled `github-native`.
        if ctx.options.changelog_preview && use_source == "github-native" {
            log.status(
                "previewing changelog from local git (use=github-native); the published GitHub \
                 release body is generated by GitHub at release time",
            );
            use_source = anodizer_core::config::ChangelogConfig::DEFAULT_USE_SOURCE.to_string();
        }

        if use_source == "github-native" {
            handle_github_native_changelog(ctx, &log, changelog_cfg.as_ref())?;
            return Ok(());
        }

        // Validate the use source against ChangelogConfig::VALID_USE_SOURCE
        // (excluding github-native which the early-return handled above).
        if !anodizer_core::config::ChangelogConfig::VALID_USE_SOURCE.contains(&use_source.as_str())
        {
            anyhow::bail!(
                "changelog: unsupported use source {:?} (expected one of: {})",
                use_source,
                anodizer_core::config::ChangelogConfig::VALID_USE_SOURCE.join(", ")
            );
        }

        let mut opts = resolve_changelog_opts(ctx, &log, changelog_cfg.as_ref())?;

        let selected = ctx.options.selected_crates.clone();
        let dist = ctx.config.dist.clone();

        let crates: Vec<_> = ctx
            .config
            .crate_universe()
            .into_iter()
            .filter(|c| selected.is_empty() || selected.contains(&c.name))
            .cloned()
            .collect();

        let ai_cfg = changelog_cfg.as_ref().and_then(|c| c.ai.clone());

        // Enabling AI disables changelog grouping: the model receives the
        // flat commit list and produces its own structure. Operators who
        // want both can instruct the prompt to emit group headings.
        if should_clear_groups_for_ai(ctx.is_snapshot(), ai_provider_active(ai_cfg.as_ref()))
            && !opts.groups.is_empty()
        {
            log.status(
                "changelog.ai enabled — `changelog.groups` is ignored; the AI prompt drives the structure",
            );
            opts.groups.clear();
        }

        // One enricher for the whole run: its email→login memo is shared
        // across every crate's changelog so a workspace release costs one
        // GitHub API call per unique author email, not per crate.
        let mut enricher = build_login_enricher(ctx, &use_source);

        let mut combined_markdown = String::new();
        for crate_cfg in &crates {
            let mut markdown =
                render_crate_changelog(ctx, &log, crate_cfg, &opts, &use_source, &mut enricher)?;
            if let Some(ref ai) = ai_cfg {
                markdown = crate::ai::enhance_with_ai(ctx, ai, &markdown, &log)?;
            }
            ctx.stage_outputs
                .changelogs
                .insert(crate_cfg.name.clone(), markdown.clone());
            combined_markdown.push_str(&markdown);
        }

        let final_markdown = wrap_with_header_footer(
            ctx,
            &log,
            &combined_markdown,
            opts.header.as_deref(),
            opts.footer.as_deref(),
        )?;

        // The standalone `changelog --format release-notes` preview streams
        // from `stage_outputs.changelogs` (populated above) to stdout; it must
        // NOT persist a `dist/CHANGELOG.md` artifact that would dirty the
        // working tree. The release pipeline leaves `changelog_preview` unset,
        // so it still writes dist normally.
        if !ctx.options.changelog_preview {
            write_changelog_dist(&log, &dist, &final_markdown)?;
        }
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Whether AI enhancement is active for this run.
///
/// Returns `true` only when `changelog.ai.use` is set to a name that
/// contains at least one non-whitespace character. Empty / missing /
/// whitespace-only values keep the native rendering pipeline intact —
/// suppressing groups and then failing inside `make_provider` would be
/// wasteful and surprising.
/// Whether the configured `changelog.groups` should be cleared because AI
/// enhancement will replace the structure.
///
/// Gated on `!is_snapshot` to match [`crate::ai::enhance_with_ai`], which
/// skips the provider call in snapshot mode. Clearing groups without the
/// enhancement that replaces them would leave a flat, un-grouped,
/// un-enhanced preview, so in snapshot the grouped structure is kept.
fn should_clear_groups_for_ai(is_snapshot: bool, ai_active: bool) -> bool {
    !is_snapshot && ai_active
}

fn ai_provider_active(ai_cfg: Option<&anodizer_core::config::ChangelogAiConfig>) -> bool {
    ai_cfg
        .and_then(|a| a.provider.as_deref())
        .is_some_and(|p| !p.trim().is_empty())
}

/// True when any crate in the universe (top-level `crates` plus every
/// `workspaces[].crates` entry) carries a complete `release.github`
/// (non-empty owner and name) — the github-native backend has a repo to
/// query. Per-crate scope: a config-level default repo does not count;
/// the notes endpoint is called per crate.
pub(crate) fn github_native_has_repo(ctx: &Context) -> bool {
    ctx.config.crate_universe().into_iter().any(|c| {
        c.release
            .as_ref()
            .and_then(|r| r.github.as_ref())
            .is_some_and(|g| !g.owner.is_empty() && !g.name.is_empty())
    })
}

/// Resolve the native pipeline's options: filters, groups, header/footer
/// content (post-`ContentSource::resolve`), abbrev, format template, and
/// pre-rendered path/title/divider templates.
fn resolve_changelog_opts(
    ctx: &mut Context,
    log: &StageLogger,
    cfg: Option<&ChangelogConfig>,
) -> Result<ChangelogOpts> {
    let sort_order = match cfg {
        Some(c) => c.resolved_sort()?.to_string(),
        None => String::new(),
    };
    let filters = cfg.and_then(|c| c.filters.as_ref());
    // The version-sync auto-exclude is folded in here (shared with the
    // render-path) and is inert in include mode — `apply_filters` (exclude) only
    // runs when `include_filters` is empty.
    let exclude_filters: Vec<String> = exclude_filters_with_version_sync(filters);
    let include_filters: Vec<String> = filters.and_then(|f| f.include.clone()).unwrap_or_default();
    let raw_groups: Vec<ChangelogGroup> = cfg.and_then(|c| c.groups.clone()).unwrap_or_default();
    // Pre-render each group's title through the project's template context
    // so configs like `title: "{{ .ProjectName }} features"` resolve. The
    // Pro template-renders these too. Walks subgroups recursively.
    let groups = render_group_titles(ctx, log, raw_groups)?;

    let header_src: Option<ContentSource> = cfg.and_then(|c| c.header.clone());
    let footer_src: Option<ContentSource> = cfg.and_then(|c| c.footer.clone());
    // Resolve the ContentSource (Inline / FromFile / FromUrl) into a raw
    // string up front so the header/footer rendering pass below can stay
    // focused on template-expansion of the resulting body.
    let header: Option<String> = header_src
        .as_ref()
        .map(|src| anodizer_core::content_source::resolve(src, "changelog header", ctx, log))
        .transpose()?;
    let footer: Option<String> = footer_src
        .as_ref()
        .map(|src| anodizer_core::content_source::resolve(src, "changelog footer", ctx, log))
        .transpose()?;

    let abbrev: i32 = cfg
        .map(|c| c.resolved_abbrev())
        .unwrap_or(ChangelogConfig::DEFAULT_ABBREV);
    let format_template: Option<String> = cfg.and_then(|c| c.format.clone());
    let raw_paths: Vec<String> = cfg.and_then(|c| c.paths.clone()).unwrap_or_default();
    let raw_title: Option<String> = cfg.and_then(|c| c.title.clone());
    let raw_divider: Option<String> = cfg.and_then(|c| c.divider.clone());

    let paths: Vec<String> = raw_paths
        .into_iter()
        .map(|p| ctx.render_template_strict(&p, "changelog path", log))
        .collect::<Result<Vec<_>>>()?;
    let title = raw_title
        .map(|t| ctx.render_template_strict(&t, "changelog title", log))
        .transpose()?;
    let divider = raw_divider
        .map(|d| ctx.render_template_strict(&d, "changelog divider", log))
        .transpose()?;

    Ok(ChangelogOpts {
        sort_order,
        exclude_filters,
        include_filters,
        groups,
        header,
        footer,
        abbrev,
        format_template,
        paths,
        title,
        divider,
    })
}

/// Resolve the changelog range start (the "previous tag") for a crate.
///
/// An explicit `--from <ref>` (carried as `ctx.options.changelog_from`)
/// overrides the auto-discovered tag, letting the operator pin the lower
/// bound. Otherwise the latest tag matching the crate's `tag_template` is
/// used. In a real release that latest tag IS the just-cut `current_tag` (and
/// always is in lockstep, where every crate shares one tag namespace); rather
/// than collapse the range, the genuine lower bound is then the tag preceding
/// `current_tag`, resolved via ancestry. When no earlier tag exists the result
/// is `None` and the caller covers all reachable commits.
///
/// In snapshot mode that drop is suppressed: `current_tag` is a *preview*
/// boundary (`resolve_git_context` resolves it to the latest EXISTING tag when
/// HEAD is ahead of the last release), not a freshly-created release tag, so
/// the auto-discovered previous tag legitimately equals it. Dropping it there
/// would erase the lower bound and leak full history — diverging from the
/// engine-backed `keep-a-changelog` / `json` formats, which bound the pending
/// window at `find_last_tag..HEAD` directly. The snapshot pending window must
/// always start at the last release tag, never collapse to full history.
///
/// An explicit `--from` is validated against git: a ref that doesn't resolve
/// to a commit `bail!`s (naming the bad ref) rather than silently degrading
/// to an empty changelog — `fetch_git_commits_in_paths` returns `Ok(vec![])` on a
/// `git log` non-zero, so an unchecked typo would emit a blank changelog with
/// no error. Auto-discovered tags are always valid, so the check is gated on
/// the explicit-`--from` arm only.
///
/// An explicit empty lower bound (`changelog ..` / `..<ref>`, carried as
/// `ctx.options.changelog_full_history`) short-circuits to `None` before any
/// auto-discovery: full history means no previous tag, so the range covers
/// every reachable commit up to the upper bound — identical to the
/// engine-backed `keep-a-changelog` / `json` formats' empty-from semantics.
pub(crate) fn resolve_prev_tag(
    ctx: &Context,
    crate_cfg: &anodizer_core::config::CrateConfig,
    monorepo_prefix: Option<&str>,
    current_tag: Option<&str>,
) -> Result<Option<String>> {
    if ctx.options.changelog_full_history {
        return Ok(None);
    }
    let candidate = match ctx.options.changelog_from.as_deref() {
        Some(from) if !from.trim().is_empty() => {
            let from = from.trim();
            // Any directory inside the repo works: git resolves a ref repo-wide,
            // so this validation is independent of the workspace root.
            let cwd = std::env::current_dir()
                .context("changelog: resolve current dir to validate --from ref")?;
            anodizer_core::git::rev_verify_commit_in(&cwd, from).with_context(|| {
                format!(
                    "changelog: --from ref {:?} does not resolve to a commit \
                     (check the tag/sha/branch name)",
                    from
                )
            })?;
            Some(from.to_string())
        }
        _ => find_latest_tag_matching_with_prefix(
            crate_cfg.resolved_tag_template(),
            ctx.config.git.as_ref(),
            Some(ctx.template_vars()),
            monorepo_prefix,
        )?,
    };
    // Snapshot AND the standalone `changelog` preview keep the auto-discovered
    // previous tag even when it equals the current `Tag`: both render the
    // pending last-tag..HEAD window, where the current `Tag` resolves to the
    // latest existing tag. Dropping it here would collapse the range to zero
    // (or leak full history), so the suppression covers both modes.
    if ctx.is_snapshot() || ctx.options.changelog_preview {
        return Ok(candidate);
    }
    // An explicit `--from` is the operator's chosen lower bound: keep it verbatim
    // even if it happens to equal the current tag.
    let from_is_explicit = ctx
        .options
        .changelog_from
        .as_deref()
        .is_some_and(|f| !f.trim().is_empty());
    match candidate {
        // Auto-discovered range start equals the just-cut tag: the latest tag
        // matching this crate's `tag_template` IS the current release tag (the
        // common case in a real release, and ALWAYS the case in lockstep where
        // every crate shares one tag namespace). The genuine lower bound is the
        // tag immediately preceding `current`, so look it back through ancestry
        // rather than collapsing to full history.
        Some(ref t) if !from_is_explicit && current_tag == Some(t.as_str()) && !t.is_empty() => {
            let prev = anodizer_core::git::find_previous_tag_with_prefix(
                t,
                ctx.config.git.as_ref(),
                Some(ctx.template_vars()),
                monorepo_prefix,
            )?;
            Ok(prev)
        }
        other => Ok(other),
    }
}

/// Write the final Markdown to `<dist>/CHANGELOG.md`, creating the
/// directory first. This file is written even in dry-run mode.
pub(crate) fn write_changelog_dist(
    log: &StageLogger,
    dist: &PathBuf,
    markdown: &str,
) -> Result<()> {
    std::fs::create_dir_all(dist)
        .with_context(|| format!("changelog: create dist dir {}", dist.display()))?;
    let notes_path = dist.join("CHANGELOG.md");
    std::fs::write(&notes_path, markdown)
        .with_context(|| format!("changelog: write {}", notes_path.display()))?;
    log.status(&format!("wrote {}", notes_path.display()));
    Ok(())
}

#[cfg(test)]
mod ai_suppression_tests {
    use super::{ai_provider_active, should_clear_groups_for_ai};
    use anodizer_core::config::ChangelogAiConfig;

    #[test]
    fn groups_kept_in_snapshot_even_with_ai_active() {
        // Snapshot mode skips enhancement, so the grouped structure must
        // survive — clearing it would yield a flat, un-enhanced preview.
        assert!(
            !should_clear_groups_for_ai(true, true),
            "snapshot + AI active must keep groups"
        );
    }

    #[test]
    fn groups_cleared_in_release_with_ai_active() {
        assert!(
            should_clear_groups_for_ai(false, true),
            "release + AI active clears groups for AI to drive structure"
        );
    }

    #[test]
    fn groups_kept_without_ai() {
        assert!(!should_clear_groups_for_ai(false, false));
        assert!(!should_clear_groups_for_ai(true, false));
    }

    #[test]
    fn no_ai_cfg_is_inactive() {
        assert!(!ai_provider_active(None));
    }

    #[test]
    fn empty_provider_is_inactive() {
        let cfg = ChangelogAiConfig {
            provider: Some(String::new()),
            ..Default::default()
        };
        assert!(!ai_provider_active(Some(&cfg)));
    }

    #[test]
    fn missing_provider_is_inactive() {
        let cfg = ChangelogAiConfig {
            provider: None,
            ..Default::default()
        };
        assert!(!ai_provider_active(Some(&cfg)));
    }

    #[test]
    fn non_empty_provider_is_active() {
        for name in ["anthropic", "openai", "ollama"] {
            let cfg = ChangelogAiConfig {
                provider: Some(name.to_string()),
                ..Default::default()
            };
            assert!(
                ai_provider_active(Some(&cfg)),
                "{name} should activate the AI path"
            );
        }
    }

    #[test]
    fn whitespace_only_provider_is_inactive() {
        for name in ["   ", "\t", " \n ", ""] {
            let cfg = ChangelogAiConfig {
                provider: Some(name.to_string()),
                ..Default::default()
            };
            assert!(
                !ai_provider_active(Some(&cfg)),
                "{name:?} should NOT activate the AI path"
            );
        }
    }
}
