//! `Stage` impl for `ChangelogStage` — the pipeline entry point.
//!
//! Orchestrates per-crate changelog generation: resolves config, fetches
//! commits via the configured backend (`use: git` / `github` / `gitlab` /
//! `gitea` / `github-native`), filters / sorts / groups, renders Markdown,
//! and writes `dist/CHANGELOG.md`.

use std::path::PathBuf;

use anodizer_core::config::{ChangelogConfig, ChangelogGroup, ContentSource};
use anodizer_core::context::Context;
use anodizer_core::git::find_latest_tag_matching_with_prefix;
use anodizer_core::log::StageLogger;
use anodizer_core::stage::Stage;
use anyhow::{Context as _, Result, bail};

use crate::fetch::{
    fetch_git_commits, fetch_gitea_commits, fetch_github_commits, fetch_gitlab_commits,
    should_preempt_scm_to_git,
};
use crate::group::{
    CommitInfo, GroupedCommits, apply_filters, apply_include_filters,
    exclude_filters_with_version_sync, group_commits, sort_commits,
};
use crate::render::{ChangelogRenderOpts, render_changelog_with_provider};

/// Resolved options for the native changelog pipeline (everything not
/// touched by the `release-notes` / `github-native` early returns).
struct ChangelogOpts {
    sort_order: String,
    exclude_filters: Vec<String>,
    include_filters: Vec<String>,
    groups: Vec<ChangelogGroup>,
    header: Option<String>,
    footer: Option<String>,
    abbrev: i32,
    format_template: Option<String>,
    paths: Vec<String>,
    title: Option<String>,
    divider: Option<String>,
}

impl Stage for super::ChangelogStage {
    fn name(&self) -> &str {
        "changelog"
    }

    fn run(&self, ctx: &mut Context) -> Result<()> {
        let log = ctx.logger("changelog");

        let changelog_cfg = ctx.config.changelog.clone();

        // Snapshot-mode opt-in (`if snapshot { skip }`
        // default; user opts back in via `changelog.snapshot: true` for local
        // preview / draft generation). The standalone `changelog --format
        // release-notes` preview bypasses the config gate entirely: it is an
        // explicit inspection request, so it must render even when the config
        // hasn't opted into snapshot rendering (the release pipeline never sets
        // `changelog_preview`, so its gate stays intact).
        if ctx.is_snapshot() && !ctx.options.changelog_preview {
            let snapshot_opt_in = changelog_cfg
                .as_ref()
                .map(|c| c.resolved_snapshot())
                .unwrap_or(false);
            if !snapshot_opt_in {
                log.skip_line(
                    ctx.options.show_skipped,
                    "skipped changelog — snapshot mode (set `changelog.snapshot: true` to render)",
                );
                return Ok(());
            }
        }

        if handle_release_notes_override(ctx, &log)? {
            return Ok(());
        }

        // If skipped, skip the stage entirely (supports template-conditional skip).
        if let Some(d) = changelog_cfg.as_ref().and_then(|c| c.skip.as_ref()) {
            let off = d
                .try_evaluates_to_true(|s| ctx.render_template(s))
                .with_context(|| "changelog: render skip template")?;
            if off {
                log.status("skipped changelog — `skip` condition evaluated truthy");
                return Ok(());
            }
        }

        // If `use: github-native`, skip changelog generation and store empty
        // bodies so the release stage can delegate to GitHub's auto-generated
        // release notes.
        let mut use_source = changelog_cfg
            .as_ref()
            .map(|c| c.resolved_use_source().to_string())
            .unwrap_or_else(|| {
                anodizer_core::config::ChangelogConfig::DEFAULT_USE_SOURCE.to_string()
            });

        // The standalone `changelog --format release-notes` preview cannot
        // delegate to GitHub: the published body is generated by GitHub at
        // release time and there is no release here to query (and no token
        // should be required for a local preview). Render from local git
        // instead — the same source kac/json fall back to — by demoting the
        // use-source to the scm default. This both skips the github-native
        // branch below AND passes the VALID_USE_SOURCE validation that would
        // otherwise bail on a now-unhandled `github-native`.
        if ctx.options.changelog_preview && use_source == "github-native" {
            log.status(
                "previewing changelog from local git (use=github-native); the published GitHub \
                 release body is generated by GitHub at release time",
            );
            use_source = anodizer_core::config::ChangelogConfig::DEFAULT_USE_SOURCE.to_string();
        }

        if use_source == "github-native" {
            handle_github_native_changelog(ctx, &log, changelog_cfg.as_ref())?;
            return Ok(());
        }

        // Validate the use source against ChangelogConfig::VALID_USE_SOURCE
        // (excluding github-native which the early-return handled above).
        if !anodizer_core::config::ChangelogConfig::VALID_USE_SOURCE.contains(&use_source.as_str())
        {
            anyhow::bail!(
                "changelog: unsupported use source {:?} (expected one of: {})",
                use_source,
                anodizer_core::config::ChangelogConfig::VALID_USE_SOURCE.join(", ")
            );
        }

        let mut opts = resolve_changelog_opts(ctx, &log, changelog_cfg.as_ref())?;

        let selected = ctx.options.selected_crates.clone();
        let dist = ctx.config.dist.clone();

        let crates: Vec<_> = ctx
            .config
            .crate_universe()
            .into_iter()
            .filter(|c| selected.is_empty() || selected.contains(&c.name))
            .cloned()
            .collect();

        let ai_cfg = changelog_cfg.as_ref().and_then(|c| c.ai.clone());

        // Enabling AI disables changelog grouping: the model receives the
        // flat commit list and produces its own structure. Operators who
        // want both can instruct the prompt to emit group headings.
        if should_clear_groups_for_ai(ctx.is_snapshot(), ai_provider_active(ai_cfg.as_ref()))
            && !opts.groups.is_empty()
        {
            log.status(
                "changelog.ai enabled — `changelog.groups` is ignored; the AI prompt drives the structure",
            );
            opts.groups.clear();
        }

        // One enricher for the whole run: its email→login memo is shared
        // across every crate's changelog so a workspace release costs one
        // GitHub API call per unique author email, not per crate.
        let mut enricher = build_login_enricher(ctx, &use_source);

        let mut combined_markdown = String::new();
        for crate_cfg in &crates {
            let mut markdown =
                render_crate_changelog(ctx, &log, crate_cfg, &opts, &use_source, &mut enricher)?;
            if let Some(ref ai) = ai_cfg {
                markdown = crate::ai::enhance_with_ai(ctx, ai, &markdown, &log)?;
            }
            ctx.stage_outputs
                .changelogs
                .insert(crate_cfg.name.clone(), markdown.clone());
            combined_markdown.push_str(&markdown);
        }

        let final_markdown = wrap_with_header_footer(
            ctx,
            &log,
            &combined_markdown,
            opts.header.as_deref(),
            opts.footer.as_deref(),
        )?;

        // The standalone `changelog --format release-notes` preview streams
        // from `stage_outputs.changelogs` (populated above) to stdout; it must
        // NOT persist a `dist/CHANGELOG.md` artifact that would dirty the
        // working tree. The release pipeline leaves `changelog_preview` unset,
        // so it still writes dist normally.
        if !ctx.options.changelog_preview {
            write_changelog_dist(&log, &dist, &final_markdown)?;
        }
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Whether AI enhancement is active for this run.
///
/// Returns `true` only when `changelog.ai.use` is set to a name that
/// contains at least one non-whitespace character. Empty / missing /
/// whitespace-only values keep the native rendering pipeline intact —
/// suppressing groups and then failing inside `make_provider` would be
/// wasteful and surprising.
/// Whether the configured `changelog.groups` should be cleared because AI
/// enhancement will replace the structure.
///
/// Gated on `!is_snapshot` to match [`crate::ai::enhance_with_ai`], which
/// skips the provider call in snapshot mode. Clearing groups without the
/// enhancement that replaces them would leave a flat, un-grouped,
/// un-enhanced preview, so in snapshot the grouped structure is kept.
fn should_clear_groups_for_ai(is_snapshot: bool, ai_active: bool) -> bool {
    !is_snapshot && ai_active
}

fn ai_provider_active(ai_cfg: Option<&anodizer_core::config::ChangelogAiConfig>) -> bool {
    ai_cfg
        .and_then(|a| a.provider.as_deref())
        .is_some_and(|p| !p.trim().is_empty())
}

/// Whether a github-native generate-notes body should be treated as empty
/// (and therefore warned about, because the GitHub release will have no
/// real release notes).
///
/// GitHub's `generate-notes` endpoint returns 2xx with a body containing
/// only a `**Full Changelog**: …/compare/…` link when there are no merged
/// PRs between the two tags. That compare-only body carries no release
/// notes, so it is treated as empty here alongside genuinely blank /
/// whitespace-only bodies.
fn github_native_body_is_empty(body: &str) -> bool {
    let trimmed = body.trim();
    if trimmed.is_empty() {
        return true;
    }
    // A body whose every non-empty line is the auto-appended compare link
    // carries no actual release notes.
    trimmed
        .lines()
        .filter(|l| !l.trim().is_empty())
        .all(|l| l.trim_start().starts_with("**Full Changelog**:"))
}

/// Honour `--release-notes <path>`: read the file, fan it out to every
/// selected crate, and write `dist/CHANGELOG.md`. Returns `true` when the
/// override path was taken (caller short-circuits the rest of the stage).
fn handle_release_notes_override(ctx: &mut Context, log: &StageLogger) -> Result<bool> {
    let Some(notes_path) = ctx.options.release_notes_path.clone() else {
        return Ok(false);
    };
    let content = std::fs::read_to_string(&notes_path).with_context(|| {
        format!(
            "changelog: failed to read release notes file: {}",
            notes_path.display()
        )
    })?;
    if content.trim().is_empty() {
        log.warn(&format!(
            "release notes file {} is empty; release body will be blank",
            notes_path.display()
        ));
    }
    log.status(&format!(
        "using custom release notes from {}",
        notes_path.display()
    ));

    let selected = ctx.options.selected_crates.clone();
    let crates: Vec<_> = ctx
        .config
        .crate_universe()
        .into_iter()
        .filter(|c| selected.is_empty() || selected.contains(&c.name))
        .cloned()
        .collect();
    for crate_cfg in &crates {
        ctx.stage_outputs
            .changelogs
            .insert(crate_cfg.name.clone(), content.clone());
    }

    let dist = ctx.config.dist.clone();
    std::fs::create_dir_all(&dist)
        .with_context(|| format!("changelog: create dist dir {}", dist.display()))?;
    let notes_out = dist.join("CHANGELOG.md");
    std::fs::write(&notes_out, &content)
        .with_context(|| format!("changelog: write {}", notes_out.display()))?;
    log.status(&format!("wrote {}", notes_out.display()));
    Ok(true)
}

/// True when any crate in the universe (top-level `crates` plus every
/// `workspaces[].crates` entry) carries a complete `release.github`
/// (non-empty owner and name) — the github-native backend has a repo to
/// query. Per-crate scope: a config-level default repo does not count;
/// the notes endpoint is called per crate.
pub(crate) fn github_native_has_repo(ctx: &Context) -> bool {
    ctx.config.crate_universe().into_iter().any(|c| {
        c.release
            .as_ref()
            .and_then(|r| r.github.as_ref())
            .is_some_and(|g| !g.owner.is_empty() && !g.name.is_empty())
    })
}

/// Handle `use: github-native`: call GitHub's generate-notes endpoint per
/// crate, wrap with header/footer, and write `dist/CHANGELOG.md`. Mirrors
/// the github-native changelog backend.
fn handle_github_native_changelog(
    ctx: &mut Context,
    log: &StageLogger,
    changelog_cfg: Option<&ChangelogConfig>,
) -> Result<()> {
    if ctx.options.token.is_none() && !ctx.is_dry_run() && !ctx.is_snapshot() {
        bail!(
            "changelog: use=github-native requires a GitHub token ({}); \
             GitHub auto-release-notes is an authenticated API",
            anodizer_core::git::github_token_hint()
        );
    }
    if !github_native_has_repo(ctx) {
        // No crate in the current scope has a GitHub release configured
        // (e.g. a library-only workspace in per-crate publish-only). The
        // stage has nothing to fetch and nothing to write — return Ok
        // silently. A library workspace legitimately omits release.github;
        // there is nothing for the operator to fix, so a warn-level log
        // would be noise that pushes them to add a `skip: [changelog]`
        // toggle just to silence it.
        log.verbose(
            "skipped changelog — use=github-native and no crate in scope has \
             release.github (library workspace)",
        );
        return Ok(());
    }

    let monorepo_prefix = ctx.config.monorepo_tag_prefix();
    let current_tag = ctx.template_vars().get("Tag").cloned().unwrap_or_default();
    let token = ctx.options.token.clone();
    let dry_run_or_snapshot = ctx.is_dry_run() || ctx.is_snapshot();

    let selected = ctx.options.selected_crates.clone();
    let crates: Vec<_> = ctx
        .config
        .crate_universe()
        .into_iter()
        .filter(|c| selected.is_empty() || selected.contains(&c.name))
        .cloned()
        .collect();

    let mut combined = String::new();
    // Tracks whether at least one per-crate body came from the real
    // GitHub generate-notes API (vs. all empty placeholders because
    // every crate lacked `release.github`). Used to set
    // `github_native_changelog` accurately — the flag signals "body
    // provenance is GitHub" to downstream consumers, so it must not be
    // set when every body is empty.
    let mut any_github_body = false;
    // Crates lacking `release.github` are collected here and reported in a
    // single aggregated warn after the loop — one line per workspace instead
    // of one per crate (a wide workspace would otherwise emit dozens).
    let mut missing_github: Vec<String> = Vec::new();
    // Crates whose github-native body came back empty in a REAL run are
    // collected here and reported in a single aggregated warn after the loop.
    // An empty body means the published GitHub release notes will be blank —
    // the operator must see this, so it is a warn (not status/verbose). This
    // is the silent-empty-release-notes outcome the warn makes visible.
    let mut empty_github_body: Vec<String> = Vec::new();
    for crate_cfg in &crates {
        let github_cfg = crate_cfg.release.as_ref().and_then(|r| r.github.as_ref());
        let Some(repo) = github_cfg else {
            missing_github.push(crate_cfg.name.clone());
            ctx.stage_outputs
                .changelogs
                .insert(crate_cfg.name.clone(), String::new());
            continue;
        };

        let current_tag_opt = if current_tag.is_empty() {
            None
        } else {
            Some(current_tag.as_str())
        };
        let prev_tag = resolve_prev_tag(ctx, crate_cfg, monorepo_prefix, current_tag_opt)?;

        let body = if dry_run_or_snapshot {
            log.status(&format!(
                "(dry-run/snapshot) would call POST /repos/{}/{}/releases/generate-notes \
                 (tag_name={:?}, previous_tag_name={:?})",
                repo.owner, repo.name, current_tag, prev_tag
            ));
            String::new()
        } else {
            log.status(&format!(
                "fetching github-native release notes for {}/{} \
                 (tag_name={:?}, previous_tag_name={:?})",
                repo.owner, repo.name, current_tag, prev_tag
            ));
            crate::github_native::generate_release_notes(
                &repo.owner,
                &repo.name,
                &current_tag,
                prev_tag.as_deref(),
                token.as_deref(),
                log,
            )
            .with_context(|| {
                format!(
                    "changelog: github-native generate-notes for crate '{}'",
                    crate_cfg.name
                )
            })?
        };

        ctx.stage_outputs
            .changelogs
            .insert(crate_cfg.name.clone(), body.clone());
        combined.push_str(&body);
        // generate-notes returns 2xx with empty content when no
        // PRs/commits sit between the two tags; only flip the
        // provenance flag in real runs when the body is non-empty so
        // downstream consumers aren't misled. In dry-run/snapshot the
        // body is always empty but the intent is still GitHub-sourced.
        if dry_run_or_snapshot || !body.trim().is_empty() {
            any_github_body = true;
        }
        // Real run + a crate that HAS release.github but got an empty body
        // back: github-native notes are PR-based, so this is the canonical
        // "no merged PRs between the two tags" case. Flag it loudly below so
        // the operator isn't surprised by a blank release body.
        if !dry_run_or_snapshot && github_native_body_is_empty(&body) {
            empty_github_body.push(crate_cfg.name.clone());
        }
    }

    // Aggregated skip warning: one line listing every crate without
    // `release.github`, so a wide workspace doesn't drown the log in
    // near-identical per-crate warnings. Warn (not status) so a genuinely
    // missing config stays visible in CI output.
    if !missing_github.is_empty() {
        log.warn(&format!(
            "skipped github-native notes (use=github-native) for {} \
             crate(s) without release.github: {} (if any should have a release, \
             add release.github.owner and release.github.name)",
            missing_github.len(),
            missing_github.join(", ")
        ));
    }

    // Aggregated empty-body warning: github-native generate-notes returned a
    // blank (or compare-link-only) body for these crates, so their GitHub
    // release notes will be EMPTY. github-native notes are PR-based, so the
    // usual cause is no merged PRs between previous_tag_name and tag_name
    // (e.g. a direct-push workflow). Point the operator at `changelog.use:
    // git` (or github/gitlab/gitea) for commit-based notes instead. Warn —
    // not status — because shipping silent empty release notes is exactly the
    // failure this surfaces.
    if !empty_github_body.is_empty() {
        log.warn(&format!(
            "use=github-native produced an EMPTY release body for {} \
             crate(s): {}. The GitHub release(s) will have NO release notes. \
             github-native notes are PR-based, so the likely cause is no merged \
             PRs between previous_tag_name and tag_name (e.g. a direct-push \
             workflow). Set `changelog.use: git` (or github/gitlab/gitea) for \
             commit-based release notes instead.",
            empty_github_body.len(),
            empty_github_body.join(", ")
        ));
    }

    ctx.stage_outputs.github_native_changelog = any_github_body;

    let header_src: Option<ContentSource> = changelog_cfg.and_then(|c| c.header.clone());
    let footer_src: Option<ContentSource> = changelog_cfg.and_then(|c| c.footer.clone());
    let header: Option<String> = header_src
        .as_ref()
        .map(|src| anodizer_core::content_source::resolve(src, "changelog header", ctx, log))
        .transpose()?;
    let footer: Option<String> = footer_src
        .as_ref()
        .map(|src| anodizer_core::content_source::resolve(src, "changelog footer", ctx, log))
        .transpose()?;

    // Header/footer in this path use unconditional emission semantics
    // (empty rendered content is still included with surrounding
    // whitespace), so it does not go through `wrap_with_header_footer`.
    let mut final_markdown = String::new();
    let mut rendered_header: Option<String> = None;
    if let Some(ref h) = header {
        let rendered = ctx.render_template_strict(h, "changelog header", log)?;
        if !rendered.trim().is_empty() {
            final_markdown.push_str(&rendered);
            final_markdown.push_str("\n\n");
            rendered_header = Some(rendered);
        }
    }
    final_markdown.push_str(&combined);
    let mut rendered_footer: Option<String> = None;
    if let Some(ref f) = footer {
        let rendered = ctx.render_template_strict(f, "changelog footer", log)?;
        if !rendered.trim().is_empty() {
            final_markdown.push('\n');
            final_markdown.push_str(&rendered);
            final_markdown.push('\n');
            rendered_footer = Some(rendered);
        }
    }
    ctx.stage_outputs.changelog_header = rendered_header;
    ctx.stage_outputs.changelog_footer = rendered_footer;

    let dist = ctx.config.dist.clone();
    write_changelog_dist(log, &dist, &final_markdown)
}

/// Resolve the native pipeline's options: filters, groups, header/footer
/// content (post-`ContentSource::resolve`), abbrev, format template, and
/// pre-rendered path/title/divider templates.
fn resolve_changelog_opts(
    ctx: &mut Context,
    log: &StageLogger,
    cfg: Option<&ChangelogConfig>,
) -> Result<ChangelogOpts> {
    let sort_order = match cfg {
        Some(c) => c.resolved_sort()?.to_string(),
        None => String::new(),
    };
    let filters = cfg.and_then(|c| c.filters.as_ref());
    // The version-sync auto-exclude is folded in here (shared with the
    // render-path) and is inert in include mode — `apply_filters` (exclude) only
    // runs when `include_filters` is empty.
    let exclude_filters: Vec<String> = exclude_filters_with_version_sync(filters);
    let include_filters: Vec<String> = filters.and_then(|f| f.include.clone()).unwrap_or_default();
    let raw_groups: Vec<ChangelogGroup> = cfg.and_then(|c| c.groups.clone()).unwrap_or_default();
    // Pre-render each group's title through the project's template context
    // so configs like `title: "{{ .ProjectName }} features"` resolve. The
    // Pro template-renders these too. Walks subgroups recursively.
    let groups = render_group_titles(ctx, log, raw_groups)?;

    let header_src: Option<ContentSource> = cfg.and_then(|c| c.header.clone());
    let footer_src: Option<ContentSource> = cfg.and_then(|c| c.footer.clone());
    // Resolve the ContentSource (Inline / FromFile / FromUrl) into a raw
    // string up front so the header/footer rendering pass below can stay
    // focused on template-expansion of the resulting body.
    let header: Option<String> = header_src
        .as_ref()
        .map(|src| anodizer_core::content_source::resolve(src, "changelog header", ctx, log))
        .transpose()?;
    let footer: Option<String> = footer_src
        .as_ref()
        .map(|src| anodizer_core::content_source::resolve(src, "changelog footer", ctx, log))
        .transpose()?;

    let abbrev: i32 = cfg
        .map(|c| c.resolved_abbrev())
        .unwrap_or(ChangelogConfig::DEFAULT_ABBREV);
    let format_template: Option<String> = cfg.and_then(|c| c.format.clone());
    let raw_paths: Vec<String> = cfg.and_then(|c| c.paths.clone()).unwrap_or_default();
    let raw_title: Option<String> = cfg.and_then(|c| c.title.clone());
    let raw_divider: Option<String> = cfg.and_then(|c| c.divider.clone());

    let paths: Vec<String> = raw_paths
        .into_iter()
        .map(|p| ctx.render_template_strict(&p, "changelog path", log))
        .collect::<Result<Vec<_>>>()?;
    let title = raw_title
        .map(|t| ctx.render_template_strict(&t, "changelog title", log))
        .transpose()?;
    let divider = raw_divider
        .map(|d| ctx.render_template_strict(&d, "changelog divider", log))
        .transpose()?;

    Ok(ChangelogOpts {
        sort_order,
        exclude_filters,
        include_filters,
        groups,
        header,
        footer,
        abbrev,
        format_template,
        paths,
        title,
        divider,
    })
}

/// Recursively render each `ChangelogGroup.title` through the project's
/// template context. Templated group headings are accepted (e.g.
/// `title: "{{ .ProjectName }} features"`); rendering at the stage edge
/// keeps `render_groups` free of template-engine ceremony.
fn render_group_titles(
    ctx: &mut Context,
    log: &StageLogger,
    groups: Vec<ChangelogGroup>,
) -> Result<Vec<ChangelogGroup>> {
    let mut out = Vec::with_capacity(groups.len());
    for g in groups {
        let rendered_title = if g.title.is_empty() {
            String::new()
        } else {
            ctx.render_template_strict(&g.title, "changelog group title", log)?
        };
        let rendered_subgroups = match g.groups {
            Some(subs) => Some(render_group_titles(ctx, log, subs)?),
            None => None,
        };
        out.push(ChangelogGroup {
            title: rendered_title,
            regexp: g.regexp,
            order: g.order,
            groups: rendered_subgroups,
        });
    }
    Ok(out)
}

/// Resolve the changelog range start (the "previous tag") for a crate.
///
/// An explicit `--from <ref>` (carried as `ctx.options.changelog_from`)
/// overrides the auto-discovered tag, letting the operator pin the lower
/// bound. Otherwise the latest tag matching the crate's `tag_template` is
/// used. In a real release that latest tag IS the just-cut `current_tag` (and
/// always is in lockstep, where every crate shares one tag namespace); rather
/// than collapse the range, the genuine lower bound is then the tag preceding
/// `current_tag`, resolved via ancestry. When no earlier tag exists the result
/// is `None` and the caller covers all reachable commits.
///
/// In snapshot mode that drop is suppressed: `current_tag` is a *preview*
/// boundary (`resolve_git_context` resolves it to the latest EXISTING tag when
/// HEAD is ahead of the last release), not a freshly-created release tag, so
/// the auto-discovered previous tag legitimately equals it. Dropping it there
/// would erase the lower bound and leak full history — diverging from the
/// engine-backed `keep-a-changelog` / `json` formats, which bound the pending
/// window at `find_last_tag..HEAD` directly. The snapshot pending window must
/// always start at the last release tag, never collapse to full history.
///
/// An explicit `--from` is validated against git: a ref that doesn't resolve
/// to a commit `bail!`s (naming the bad ref) rather than silently degrading
/// to an empty changelog — `fetch_git_commits_in_paths` returns `Ok(vec![])` on a
/// `git log` non-zero, so an unchecked typo would emit a blank changelog with
/// no error. Auto-discovered tags are always valid, so the check is gated on
/// the explicit-`--from` arm only.
///
/// An explicit empty lower bound (`changelog ..` / `..<ref>`, carried as
/// `ctx.options.changelog_full_history`) short-circuits to `None` before any
/// auto-discovery: full history means no previous tag, so the range covers
/// every reachable commit up to the upper bound — identical to the
/// engine-backed `keep-a-changelog` / `json` formats' empty-from semantics.
fn resolve_prev_tag(
    ctx: &Context,
    crate_cfg: &anodizer_core::config::CrateConfig,
    monorepo_prefix: Option<&str>,
    current_tag: Option<&str>,
) -> Result<Option<String>> {
    if ctx.options.changelog_full_history {
        return Ok(None);
    }
    let candidate = match ctx.options.changelog_from.as_deref() {
        Some(from) if !from.trim().is_empty() => {
            let from = from.trim();
            // Any directory inside the repo works: git resolves a ref repo-wide,
            // so this validation is independent of the workspace root.
            let cwd = std::env::current_dir()
                .context("changelog: resolve current dir to validate --from ref")?;
            anodizer_core::git::rev_verify_commit_in(&cwd, from).with_context(|| {
                format!(
                    "changelog: --from ref {:?} does not resolve to a commit \
                     (check the tag/sha/branch name)",
                    from
                )
            })?;
            Some(from.to_string())
        }
        _ => find_latest_tag_matching_with_prefix(
            &crate_cfg.tag_template,
            ctx.config.git.as_ref(),
            Some(ctx.template_vars()),
            monorepo_prefix,
        )?,
    };
    // Snapshot AND the standalone `changelog` preview keep the auto-discovered
    // previous tag even when it equals the current `Tag`: both render the
    // pending last-tag..HEAD window, where the current `Tag` resolves to the
    // latest existing tag. Dropping it here would collapse the range to zero
    // (or leak full history), so the suppression covers both modes.
    if ctx.is_snapshot() || ctx.options.changelog_preview {
        return Ok(candidate);
    }
    // An explicit `--from` is the operator's chosen lower bound: keep it verbatim
    // even if it happens to equal the current tag.
    let from_is_explicit = ctx
        .options
        .changelog_from
        .as_deref()
        .is_some_and(|f| !f.trim().is_empty());
    match candidate {
        // Auto-discovered range start equals the just-cut tag: the latest tag
        // matching this crate's `tag_template` IS the current release tag (the
        // common case in a real release, and ALWAYS the case in lockstep where
        // every crate shares one tag namespace). The genuine lower bound is the
        // tag immediately preceding `current`, so look it back through ancestry
        // rather than collapsing to full history.
        Some(ref t) if !from_is_explicit && current_tag == Some(t.as_str()) && !t.is_empty() => {
            let prev = anodizer_core::git::find_previous_tag_with_prefix(
                t,
                ctx.config.git.as_ref(),
                Some(ctx.template_vars()),
                monorepo_prefix,
            )?;
            Ok(prev)
        }
        other => Ok(other),
    }
}

/// Resolve the commit path-scope for `crate_cfg` via the shared
/// [`anodizer_core::changelog_scope`] resolver — the single source of truth
/// every changelog format routes through. A per-crate track scopes to its own
/// directory; the aggregate to the union of all crate dirs + manifests (or the
/// monorepo dir / whole repo). `changelog.paths`, when set, can only NARROW
/// the derived scope, never replace it.
fn resolve_scope(
    changelog_paths: &[String],
    crate_path: &str,
    all_crate_dirs: &[String],
    monorepo_dir: Option<&str>,
) -> anodizer_core::changelog_scope::ChangelogScope {
    anodizer_core::changelog_scope::resolve_changelog_scope(
        crate_path,
        all_crate_dirs,
        monorepo_dir,
        changelog_paths,
    )
}

/// Build the GitHub login enricher for this run, or `None` when enrichment
/// cannot apply: a non-GitHub changelog source (`gitlab`/`gitea` logins live
/// in a different namespace), no token through the standard chain
/// (`--token` → `ANODIZER_GITHUB_TOKEN` → `GITHUB_TOKEN`; no ambient-auth
/// lookups, by contract — unauthenticated runs keep name-based rendering),
/// or no derivable GitHub target (`release.github` config, falling back to
/// the `origin` remote).
fn build_login_enricher(
    ctx: &Context,
    use_source: &str,
) -> Option<crate::enrich::LoginEnricher<'static>> {
    if !crate::enrich::use_source_supports_github_logins(use_source) {
        return None;
    }
    let token =
        anodizer_core::git::resolve_github_token_with_env(ctx.options.token.as_deref(), &|key| {
            ctx.env_var(key)
        })?;
    let configured = ctx
        .config
        .crate_universe()
        .into_iter()
        .filter_map(|c| c.release.as_ref().and_then(|r| r.github.as_ref()))
        .map(|g| (g.owner.clone(), g.name.clone()))
        .find(|(o, n)| !o.is_empty() && !n.is_empty());
    let root = ctx
        .options
        .project_root
        .clone()
        .unwrap_or_else(|| std::path::PathBuf::from("."));
    let (owner, repo) = crate::enrich::derive_github_target(
        configured.as_ref().map(|(o, n)| (o.as_str(), n.as_str())),
        &root,
    )?;
    Some(crate::enrich::LoginEnricher::for_github_repo(
        owner, repo, token, &root,
    ))
}

/// Fetch commits for a crate via the configured SCM backend, with
/// fallback-to-git on transient SCM API failures (strict mode escalates
/// to an error). Returns `(commits, logins_str)`.
#[allow(clippy::too_many_arguments)]
fn fetch_crate_commits(
    ctx: &mut Context,
    log: &StageLogger,
    use_source: &str,
    prev_tag: &Option<String>,
    to: Option<&str>,
    scope: &anodizer_core::changelog_scope::ChangelogScope,
    crate_name: &str,
    workspace_root: &std::path::Path,
) -> Result<(Vec<CommitInfo>, String)> {
    let paths = scope.pathspecs();
    let use_github = use_source == "github";
    let use_gitlab = use_source == "gitlab";
    let use_gitea = use_source == "gitea";

    // Pre-empt the SCM API call when there is no previous tag (first
    // release on a branch). The changelog backend does the
    // same: it warns and returns the git changeloger directly.
    let scm_no_prev_tag = should_preempt_scm_to_git(use_github, use_gitlab, use_gitea, prev_tag);
    if scm_no_prev_tag {
        let scm_label = if use_github {
            "github"
        } else if use_gitlab {
            "gitlab"
        } else {
            "gitea"
        };
        log.status(&format!(
            "no previous tag found — using 'git' instead of '{}' for crate '{}'",
            scm_label, crate_name
        ));
    }

    if scm_no_prev_tag {
        return Ok((
            fetch_git_commits_scoped(workspace_root, prev_tag, to, scope, crate_name, log)?,
            String::new(),
        ));
    }
    if use_github {
        match fetch_github_commits(ctx, prev_tag, paths, log) {
            Ok((infos, logins)) => return Ok((infos, logins)),
            Err(e) => {
                ctx.strict_guard(
                    log,
                    &format!(
                        "changelog GitHub API fetch failed, falling back to git: {}",
                        e
                    ),
                )?;
                return Ok((
                    fetch_git_commits_scoped(workspace_root, prev_tag, to, scope, crate_name, log)?,
                    String::new(),
                ));
            }
        }
    }
    if use_gitlab {
        match fetch_gitlab_commits(ctx, prev_tag, log) {
            Ok((infos, logins)) => return Ok((infos, logins)),
            Err(e) => {
                ctx.strict_guard(
                    log,
                    &format!(
                        "changelog GitLab API fetch failed, falling back to git: {}",
                        e
                    ),
                )?;
                return Ok((
                    fetch_git_commits_scoped(workspace_root, prev_tag, to, scope, crate_name, log)?,
                    String::new(),
                ));
            }
        }
    }
    if use_gitea {
        match fetch_gitea_commits(ctx, prev_tag, log) {
            Ok((infos, logins)) => return Ok((infos, logins)),
            Err(e) => {
                ctx.strict_guard(
                    log,
                    &format!(
                        "changelog Gitea API fetch failed, falling back to git: {}",
                        e
                    ),
                )?;
                return Ok((
                    fetch_git_commits_scoped(workspace_root, prev_tag, to, scope, crate_name, log)?,
                    String::new(),
                ));
            }
        }
    }
    Ok((
        fetch_git_commits_scoped(workspace_root, prev_tag, to, scope, crate_name, log)?,
        String::new(),
    ))
}

/// Fetch git commits scoped by `scope.dirs`, then apply the precise
/// `changelog.paths` glob intersect ([`scope.narrow`]) when one is required.
///
/// When no narrowing is needed the git pathspec already bounds the result
/// exactly, so this delegates to the metadata-only [`fetch_git_commits`].
/// Otherwise it fetches touched-file lists and drops commits whose files all
/// fall outside `changelog.paths` — the exact intersection of the derived
/// directory scope with the configured globs.
fn fetch_git_commits_scoped(
    workspace_root: &std::path::Path,
    prev_tag: &Option<String>,
    to: Option<&str>,
    scope: &anodizer_core::changelog_scope::ChangelogScope,
    crate_name: &str,
    log: &StageLogger,
) -> Result<Vec<CommitInfo>> {
    let paths = scope.pathspecs();
    if scope.narrow.is_none() {
        return fetch_git_commits(workspace_root, prev_tag, to, paths, crate_name, log);
    }
    crate::fetch::fetch_git_commits_narrowed(workspace_root, prev_tag, to, scope, crate_name, log)
}

/// Run the per-crate fetch → filter → sort → group → render pipeline
/// and return the rendered Markdown for that crate.
fn render_crate_changelog(
    ctx: &mut Context,
    log: &StageLogger,
    crate_cfg: &anodizer_core::config::CrateConfig,
    opts: &ChangelogOpts,
    use_source: &str,
    enricher: &mut Option<crate::enrich::LoginEnricher<'static>>,
) -> Result<String> {
    let crate_name = crate_cfg.name.clone();
    let use_github = use_source == "github";
    let use_gitlab = use_source == "gitlab";
    let use_gitea = use_source == "gitea";

    // Find the previous tag for this crate, excluding the current tag
    // (otherwise the "latest matching tag" IS the current tag and the
    // commit range collapses to zero). An explicit `--from <ref>` overrides
    // the auto-discovered tag as the range start.
    let monorepo_prefix = ctx.config.monorepo_tag_prefix();
    let current_tag = ctx.template_vars().get("Tag").cloned();
    let prev_tag = resolve_prev_tag(ctx, crate_cfg, monorepo_prefix, current_tag.as_deref())?;

    // Source the aggregate's crate dirs + monorepo dir from `.anodizer.yaml` —
    // the SAME read the engine-backed kac/json formats use — so all three
    // formats build an identical aggregate union and cannot drift. The
    // standalone release-notes command flattens `ctx.config.crates` to one
    // path-cleared aggregate entry, so reading them off `ctx.config` would lose
    // the union; the on-disk read recovers it.
    let scope_root = ctx
        .options
        .project_root
        .clone()
        .unwrap_or_else(|| std::path::PathBuf::from("."));
    let scope_inputs = crate::render::load_scope_inputs(&scope_root)?;
    let monorepo_dir = scope_inputs
        .monorepo_dir
        .clone()
        .or_else(|| ctx.config.monorepo_dir().map(str::to_string));
    let scope = resolve_scope(
        &opts.paths,
        &crate_cfg.path,
        &scope_inputs.crate_dirs,
        monorepo_dir.as_deref(),
    );
    let paths = scope.pathspecs().to_vec();

    // The GitHub API only supports filtering by a single path parameter;
    // GitLab/Gitea compare APIs don't support path filtering at all.
    if use_github && paths.len() > 1 {
        log.warn(&format!(
            "GitHub API only supports a single path filter; \
             only the first of {} paths ('{}') will be used for API queries. \
             Use `use: git` for accurate multi-path filtering.",
            paths.len(),
            paths[0]
        ));
    }
    if (use_gitlab || use_gitea) && !paths.is_empty() {
        log.warn(&format!(
            "{} API does not support path filtering; \
             {} path(s) will be ignored. Use `use: git` for path-based filtering.",
            if use_gitlab { "GitLab" } else { "Gitea" },
            paths.len()
        ));
    }
    // A precise `changelog.paths` glob narrowing applies only to `use: git`
    // (the SCM compare APIs already warn that path filtering is coarse /
    // unsupported above). Surface the limitation rather than silently widen.
    if scope.narrow.is_some() && (use_github || use_gitlab || use_gitea) {
        log.warn(
            "`changelog.paths` narrows the per-crate scope, but the \
             SCM compare API cannot apply it precisely; the result may include \
             commits outside the configured paths. Use `use: git` for an exact \
             intersect.",
        );
    }

    // The explicit upper bound (`changelog <from>..<to>` / single tag): bounds
    // the commit walk at `<to>` instead of HEAD. `None` keeps the pending
    // window running to HEAD. Cloned before the `&mut ctx` borrow below.
    let changelog_to = ctx.options.changelog_to.clone();
    let (all_commit_infos, logins_str) = fetch_crate_commits(
        ctx,
        log,
        use_source,
        &prev_tag,
        changelog_to.as_deref(),
        &scope,
        &crate_name,
        &scope_root,
    )?;

    // include and exclude are mutually exclusive:
    // if include patterns are configured, exclude is completely ignored.
    let filtered = if !opts.include_filters.is_empty() {
        apply_include_filters(&all_commit_infos, &opts.include_filters, log)?
    } else {
        apply_filters(&all_commit_infos, &opts.exclude_filters, log)?
    };

    let mut sorted = filtered;
    sort_commits(&mut sorted, &opts.sort_order)?;

    // Resolve GitHub logins for commits that arrived without one (the
    // local-git backend, or SCM-API authors with no linked account). The
    // run-wide enricher memoizes per email, and unresolved commits keep
    // their byte-identical name-based rendering.
    if let Some(e) = enricher.as_mut() {
        e.enrich(&mut sorted);
    }

    let grouped = if opts.groups.is_empty() {
        // No groups configured — render commits as a flat list without
        // any group heading. Only a "## Changes" heading is emitted
        // heading when groups ARE configured (for the "others" bucket);
        // with no groups the changelog is a plain bullet list.
        if sorted.is_empty() {
            vec![]
        } else {
            vec![GroupedCommits {
                title: String::new(),
                commits: sorted,
                subgroups: Vec::new(),
            }]
        }
    } else {
        group_commits(&sorted, &opts.groups, log)?
    };

    let scm_provider = ctx.token_type.to_string();
    render_changelog_with_provider(
        &grouped,
        ChangelogRenderOpts {
            abbrev: opts.abbrev,
            format_template: opts.format_template.as_deref(),
            logins: &logins_str,
            use_source,
            title: opts.title.as_deref(),
            divider: opts.divider.as_deref(),
            scm_provider: Some(&scm_provider),
            // The stage body becomes the GitHub release body, where bare
            // `@login` mentions are autolinked by GitHub itself.
            login_style: crate::render::LoginStyle::Bare,
        },
    )
}

/// Render header/footer through the template engine and wrap the
/// combined per-crate body. Stashes the rendered header/footer on
/// `ctx.stage_outputs` so the release stage can re-use them when no
/// `release.header` / `release.footer` override is configured (mirrors
/// the release-header content-loading flow).
fn wrap_with_header_footer(
    ctx: &mut Context,
    log: &StageLogger,
    body: &str,
    header: Option<&str>,
    footer: Option<&str>,
) -> Result<String> {
    let mut final_markdown = String::new();
    let mut rendered_header: Option<String> = None;
    if let Some(h) = header {
        let rendered = ctx.render_template_strict(h, "changelog header", log)?;
        if rendered.trim().is_empty() {
            log.warn("header rendered to an empty string (will be omitted)");
        } else {
            final_markdown.push_str(&rendered);
            final_markdown.push_str("\n\n");
            rendered_header = Some(rendered);
        }
    }
    final_markdown.push_str(body);
    let mut rendered_footer: Option<String> = None;
    if let Some(f) = footer {
        let rendered = ctx.render_template_strict(f, "changelog footer", log)?;
        if rendered.trim().is_empty() {
            log.warn("footer rendered to an empty string (will be omitted)");
        } else {
            final_markdown.push('\n');
            final_markdown.push_str(&rendered);
            final_markdown.push('\n');
            rendered_footer = Some(rendered);
        }
    }
    ctx.stage_outputs.changelog_header = rendered_header;
    ctx.stage_outputs.changelog_footer = rendered_footer;
    Ok(final_markdown)
}

/// Write the final Markdown to `<dist>/CHANGELOG.md`, creating the
/// directory first. This file is written even in dry-run mode.
fn write_changelog_dist(log: &StageLogger, dist: &PathBuf, markdown: &str) -> Result<()> {
    std::fs::create_dir_all(dist)
        .with_context(|| format!("changelog: create dist dir {}", dist.display()))?;
    let notes_path = dist.join("CHANGELOG.md");
    std::fs::write(&notes_path, markdown)
        .with_context(|| format!("changelog: write {}", notes_path.display()))?;
    log.status(&format!("wrote {}", notes_path.display()));
    Ok(())
}

#[cfg(test)]
mod github_native_empty_body_tests {
    use super::github_native_body_is_empty;

    #[test]
    fn blank_body_is_empty() {
        assert!(github_native_body_is_empty(""));
        assert!(github_native_body_is_empty("   \n\t  \n"));
    }

    #[test]
    fn compare_link_only_body_is_empty() {
        // The exact shape generate-notes returns when there are no merged
        // PRs between the two tags (proven live against this repo's
        // v0.4.0..v0.5.0 range).
        let body = "**Full Changelog**: https://github.com/o/r/compare/v0.4.0...v0.5.0";
        assert!(
            github_native_body_is_empty(body),
            "compare-link-only body must warn → treated as empty"
        );
    }

    #[test]
    fn compare_link_with_surrounding_blank_lines_is_empty() {
        let body = "\n\n**Full Changelog**: https://github.com/o/r/compare/a...b\n\n";
        assert!(github_native_body_is_empty(body));
    }

    #[test]
    fn body_with_real_notes_is_not_empty() {
        let body = "## What's Changed\n* feat: add thing by @x in #1\n\n\
                    **Full Changelog**: https://github.com/o/r/compare/a...b";
        assert!(
            !github_native_body_is_empty(body),
            "a body with actual notes must NOT be treated as empty"
        );
    }
}

#[cfg(test)]
mod login_enricher_gating_tests {
    use super::build_login_enricher;
    use anodizer_core::config::{CrateConfig, ReleaseConfig, ScmRepoConfig};
    use anodizer_core::test_helpers::TestContextBuilder;

    fn ctx_with(
        token: Option<&str>,
        github: Option<(&str, &str)>,
        root: std::path::PathBuf,
    ) -> anodizer_core::context::Context {
        ctx_with_env(token, github, root, &[])
    }

    /// Builds a context whose env source is map-backed (hermetic: the
    /// developer's or CI's real `GITHUB_TOKEN` can never leak into these
    /// gates). The empty-string defaults double as coverage that GHA's
    /// missing-secret materialization (`""`) counts as absent; `env` pairs
    /// override them.
    fn ctx_with_env(
        token: Option<&str>,
        github: Option<(&str, &str)>,
        root: std::path::PathBuf,
        env: &[(&str, &str)],
    ) -> anodizer_core::context::Context {
        let mut builder = TestContextBuilder::new()
            .project_name("test")
            .token(token.map(str::to_string))
            .project_root(root)
            .crates(vec![CrateConfig {
                name: "mylib".to_string(),
                path: ".".to_string(),
                tag_template: "v{{ .Version }}".to_string(),
                release: github.map(|(owner, name)| ReleaseConfig {
                    github: Some(ScmRepoConfig {
                        owner: owner.to_string(),
                        name: name.to_string(),
                        token: None,
                    }),
                    ..Default::default()
                }),
                ..Default::default()
            }])
            .env("ANODIZER_GITHUB_TOKEN", "")
            .env("GITHUB_TOKEN", "");
        for (k, v) in env {
            builder = builder.env(*k, *v);
        }
        builder.build()
    }

    /// No token anywhere in the chain (`--token` → `ANODIZER_GITHUB_TOKEN`
    /// → `GITHUB_TOKEN`) → no enricher, regardless of a configured GitHub
    /// target: unauthenticated runs keep name-based rendering and never
    /// attempt ambient-auth lookups.
    #[test]
    fn no_token_disables_enrichment() {
        let tmp = tempfile::tempdir().unwrap();
        let ctx = ctx_with(None, Some(("octo", "repo")), tmp.path().to_path_buf());
        assert!(build_login_enricher(&ctx, "git").is_none());
        let ctx = ctx_with(Some(""), Some(("octo", "repo")), tmp.path().to_path_buf());
        assert!(
            build_login_enricher(&ctx, "git").is_none(),
            "empty token counts as absent"
        );
    }

    /// A run with only the `GITHUB_TOKEN` env var set (no `--token` flag —
    /// the standard GitHub Actions shape) must get pipeline enrichment,
    /// and `ANODIZER_GITHUB_TOKEN` must work the same way.
    #[test]
    fn env_token_alone_enables_enrichment() {
        let tmp = tempfile::tempdir().unwrap();
        let ctx = ctx_with_env(
            None,
            Some(("octo", "repo")),
            tmp.path().to_path_buf(),
            &[("GITHUB_TOKEN", "gh-tok")],
        );
        assert!(
            build_login_enricher(&ctx, "git").is_some(),
            "GITHUB_TOKEN env alone must enable enrichment"
        );
        let ctx = ctx_with_env(
            None,
            Some(("octo", "repo")),
            tmp.path().to_path_buf(),
            &[("ANODIZER_GITHUB_TOKEN", "anod-tok")],
        );
        assert!(
            build_login_enricher(&ctx, "git").is_some(),
            "ANODIZER_GITHUB_TOKEN env alone must enable enrichment"
        );
    }

    /// GitLab/Gitea changelog sources never enrich from GitHub (different
    /// login namespaces), token or not.
    #[test]
    fn non_github_sources_disable_enrichment() {
        let tmp = tempfile::tempdir().unwrap();
        for src in ["gitlab", "gitea", "github-native"] {
            let ctx = ctx_with(
                Some("tok"),
                Some(("octo", "repo")),
                tmp.path().to_path_buf(),
            );
            assert!(
                build_login_enricher(&ctx, src).is_none(),
                "{src} must not enrich"
            );
        }
    }

    /// Token + configured `release.github` → enricher, for both the git and
    /// github sources (the latter backfills authors the compare API returned
    /// without a login).
    #[test]
    fn token_and_configured_target_enable_enrichment() {
        let tmp = tempfile::tempdir().unwrap();
        for src in ["git", "github"] {
            let ctx = ctx_with(
                Some("tok"),
                Some(("octo", "repo")),
                tmp.path().to_path_buf(),
            );
            assert!(
                build_login_enricher(&ctx, src).is_some(),
                "{src} must enrich"
            );
        }
    }

    /// Token but no configured target AND no GitHub remote (the project root
    /// is not even a git repo) → no enricher.
    #[test]
    fn no_derivable_target_disables_enrichment() {
        let tmp = tempfile::tempdir().unwrap();
        let ctx = ctx_with(Some("tok"), None, tmp.path().to_path_buf());
        assert!(build_login_enricher(&ctx, "git").is_none());
    }
}

#[cfg(test)]
mod ai_suppression_tests {
    use super::{ai_provider_active, should_clear_groups_for_ai};
    use anodizer_core::config::ChangelogAiConfig;

    #[test]
    fn groups_kept_in_snapshot_even_with_ai_active() {
        // Snapshot mode skips enhancement, so the grouped structure must
        // survive — clearing it would yield a flat, un-enhanced preview.
        assert!(
            !should_clear_groups_for_ai(true, true),
            "snapshot + AI active must keep groups"
        );
    }

    #[test]
    fn groups_cleared_in_release_with_ai_active() {
        assert!(
            should_clear_groups_for_ai(false, true),
            "release + AI active clears groups for AI to drive structure"
        );
    }

    #[test]
    fn groups_kept_without_ai() {
        assert!(!should_clear_groups_for_ai(false, false));
        assert!(!should_clear_groups_for_ai(true, false));
    }

    #[test]
    fn no_ai_cfg_is_inactive() {
        assert!(!ai_provider_active(None));
    }

    #[test]
    fn empty_provider_is_inactive() {
        let cfg = ChangelogAiConfig {
            provider: Some(String::new()),
            ..Default::default()
        };
        assert!(!ai_provider_active(Some(&cfg)));
    }

    #[test]
    fn missing_provider_is_inactive() {
        let cfg = ChangelogAiConfig {
            provider: None,
            ..Default::default()
        };
        assert!(!ai_provider_active(Some(&cfg)));
    }

    #[test]
    fn non_empty_provider_is_active() {
        for name in ["anthropic", "openai", "ollama"] {
            let cfg = ChangelogAiConfig {
                provider: Some(name.to_string()),
                ..Default::default()
            };
            assert!(
                ai_provider_active(Some(&cfg)),
                "{name} should activate the AI path"
            );
        }
    }

    #[test]
    fn whitespace_only_provider_is_inactive() {
        for name in ["   ", "\t", " \n ", ""] {
            let cfg = ChangelogAiConfig {
                provider: Some(name.to_string()),
                ..Default::default()
            };
            assert!(
                !ai_provider_active(Some(&cfg)),
                "{name:?} should NOT activate the AI path"
            );
        }
    }
}
