use anodizer_core::context::Context;
use anodizer_core::log::StageLogger;
use anyhow::{Context as _, Result};
use serde::Serialize;

use crate::util::{self, OsArtifact};

// ---------------------------------------------------------------------------
// KrewManifestParams
// ---------------------------------------------------------------------------

/// Parameters for generating a Krew plugin manifest YAML.
pub(crate) struct KrewManifestParams<'a> {
    pub(crate) name: &'a str,
    pub(crate) version: &'a str,
    pub(crate) homepage: &'a str,
    pub(crate) short_description: &'a str,
    pub(crate) description: &'a str,
    pub(crate) caveats: &'a str,
    /// `(os, arch, url, sha256, binary_name)` tuples for each platform.
    pub(crate) platforms: &'a [KrewPlatform],
}

/// A single platform entry in the Krew manifest.
pub(crate) struct KrewPlatform {
    pub(crate) os: String,
    pub(crate) arch: String,
    pub(crate) url: String,
    pub(crate) sha256: String,
    pub(crate) bin: String,
}

// ---------------------------------------------------------------------------
// Serde structs for Krew YAML manifest
// ---------------------------------------------------------------------------

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct KrewManifestYaml {
    #[serde(rename = "apiVersion")]
    api_version: String,
    kind: String,
    metadata: KrewMetadata,
    spec: KrewSpec,
}

#[derive(Serialize)]
struct KrewMetadata {
    name: String,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct KrewSpec {
    version: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    homepage: Option<String>,
    short_description: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    caveats: Option<String>,
    platforms: Vec<KrewPlatformYaml>,
}

#[derive(Serialize)]
struct KrewPlatformYaml {
    selector: KrewSelector,
    uri: String,
    sha256: String,
    bin: String,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct KrewSelector {
    match_labels: KrewMatchLabels,
}

#[derive(Serialize)]
struct KrewMatchLabels {
    os: String,
    arch: String,
}

// ---------------------------------------------------------------------------
// generate_manifest
// ---------------------------------------------------------------------------

/// Generate a Krew plugin manifest YAML string.
///
/// Uses `serde_yaml_ng` for proper YAML serialization with correct escaping
/// of special characters. The `description` and `caveats` fields use YAML
/// block scalar style (literal `|`) when present, achieved via post-processing.
pub(crate) fn generate_manifest(params: &KrewManifestParams<'_>) -> Result<String> {
    let mut platforms: Vec<KrewPlatformYaml> = params
        .platforms
        .iter()
        .map(|p| KrewPlatformYaml {
            selector: KrewSelector {
                match_labels: KrewMatchLabels {
                    os: p.os.clone(),
                    arch: krew_arch(&p.arch).to_string(),
                },
            },
            uri: p.url.clone(),
            sha256: p.sha256.clone(),
            bin: p.bin.clone(),
        })
        .collect();

    // sort platforms by URI descending.
    platforms.sort_by(|a, b| b.uri.cmp(&a.uri));

    let manifest = KrewManifestYaml {
        api_version: "krew.googlecontainertools.github.com/v1alpha2".to_string(),
        kind: "Plugin".to_string(),
        metadata: KrewMetadata {
            name: params.name.to_string(),
        },
        spec: KrewSpec {
            version: format!("v{}", params.version),
            homepage: if params.homepage.is_empty() {
                None
            } else {
                Some(params.homepage.to_string())
            },
            short_description: params.short_description.to_string(),
            description: if params.description.is_empty() {
                None
            } else {
                Some(params.description.to_string())
            },
            caveats: if params.caveats.is_empty() {
                None
            } else {
                Some(params.caveats.to_string())
            },
            platforms,
        },
    };

    let yaml = serde_yaml_ng::to_string(&manifest).context("krew: serialize manifest")?;

    Ok(format!(
        "# This file was generated by anodizer. DO NOT EDIT.\n{}",
        yaml
    ))
}

/// Map the internal arch names to Krew's expected labels.
///
/// This is a publisher-specific mapping layer on top of the generic
/// `infer_arch` in `util.rs`. The util layer produces canonical short
/// forms (`"amd64"`, `"arm64"`), and this function translates them
/// to whatever Krew expects. Today the mapping is a no-op for the
/// common cases, but keeping a separate layer allows adapting to
/// future Krew label changes without touching the shared inference.
fn krew_arch(arch: &str) -> &str {
    match arch {
        "amd64" | "x86_64" => "amd64",
        "arm64" | "aarch64" => "arm64",
        other => other,
    }
}

/// Map the internal OS names to Krew's expected labels.
///
/// See `krew_arch` for the rationale behind keeping a separate mapping
/// layer on top of `infer_os` in `util.rs`.
fn krew_os(os: &str) -> &str {
    match os {
        "darwin" | "macos" => "darwin",
        "linux" => "linux",
        "windows" => "windows",
        other => other,
    }
}

// ---------------------------------------------------------------------------
// krew-release-bot mode selection
// ---------------------------------------------------------------------------
//
// A plugin's first appearance in `kubernetes-sigs/krew-index` requires a
// human-reviewed PR; subsequent version bumps are mechanical. The krew
// maintainers run a hosted webhook (`krew-release-bot`) that performs the
// fork + version-bump PR server-side, under the bot's own GitHub account,
// for any plugin already in the index. anodizer drives that webhook
// directly so a release is self-contained — no separate GitHub-Actions
// workflow step is required.
//
// The single signal that decides the mode is whether the plugin already
// exists in krew-index:
//   - Plugin NOT in index → `PrDirect`: anodizer clones a fork, writes
//     `plugins/<name>.yaml`, commits, and opens the initial PR against
//     `kubernetes-sigs/krew-index`. A human reviews + merges it.
//   - Plugin IS in index → `BotWebhook`: anodizer POSTs a `ReleaseRequest`
//     (the fully-rendered manifest plus the release tag) to the hosted
//     webhook, which opens the version-bump PR on the plugin's behalf.
//     No fork, no token, no workflow.
//
// The membership probe is an anonymous GET against the GitHub contents API:
//   `api.github.com/repos/kubernetes-sigs/krew-index/contents/plugins/<name>.yaml`
// → 200 means published; 404 means not yet; any other status (rate-limit,
// 5xx) is treated as "unknown" and falls back to the safe `PrDirect` flow.

/// The two publish modes the krew publisher dispatches between.
#[derive(Debug, Clone, PartialEq, Eq)]
enum KrewMode {
    /// Initial-submission flow — plugin isn't in krew-index yet.
    /// Behaviour: clone fork, write `plugins/<name>.yaml`, commit, PR
    /// against `kubernetes-sigs/krew-index`.
    PrDirect,
    /// Version-update flow — plugin IS in krew-index. Behaviour: POST a
    /// `ReleaseRequest` to the hosted krew-release-bot webhook, which
    /// opens the krew-index PR server-side. Self-contained: no fork, no
    /// token, no GitHub-Actions workflow step.
    BotWebhook,
}

/// Detect the appropriate krew mode for a given plugin. Always succeeds —
/// a membership-probe error falls back to the safe `PrDirect` mode rather
/// than aborting the publisher.
fn detect_krew_mode(plugin_name: &str, token: Option<&str>) -> KrewMode {
    map_probe_to_mode(is_plugin_in_krew_index(plugin_name, token))
}

/// Pure dispatch from a krew-index membership-probe result to a mode.
/// `Some(true)` (published) → webhook flow; `Some(false)` (not yet
/// published) and `None` (probe failed / unknown) both → the safe
/// PR-direct flow.
fn map_probe_to_mode(in_index: Option<bool>) -> KrewMode {
    match in_index {
        Some(true) => KrewMode::BotWebhook,
        _ => KrewMode::PrDirect,
    }
}

/// HTTP probe: does `kubernetes-sigs/krew-index/plugins/<name>.yaml` exist?
/// Returns:
///   - `Some(true)` → 200 OK, the plugin is published.
///   - `Some(false)` → 404 Not Found, the plugin is not yet published.
///   - `None` → network error, rate-limit, or unexpected status. Caller
///     treats this as "unknown" and falls back to `pr-direct`.
///
/// `token` is optional — anodizer's GitHub PATs are scoped enough that
/// passing one raises the rate limit from 60/hr (anon) to 5,000/hr
/// (authenticated), but an anonymous probe is sufficient for low-volume
/// release cadence (≤ 60 releases per hour from one IP is generous).
fn is_plugin_in_krew_index(plugin_name: &str, token: Option<&str>) -> Option<bool> {
    let url = format!(
        "https://api.github.com/repos/kubernetes-sigs/krew-index/contents/plugins/{}.yaml",
        plugin_name
    );
    let client = anodizer_core::http::blocking_client(std::time::Duration::from_secs(10)).ok()?;
    let mut req = client
        .get(&url)
        .header("Accept", "application/vnd.github+json");
    if let Some(tok) = token {
        req = req.bearer_auth(tok);
    }
    let resp = req.send().ok()?;
    let status = resp.status();
    if status.is_success() {
        return Some(true);
    }
    if status == reqwest::StatusCode::NOT_FOUND {
        return Some(false);
    }
    // 403 (rate limited / token denied), 5xx (GitHub flaking) — both go
    // back as `None` so the caller falls through to `pr-direct`.
    None
}

// ---------------------------------------------------------------------------
// krew-release-bot webhook submission
// ---------------------------------------------------------------------------

/// Default hosted krew-release-bot webhook endpoint. The bot forks
/// krew-index and opens the version-bump PR server-side under its own
/// GitHub account, so anodizer sends no token.
const DEFAULT_KREW_RELEASE_BOT_WEBHOOK_URL: &str =
    "https://krew-release-bot.rajatjindal.com/github-action-webhook";

/// Resolve the effective webhook URL: the `KREW_RELEASE_BOT_WEBHOOK_URL`
/// env var (trimmed, empty treated as unset) else
/// [`DEFAULT_KREW_RELEASE_BOT_WEBHOOK_URL`]. Mirrors the bot client's own
/// `getWebhookURL()` precedence so a self-hosted deployment is reachable
/// the same way.
fn resolve_webhook_url(env: &dyn anodizer_core::env_source::EnvSource) -> String {
    env.var("KREW_RELEASE_BOT_WEBHOOK_URL")
        .map(|v| v.trim().to_string())
        .filter(|v| !v.is_empty())
        .unwrap_or_else(|| DEFAULT_KREW_RELEASE_BOT_WEBHOOK_URL.to_string())
}

/// The JSON body POSTed to the krew-release-bot webhook.
///
/// Field names and shapes mirror the bot's server-side `ReleaseRequest`
/// struct: `processed_template` is the fully-rendered manifest bytes
/// (the server's Go decoder expects a base64 string for its `[]byte`
/// field, which serde produces from a `Vec<u8>` only via an explicit
/// encoder — handled at the call site). Sending both `tag_name` and the
/// rendered manifest covers either server behaviour: trusting the
/// pre-rendered bytes or recomputing shas from the release assets at
/// `tag_name`.
#[derive(Debug, Serialize)]
struct KrewReleaseRequest {
    #[serde(rename = "tagName")]
    tag_name: String,
    #[serde(rename = "pluginName")]
    plugin_name: String,
    #[serde(rename = "pluginOwner")]
    plugin_owner: String,
    #[serde(rename = "pluginRepo")]
    plugin_repo: String,
    #[serde(rename = "pluginReleaseActor")]
    plugin_release_actor: String,
    #[serde(rename = "templateFile")]
    template_file: String,
    /// Base64 of the rendered manifest bytes. The bot's `[]byte` JSON
    /// field decodes from a base64 string (Go's `encoding/json`
    /// convention), so the bytes are pre-encoded here.
    #[serde(rename = "processedTemplate")]
    processed_template: String,
}

impl KrewReleaseRequest {
    /// Build a `ReleaseRequest` from the resolved release coordinates and
    /// the fully-rendered manifest. `tag_name` is normalized to the
    /// `v<semver>` shape the krew-index manifest's `spec.version` carries.
    fn new(
        tag_name: &str,
        plugin_name: &str,
        plugin_owner: &str,
        plugin_repo: &str,
        plugin_release_actor: &str,
        rendered_manifest: &str,
    ) -> Self {
        use base64::Engine as _;
        Self {
            tag_name: tag_name.to_string(),
            plugin_name: plugin_name.to_string(),
            plugin_owner: plugin_owner.to_string(),
            plugin_repo: plugin_repo.to_string(),
            plugin_release_actor: plugin_release_actor.to_string(),
            template_file: ".krew.yaml".to_string(),
            processed_template: base64::engine::general_purpose::STANDARD
                .encode(rendered_manifest.as_bytes()),
        }
    }
}

/// Whether a non-200 webhook response body indicates the version/PR is
/// already submitted (an idempotent re-run), versus a genuine failure.
///
/// The bot server returns HTTP 500 for every failure path, wrapping the
/// underlying error message in the response body (`opening pr: <err>`).
/// When a PR for the same fork branch already exists, GitHub's create-PR
/// call fails with a 422 whose message contains `pull request already
/// exists`; an unchanged manifest fails the commit step with a
/// nothing-to-commit / `already up-to-date` message. Both are benign:
/// the previous submission already did the work. Match those phrases so a
/// re-run of an already-published version is treated as a no-op success
/// rather than a hard failure.
fn webhook_body_is_already_submitted(body: &str) -> bool {
    let lower = body.to_ascii_lowercase();
    lower.contains("pull request already exists")
        || lower.contains("already exists")
        || lower.contains("already up-to-date")
        || lower.contains("already up to date")
        || lower.contains("clean working tree")
        || lower.contains("nothing to commit")
}

/// POST a [`KrewReleaseRequest`] to the krew-release-bot webhook and map
/// the response to a publish result.
///
/// A single attempt with a 30s timeout mirrors the bot's own client
/// (`action_runner.go::submitForPR`). The retry helper is deliberately
/// NOT used here: the server returns HTTP 500 for every failure path,
/// including the benign "PR already exists" case, so a generic 5xx-retry
/// classifier would both burn the budget on an idempotent re-run and
/// flood the bot with duplicate submissions.
///
/// Outcome mapping:
///   - HTTP 200 → success; the body (`PR "<url>" submitted successfully`)
///     is logged.
///   - non-200 whose body matches [`webhook_body_is_already_submitted`] →
///     idempotent no-op success (the version was already submitted).
///   - any other non-200 / transport error → loud error. The release
///     must not silently skip krew.
fn submit_krew_release_webhook(
    webhook_url: &str,
    request: &KrewReleaseRequest,
    plugin_name: &str,
    version: &str,
    log: &StageLogger,
) -> Result<()> {
    let client = anodizer_core::http::blocking_client(std::time::Duration::from_secs(30))
        .context("krew: build webhook HTTP client")?;
    let body = serde_json::to_string(request).context("krew: serialize ReleaseRequest")?;

    let resp = client
        .post(webhook_url)
        .header("Content-Type", "application/json")
        .body(body)
        .send()
        .with_context(|| format!("krew: POST to krew-release-bot webhook {}", webhook_url))?;

    let status = resp.status();
    let resp_body = anodizer_core::http::body_of_blocking(resp);

    if status.is_success() {
        log.status(&format!(
            "krew: mode=bot-webhook plugin={} v{} submitted to {} ({})",
            plugin_name,
            version,
            webhook_url,
            resp_body.trim()
        ));
        return Ok(());
    }

    if webhook_body_is_already_submitted(&resp_body) {
        log.status(&format!(
            "krew: plugin={} v{} already submitted upstream — treating as \
             idempotent no-op (webhook HTTP {})",
            plugin_name, version, status
        ));
        return Ok(());
    }

    anyhow::bail!(
        "krew: krew-release-bot webhook {} returned HTTP {} for plugin '{}' v{}: {}",
        webhook_url,
        status,
        plugin_name,
        version,
        resp_body.trim()
    )
}

/// Convert `OsArtifact`s into `KrewPlatform`s.
///
/// When an artifact has arch "all", it is expanded into platform entries
/// for both amd64 and arm64.
///
/// `bin:` resolution per platform:
/// 1. Use the artifact's in-archive binary name when known
///    (`OsArtifact.binary`, populated from `extra_binaries[0]` for archives
///    or the `binary` metadata for uploadable binaries).
/// 2. Fall back to `default_binary_name` (the crate name) when the artifact
///    didn't carry a binary name.
/// 3. Append `.exe` for Windows targets when the resolved name doesn't
///    already end in `.exe`. Krew takes `bin:` literally — it does NOT
///    add `.exe` itself — so a Windows entry without the suffix fails to
///    install (krew validator: "source binary cannot be found in extracted
///    archive"). GoReleaser produces `.exe` naturally because its Go
///    builder appends it to `binary.Name`; anodizer's archive metadata
///    stores the suffix-less name, so we normalize here.
fn artifacts_to_platforms(
    artifacts: &[OsArtifact],
    default_binary_name: &str,
) -> Vec<KrewPlatform> {
    fn resolve_bin(a: &OsArtifact, default: &str, target_os: &str) -> String {
        let base = a.binary.clone().unwrap_or_else(|| default.to_string());
        if target_os == "windows" && !base.to_ascii_lowercase().ends_with(".exe") {
            format!("{}.exe", base)
        } else {
            base
        }
    }

    let mut platforms = Vec::new();
    for a in artifacts {
        let os = krew_os(&a.os).to_string();
        if a.arch == "all" {
            // Expand "all" into amd64 + arm64 entries
            for expanded_arch in &["amd64", "arm64"] {
                platforms.push(KrewPlatform {
                    os: os.clone(),
                    arch: expanded_arch.to_string(),
                    url: a.url.clone(),
                    sha256: a.sha256.clone(),
                    bin: resolve_bin(a, default_binary_name, &os),
                });
            }
        } else {
            platforms.push(KrewPlatform {
                arch: krew_arch(&a.arch).to_string(),
                url: a.url.clone(),
                sha256: a.sha256.clone(),
                bin: resolve_bin(a, default_binary_name, &os),
                os,
            });
        }
    }
    platforms
}

// ---------------------------------------------------------------------------
// publish_to_krew
// ---------------------------------------------------------------------------

/// Per-crate outcome returned by [`publish_to_krew`].
///
/// `pushed` flags whether the run made a real upstream side effect
/// (the `PrDirect` flow's branch push + PR open). Drives the caller's
/// `any_pushed` gate that decides whether to populate rollback evidence.
/// The `BotWebhook` flow always leaves `pushed = false`: the
/// krew-release-bot server owns the krew-index PR, so anodizer has
/// nothing to roll back.
#[derive(Debug, Default, Clone)]
pub struct KrewPublishOutcome {
    /// `true` when the `PrDirect` flow pushed a branch + opened a PR.
    /// The caller's `any_pushed` gate checks this.
    pub pushed: bool,
}

impl KrewPublishOutcome {
    /// Convenience constructor for run paths that exit before reaching
    /// the webhook / push branches.
    fn skipped() -> Self {
        Self { pushed: false }
    }
}

pub fn publish_to_krew(
    ctx: &mut Context,
    crate_name: &str,
    log: &StageLogger,
) -> Result<KrewPublishOutcome> {
    let (_crate_cfg, publish) = crate::util::get_publish_config(ctx, crate_name, "krew")?;

    let krew_cfg = publish
        .krew
        .as_ref()
        .ok_or_else(|| anyhow::anyhow!("krew: no krew config for '{}'", crate_name))?;

    // Honor `skip` first (template-aware), then `skip_upload`. `skip` lets
    // projects that aren't kubectl plugins keep a krew block in shared
    // config and turn it off without removing the surrounding
    // repository/short_description boilerplate.
    if let Some(d) = krew_cfg.skip.as_ref() {
        let off = d
            .try_evaluates_to_true(|tmpl| ctx.render_template(tmpl))
            .with_context(|| format!("krew: render skip template for '{}'", crate_name))?;
        if off {
            log.status(&format!(
                "krew: skipping config for '{}' (skip=true)",
                crate_name
            ));
            return Ok(KrewPublishOutcome::skipped());
        }
    }
    let proceed = anodizer_core::config::evaluate_if_condition(
        krew_cfg.if_condition.as_deref(),
        &format!("krew publisher for crate '{}'", crate_name),
        |t| ctx.render_template(t),
    )?;
    if !proceed {
        log.status(&format!(
            "krew: skipping '{}' — `if` condition evaluated falsy",
            crate_name
        ));
        return Ok(KrewPublishOutcome::skipped());
    }
    if util::should_skip_upload(krew_cfg.skip_upload.as_ref(), ctx, log) {
        log.status(&format!(
            "krew: skipping upload for '{}' (skip_upload={})",
            crate_name,
            krew_cfg
                .skip_upload
                .as_ref()
                .map(|v| v.as_str())
                .unwrap_or("")
        ));
        return Ok(KrewPublishOutcome::skipped());
    }

    // Resolve repository owner/name from `repository:` (RepositoryConfig).
    // GoReleaser applies TemplateRef() to repository fields (krew.go:292-296).
    let (repo_owner_raw, repo_name_raw) =
        crate::util::resolve_repo_owner_name(krew_cfg.repository.as_ref())
            .ok_or_else(|| anyhow::anyhow!("krew: no repository config for '{}'", crate_name))?;
    let repo_owner = ctx
        .render_template(&repo_owner_raw)
        .unwrap_or(repo_owner_raw);
    let repo_name = ctx.render_template(&repo_name_raw).unwrap_or(repo_name_raw);

    if ctx.is_dry_run() {
        log.status(&format!(
            "(dry-run) would submit Krew plugin manifest for '{}' to {}/{}",
            crate_name, repo_owner, repo_name
        ));
        return Ok(KrewPublishOutcome::skipped());
    }

    let version = ctx.version();

    // validate required fields before proceeding.
    // GoReleaser Pro parity: fall back to `metadata.description` when krew config unset.
    let effective_description: Option<&str> = krew_cfg
        .description
        .as_deref()
        .or_else(|| ctx.config.meta_description());
    if effective_description.is_none_or(str::is_empty) {
        anyhow::bail!("krew: manifest description is not set for '{}'", crate_name);
    }
    if krew_cfg
        .short_description
        .as_ref()
        .is_none_or(|s| s.is_empty())
    {
        anyhow::bail!(
            "krew: manifest short_description is not set for '{}'",
            crate_name
        );
    }

    let description_raw = krew_cfg
        .description
        .as_deref()
        .or_else(|| ctx.config.meta_description())
        .unwrap_or(crate_name);
    let description = ctx
        .render_template(description_raw)
        .unwrap_or_else(|_| description_raw.to_string());
    let short_description_raw = krew_cfg.short_description.as_deref().unwrap_or(crate_name);
    let short_description = ctx
        .render_template(short_description_raw)
        .unwrap_or_else(|_| short_description_raw.to_string());
    // Derive GitHub slug (owner/repo) for homepage fallback, consistent with homebrew.
    let plugin_github = _crate_cfg
        .release
        .as_ref()
        .and_then(|r| r.github.as_ref())
        .map(|gh| (gh.owner.clone(), gh.name.clone()));
    let github_slug = plugin_github
        .as_ref()
        .map(|(owner, name)| format!("{}/{}", owner, name));
    let homepage_raw = krew_cfg.homepage.clone().unwrap_or_else(|| {
        github_slug
            .as_deref()
            .map(|slug| format!("https://github.com/{}", slug))
            .unwrap_or_else(|| format!("https://github.com/{}/{}", repo_owner, crate_name))
    });
    let homepage = ctx
        .render_template(&homepage_raw)
        .with_context(|| format!("krew: render homepage template for '{}'", crate_name))?;
    // GoReleaser krew.go:154-160 templates Caveats alongside the other
    // narrative fields; anodizer was passing it through verbatim.
    let caveats_raw = krew_cfg.caveats.clone().unwrap_or_default();
    let caveats = ctx
        .render_template(&caveats_raw)
        .with_context(|| format!("krew: render caveats template for '{}'", crate_name))?;

    // Find artifacts across all platforms, applying IDs + amd64_variant/arm_variant filter.
    let ids_filter = krew_cfg.ids.as_deref();
    let amd64_variant = krew_cfg.amd64_variant.as_deref().or(Some("v1"));
    let arm_variant = krew_cfg.arm_variant.as_deref();

    // Krew plugins only support a single
    // binary per archive. Check archive artifacts before building the manifest
    // so we fail fast with a clear error instead of shipping a broken plugin.
    for archive in ctx
        .artifacts
        .by_kind_and_crate(anodizer_core::artifact::ArtifactKind::Archive, crate_name)
    {
        if let Some(ids) = ids_filter
            && !ids.is_empty()
            && !archive
                .metadata
                .get("id")
                .map(|id| ids.iter().any(|i| i == id))
                .unwrap_or(false)
        {
            continue;
        }
        let binary_count = archive.extra_binaries().len();
        if binary_count != 1 {
            anyhow::bail!(
                "krew: only one binary per archive allowed, got {} on {:?}",
                binary_count,
                archive.name
            );
        }
    }

    let all_artifacts = util::find_all_platform_artifacts_with_variant(
        ctx,
        crate_name,
        ids_filter,
        amd64_variant,
        arm_variant,
    )?;

    let url_template = krew_cfg.url_template.as_deref();

    if all_artifacts.is_empty() {
        // GR krew.go:115-117 returns ErrNoArchivesFound — a krew manifest
        // with no real artifacts is unusable (the placeholder URL was a
        // fabricated guess that produced 404s on install). Fail loudly.
        anyhow::bail!(
            "krew: no archive artifacts found for '{}'. The krew publisher \
             needs at least one platform archive to construct the manifest. \
             Either add Windows/Linux/macOS targets for this crate or remove \
             the krew publisher config.",
            crate_name
        );
    }
    // The Krew schema requires `spec.platforms[].sha256` to be a non-empty
    // hex digest — krew's `addURIAndSha` validator rejects manifests with
    // empty hashes ("Hash validation failed"). Empty sha256 metadata
    // would silently produce an unusable plugin manifest.
    if let Some(empty) = all_artifacts.iter().find(|a| a.sha256.is_empty()) {
        anyhow::bail!(
            "krew: artifact for crate '{}' at url '{}' (os={}, arch={}) is \
             missing required sha256 metadata. The generated krew plugin \
             manifest would embed an empty `sha256:` field, which krew \
             rejects at install time. Check dist/artifacts.json for the \
             archive entry's metadata.sha256, and re-run `task release` from \
             a clean dist/ if the field is absent or empty.",
            crate_name,
            empty.url,
            empty.os,
            empty.arch,
        );
    }
    let platforms = {
        let mut plats = artifacts_to_platforms(&all_artifacts, crate_name);
        if let Some(tmpl) = url_template {
            for p in &mut plats {
                p.url = util::render_url_template_with_ctx(
                    ctx, tmpl, crate_name, &version, &p.arch, &p.os,
                );
            }
        }
        plats
    };

    let manifest = generate_manifest(&KrewManifestParams {
        name: crate_name,
        version: &version,
        homepage: &homepage,
        short_description: &short_description,
        description: &description,
        caveats: &caveats,
        platforms: &platforms,
    })?;

    // Use name override if set; render through template engine.
    let plugin_name_raw = krew_cfg.name.as_deref().unwrap_or(crate_name);
    let plugin_name_rendered = ctx
        .render_template(plugin_name_raw)
        .unwrap_or_else(|_| plugin_name_raw.to_string());
    let plugin_name = plugin_name_rendered.as_str();

    // Clone the krew-index fork, write the plugin manifest, commit, push.
    let token =
        util::resolve_repo_token(ctx, krew_cfg.repository.as_ref(), Some("KREW_INDEX_TOKEN"));

    // ── krew-release-bot mode selection ──────────────────────────────
    // A plugin already in krew-index takes the self-contained webhook
    // flow: anodizer POSTs the rendered manifest + tag to the hosted bot,
    // which opens the version-bump PR server-side. A plugin not yet in
    // the index takes the PR-direct flow below (clone fork → write
    // manifest → open the initial PR). A membership-probe error falls
    // back to PrDirect so a network blip never blocks the release.
    let mode = detect_krew_mode(plugin_name, token.as_deref());
    if mode == KrewMode::BotWebhook {
        // The bot needs the plugin's OWN GitHub repo (where the release +
        // assets live), not the krew-index fork coordinates resolved
        // above. Require it: the webhook fetches release assets from
        // `<owner>/<repo>` at `tagName` to recompute shas, so missing
        // coordinates would silently mis-target the bot.
        let (plugin_owner, plugin_repo) = plugin_github.clone().ok_or_else(|| {
            anyhow::anyhow!(
                "krew: plugin '{}' is in krew-index (webhook flow) but has no \
                 `release.github` owner/repo — the krew-release-bot webhook \
                 needs the plugin's GitHub repo to fetch release assets",
                plugin_name
            )
        })?;
        // Actor must be a valid GitHub login. Prefer the CI-provided
        // GITHUB_ACTOR, then ANODIZER_GITHUB_ACTOR, falling back to the
        // plugin repo owner (always a real login).
        let env = ctx.env_source();
        let actor = env
            .var("GITHUB_ACTOR")
            .or_else(|| env.var("ANODIZER_GITHUB_ACTOR"))
            .map(|a| a.trim().to_string())
            .filter(|a| !a.is_empty())
            .unwrap_or_else(|| plugin_owner.clone());
        let webhook_url = resolve_webhook_url(env);
        let request = KrewReleaseRequest::new(
            &format!("v{}", version),
            plugin_name,
            &plugin_owner,
            &plugin_repo,
            &actor,
            &manifest,
        );
        submit_krew_release_webhook(&webhook_url, &request, plugin_name, &version, log)?;
        return Ok(KrewPublishOutcome { pushed: false });
    }
    log.status(&format!("krew: mode=pr-direct plugin={}", plugin_name));

    let tmp_dir = tempfile::tempdir().context("krew: create temp dir")?;
    let repo_path = tmp_dir.path();

    util::clone_repo(
        krew_cfg.repository.as_ref(),
        &repo_owner,
        &repo_name,
        token.as_deref(),
        repo_path,
        "krew",
        log,
    )?;

    // Write plugin manifest under plugins/<name>.yaml.
    let plugins_dir = repo_path.join("plugins");
    std::fs::create_dir_all(&plugins_dir)
        .with_context(|| format!("krew: create plugins dir {}", plugins_dir.display()))?;

    let manifest_file = plugins_dir.join(format!("{}.yaml", plugin_name));
    std::fs::write(&manifest_file, &manifest)
        .with_context(|| format!("krew: write manifest {}", manifest_file.display()))?;

    log.status(&format!(
        "wrote Krew plugin manifest: {}",
        manifest_file.display()
    ));

    let commit_msg = crate::homebrew::render_commit_msg(
        krew_cfg.commit_msg_template.as_deref(),
        plugin_name,
        &version,
        "plugin",
    );
    let branch_name = format!("{}-v{}", plugin_name, version);
    let commit_opts = util::resolve_commit_opts(ctx, krew_cfg.commit_author.as_ref());
    // Always create a versioned branch for Krew PRs.
    let branch = Some(branch_name.as_str());
    let push_outcome = util::commit_and_push_with_opts(
        repo_path,
        &["."],
        &commit_msg,
        branch,
        "krew",
        &commit_opts,
    )?;
    let pushed = match push_outcome {
        util::CommitOutcome::Pushed => {
            log.status(&format!(
                "Krew manifest pushed to {}/{} branch '{}'",
                repo_owner, repo_name, branch_name
            ));
            true
        }
        util::CommitOutcome::NoChanges => {
            log.status(&format!(
                "krew: nothing to push, manifest for '{}' already up to date",
                plugin_name
            ));
            false
        }
    };

    // Submit a PR. When `repository.pull_request` is configured, use the
    // unified PR helper (which respects `base`, `draft`, `body`); otherwise
    // submit a PR via `gh` CLI against the canonical kubernetes-sigs/krew-index
    // (or `repository.pull_request.base` when set).
    let has_pr_config = krew_cfg
        .repository
        .as_ref()
        .and_then(|r| r.pull_request.as_ref())
        .and_then(|pr| pr.enabled)
        .unwrap_or(false);

    let update_existing_pr = krew_cfg
        .update_existing_pr
        .as_ref()
        .map(|v| {
            v.try_evaluates_to_true(|tmpl| ctx.render_template(tmpl))
                .unwrap_or(false)
        })
        .unwrap_or(false);

    // Clone the repository config so the PR submission helpers no
    // longer borrow from `ctx.config` (via `krew_cfg`). NLL then
    // drops the immutable borrow, making the subsequent `&mut ctx`
    // call legal.
    let repo_for_pr = krew_cfg.repository.clone();

    let pr_outcome = if has_pr_config {
        util::maybe_submit_pr(
            repo_path,
            repo_for_pr.as_ref(),
            &util::PrOrigin {
                repo_owner: &repo_owner,
                repo_name: &repo_name,
                branch_name: &branch_name,
                update_existing_pr,
            },
            &format!("Add/update {} plugin to v{}", crate_name, version),
            &format!(
                "## Plugin\n- **Name**: {}\n- **Version**: v{}\n\nAutomatically submitted by anodizer.",
                crate_name, version
            ),
            "krew",
            log,
        )
    } else {
        // No `repository.pull_request:` block — always submit a PR against the
        // canonical kubernetes-sigs/krew-index slug (or the override in
        // `repository.pull_request.base`). Submitting against the user's own
        // fork would silently create useless intra-fork PRs against the user's
        // empty `main` branch instead of against the real upstream.
        let upstream_slug = repo_for_pr
            .as_ref()
            .and_then(|r| r.pull_request.as_ref())
            .and_then(|pr| pr.base.as_ref())
            .and_then(|base| match (base.owner.as_deref(), base.name.as_deref()) {
                (Some(o), Some(n)) => Some(format!("{}/{}", o, n)),
                _ => None,
            })
            .unwrap_or_else(|| "kubernetes-sigs/krew-index".to_string());

        util::submit_pr_via_gh_with_opts(
            repo_path,
            &upstream_slug,
            &format!("{}:{}", repo_owner, branch_name),
            &format!("Add/update {} plugin to v{}", crate_name, version),
            &format!(
                "## Plugin\n- **Name**: {}\n- **Version**: v{}\n\nAutomatically submitted by anodizer.",
                crate_name, version
            ),
            "krew",
            log,
            util::SubmitPrOpts { update_existing_pr },
        )
    };

    // Surface PR-already-exists skips to the dispatch summary table.
    if let Some(outcome) = pr_outcome {
        ctx.record_publisher_outcome(outcome);
    }

    Ok(KrewPublishOutcome { pushed })
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
#[allow(clippy::field_reassign_with_default)]
mod tests {
    use super::*;

    // -----------------------------------------------------------------------
    // krew-release-bot mode selection + webhook tests
    // -----------------------------------------------------------------------

    /// Mode selection: a plugin NOT in krew-index takes `PrDirect`.
    /// `is_plugin_in_krew_index` returning `Some(false)` (here forced by
    /// an unreachable token-less probe against a 404 fixture is awkward,
    /// so the redesign is asserted through `detect_krew_mode`'s pure
    /// dispatch on each probe outcome via the helper below).
    #[test]
    fn mode_selection_maps_index_membership_to_mode() {
        // Pure dispatch: probe says "in index" → BotWebhook; anything
        // else (not in index / unknown) → PrDirect.
        assert_eq!(map_probe_to_mode(Some(true)), KrewMode::BotWebhook);
        assert_eq!(map_probe_to_mode(Some(false)), KrewMode::PrDirect);
        assert_eq!(map_probe_to_mode(None), KrewMode::PrDirect);
    }

    /// The `ReleaseRequest` body carries the exact field names + values
    /// the bot's server-side struct expects, and base64-encodes the
    /// rendered manifest into `processedTemplate` (the server's `[]byte`
    /// JSON field).
    #[test]
    fn release_request_body_construction() {
        use base64::Engine as _;
        let manifest = "apiVersion: krew.googlecontainertools.github.com/v1alpha2\nkind: Plugin\n";
        let req = KrewReleaseRequest::new(
            "v1.2.3",
            "mytool",
            "acme",
            "mytool-repo",
            "octocat",
            manifest,
        );
        let json = serde_json::to_string(&req).unwrap();
        let v: serde_json::Value = serde_json::from_str(&json).unwrap();
        assert_eq!(v["tagName"], "v1.2.3");
        assert_eq!(v["pluginName"], "mytool");
        assert_eq!(v["pluginOwner"], "acme");
        assert_eq!(v["pluginRepo"], "mytool-repo");
        assert_eq!(v["pluginReleaseActor"], "octocat");
        assert_eq!(v["templateFile"], ".krew.yaml");
        // processedTemplate must be base64 of the raw manifest bytes so
        // the bot's Go `[]byte` decoder reconstructs the exact manifest.
        let expected = base64::engine::general_purpose::STANDARD.encode(manifest.as_bytes());
        assert_eq!(v["processedTemplate"], expected);
        let decoded = base64::engine::general_purpose::STANDARD
            .decode(v["processedTemplate"].as_str().unwrap())
            .unwrap();
        assert_eq!(String::from_utf8(decoded).unwrap(), manifest);
    }

    /// Webhook URL: env override wins; empty/unset falls back to the
    /// hosted default.
    #[test]
    fn webhook_url_resolution_honors_env_override() {
        use anodizer_core::env_source::MapEnvSource;
        let default_env = MapEnvSource::new();
        assert_eq!(
            resolve_webhook_url(&default_env),
            DEFAULT_KREW_RELEASE_BOT_WEBHOOK_URL
        );

        let custom_env = MapEnvSource::new().with(
            "KREW_RELEASE_BOT_WEBHOOK_URL",
            "https://krew.internal.example/webhook",
        );
        assert_eq!(
            resolve_webhook_url(&custom_env),
            "https://krew.internal.example/webhook"
        );

        let blank_env = MapEnvSource::new().with("KREW_RELEASE_BOT_WEBHOOK_URL", "  ");
        assert_eq!(
            resolve_webhook_url(&blank_env),
            DEFAULT_KREW_RELEASE_BOT_WEBHOOK_URL
        );
    }

    /// The already-submitted classifier recognizes the bot's
    /// duplicate-PR / nothing-to-commit signals and rejects genuine
    /// failures.
    #[test]
    fn webhook_already_submitted_classifier() {
        assert!(webhook_body_is_already_submitted(
            "opening pr: A pull request already exists for acme:mytool-v1.2.3"
        ));
        assert!(webhook_body_is_already_submitted(
            "opening pr: already up-to-date"
        ));
        assert!(webhook_body_is_already_submitted("nothing to commit"));
        assert!(!webhook_body_is_already_submitted(
            "opening pr: failed when validating plugin spec"
        ));
        assert!(!webhook_body_is_already_submitted("internal server error"));
    }

    /// HTTP 200 → success.
    #[test]
    fn webhook_submit_succeeds_on_200() {
        use anodizer_core::test_helpers::responder::spawn_oneshot_http_responder;
        let body =
            "PR \"https://github.com/kubernetes-sigs/krew-index/pull/42\" submitted successfully";
        let (addr, calls) = spawn_oneshot_http_responder(vec![Box::leak(
            format!(
                "HTTP/1.1 200 OK\r\nContent-Length: {}\r\n\r\n{}",
                body.len(),
                body
            )
            .into_boxed_str(),
        )]);
        let url = format!("http://{addr}/github-action-webhook");
        let req =
            KrewReleaseRequest::new("v1.0.0", "mytool", "acme", "repo", "octocat", "manifest");
        let log = StageLogger::new("publish", anodizer_core::log::Verbosity::Quiet);
        let r = submit_krew_release_webhook(&url, &req, "mytool", "1.0.0", &log);
        assert!(r.is_ok(), "200 must succeed: {r:?}");
        assert_eq!(calls.load(std::sync::atomic::Ordering::SeqCst), 1);
    }

    /// A non-200 whose body signals an already-existing PR is an
    /// idempotent no-op success.
    #[test]
    fn webhook_submit_idempotent_on_already_exists() {
        use anodizer_core::test_helpers::responder::spawn_oneshot_http_responder;
        let body = "opening pr: A pull request already exists for acme:mytool-v1.0.0";
        let (addr, _calls) = spawn_oneshot_http_responder(vec![Box::leak(
            format!(
                "HTTP/1.1 500 Internal Server Error\r\nContent-Length: {}\r\n\r\n{}",
                body.len(),
                body
            )
            .into_boxed_str(),
        )]);
        let url = format!("http://{addr}/github-action-webhook");
        let req =
            KrewReleaseRequest::new("v1.0.0", "mytool", "acme", "repo", "octocat", "manifest");
        let log = StageLogger::new("publish", anodizer_core::log::Verbosity::Quiet);
        let r = submit_krew_release_webhook(&url, &req, "mytool", "1.0.0", &log);
        assert!(
            r.is_ok(),
            "already-exists 500 must be a no-op success: {r:?}"
        );
    }

    /// A genuine failure (non-200, body not an already-exists signal)
    /// surfaces a loud error — krew must never silently skip.
    #[test]
    fn webhook_submit_errors_on_genuine_failure() {
        use anodizer_core::test_helpers::responder::spawn_oneshot_http_responder;
        let body = "opening pr: failed when validating plugin spec";
        let (addr, _calls) = spawn_oneshot_http_responder(vec![Box::leak(
            format!(
                "HTTP/1.1 500 Internal Server Error\r\nContent-Length: {}\r\n\r\n{}",
                body.len(),
                body
            )
            .into_boxed_str(),
        )]);
        let url = format!("http://{addr}/github-action-webhook");
        let req =
            KrewReleaseRequest::new("v1.0.0", "mytool", "acme", "repo", "octocat", "manifest");
        let log = StageLogger::new("publish", anodizer_core::log::Verbosity::Quiet);
        let err = submit_krew_release_webhook(&url, &req, "mytool", "1.0.0", &log)
            .expect_err("genuine 500 must error");
        let chain = format!("{err:#}");
        assert!(
            chain.contains("500") && chain.contains("validating plugin spec"),
            "error must surface status + body: {chain}"
        );
    }

    // -----------------------------------------------------------------------
    // generate_manifest tests
    // -----------------------------------------------------------------------

    #[test]
    fn test_generate_manifest_basic() {
        let manifest = generate_manifest(&KrewManifestParams {
            name: "kubectl-mytool",
            version: "1.0.0",
            homepage: "https://github.com/org/mytool",
            short_description: "A kubectl plugin",
            description: "A great kubectl plugin for managing things.",
            caveats: "",
            platforms: &[
                KrewPlatform {
                    os: "linux".to_string(),
                    arch: "amd64".to_string(),
                    url: "https://example.com/mytool-linux-amd64.tar.gz".to_string(),
                    sha256: "deadbeef".to_string(),
                    bin: "kubectl-mytool".to_string(),
                },
                KrewPlatform {
                    os: "darwin".to_string(),
                    arch: "amd64".to_string(),
                    url: "https://example.com/mytool-darwin-amd64.tar.gz".to_string(),
                    sha256: "cafebabe".to_string(),
                    bin: "kubectl-mytool".to_string(),
                },
            ],
        })
        .unwrap();

        // Header comment is present.
        assert!(manifest.starts_with("# This file was generated by anodizer. DO NOT EDIT.\n"));
        assert!(manifest.contains("apiVersion: krew.googlecontainertools.github.com/v1alpha2"));
        assert!(manifest.contains("kind: Plugin"));
        assert!(manifest.contains("  name: kubectl-mytool"));
        assert!(manifest.contains("version: v1.0.0"));
        assert!(manifest.contains("homepage: https://github.com/org/mytool"));
        assert!(manifest.contains("shortDescription: A kubectl plugin"));
        assert!(manifest.contains("A great kubectl plugin for managing things."));
        assert!(!manifest.contains("caveats:"));
        assert!(manifest.contains("platforms:"));
        assert!(manifest.contains("os: linux"));
        assert!(manifest.contains("arch: amd64"));
        assert!(manifest.contains("uri: https://example.com/mytool-linux-amd64.tar.gz"));
        assert!(manifest.contains("sha256: deadbeef"));
        assert!(manifest.contains("bin: kubectl-mytool"));
        assert!(manifest.contains("os: darwin"));
        assert!(manifest.contains("uri: https://example.com/mytool-darwin-amd64.tar.gz"));
        assert!(manifest.contains("sha256: cafebabe"));
    }

    #[test]
    fn test_generate_manifest_with_caveats() {
        let manifest = generate_manifest(&KrewManifestParams {
            name: "my-plugin",
            version: "2.0.0",
            homepage: "https://example.com",
            short_description: "Plugin",
            description: "A plugin",
            caveats: "Run 'kubectl my-plugin init' after installation.",
            platforms: &[KrewPlatform {
                os: "linux".to_string(),
                arch: "amd64".to_string(),
                url: "https://example.com/plugin.tar.gz".to_string(),
                sha256: "hash".to_string(),
                bin: "kubectl-my-plugin".to_string(),
            }],
        })
        .unwrap();

        assert!(manifest.contains("caveats:"));
        assert!(manifest.contains("Run 'kubectl my-plugin init' after installation."));
    }

    #[test]
    fn test_generate_manifest_no_homepage() {
        let manifest = generate_manifest(&KrewManifestParams {
            name: "tool",
            version: "1.0.0",
            homepage: "",
            short_description: "A tool",
            description: "desc",
            caveats: "",
            platforms: &[KrewPlatform {
                os: "linux".to_string(),
                arch: "amd64".to_string(),
                url: "https://example.com/tool.tar.gz".to_string(),
                sha256: "hash".to_string(),
                bin: "kubectl-tool".to_string(),
            }],
        })
        .unwrap();

        assert!(!manifest.contains("homepage:"));
    }

    #[test]
    fn test_generate_manifest_multi_platform() {
        let manifest = generate_manifest(&KrewManifestParams {
            name: "multi",
            version: "1.0.0",
            homepage: "https://example.com",
            short_description: "Multi-platform plugin",
            description: "A plugin for all platforms.",
            caveats: "",
            platforms: &[
                KrewPlatform {
                    os: "linux".to_string(),
                    arch: "amd64".to_string(),
                    url: "https://example.com/multi-linux-amd64.tar.gz".to_string(),
                    sha256: "hash_linux_amd64".to_string(),
                    bin: "kubectl-multi".to_string(),
                },
                KrewPlatform {
                    os: "linux".to_string(),
                    arch: "arm64".to_string(),
                    url: "https://example.com/multi-linux-arm64.tar.gz".to_string(),
                    sha256: "hash_linux_arm64".to_string(),
                    bin: "kubectl-multi".to_string(),
                },
                KrewPlatform {
                    os: "darwin".to_string(),
                    arch: "amd64".to_string(),
                    url: "https://example.com/multi-darwin-amd64.tar.gz".to_string(),
                    sha256: "hash_darwin_amd64".to_string(),
                    bin: "kubectl-multi".to_string(),
                },
                KrewPlatform {
                    os: "darwin".to_string(),
                    arch: "arm64".to_string(),
                    url: "https://example.com/multi-darwin-arm64.tar.gz".to_string(),
                    sha256: "hash_darwin_arm64".to_string(),
                    bin: "kubectl-multi".to_string(),
                },
                KrewPlatform {
                    os: "windows".to_string(),
                    arch: "amd64".to_string(),
                    url: "https://example.com/multi-windows-amd64.zip".to_string(),
                    sha256: "hash_windows_amd64".to_string(),
                    bin: "kubectl-multi".to_string(),
                },
            ],
        })
        .unwrap();

        // Count platform entries (each starts with "- selector:")
        let platform_count = manifest.matches("- selector:").count();
        assert_eq!(platform_count, 5);

        // Verify all platforms present
        assert!(manifest.contains("hash_linux_amd64"));
        assert!(manifest.contains("hash_linux_arm64"));
        assert!(manifest.contains("hash_darwin_amd64"));
        assert!(manifest.contains("hash_darwin_arm64"));
        assert!(manifest.contains("hash_windows_amd64"));
    }

    #[test]
    fn test_generate_manifest_complete_structure() {
        let manifest = generate_manifest(&KrewManifestParams {
            name: "kubectl-anodizer",
            version: "3.2.1",
            homepage: "https://github.com/tj-smith47/anodizer",
            short_description: "Release automation as a kubectl plugin",
            description: "A comprehensive release automation tool\nfor Kubernetes-based projects.",
            caveats: "Ensure kubectl is configured before use.",
            platforms: &[KrewPlatform {
                os: "linux".to_string(),
                arch: "amd64".to_string(),
                url: "https://github.com/tj-smith47/anodizer/releases/download/v3.2.1/anodizer-3.2.1-linux-amd64.tar.gz".to_string(),
                sha256: "aabbccdd".to_string(),
                bin: "kubectl-anodizer".to_string(),
            }],
        }).unwrap();

        // Starts with header comment
        assert!(manifest.starts_with("# This file was generated by anodizer. DO NOT EDIT.\n"));

        // Verify structure order (line 0 is the header comment)
        let lines: Vec<&str> = manifest.lines().collect();
        assert_eq!(
            lines[0],
            "# This file was generated by anodizer. DO NOT EDIT."
        );
        assert_eq!(
            lines[1],
            "apiVersion: krew.googlecontainertools.github.com/v1alpha2"
        );
        assert_eq!(lines[2], "kind: Plugin");
        assert_eq!(lines[3], "metadata:");
        assert_eq!(lines[4], "  name: kubectl-anodizer");
        assert_eq!(lines[5], "spec:");
        assert!(lines[6].contains("version: v3.2.1"));

        // Multi-line description
        assert!(manifest.contains("A comprehensive release automation tool"));
        assert!(manifest.contains("for Kubernetes-based projects."));

        // Caveats
        assert!(manifest.contains("Ensure kubectl is configured before use."));
    }

    // -----------------------------------------------------------------------
    // krew_arch / krew_os helper tests
    // -----------------------------------------------------------------------

    #[test]
    fn test_krew_arch_mapping() {
        assert_eq!(krew_arch("amd64"), "amd64");
        assert_eq!(krew_arch("x86_64"), "amd64");
        assert_eq!(krew_arch("arm64"), "arm64");
        assert_eq!(krew_arch("aarch64"), "arm64");
        assert_eq!(krew_arch("unknown"), "unknown");
    }

    #[test]
    fn test_krew_os_mapping() {
        assert_eq!(krew_os("darwin"), "darwin");
        assert_eq!(krew_os("macos"), "darwin");
        assert_eq!(krew_os("linux"), "linux");
        assert_eq!(krew_os("windows"), "windows");
        assert_eq!(krew_os("freebsd"), "freebsd");
    }

    // -----------------------------------------------------------------------
    // publish_to_krew dry-run tests
    // -----------------------------------------------------------------------

    #[test]
    fn test_publish_to_krew_missing_config() {
        use anodizer_core::config::{Config, CrateConfig, PublishConfig};
        use anodizer_core::context::{Context, ContextOptions};
        use anodizer_core::log::{StageLogger, Verbosity};

        let mut config = Config::default();
        config.crates = vec![CrateConfig {
            name: "mytool".to_string(),
            path: ".".to_string(),
            tag_template: "v{{ .Version }}".to_string(),
            publish: Some(PublishConfig::default()),
            ..Default::default()
        }];

        let mut ctx = Context::new(
            config,
            ContextOptions {
                dry_run: true,
                ..Default::default()
            },
        );
        let log = StageLogger::new("publish", Verbosity::Normal);

        assert!(publish_to_krew(&mut ctx, "mytool", &log).is_err());
    }

    #[test]
    fn test_publish_to_krew_missing_manifests_repo() {
        use anodizer_core::config::{Config, CrateConfig, KrewConfig, PublishConfig};
        use anodizer_core::context::{Context, ContextOptions};
        use anodizer_core::log::{StageLogger, Verbosity};

        let mut config = Config::default();
        config.crates = vec![CrateConfig {
            name: "mytool".to_string(),
            path: ".".to_string(),
            tag_template: "v{{ .Version }}".to_string(),
            publish: Some(PublishConfig {
                krew: Some(KrewConfig {
                    repository: None, // Missing
                    ..Default::default()
                }),
                ..Default::default()
            }),
            ..Default::default()
        }];

        let mut ctx = Context::new(
            config,
            ContextOptions {
                dry_run: true,
                ..Default::default()
            },
        );
        let log = StageLogger::new("publish", Verbosity::Normal);

        assert!(publish_to_krew(&mut ctx, "mytool", &log).is_err());
    }

    // -----------------------------------------------------------------------
    // artifacts_to_platforms .exe / binary-name-resolution tests
    // -----------------------------------------------------------------------

    fn make_os_artifact(os: &str, arch: &str, binary: Option<&str>) -> OsArtifact {
        OsArtifact {
            url: format!("https://example.com/{}-{}.tar.gz", os, arch),
            sha256: "deadbeef".into(),
            os: os.into(),
            arch: arch.into(),
            id: None,
            amd64_variant: None,
            arm_variant: None,
            binary: binary.map(|s| s.to_string()),
        }
    }

    #[test]
    fn test_artifacts_to_platforms_appends_exe_for_windows() {
        let arts = vec![
            make_os_artifact("linux", "amd64", Some("cfgd")),
            make_os_artifact("windows", "amd64", Some("cfgd")),
            make_os_artifact("darwin", "arm64", Some("cfgd")),
        ];
        let plats = artifacts_to_platforms(&arts, "cfgd");
        let by_os = |os: &str| plats.iter().find(|p| p.os == os).expect("missing platform");
        assert_eq!(by_os("linux").bin, "cfgd");
        assert_eq!(by_os("windows").bin, "cfgd.exe");
        assert_eq!(by_os("darwin").bin, "cfgd");
    }

    #[test]
    fn test_artifacts_to_platforms_does_not_double_suffix_exe() {
        let arts = vec![make_os_artifact("windows", "amd64", Some("cfgd.exe"))];
        let plats = artifacts_to_platforms(&arts, "cfgd");
        assert_eq!(plats[0].bin, "cfgd.exe");
    }

    #[test]
    fn test_artifacts_to_platforms_uses_archive_binary_name_over_default() {
        // Crate is `kubectl-cfgd` but ships binary `cfgd` — the manifest
        // must point at the in-archive name, not the crate name.
        let arts = vec![make_os_artifact("linux", "amd64", Some("cfgd"))];
        let plats = artifacts_to_platforms(&arts, "kubectl-cfgd");
        assert_eq!(plats[0].bin, "cfgd");
    }

    #[test]
    fn test_artifacts_to_platforms_falls_back_to_default_when_binary_unset() {
        let arts = vec![make_os_artifact("linux", "amd64", None)];
        let plats = artifacts_to_platforms(&arts, "cfgd");
        assert_eq!(plats[0].bin, "cfgd");
    }

    #[test]
    fn test_artifacts_to_platforms_arch_all_expands_with_correct_bin() {
        // arch=all should expand to amd64+arm64 with the same bin name on
        // both. Not a Windows test (krew doesn't use arch=all on windows
        // in practice) — just confirms the expansion path also flows
        // through resolve_bin.
        let arts = vec![make_os_artifact("darwin", "all", Some("cfgd"))];
        let plats = artifacts_to_platforms(&arts, "cfgd");
        assert_eq!(plats.len(), 2);
        assert!(plats.iter().all(|p| p.bin == "cfgd"));
        let arches: Vec<_> = plats.iter().map(|p| p.arch.as_str()).collect();
        assert!(arches.contains(&"amd64"));
        assert!(arches.contains(&"arm64"));
    }

    /// Regression for GoReleaser parity P9.1 (commit cba5b9f):
    /// `krew.skip_upload: "{{ .IsSnapshot }}"` must template-expand
    /// before its bool/auto/empty interpretation. On a snapshot run
    /// the rendered value is `"true"` and the publish path must
    /// short-circuit to `Ok(())` BEFORE the missing-repository check.
    #[test]
    fn krew_skip_upload_template_expands_to_true_on_snapshot() {
        use anodizer_core::config::{Config, CrateConfig, KrewConfig, PublishConfig, StringOrBool};
        use anodizer_core::context::{Context, ContextOptions};
        use anodizer_core::log::{StageLogger, Verbosity};

        let mut config = Config::default();
        config.project_name = "mytool".to_string();
        config.crates = vec![CrateConfig {
            name: "mytool".to_string(),
            path: ".".to_string(),
            tag_template: "v{{ .Version }}".to_string(),
            publish: Some(PublishConfig {
                krew: Some(KrewConfig {
                    // repository intentionally None — would normally
                    // hard-fail with "no repository config", but the
                    // skip_upload short-circuit must run BEFORE the
                    // repository-missing check.
                    repository: None,
                    skip_upload: Some(StringOrBool::String("{{ .IsSnapshot }}".to_string())),
                    ..Default::default()
                }),
                ..Default::default()
            }),
            ..Default::default()
        }];

        let mut ctx = Context::new(
            config,
            ContextOptions {
                snapshot: true,
                ..Default::default()
            },
        );
        ctx.template_vars_mut().set("IsSnapshot", "true");

        let log = StageLogger::new("publish", Verbosity::Normal);
        publish_to_krew(&mut ctx, "mytool", &log).expect(
            "skip_upload='{{ .IsSnapshot }}' on snapshot must short-circuit \
             to Ok(()) before the repository-missing check (GR cba5b9f)",
        );
    }
}

// ---------------------------------------------------------------------------
// KrewPublisher — Publisher trait wrapper (close-PR rollback)
// ---------------------------------------------------------------------------

// Krew plugin-index publisher. Each successful per-crate publish opens a
// PR against an upstream `krew-index`-style repo from a fork. The rollback
// path closes those PRs via `PATCH /repos/<upstream>/pulls/<n>` with
// `state=closed`.
//
// PR-number discovery uses the query-at-rollback-time approach: at
// publish time only the upstream coordinates, the fork owner, and the
// branch name the publish path pushed to are recorded. At rollback time
// open PRs filtered by `head=<fork_owner>:<branch>` are listed and each
// match is closed. This sidesteps modifying the unchanged
// `publish_to_krew` body to surface the new PR number, and stays robust
// against a stale evidence file stitched in from an older run.
//
// CREDENTIAL HANDLING: `KrewPrTarget` stores `token_env_var` — the
// NAME of the env var to consult at rollback time — not the resolved
// token VALUE. Same rule applies to every PR-based publisher that
// touches GitHub auth.

simple_publisher!(
    KrewPublisher,
    "krew",
    anodizer_core::PublisherGroup::Manager,
    false,
    Some("GITHUB_TOKEN pull_request:write"),
);

/// Aliased to the core-owned snapshot so the evidence schema lives in
/// [`anodizer_core::publish_evidence`] and credential-shaped fields
/// have no slot to land in. One entry per crate whose publish path
/// successfully pushed a branch to its fork.
type KrewPrTarget = anodizer_core::publish_evidence::KrewTargetSnapshot;

/// Decode the `krew_targets` array from
/// [`anodizer_core::PublishEvidence::extra`].
fn decode_krew_targets(extra: &anodizer_core::PublishEvidenceExtra) -> Vec<KrewPrTarget> {
    match extra {
        anodizer_core::PublishEvidenceExtra::Krew(k) => k.krew_targets.clone(),
        _ => Vec::new(),
    }
}

/// Resolve the upstream `<owner>/<repo>` slug for a krew target — mirrors
/// the dispatch logic in `publish_to_krew`: prefer
/// `repository.pull_request.base` when set, else fall back to the
/// canonical kubernetes-sigs/krew-index.
fn resolve_krew_upstream(krew_cfg: &anodizer_core::config::KrewConfig) -> (String, String) {
    if let Some(base) = krew_cfg
        .repository
        .as_ref()
        .and_then(|r| r.pull_request.as_ref())
        .and_then(|pr| pr.base.as_ref())
        && let (Some(o), Some(n)) = (base.owner.as_deref(), base.name.as_deref())
    {
        return (o.to_string(), n.to_string());
    }
    ("kubernetes-sigs".to_string(), "krew-index".to_string())
}

/// Build a [`KrewPrTarget`] for each crate the publisher would run on.
/// Reads config + the live process version so the branch name matches
/// what `publish_to_krew` will push.
fn collect_krew_run_targets(ctx: &Context) -> Vec<KrewPrTarget> {
    let mut out: Vec<KrewPrTarget> = Vec::new();
    let version = ctx.version();
    let selected = &ctx.options.selected_crates;
    for c in &ctx.config.crates {
        if !selected.is_empty() && !selected.contains(&c.name) {
            continue;
        }
        let Some(krew_cfg) = c.publish.as_ref().and_then(|p| p.krew.as_ref()) else {
            continue;
        };
        let Some((fork_owner_raw, _)) =
            crate::util::resolve_repo_owner_name(krew_cfg.repository.as_ref())
        else {
            continue;
        };
        let fork_owner = ctx
            .render_template(&fork_owner_raw)
            .unwrap_or(fork_owner_raw);
        // Plugin-name override mirrors `publish_to_krew`'s resolution.
        let plugin_name_raw = krew_cfg.name.as_deref().unwrap_or(&c.name);
        let plugin_name = ctx
            .render_template(plugin_name_raw)
            .unwrap_or_else(|_| plugin_name_raw.to_string());
        let branch = format!("{}-v{}", plugin_name, version);
        let (upstream_owner, upstream_repo) = resolve_krew_upstream(krew_cfg);
        out.push(KrewPrTarget {
            target: c.name.clone(),
            upstream_owner,
            upstream_repo,
            fork_owner,
            branch,
            token_env_var: Some("KREW_INDEX_TOKEN".to_string()),
        });
    }
    out
}

/// True when the crate has a `publish.krew` block — mirrors the
/// `per_crate!` predicate in `lib.rs` so the publisher iterates
/// exactly the same crate universe.
fn is_krew_per_crate_configured(ctx: &Context, crate_name: &str) -> bool {
    crate::util::all_crates(ctx)
        .into_iter()
        .any(|c| c.name == crate_name && c.publish.as_ref().is_some_and(|p| p.krew.is_some()))
}

/// Message emitted at publisher entry. Names how many crates the publisher
/// is iterating over. Factored into a helper so tests can pin the exact
/// substring an operator scans the log for.
pub(crate) fn run_start_message(selected_total: usize) -> String {
    format!(
        "krew: starting publish for {} selected crate(s)",
        selected_total
    )
}

/// Message emitted when a selected crate has no `publish.krew` block.
/// Replaces what used to be a silent `continue` — operators need to see
/// why a per-crate publish was a no-op rather than guess from a blank log.
pub(crate) fn run_skip_unconfigured_message(crate_name: &str) -> String {
    format!(
        "krew: skipping crate '{}' — no krew config block",
        crate_name
    )
}

/// Message emitted just before delegating to `publish_to_krew`. Anchors
/// the krew activity (plugin manifest render, fork clone, PR submission)
/// to a specific crate in the log so multi-crate workspaces are
/// disambiguatable.
pub(crate) fn run_per_crate_start_message(crate_name: &str) -> String {
    format!("krew: starting per-crate publish for '{}'", crate_name)
}

/// Final summary emitted at publisher exit. `processed` is the count of
/// crates the publisher actually invoked `publish_to_krew` on (not the
/// count of successful PRs — `publish_to_krew` has its own skip paths for
/// skip_upload/dry-run/etc., each of which logs its own status line).
pub(crate) fn run_done_message(processed: usize) -> String {
    format!("krew: completed — {} crate(s) processed", processed)
}

/// Decision predicate for the no-eligible-crates warning. True when the
/// publisher walked the selection but the configured-predicate filtered
/// every crate out — distinct from "ran successfully in dry-run mode".
///
/// `processed` is the count of crates whose `is_krew_per_crate_configured`
/// check passed and whose `publish_to_krew` invocation was reached.
/// `selected_len` is the size of the implicit-all-resolved selection.
pub(crate) fn should_warn_no_eligible(processed: usize, selected_len: usize) -> bool {
    processed == 0 && selected_len > 0
}

/// Warning emitted when the publisher was registered (at least one crate
/// has a `publish.krew` block at the config level) but the run path
/// processed zero crates.
///
/// With the implicit-all default in
/// [`crate::publisher_helpers::effective_publish_crates`], an empty
/// `selected_crates` resolves to every crate carrying a `publish.krew`
/// block — so a zero-processed run means `--crate`/`--all` matrix
/// selection was non-empty AND filtered every krew-configured crate out.
/// Operators must see this — otherwise the publisher's `succeeded` status
/// hides the fact that nothing was pushed.
pub(crate) fn run_no_eligible_crates_warning(selected_total: usize) -> String {
    format!(
        "krew: registered but 0 of {} effective crate(s) had a krew \
         config block — nothing pushed. Check that --crate / --all selects a \
         crate whose publish.krew block is set.",
        selected_total
    )
}

impl anodizer_core::Publisher for KrewPublisher {
    fn name(&self) -> &str {
        Self::PUBLISHER_NAME
    }
    fn group(&self) -> anodizer_core::PublisherGroup {
        Self::PUBLISHER_GROUP
    }
    fn required(&self) -> bool {
        Self::resolved_required(self)
    }
    fn rollback_scope_needed(&self) -> Option<&'static str> {
        Self::ROLLBACK_SCOPE
    }
    fn skips_on_nightly(&self) -> bool {
        true
    }

    fn run(&self, ctx: &mut Context) -> anyhow::Result<anodizer_core::PublishEvidence> {
        let log = ctx.logger("publish");
        let selected =
            crate::publisher_helpers::effective_publish_crates(ctx, is_krew_per_crate_configured);
        log.status(&run_start_message(selected.len()));
        let mut processed = 0usize;
        let mut any_pushed = false;
        for crate_name in &selected {
            // Defensive guard for explicit `--crate=X` selection when X has no
            // publisher block; implicit-all is already filtered by effective_publish_crates above.
            if !is_krew_per_crate_configured(ctx, crate_name) {
                log.status(&run_skip_unconfigured_message(crate_name));
                continue;
            }
            processed += 1;
            log.status(&run_per_crate_start_message(crate_name));
            let outcome = publish_to_krew(ctx, crate_name, &log)?;
            if outcome.pushed {
                any_pushed = true;
            }
        }
        if should_warn_no_eligible(processed, selected.len()) {
            log.warn(&run_no_eligible_crates_warning(selected.len()));
        } else {
            log.status(&run_done_message(processed));
        }
        let mut evidence = anodizer_core::PublishEvidence::new("krew");
        // Record rollback evidence only for the PrDirect flow, which
        // pushes a branch + opens a PR anodizer can later close. The
        // BotWebhook flow has no anodizer-owned PR (the krew-release-bot
        // server opens it), so there is nothing to roll back and no
        // evidence to record.
        if any_pushed {
            evidence.extra = anodizer_core::PublishEvidenceExtra::Krew(
                anodizer_core::publish_evidence::KrewExtra {
                    krew_targets: collect_krew_run_targets(ctx),
                },
            );
        }
        Ok(evidence)
    }

    fn rollback(
        &self,
        ctx: &mut Context,
        evidence: &anodizer_core::PublishEvidence,
    ) -> anyhow::Result<()> {
        let log = ctx.logger("publish");
        let targets = decode_krew_targets(&evidence.extra);

        // Only the PrDirect flow records PR targets; the BotWebhook flow
        // records none (the krew-release-bot server owns the PR). Nothing
        // to roll back when there are no targets.
        if targets.is_empty() {
            log.warn(&crate::publisher_helpers::rollback_empty_warning_msg(
                "krew",
                "PR targets",
            ));
            return Ok(());
        }

        // Resolve token at rollback time — never persisted in evidence.
        // Falls back to ANODIZER_GITHUB_TOKEN then GITHUB_TOKEN, same as
        // every git-revert publisher.
        let env = ctx.env_source();
        let resolve_token = |t: &KrewPrTarget| -> Option<String> {
            t.token_env_var
                .as_deref()
                .and_then(|n| env.var(n))
                .or_else(|| env.var("ANODIZER_GITHUB_TOKEN"))
                .or_else(|| env.var("GITHUB_TOKEN"))
        };

        // Fan out at PR granularity, not target granularity: a single
        // krew target can map to multiple open PRs if the publish path
        // pushed the same branch twice (idempotent re-publish). We dedup
        // PR numbers per (upstream, n) so we don't try to close the same
        // PR twice when two targets share the same fork branch.
        struct CloseJob {
            upstream_owner: String,
            upstream_repo: String,
            pr_number: u64,
            token: String,
            target_label: String,
        }
        let mut jobs: Vec<CloseJob> = Vec::new();
        let mut seen: std::collections::BTreeSet<(String, String, u64)> =
            std::collections::BTreeSet::new();
        for t in &targets {
            let Some(token) = resolve_token(t) else {
                log.warn(&format!(
                    "krew: no token resolvable for {} (env var ${} / \
                     ANODIZER_GITHUB_TOKEN / GITHUB_TOKEN all unset); \
                     skipping rollback for this target",
                    t.target,
                    t.token_env_var.as_deref().unwrap_or("KREW_INDEX_TOKEN"),
                ));
                continue;
            };
            let env_hint_for_target = t.token_env_var.as_deref().unwrap_or("KREW_INDEX_TOKEN");
            let pr_numbers = match crate::util::find_open_pr_numbers_for_head(
                &t.upstream_owner,
                &t.upstream_repo,
                &t.fork_owner,
                &t.branch,
                Some(&token),
                env_hint_for_target,
            ) {
                Ok(v) => v,
                Err(e) => {
                    // Auth-failure / repo-not-found / transport problems
                    // surface as actionable warns naming the actual
                    // failure mode — not the misleading "no PR found,
                    // verify manually" that previously fired here.
                    log.warn(&format!(
                        "krew: failed to query upstream {}/{} for open PRs ({}); \
                         {} — manual cleanup required",
                        t.upstream_owner, t.upstream_repo, t.target, e
                    ));
                    continue;
                }
            };
            if pr_numbers.is_empty() {
                log.warn(&format!(
                    "krew: no open PRs found for head={}:{} against {}/{}; \
                     verify manually",
                    t.fork_owner, t.branch, t.upstream_owner, t.upstream_repo,
                ));
                continue;
            }
            for n in pr_numbers {
                let key = (t.upstream_owner.clone(), t.upstream_repo.clone(), n);
                if seen.insert(key) {
                    jobs.push(CloseJob {
                        upstream_owner: t.upstream_owner.clone(),
                        upstream_repo: t.upstream_repo.clone(),
                        pr_number: n,
                        token: token.clone(),
                        target_label: t.target.clone(),
                    });
                }
            }
        }

        let env_hint = targets
            .first()
            .and_then(|t| t.token_env_var.as_deref())
            .unwrap_or("KREW_INDEX_TOKEN");

        // Three-bucket count: (closed, already_closed, failed).
        // `already_closed` is a success bucket — 404 / 410 / 422 from
        // the PATCH means the desired end-state ("PR not open") is
        // already true (maintainer closed it, repo renamed, PR
        // deleted). Re-running --rollback-only after a partial
        // success must NOT surface those as failures.
        let counts = std::sync::Mutex::new((0usize, 0usize, 0usize));
        for chunk in jobs.chunks(crate::util::ROLLBACK_PARALLELISM) {
            std::thread::scope(|s| {
                let mut handles = Vec::with_capacity(chunk.len());
                for job in chunk {
                    let log = log.clone();
                    let counts = &counts;
                    handles.push(s.spawn(move || {
                        let pr_url = format!(
                            "https://github.com/{}/{}/pull/{}",
                            job.upstream_owner, job.upstream_repo, job.pr_number
                        );
                        log.status(&format!(
                            "krew: closing PR {} ({})",
                            job.target_label, pr_url
                        ));
                        let outcome = crate::util::close_pr_via_api(
                            &job.upstream_owner,
                            &job.upstream_repo,
                            job.pr_number,
                            &job.token,
                        );
                        match outcome {
                            crate::util::CloseOutcome::Closed => {
                                let mut c = crate::util::lock_recover(counts, &log, "krew");
                                c.0 += 1;
                            }
                            crate::util::CloseOutcome::AlreadyClosed => {
                                let mut c = crate::util::lock_recover(counts, &log, "krew");
                                c.1 += 1;
                                log.status(&format!(
                                    "krew: PR {} ({}) already closed/deleted upstream — \
                                     rollback noticed the existing state",
                                    job.target_label, pr_url
                                ));
                            }
                            crate::util::CloseOutcome::Failed(err) => {
                                let mut c = crate::util::lock_recover(counts, &log, "krew");
                                c.2 += 1;
                                log.warn(&crate::publisher_helpers::rollback_failure_warning_msg(
                                    "krew",
                                    &job.target_label,
                                    &pr_url,
                                    &err,
                                    Some(env_hint),
                                ));
                            }
                        }
                    }));
                }
                for h in handles {
                    crate::util::join_or_warn(h, &log, "krew");
                }
            });
        }
        // `into_inner` consumes the Mutex; poison here means a worker
        // panicked. Counter state is still valid (3-tuple of usize) so
        // recover and emit the summary rather than abandon the operator.
        let (closed, already_closed, failed) = match counts.into_inner() {
            Ok(c) => c,
            Err(poisoned) => {
                log.warn("krew: mutex poisoned by worker panic; reporting counters as-of poison");
                poisoned.into_inner()
            }
        };
        log.status(&format!(
            "krew: closed {}, already-closed {}, failed {}",
            closed, already_closed, failed
        ));
        Ok(())
    }

    fn preflight(&self, _ctx: &Context) -> anyhow::Result<anodizer_core::PreflightCheck> {
        Ok(anodizer_core::PreflightCheck::Pass)
    }
}

#[cfg(test)]
mod publisher_tests {
    use super::*;
    use anodizer_core::config::{
        CrateConfig, KrewConfig, PublishConfig, RepositoryConfig, StringOrBool,
    };
    use anodizer_core::test_helpers::TestContextBuilder;
    use anodizer_core::{PreflightCheck, PublishEvidence, Publisher, PublisherGroup};

    fn krew_crate(name: &str) -> CrateConfig {
        CrateConfig {
            name: name.to_string(),
            path: ".".to_string(),
            tag_template: "v{{ .Version }}".to_string(),
            publish: Some(PublishConfig {
                krew: Some(KrewConfig {
                    repository: Some(RepositoryConfig {
                        owner: Some("acme".to_string()),
                        name: Some("krew-index-fork".to_string()),
                        ..Default::default()
                    }),
                    short_description: Some("a kubectl plugin".to_string()),
                    description: Some("a kubectl plugin".to_string()),
                    ..Default::default()
                }),
                ..Default::default()
            }),
            ..Default::default()
        }
    }

    #[test]
    fn krew_publisher_classification() {
        let p = KrewPublisher::new();
        assert_eq!(p.name(), "krew");
        assert_eq!(p.group(), PublisherGroup::Manager);
        assert!(!p.required());
        assert_eq!(
            p.rollback_scope_needed(),
            Some("GITHUB_TOKEN pull_request:write")
        );
    }

    #[test]
    fn krew_preflight_defaults_to_pass() {
        let ctx = TestContextBuilder::new().build();
        let p = KrewPublisher::new();
        assert!(matches!(
            p.preflight(&ctx).expect("preflight ok"),
            PreflightCheck::Pass
        ));
    }

    #[test]
    fn krew_rollback_warns_when_no_targets_recorded() {
        let capture = anodizer_core::log::LogCapture::new();
        let mut ctx = TestContextBuilder::new().build();
        ctx.with_log_capture(capture.clone());
        let evidence = PublishEvidence::new("krew");
        let p = KrewPublisher::new();
        assert!(p.rollback(&mut ctx, &evidence).is_ok());

        let warns = capture.warn_messages();
        assert!(
            warns
                .iter()
                .any(|m| m.contains("krew") && m.contains("PR targets") && m.contains("verify")),
            "expected captured warn naming publisher + target-noun + 'verify'; got: {warns:?}"
        );
    }

    #[test]
    fn krew_target_extra_roundtrips() {
        let original = vec![KrewPrTarget {
            target: "demo".into(),
            upstream_owner: "kubernetes-sigs".into(),
            upstream_repo: "krew-index".into(),
            fork_owner: "acme".into(),
            branch: "demo-v1.2.3".into(),
            token_env_var: Some("KREW_INDEX_TOKEN".into()),
        }];
        let extra =
            anodizer_core::PublishEvidenceExtra::Krew(anodizer_core::publish_evidence::KrewExtra {
                krew_targets: original.clone(),
            });
        let decoded = decode_krew_targets(&extra);
        assert_eq!(decoded, original);
    }

    #[test]
    fn krew_target_extra_carries_no_secret_material() {
        // Structural pin: build a typed-variant evidence and assert
        // (a) no credential-shaped keys appear AND (b) the
        // operator-public PR coordinates are preserved.
        let mut e = anodizer_core::PublishEvidence::new("krew");
        e.extra =
            anodizer_core::PublishEvidenceExtra::Krew(anodizer_core::publish_evidence::KrewExtra {
                krew_targets: vec![KrewPrTarget {
                    target: "demo".into(),
                    upstream_owner: "kubernetes-sigs".into(),
                    upstream_repo: "krew-index".into(),
                    fork_owner: "acme".into(),
                    branch: "demo-v1.2.3".into(),
                    token_env_var: Some("KREW_INDEX_TOKEN".into()),
                }],
            });
        let s = serde_json::to_string(&e).expect("serialize");
        assert!(!s.contains("\"token\":"), "{s}");
        assert!(!s.contains("\"password\":"), "{s}");
        assert!(!s.contains("\"pat\":"), "{s}");
        assert!(!s.contains("\"private_key\":"), "{s}");
        assert!(!s.contains("\"secret\":"), "{s}");
        assert!(!s.contains("\"api_key\":"), "{s}");
        assert!(s.contains("KREW_INDEX_TOKEN"), "{s}");
        assert!(s.contains("\"upstream_owner\":\"kubernetes-sigs\""), "{s}");
        assert!(s.contains("\"upstream_repo\":\"krew-index\""), "{s}");
        assert!(s.contains("\"fork_owner\":\"acme\""), "{s}");
    }

    #[test]
    fn krew_effective_publish_crates_implicit_all_when_selection_empty() {
        // Regression pin for the `selected_crates = Vec::new()` failure
        // mode: the run path used to iterate the empty Vec and silently
        // skip every configured krew plugin. The helper now resolves to
        // implicit-all over `publish.krew`-carrying crates.
        let ctx = TestContextBuilder::new()
            .crates(vec![
                krew_crate("alpha"),
                krew_crate("beta"),
                CrateConfig {
                    name: "gamma".to_string(),
                    path: ".".to_string(),
                    tag_template: "v{{ .Version }}".to_string(),
                    publish: Some(PublishConfig::default()),
                    ..Default::default()
                },
            ])
            .build();
        let names =
            crate::publisher_helpers::effective_publish_crates(&ctx, is_krew_per_crate_configured);
        assert_eq!(names, vec!["alpha".to_string(), "beta".to_string()]);
    }

    #[test]
    fn krew_effective_publish_crates_honors_non_empty_selection() {
        let ctx = TestContextBuilder::new()
            .crates(vec![krew_crate("alpha"), krew_crate("beta")])
            .selected_crates(vec!["beta".to_string()])
            .build();
        let names =
            crate::publisher_helpers::effective_publish_crates(&ctx, is_krew_per_crate_configured);
        assert_eq!(names, vec!["beta".to_string()]);
    }

    #[test]
    fn krew_collect_run_targets_uses_default_upstream() {
        let ctx = TestContextBuilder::new()
            .crates(vec![krew_crate("demo")])
            .build();
        let targets = collect_krew_run_targets(&ctx);
        assert_eq!(targets.len(), 1);
        assert_eq!(targets[0].target, "demo");
        assert_eq!(targets[0].upstream_owner, "kubernetes-sigs");
        assert_eq!(targets[0].upstream_repo, "krew-index");
        assert_eq!(targets[0].fork_owner, "acme");
        assert!(
            targets[0].branch.starts_with("demo-v"),
            "branch: {}",
            targets[0].branch
        );
    }

    #[test]
    fn krew_collect_run_targets_honors_pull_request_base_override() {
        use anodizer_core::config::{PullRequestBaseConfig, PullRequestConfig};
        let mut c = krew_crate("demo");
        if let Some(p) = c.publish.as_mut()
            && let Some(k) = p.krew.as_mut()
            && let Some(r) = k.repository.as_mut()
        {
            r.pull_request = Some(PullRequestConfig {
                enabled: Some(true),
                base: Some(PullRequestBaseConfig {
                    owner: Some("custom-org".to_string()),
                    name: Some("custom-index".to_string()),
                    branch: None,
                }),
                draft: None,
                body: None,
            });
        }
        let ctx = TestContextBuilder::new().crates(vec![c]).build();
        let targets = collect_krew_run_targets(&ctx);
        assert_eq!(targets.len(), 1);
        assert_eq!(targets[0].upstream_owner, "custom-org");
        assert_eq!(targets[0].upstream_repo, "custom-index");
    }

    // -----------------------------------------------------------------------
    // Log-message helpers — the operator-facing log strings the publisher
    // emits at each boundary.

    #[test]
    fn run_start_message_names_selected_total() {
        let msg = run_start_message(3);
        assert!(msg.starts_with("krew:"), "{msg}");
        assert!(msg.contains("starting publish"), "{msg}");
        assert!(msg.contains("3 selected"), "{msg}");
    }

    #[test]
    fn run_skip_unconfigured_message_names_crate() {
        let msg = run_skip_unconfigured_message("demo");
        assert!(msg.starts_with("krew:"), "{msg}");
        assert!(msg.contains("skipping crate 'demo'"), "{msg}");
        assert!(msg.contains("no krew config block"), "{msg}");
    }

    #[test]
    fn run_per_crate_start_message_names_crate() {
        let msg = run_per_crate_start_message("demo");
        assert!(msg.starts_with("krew:"), "{msg}");
        assert!(msg.contains("starting per-crate publish"), "{msg}");
        assert!(msg.contains("'demo'"), "{msg}");
    }

    #[test]
    fn run_done_message_reports_processed_count() {
        let msg = run_done_message(2);
        assert!(msg.starts_with("krew:"), "{msg}");
        assert!(msg.contains("completed"), "{msg}");
        assert!(msg.contains("2 crate(s) processed"), "{msg}");
    }

    #[test]
    fn run_no_eligible_crates_warning_names_remediation() {
        let msg = run_no_eligible_crates_warning(5);
        assert!(msg.starts_with("krew:"), "{msg}");
        assert!(msg.contains("registered"), "{msg}");
        assert!(msg.contains("0 of 5 effective"), "{msg}");
        assert!(msg.contains("nothing pushed"), "{msg}");
        assert!(msg.contains("--crate"), "{msg}");
        assert!(msg.contains("--all"), "{msg}");
    }

    /// The no-eligible-crates warning must fire only when the iteration
    /// loop's configured-predicate filtered every selected crate out — not
    /// when the publish path was reached successfully.
    #[test]
    fn should_warn_no_eligible_only_fires_when_predicate_filtered_everything() {
        // One configured crate reached the publish path → no warning.
        assert!(!should_warn_no_eligible(1, 1));
        // True positive: none configured.
        assert!(should_warn_no_eligible(0, 3));
        // Empty selection → no warning.
        assert!(!should_warn_no_eligible(0, 0));
        // Partial-skip → no warning.
        assert!(!should_warn_no_eligible(1, 3));
    }

    /// Run the publisher end-to-end in dry-run mode against a context that
    /// selects a krew-configured crate. Verifies the run path is wired
    /// (returns Ok). The log lines are written to stderr and asserted
    /// indirectly via the helper-string tests above.
    #[test]
    fn krew_publisher_run_dry_run_returns_ok() {
        let mut ctx = TestContextBuilder::new()
            .crates(vec![krew_crate("demo")])
            .selected_crates(vec!["demo".to_string()])
            .dry_run(true)
            .build();
        let p = KrewPublisher::new();
        let evidence = p.run(&mut ctx).expect("dry-run publisher.run");
        // dry-run publish_to_krew short-circuits before branch push; no actual
        // push occurred so evidence.extra must be empty (no phantom targets).
        let targets = decode_krew_targets(&evidence.extra);
        assert!(
            targets.is_empty(),
            "dry-run must not record rollback targets: {targets:?}"
        );
    }

    /// When the publisher is registered (a crate has a krew block) but the
    /// selected-crates filter excludes every krew-configured crate, the run
    /// path must still return Ok and the processed count is zero.
    #[test]
    fn krew_publisher_run_no_eligible_crates_returns_ok() {
        let mut ctx = TestContextBuilder::new()
            .crates(vec![
                krew_crate("demo"),
                CrateConfig {
                    name: "other".to_string(),
                    path: ".".to_string(),
                    tag_template: "v{{ .Version }}".to_string(),
                    publish: Some(PublishConfig::default()),
                    ..Default::default()
                },
            ])
            // Select only the non-krew crate — publisher registered but
            // run path will iterate zero krew-configured crates.
            .selected_crates(vec!["other".to_string()])
            .dry_run(true)
            .build();
        let p = KrewPublisher::new();
        // Must return Ok even when no krew-configured crate is selected.
        p.run(&mut ctx).expect("publisher.run ok");
    }

    /// Implicit-all selection (empty `selected_crates`) + dry-run must
    /// produce empty evidence. The implicit-all path resolves through
    /// `effective_publish_crates` to every krew-configured crate, so this
    /// pins the gate where phantom rollback targets used to leak.
    #[test]
    fn test_publish_to_krew_dry_run_implicit_all_produces_empty_evidence() {
        let mut ctx = TestContextBuilder::new()
            .crates(vec![krew_crate("demo"), krew_crate("other")])
            // No selected_crates → implicit-all resolves to both krew crates.
            .dry_run(true)
            .build();
        let p = KrewPublisher::new();
        let evidence = p.run(&mut ctx).expect("dry-run implicit-all publisher.run");
        let targets = decode_krew_targets(&evidence.extra);
        assert!(
            targets.is_empty(),
            "dry-run + implicit-all must not record rollback targets: {targets:?}"
        );
    }

    /// skip_upload path must produce empty evidence — no branch push occurred.
    #[test]
    fn krew_publisher_run_skip_upload_produces_empty_evidence() {
        let mut crate_with_skip = krew_crate("demo");
        if let Some(ref mut publish) = crate_with_skip.publish
            && let Some(ref mut krew) = publish.krew
        {
            krew.skip_upload = Some(StringOrBool::Bool(true));
        }
        let mut ctx = TestContextBuilder::new()
            .crates(vec![crate_with_skip])
            .selected_crates(vec!["demo".to_string()])
            .build();
        let p = KrewPublisher::new();
        let evidence = p.run(&mut ctx).expect("skip_upload publisher.run");
        let targets = decode_krew_targets(&evidence.extra);
        assert!(
            targets.is_empty(),
            "skip_upload must not record rollback targets: {targets:?}"
        );
    }

    #[test]
    fn krew_publisher_visible_work_contract() {
        use crate::testing::assert_publisher_visible_work_contract;
        let mut ctx = TestContextBuilder::new()
            .crates(vec![krew_crate("demo")])
            .selected_crates(vec!["demo".to_string()])
            .dry_run(true)
            .build();
        let p = KrewPublisher::new();
        assert_publisher_visible_work_contract(&p, &mut ctx);
    }

    /// Building a krew plugin manifest for an artifact whose `sha256`
    /// metadata is empty must bail with an actionable error. Defaulting
    /// to `""` would embed an empty `sha256:` field in the rendered
    /// manifest, which krew's `addURIAndSha` validator rejects at
    /// install time. The bail message must name the publisher, the
    /// field, the offending artifact context, and a next-step hint.
    #[test]
    fn krew_sha256_empty_metadata_bails_with_actionable_error() {
        use anodizer_core::artifact::{Artifact, ArtifactKind};
        use anodizer_core::config::{
            Config, CrateConfig, KrewConfig, PublishConfig, RepositoryConfig,
        };
        use anodizer_core::context::{Context, ContextOptions};
        use anodizer_core::log::{StageLogger, Verbosity};
        let config = Config {
            crates: vec![CrateConfig {
                name: "mytool".to_string(),
                path: ".".to_string(),
                tag_template: "v{{ .Version }}".to_string(),
                publish: Some(PublishConfig {
                    krew: Some(KrewConfig {
                        repository: Some(RepositoryConfig {
                            owner: Some("acme".to_string()),
                            name: Some("krew-index-fork".to_string()),
                            ..Default::default()
                        }),
                        short_description: Some("a kubectl plugin".to_string()),
                        description: Some("a kubectl plugin".to_string()),
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
                ..Default::default()
            }],
            ..Default::default()
        };
        let mut ctx = Context::new(config, ContextOptions::default());
        ctx.artifacts.add(Artifact {
            kind: ArtifactKind::Archive,
            path: std::path::PathBuf::from("/tmp/mytool-linux-amd64.tar.gz"),
            name: "mytool-linux-amd64.tar.gz".to_string(),
            target: Some("x86_64-unknown-linux-gnu".to_string()),
            crate_name: "mytool".to_string(),
            metadata: {
                let mut m = std::collections::HashMap::new();
                m.insert(
                    "url".to_string(),
                    "https://example.com/mytool-linux-amd64.tar.gz".to_string(),
                );
                m.insert("extra_binaries".to_string(), "mytool".to_string());
                m
            },
            size: None,
        });
        let log = StageLogger::new("publish", Verbosity::Quiet);
        let err = publish_to_krew(&mut ctx, "mytool", &log).expect_err("missing sha256 must bail");
        let msg = format!("{err:#}");
        assert!(
            msg.contains("missing sha256 metadata"),
            "error must mention missing sha256; got: {msg}"
        );
        assert!(
            msg.contains("mytool"),
            "error must name the offending crate; got: {msg}"
        );
        assert!(
            msg.contains("checksum stage"),
            "error must mention the checksum stage; got: {msg}"
        );
    }
}
