use std::path::{Path, PathBuf};

use anodizer_core::context::Context;
use anodizer_core::log::StageLogger;
use anyhow::{Context as _, Result};
use serde::Serialize;

use crate::util::{self, OsArtifact};

// ---------------------------------------------------------------------------
// KrewManifestParams
// ---------------------------------------------------------------------------

/// Parameters for generating a Krew plugin manifest YAML.
pub(crate) struct KrewManifestParams<'a> {
    pub(crate) name: &'a str,
    pub(crate) version: &'a str,
    pub(crate) homepage: &'a str,
    pub(crate) short_description: &'a str,
    pub(crate) description: &'a str,
    pub(crate) caveats: &'a str,
    /// `(os, arch, url, sha256, binary_name)` tuples for each platform.
    pub(crate) platforms: &'a [KrewPlatform],
}

/// A single platform entry in the Krew manifest.
pub(crate) struct KrewPlatform {
    pub(crate) os: String,
    pub(crate) arch: String,
    pub(crate) url: String,
    pub(crate) sha256: String,
    pub(crate) bin: String,
}

// ---------------------------------------------------------------------------
// Serde structs for Krew YAML manifest
// ---------------------------------------------------------------------------

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct KrewManifestYaml {
    #[serde(rename = "apiVersion")]
    api_version: String,
    kind: String,
    metadata: KrewMetadata,
    spec: KrewSpec,
}

#[derive(Serialize)]
struct KrewMetadata {
    name: String,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct KrewSpec {
    version: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    homepage: Option<String>,
    short_description: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    caveats: Option<String>,
    platforms: Vec<KrewPlatformYaml>,
}

#[derive(Serialize)]
struct KrewPlatformYaml {
    selector: KrewSelector,
    uri: String,
    sha256: String,
    bin: String,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct KrewSelector {
    match_labels: KrewMatchLabels,
}

#[derive(Serialize)]
struct KrewMatchLabels {
    os: String,
    arch: String,
}

// ---------------------------------------------------------------------------
// generate_manifest
// ---------------------------------------------------------------------------

/// Generate a Krew plugin manifest YAML string.
///
/// Uses `serde_yaml_ng` for proper YAML serialization with correct escaping
/// of special characters. The `description` and `caveats` fields use YAML
/// block scalar style (literal `|`) when present, achieved via post-processing.
pub(crate) fn generate_manifest(params: &KrewManifestParams<'_>) -> Result<String> {
    let mut platforms: Vec<KrewPlatformYaml> = params
        .platforms
        .iter()
        .map(|p| KrewPlatformYaml {
            selector: KrewSelector {
                match_labels: KrewMatchLabels {
                    os: p.os.clone(),
                    arch: krew_arch(&p.arch).to_string(),
                },
            },
            uri: p.url.clone(),
            sha256: p.sha256.clone(),
            bin: p.bin.clone(),
        })
        .collect();

    // sort platforms by URI descending.
    platforms.sort_by(|a, b| b.uri.cmp(&a.uri));

    let manifest = KrewManifestYaml {
        api_version: "krew.googlecontainertools.github.com/v1alpha2".to_string(),
        kind: "Plugin".to_string(),
        metadata: KrewMetadata {
            name: params.name.to_string(),
        },
        spec: KrewSpec {
            version: format!("v{}", params.version),
            homepage: if params.homepage.is_empty() {
                None
            } else {
                Some(params.homepage.to_string())
            },
            short_description: params.short_description.to_string(),
            description: if params.description.is_empty() {
                None
            } else {
                Some(params.description.to_string())
            },
            caveats: if params.caveats.is_empty() {
                None
            } else {
                Some(params.caveats.to_string())
            },
            platforms,
        },
    };

    let yaml = serde_yaml_ng::to_string(&manifest).context("krew: serialize manifest")?;

    Ok(format!(
        "# This file was generated by anodizer. DO NOT EDIT.\n{}",
        yaml
    ))
}

/// Map the internal arch names to Krew's expected labels.
///
/// This is a publisher-specific mapping layer on top of the generic
/// `infer_arch` in `util.rs`. The util layer produces canonical short
/// forms (`"amd64"`, `"arm64"`), and this function translates them
/// to whatever Krew expects. Today the mapping is a no-op for the
/// common cases, but keeping a separate layer allows adapting to
/// future Krew label changes without touching the shared inference.
fn krew_arch(arch: &str) -> &str {
    match arch {
        "amd64" | "x86_64" => "amd64",
        "arm64" | "aarch64" => "arm64",
        other => other,
    }
}

/// Map the internal OS names to Krew's expected labels.
///
/// See `krew_arch` for the rationale behind keeping a separate mapping
/// layer on top of `infer_os` in `util.rs`.
fn krew_os(os: &str) -> &str {
    match os {
        "darwin" | "macos" => "darwin",
        "linux" => "linux",
        "windows" => "windows",
        other => other,
    }
}

// ---------------------------------------------------------------------------
// krew-release-bot auto-detection
// ---------------------------------------------------------------------------
//
// Spec: `.claude/features/krew-bot-auto-detect.md`.
//
// Once a plugin lands in `kubernetes-sigs/krew-index`, the krew maintainers
// recommend switching from anodizer's `pr-direct` (clone fork → write manifest
// → PR) flow to `krew-release-bot` — a GitHub Action in the plugin's own repo
// that opens the krew-index PR on the plugin's behalf on every git-tag push.
//
// Anodizer auto-detects which mode applies. No config key; the consumer never
// has to toggle a flag.
//
// Two signals decide the mode:
//   1. Plugin in krew-index?  Anon GET against the GitHub contents API:
//        `api.github.com/repos/kubernetes-sigs/krew-index/contents/plugins/<name>.yaml`
//      → 200 means published; 404 means not yet; any other error means
//      "unknown" and we fall back to the safe `pr-direct` flow.
//   2. Bot wired in this repo?  Grep `.github/workflows/*.yml` for
//      `rajatjindal/krew-release-bot` (the published Action). The Action
//      input `krew_template_file` is also parsed when present so anodizer
//      writes the template to the path the user's workflow actually reads.

/// Three publish modes the krew publisher dispatches between.
#[derive(Debug, Clone, PartialEq, Eq)]
enum KrewMode {
    /// Initial-submission flow — plugin isn't in krew-index yet.
    /// Behaviour: clone fork, write `plugins/<name>.yaml`, commit, PR
    /// against `kubernetes-sigs/krew-index`. Unchanged from pre-detection.
    PrDirect,
    /// Plugin IS in krew-index but the bot is NOT wired in this repo.
    /// Behaviour: same `pr-direct` flow PLUS a one-line hint in the run
    /// summary pointing the user at the bot setup doc. Wiring the bot is
    /// the user's call; anodizer never edits `.github/workflows/`.
    PrDirectWithHint,
    /// Plugin IS in krew-index AND the bot is wired in this repo.
    /// Behaviour: render the manifest as a bot template (uses
    /// `{{ .TagName }}` + `addURIAndSha` placeholders) and write it to
    /// `<workdir>/<template_path>`. NO PR against krew-index — the bot
    /// opens that PR when the user pushes the release tag.
    BotTemplate { template_path: PathBuf },
}

/// Detect the appropriate krew mode for a given plugin in the current
/// repository. Always succeeds — every detection error falls back to
/// the safe `PrDirect` mode rather than aborting the publisher.
fn detect_krew_mode(plugin_name: &str, workdir: Option<&Path>, token: Option<&str>) -> KrewMode {
    let in_index = matches!(is_plugin_in_krew_index(plugin_name, token), Some(true));
    if !in_index {
        return KrewMode::PrDirect;
    }
    // Plugin is in krew-index. Check whether the user has already wired
    // the bot in this repo's workflows.
    let workflow_hit = workdir.and_then(find_wired_bot_workflow);
    match workflow_hit {
        Some(hit) => KrewMode::BotTemplate {
            template_path: resolve_bot_template_path(workdir, plugin_name, hit.as_path()),
        },
        None => KrewMode::PrDirectWithHint,
    }
}

/// HTTP probe: does `kubernetes-sigs/krew-index/plugins/<name>.yaml` exist?
/// Returns:
///   - `Some(true)` → 200 OK, the plugin is published.
///   - `Some(false)` → 404 Not Found, the plugin is not yet published.
///   - `None` → network error, rate-limit, or unexpected status. Caller
///     treats this as "unknown" and falls back to `pr-direct`.
///
/// `token` is optional — anodizer's GitHub PATs are scoped enough that
/// passing one raises the rate limit from 60/hr (anon) to 5,000/hr
/// (authenticated), but an anonymous probe is sufficient for low-volume
/// release cadence (≤ 60 releases per hour from one IP is generous).
fn is_plugin_in_krew_index(plugin_name: &str, token: Option<&str>) -> Option<bool> {
    let url = format!(
        "https://api.github.com/repos/kubernetes-sigs/krew-index/contents/plugins/{}.yaml",
        plugin_name
    );
    let client = anodizer_core::http::blocking_client(std::time::Duration::from_secs(10)).ok()?;
    let mut req = client
        .get(&url)
        .header("Accept", "application/vnd.github+json");
    if let Some(tok) = token {
        req = req.bearer_auth(tok);
    }
    let resp = req.send().ok()?;
    let status = resp.status();
    if status.is_success() {
        return Some(true);
    }
    if status == reqwest::StatusCode::NOT_FOUND {
        return Some(false);
    }
    // 403 (rate limited / token denied), 5xx (GitHub flaking) — both go
    // back as `None` so the caller falls through to `pr-direct`.
    None
}

/// Scan `<workdir>/.github/workflows/*.yml` (and `*.yaml`) for the
/// `rajatjindal/krew-release-bot` Action reference. Returns the path
/// to the FIRST workflow file that hits, or `None` when nothing
/// matches (or the workflows dir doesn't exist).
///
/// Loud match string: `rajatjindal/krew-release-bot`. The Action's
/// canonical reference shape is `uses: rajatjindal/krew-release-bot@vX`,
/// so a substring search avoids brittleness against `@<ref>` and any
/// custom-fork rewrites.
fn find_wired_bot_workflow(workdir: &Path) -> Option<PathBuf> {
    let dir = workdir.join(".github").join("workflows");
    let entries = std::fs::read_dir(&dir).ok()?;
    for entry in entries.flatten() {
        let path = entry.path();
        let is_yaml = path
            .extension()
            .and_then(|e| e.to_str())
            .map(|e| matches!(e.to_ascii_lowercase().as_str(), "yml" | "yaml"))
            .unwrap_or(false);
        if !is_yaml {
            continue;
        }
        if let Ok(content) = std::fs::read_to_string(&path)
            && content.contains("rajatjindal/krew-release-bot")
        {
            return Some(path);
        }
    }
    None
}

/// Resolve where the bot expects to find its template file.
///
/// Precedence:
///   1. The workflow file `workflow_path` is parsed for a
///      `krew_template_file: <value>` line. When found, that path
///      (joined against `workdir`) wins — anodizer writes wherever the
///      user told the bot to read from.
///   2. Otherwise, fall back to the bot's documented default,
///      `<workdir>/.krew.yaml`. The feature spec also proposes
///      `.krew/<name>.yaml` for multi-plugin workspaces; when the
///      `.krew/` directory already exists we pick that per-plugin
///      shape so a workspace with several kubectl plugins keeps each
///      template separate. The user can override either default by
///      adding `krew_template_file:` to the workflow.
fn resolve_bot_template_path(
    workdir: Option<&Path>,
    plugin_name: &str,
    workflow_path: &Path,
) -> PathBuf {
    let workdir = workdir.unwrap_or_else(|| Path::new("."));
    if let Some(custom) = read_krew_template_file_input(workflow_path) {
        return workdir.join(custom);
    }
    let dot_krew_dir = workdir.join(".krew");
    if dot_krew_dir.is_dir() {
        return dot_krew_dir.join(format!("{}.yaml", plugin_name));
    }
    workdir.join(".krew.yaml")
}

/// Parse a YAML workflow file for the bot's `krew_template_file:` action
/// input. Returns the parsed value when present, else `None`.
///
/// Best-effort regex-free parse: walk the file looking for a line that
/// contains `krew_template_file:` and split on the first colon. This
/// avoids pulling in a YAML parser for a one-line lookup and tolerates
/// the value being quoted ("...", '...') or bare.
fn read_krew_template_file_input(workflow_path: &Path) -> Option<String> {
    let content = std::fs::read_to_string(workflow_path).ok()?;
    for raw_line in content.lines() {
        let line = raw_line.trim_start();
        if !line.starts_with("krew_template_file:") {
            continue;
        }
        let (_, rhs) = line.split_once(':')?;
        let v = rhs.trim();
        // Strip single or double quotes if present.
        let stripped = v
            .strip_prefix('"')
            .and_then(|s| s.strip_suffix('"'))
            .or_else(|| v.strip_prefix('\'').and_then(|s| s.strip_suffix('\'')))
            .unwrap_or(v);
        if stripped.is_empty() {
            return None;
        }
        return Some(stripped.to_string());
    }
    None
}

// ---------------------------------------------------------------------------
// Bot template generation
// ---------------------------------------------------------------------------

/// Swap the concrete release version out of every platform URL for the
/// bot's `{{ .TagName }}` placeholder so the resulting template is
/// version-independent. Commits made once and reused for every future
/// release without re-rendering.
///
/// Replaces both the `v<ver>` and bare `<ver>` forms — most release URLs
/// embed the tag as `v<ver>` in the release path (e.g.
/// `/releases/download/v1.2.3/...`) AND a bare `<ver>` in the artifact
/// filename (e.g. `tool-1.2.3-linux-amd64.tar.gz`). Both need to flip
/// to the bot's placeholder. Order matters: replace the longer form
/// first so `v1.2.3` doesn't collapse to `v{{ .TagName }}` mid-replace.
fn platforms_with_tag_placeholders(platforms: &[KrewPlatform], version: &str) -> Vec<KrewPlatform> {
    let placeholder = "{{ .TagName }}";
    let v_form = format!("v{}", version);
    platforms
        .iter()
        .map(|p| {
            let mut url = p.url.replace(&v_form, placeholder);
            if !version.is_empty() {
                url = url.replace(version, placeholder);
            }
            KrewPlatform {
                os: p.os.clone(),
                arch: p.arch.clone(),
                url,
                sha256: p.sha256.clone(),
                bin: p.bin.clone(),
            }
        })
        .collect()
}

/// Render a krew-release-bot template variant of the plugin manifest.
///
/// The bot consumes Go-template syntax with two custom funcs:
///   - `{{ .TagName }}` — replaced with the pushed git tag at bot run
///     time (e.g. `v1.2.3`). Used in the spec's `version` and inside
///     every URL passed to `addURIAndSha`.
///   - `{{ addURIAndSha "<URL with .TagName>" .TagName | indent N }}` —
///     downloads the URL at bot run time, computes the sha256, and
///     emits two indented YAML lines (`uri:` + `sha256:`) inline.
///
/// Per-platform we emit ONE `addURIAndSha` call (not a separate `uri:` +
/// `sha256:` pair), since the bot can compute the hash itself from the
/// release artifacts the publisher uploads via `stage-release`.
///
/// `url_template` MUST be a tag-aware template string (e.g.
/// `"https://github.com/{{ .repo_owner }}/{{ .crate_name }}/releases/download/{{ .TagName }}/...tar.gz"`)
/// — the caller substitutes runtime values for everything EXCEPT
/// `.TagName`, which the bot owns. The tag placeholder is what makes
/// the template version-independent: once committed, the same file
/// drives every future release without anodizer touching it again.
fn generate_bot_template(params: &KrewManifestParams<'_>) -> Result<String> {
    use std::fmt::Write as _;

    // Header + top-level metadata. We use literal strings rather than
    // serde_yaml_ng so that the embedded `{{ ... }}` placeholders
    // survive untouched (a YAML serializer would either quote the
    // braces, escape them, or treat them as plain text in ways that
    // break Go templating).
    let mut out = String::new();
    out.push_str("# This file was generated by anodizer for krew-release-bot. DO NOT EDIT.\n");
    out.push_str("apiVersion: krew.googlecontainertools.github.com/v1alpha2\n");
    out.push_str("kind: Plugin\n");
    out.push_str("metadata:\n");
    writeln!(out, "  name: {}", params.name)?;
    out.push_str("spec:\n");
    // `{{ .TagName }}` already starts with `v` for a typical
    // `v<semver>` tag. Don't prepend `v` here or the bot would emit
    // `vv1.0.0`. (anodizer's PR-direct path stamps `v{version}` because
    // it has the resolved version string in hand; the bot doesn't.)
    out.push_str("  version: \"{{ .TagName }}\"\n");
    if !params.homepage.is_empty() {
        writeln!(out, "  homepage: {}", params.homepage)?;
    }
    writeln!(out, "  shortDescription: {}", params.short_description)?;
    if !params.description.is_empty() {
        out.push_str("  description: |\n");
        for line in params.description.lines() {
            writeln!(out, "    {}", line)?;
        }
    }
    if !params.caveats.is_empty() {
        out.push_str("  caveats: |\n");
        for line in params.caveats.lines() {
            writeln!(out, "    {}", line)?;
        }
    }
    out.push_str("  platforms:\n");

    // Sort by uri descending to match `generate_manifest`'s ordering —
    // the bot has no opinion on order, so keeping it consistent with
    // the pr-direct path lets a side-by-side diff stay readable.
    let mut sorted: Vec<&KrewPlatform> = params.platforms.iter().collect();
    sorted.sort_by(|a, b| b.url.cmp(&a.url));

    for p in sorted {
        out.push_str("    - selector:\n");
        out.push_str("        matchLabels:\n");
        writeln!(out, "          os: {}", p.os)?;
        writeln!(out, "          arch: {}", krew_arch(&p.arch))?;
        // `addURIAndSha` MUST receive a URL whose `.TagName` placeholder
        // is still un-rendered — the bot expands it at PR time using
        // the actual pushed tag. The indent value (6) matches the
        // spec.platforms[].uri / sha256 indent the bot expects: two
        // spaces under `- selector:` plus four for the `uri:` line
        // emitted by the function.
        writeln!(
            out,
            "      {{{{addURIAndSha \"{}\" .TagName | indent 6}}}}",
            p.url
        )?;
        writeln!(out, "      bin: {}", p.bin)?;
    }
    Ok(out)
}

/// Convert `OsArtifact`s into `KrewPlatform`s.
///
/// When an artifact has arch "all", it is expanded into platform entries
/// for both amd64 and arm64.
///
/// `bin:` resolution per platform:
/// 1. Use the artifact's in-archive binary name when known
///    (`OsArtifact.binary`, populated from `extra_binaries[0]` for archives
///    or the `binary` metadata for uploadable binaries).
/// 2. Fall back to `default_binary_name` (the crate name) when the artifact
///    didn't carry a binary name.
/// 3. Append `.exe` for Windows targets when the resolved name doesn't
///    already end in `.exe`. Krew takes `bin:` literally — it does NOT
///    add `.exe` itself — so a Windows entry without the suffix fails to
///    install (krew validator: "source binary cannot be found in extracted
///    archive"). GoReleaser produces `.exe` naturally because its Go
///    builder appends it to `binary.Name`; anodizer's archive metadata
///    stores the suffix-less name, so we normalize here.
fn artifacts_to_platforms(
    artifacts: &[OsArtifact],
    default_binary_name: &str,
) -> Vec<KrewPlatform> {
    fn resolve_bin(a: &OsArtifact, default: &str, target_os: &str) -> String {
        let base = a.binary.clone().unwrap_or_else(|| default.to_string());
        if target_os == "windows" && !base.to_ascii_lowercase().ends_with(".exe") {
            format!("{}.exe", base)
        } else {
            base
        }
    }

    let mut platforms = Vec::new();
    for a in artifacts {
        let os = krew_os(&a.os).to_string();
        if a.arch == "all" {
            // Expand "all" into amd64 + arm64 entries
            for expanded_arch in &["amd64", "arm64"] {
                platforms.push(KrewPlatform {
                    os: os.clone(),
                    arch: expanded_arch.to_string(),
                    url: a.url.clone(),
                    sha256: a.sha256.clone(),
                    bin: resolve_bin(a, default_binary_name, &os),
                });
            }
        } else {
            platforms.push(KrewPlatform {
                arch: krew_arch(&a.arch).to_string(),
                url: a.url.clone(),
                sha256: a.sha256.clone(),
                bin: resolve_bin(a, default_binary_name, &os),
                os,
            });
        }
    }
    platforms
}

// ---------------------------------------------------------------------------
// publish_to_krew
// ---------------------------------------------------------------------------

pub fn publish_to_krew(ctx: &mut Context, crate_name: &str, log: &StageLogger) -> Result<bool> {
    let (_crate_cfg, publish) = crate::util::get_publish_config(ctx, crate_name, "krew")?;

    let krew_cfg = publish
        .krew
        .as_ref()
        .ok_or_else(|| anyhow::anyhow!("krew: no krew config for '{}'", crate_name))?;

    // Honor `skip` first (template-aware), then `skip_upload`. `skip` lets
    // projects that aren't kubectl plugins keep a krew block in shared
    // config and turn it off without removing the surrounding
    // repository/short_description boilerplate.
    if let Some(d) = krew_cfg.skip.as_ref() {
        let off = d
            .try_evaluates_to_true(|tmpl| ctx.render_template(tmpl))
            .with_context(|| format!("krew: render skip template for '{}'", crate_name))?;
        if off {
            log.status(&format!(
                "krew: skipping config for '{}' (skip=true)",
                crate_name
            ));
            return Ok(false);
        }
    }
    if util::should_skip_upload(krew_cfg.skip_upload.as_ref(), ctx, log) {
        log.status(&format!(
            "krew: skipping upload for '{}' (skip_upload={})",
            crate_name,
            krew_cfg
                .skip_upload
                .as_ref()
                .map(|v| v.as_str())
                .unwrap_or("")
        ));
        return Ok(false);
    }

    // Resolve repository owner/name from `repository:` (RepositoryConfig).
    // GoReleaser applies TemplateRef() to repository fields (krew.go:292-296).
    let (repo_owner_raw, repo_name_raw) =
        crate::util::resolve_repo_owner_name(krew_cfg.repository.as_ref())
            .ok_or_else(|| anyhow::anyhow!("krew: no repository config for '{}'", crate_name))?;
    let repo_owner = ctx
        .render_template(&repo_owner_raw)
        .unwrap_or(repo_owner_raw);
    let repo_name = ctx.render_template(&repo_name_raw).unwrap_or(repo_name_raw);

    if ctx.is_dry_run() {
        log.status(&format!(
            "(dry-run) would submit Krew plugin manifest for '{}' to {}/{}",
            crate_name, repo_owner, repo_name
        ));
        return Ok(false);
    }

    let version = ctx.version();

    // validate required fields before proceeding.
    // GoReleaser Pro parity: fall back to `metadata.description` when krew config unset.
    let effective_description: Option<&str> = krew_cfg
        .description
        .as_deref()
        .or_else(|| ctx.config.meta_description());
    if effective_description.is_none_or(str::is_empty) {
        anyhow::bail!("krew: manifest description is not set for '{}'", crate_name);
    }
    if krew_cfg
        .short_description
        .as_ref()
        .is_none_or(|s| s.is_empty())
    {
        anyhow::bail!(
            "krew: manifest short_description is not set for '{}'",
            crate_name
        );
    }

    let description_raw = krew_cfg
        .description
        .as_deref()
        .or_else(|| ctx.config.meta_description())
        .unwrap_or(crate_name);
    let description = ctx
        .render_template(description_raw)
        .unwrap_or_else(|_| description_raw.to_string());
    let short_description_raw = krew_cfg.short_description.as_deref().unwrap_or(crate_name);
    let short_description = ctx
        .render_template(short_description_raw)
        .unwrap_or_else(|_| short_description_raw.to_string());
    // Derive GitHub slug (owner/repo) for homepage fallback, consistent with homebrew.
    let github_slug = _crate_cfg
        .release
        .as_ref()
        .and_then(|r| r.github.as_ref())
        .map(|gh| format!("{}/{}", gh.owner, gh.name));
    let homepage_raw = krew_cfg.homepage.clone().unwrap_or_else(|| {
        github_slug
            .as_deref()
            .map(|slug| format!("https://github.com/{}", slug))
            .unwrap_or_else(|| format!("https://github.com/{}/{}", repo_owner, crate_name))
    });
    let homepage = ctx
        .render_template(&homepage_raw)
        .with_context(|| format!("krew: render homepage template for '{}'", crate_name))?;
    // GoReleaser krew.go:154-160 templates Caveats alongside the other
    // narrative fields; anodizer was passing it through verbatim.
    let caveats_raw = krew_cfg.caveats.clone().unwrap_or_default();
    let caveats = ctx
        .render_template(&caveats_raw)
        .with_context(|| format!("krew: render caveats template for '{}'", crate_name))?;

    // Find artifacts across all platforms, applying IDs + amd64_variant/arm_variant filter.
    let ids_filter = krew_cfg.ids.as_deref();
    let amd64_variant = krew_cfg.amd64_variant.as_deref().or(Some("v1"));
    let arm_variant = krew_cfg.arm_variant.as_deref();

    // Krew plugins only support a single
    // binary per archive. Check archive artifacts before building the manifest
    // so we fail fast with a clear error instead of shipping a broken plugin.
    for archive in ctx
        .artifacts
        .by_kind_and_crate(anodizer_core::artifact::ArtifactKind::Archive, crate_name)
    {
        if let Some(ids) = ids_filter
            && !ids.is_empty()
            && !archive
                .metadata
                .get("id")
                .map(|id| ids.iter().any(|i| i == id))
                .unwrap_or(false)
        {
            continue;
        }
        let binary_count = archive.extra_binaries().len();
        if binary_count != 1 {
            anyhow::bail!(
                "krew: only one binary per archive allowed, got {} on {:?}",
                binary_count,
                archive.name
            );
        }
    }

    let all_artifacts = util::find_all_platform_artifacts_with_variant(
        ctx,
        crate_name,
        ids_filter,
        amd64_variant,
        arm_variant,
    );

    let url_template = krew_cfg.url_template.as_deref();

    if all_artifacts.is_empty() {
        // GR krew.go:115-117 returns ErrNoArchivesFound — a krew manifest
        // with no real artifacts is unusable (the placeholder URL was a
        // fabricated guess that produced 404s on install). Fail loudly.
        anyhow::bail!(
            "krew: no archive artifacts found for '{}'. The krew publisher \
             needs at least one platform archive to construct the manifest. \
             Either add Windows/Linux/macOS targets for this crate or remove \
             the krew publisher config.",
            crate_name
        );
    }
    // The Krew schema requires `spec.platforms[].sha256` to be a non-empty
    // hex digest — krew's `addURIAndSha` validator rejects manifests with
    // empty hashes ("Hash validation failed"). Empty sha256 metadata
    // would silently produce an unusable plugin manifest.
    if let Some(empty) = all_artifacts.iter().find(|a| a.sha256.is_empty()) {
        anyhow::bail!(
            "krew: artifact for crate '{}' at url '{}' (os={}, arch={}) is \
             missing required sha256 metadata. The generated krew plugin \
             manifest would embed an empty `sha256:` field, which krew \
             rejects at install time. Check dist/artifacts.json for the \
             archive entry's metadata.sha256, and re-run `task release` from \
             a clean dist/ if the field is absent or empty.",
            crate_name,
            empty.url,
            empty.os,
            empty.arch,
        );
    }
    let platforms = {
        let mut plats = artifacts_to_platforms(&all_artifacts, crate_name);
        if let Some(tmpl) = url_template {
            for p in &mut plats {
                p.url = util::render_url_template_with_ctx(
                    ctx, tmpl, crate_name, &version, &p.arch, &p.os,
                );
            }
        }
        plats
    };

    let manifest = generate_manifest(&KrewManifestParams {
        name: crate_name,
        version: &version,
        homepage: &homepage,
        short_description: &short_description,
        description: &description,
        caveats: &caveats,
        platforms: &platforms,
    })?;

    // Use name override if set; render through template engine.
    let plugin_name_raw = krew_cfg.name.as_deref().unwrap_or(crate_name);
    let plugin_name_rendered = ctx
        .render_template(plugin_name_raw)
        .unwrap_or_else(|_| plugin_name_raw.to_string());
    let plugin_name = plugin_name_rendered.as_str();

    // Clone the krew-index fork, write the plugin manifest, commit, push.
    let token =
        util::resolve_repo_token(ctx, krew_cfg.repository.as_ref(), Some("KREW_INDEX_TOKEN"));

    // ── krew-release-bot auto-detection ──────────────────────────────
    // Once a plugin lands in `kubernetes-sigs/krew-index`, the krew
    // maintainers recommend switching from the PR-direct flow to the
    // krew-release-bot Action. Detect which mode applies and branch.
    // Detection failures fall back to the safe `PrDirect` mode so a
    // network blip or permission hiccup never blocks the release.
    let mode = detect_krew_mode(
        plugin_name,
        ctx.options.project_root.as_deref(),
        token.as_deref(),
    );
    if let KrewMode::BotTemplate { template_path } = &mode {
        // Bot-template mode: write a `{{ .TagName }}`-templated manifest
        // to the path the user's workflow reads from, then return.
        // The bot owns the krew-index PR — anodizer must NOT clone or
        // PR against `kubernetes-sigs/krew-index` from this code path
        // or two PRs would race to land the same version.
        let bot_platforms = platforms_with_tag_placeholders(&platforms, &version);
        let bot_template = generate_bot_template(&KrewManifestParams {
            name: plugin_name,
            version: &version, // ignored by the renderer; placeholder rules
            homepage: &homepage,
            short_description: &short_description,
            description: &description,
            caveats: &caveats,
            platforms: &bot_platforms,
        })?;
        if let Some(parent) = template_path.parent() {
            std::fs::create_dir_all(parent).with_context(|| {
                format!("krew: create bot-template parent dir {}", parent.display())
            })?;
        }
        std::fs::write(template_path, &bot_template)
            .with_context(|| format!("krew: write bot template to {}", template_path.display()))?;
        log.status(&format!(
            "krew: mode=bot-template plugin={} template={} \
             (krew-release-bot will open the krew-index PR on tag push)",
            plugin_name,
            template_path.display()
        ));
        return Ok(false);
    }
    if matches!(mode, KrewMode::PrDirectWithHint) {
        log.status(&format!(
            "krew: mode=pr-direct-with-hint plugin={} — published in krew-index; \
             consider wiring `rajatjindal/krew-release-bot` so future releases \
             auto-merge without a manual PR \
             (https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/)",
            plugin_name
        ));
    } else {
        log.status(&format!("krew: mode=pr-direct plugin={}", plugin_name));
    }

    let tmp_dir = tempfile::tempdir().context("krew: create temp dir")?;
    let repo_path = tmp_dir.path();

    util::clone_repo(
        krew_cfg.repository.as_ref(),
        &repo_owner,
        &repo_name,
        token.as_deref(),
        repo_path,
        "krew",
        log,
    )?;

    // Write plugin manifest under plugins/<name>.yaml.
    let plugins_dir = repo_path.join("plugins");
    std::fs::create_dir_all(&plugins_dir)
        .with_context(|| format!("krew: create plugins dir {}", plugins_dir.display()))?;

    let manifest_file = plugins_dir.join(format!("{}.yaml", plugin_name));
    std::fs::write(&manifest_file, &manifest)
        .with_context(|| format!("krew: write manifest {}", manifest_file.display()))?;

    log.status(&format!(
        "wrote Krew plugin manifest: {}",
        manifest_file.display()
    ));

    let commit_msg = crate::homebrew::render_commit_msg(
        krew_cfg.commit_msg_template.as_deref(),
        plugin_name,
        &version,
        "plugin",
    );
    let branch_name = format!("{}-v{}", plugin_name, version);
    let commit_opts = util::resolve_commit_opts(ctx, krew_cfg.commit_author.as_ref());
    // Always create a versioned branch for Krew PRs.
    let branch = Some(branch_name.as_str());
    let push_outcome = util::commit_and_push_with_opts(
        repo_path,
        &["."],
        &commit_msg,
        branch,
        "krew",
        &commit_opts,
    )?;
    let pushed = match push_outcome {
        util::CommitOutcome::Pushed => {
            log.status(&format!(
                "Krew manifest pushed to {}/{} branch '{}'",
                repo_owner, repo_name, branch_name
            ));
            true
        }
        util::CommitOutcome::NoChanges => {
            log.status(&format!(
                "krew: nothing to push, manifest for '{}' already up to date",
                plugin_name
            ));
            false
        }
    };

    // Submit a PR. When `repository.pull_request` is configured, use the
    // unified PR helper (which respects `base`, `draft`, `body`); otherwise
    // submit a PR via `gh` CLI against the canonical kubernetes-sigs/krew-index
    // (or `repository.pull_request.base` when set).
    let has_pr_config = krew_cfg
        .repository
        .as_ref()
        .and_then(|r| r.pull_request.as_ref())
        .and_then(|pr| pr.enabled)
        .unwrap_or(false);

    let update_existing_pr = krew_cfg
        .update_existing_pr
        .as_ref()
        .map(|v| {
            v.try_evaluates_to_true(|tmpl| ctx.render_template(tmpl))
                .unwrap_or(false)
        })
        .unwrap_or(false);

    // Clone the repository config so the PR submission helpers no
    // longer borrow from `ctx.config` (via `krew_cfg`). NLL then
    // drops the immutable borrow, making the subsequent `&mut ctx`
    // call legal.
    let repo_for_pr = krew_cfg.repository.clone();

    let pr_outcome = if has_pr_config {
        util::maybe_submit_pr(
            repo_path,
            repo_for_pr.as_ref(),
            &util::PrOrigin {
                repo_owner: &repo_owner,
                repo_name: &repo_name,
                branch_name: &branch_name,
                update_existing_pr,
            },
            &format!("Add/update {} plugin to v{}", crate_name, version),
            &format!(
                "## Plugin\n- **Name**: {}\n- **Version**: v{}\n\nAutomatically submitted by anodizer.",
                crate_name, version
            ),
            "krew",
            log,
        )
    } else {
        // No `repository.pull_request:` block — always submit a PR against the
        // canonical kubernetes-sigs/krew-index slug (or the override in
        // `repository.pull_request.base`). Submitting against the user's own
        // fork would silently create useless intra-fork PRs against the user's
        // empty `main` branch instead of against the real upstream.
        let upstream_slug = repo_for_pr
            .as_ref()
            .and_then(|r| r.pull_request.as_ref())
            .and_then(|pr| pr.base.as_ref())
            .and_then(|base| match (base.owner.as_deref(), base.name.as_deref()) {
                (Some(o), Some(n)) => Some(format!("{}/{}", o, n)),
                _ => None,
            })
            .unwrap_or_else(|| "kubernetes-sigs/krew-index".to_string());

        util::submit_pr_via_gh_with_opts(
            repo_path,
            &upstream_slug,
            &format!("{}:{}", repo_owner, branch_name),
            &format!("Add/update {} plugin to v{}", crate_name, version),
            &format!(
                "## Plugin\n- **Name**: {}\n- **Version**: v{}\n\nAutomatically submitted by anodizer.",
                crate_name, version
            ),
            "krew",
            log,
            util::SubmitPrOpts { update_existing_pr },
        )
    };

    // Surface PR-already-exists skips to the dispatch summary table.
    if let Some(outcome) = pr_outcome {
        ctx.record_publisher_outcome(outcome);
    }

    Ok(pushed)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
#[allow(clippy::field_reassign_with_default)]
mod tests {
    use super::*;

    // -----------------------------------------------------------------------
    // krew-release-bot auto-detection tests
    // -----------------------------------------------------------------------

    /// No workflows dir → `find_wired_bot_workflow` returns None.
    #[test]
    fn find_wired_bot_workflow_returns_none_when_no_workflows_dir() {
        let tmp = tempfile::tempdir().unwrap();
        assert!(find_wired_bot_workflow(tmp.path()).is_none());
    }

    /// Workflows dir exists but no file references the bot → None.
    #[test]
    fn find_wired_bot_workflow_returns_none_when_bot_not_referenced() {
        let tmp = tempfile::tempdir().unwrap();
        let wf = tmp.path().join(".github").join("workflows");
        std::fs::create_dir_all(&wf).unwrap();
        std::fs::write(
            wf.join("release.yml"),
            "name: Release\njobs:\n  build:\n    runs-on: ubuntu-latest\n",
        )
        .unwrap();
        assert!(find_wired_bot_workflow(tmp.path()).is_none());
    }

    /// Any workflow referencing `rajatjindal/krew-release-bot` → that path.
    #[test]
    fn find_wired_bot_workflow_matches_bot_reference() {
        let tmp = tempfile::tempdir().unwrap();
        let wf = tmp.path().join(".github").join("workflows");
        std::fs::create_dir_all(&wf).unwrap();
        let target = wf.join("krew.yaml");
        std::fs::write(
            &target,
            "name: Update krew-index\non:\n  push:\n    tags: ['v*']\njobs:\n  update:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: rajatjindal/krew-release-bot@v0.0.46\n",
        )
        .unwrap();
        let hit = find_wired_bot_workflow(tmp.path()).unwrap();
        assert_eq!(hit, target);
    }

    /// Bot reference matches regardless of `.yml` vs `.yaml` extension.
    #[test]
    fn find_wired_bot_workflow_matches_yml_extension_too() {
        let tmp = tempfile::tempdir().unwrap();
        let wf = tmp.path().join(".github").join("workflows");
        std::fs::create_dir_all(&wf).unwrap();
        let target = wf.join("release.yml");
        std::fs::write(
            &target,
            "jobs:\n  x:\n    uses: rajatjindal/krew-release-bot@v0.0.46\n",
        )
        .unwrap();
        let hit = find_wired_bot_workflow(tmp.path()).unwrap();
        assert_eq!(hit, target);
    }

    /// `krew_template_file:` action input is parsed when present so we
    /// write the template to the path the user's workflow reads from.
    #[test]
    fn read_krew_template_file_input_extracts_custom_path() {
        let tmp = tempfile::tempdir().unwrap();
        let wf = tmp.path().join("krew.yaml");
        std::fs::write(
            &wf,
            "      - uses: rajatjindal/krew-release-bot@v0.0.46\n        with:\n          krew_template_file: .krew/my-plugin.yaml\n",
        )
        .unwrap();
        assert_eq!(
            read_krew_template_file_input(&wf),
            Some(".krew/my-plugin.yaml".to_string())
        );
    }

    /// Quoted values (single + double) are unwrapped.
    #[test]
    fn read_krew_template_file_input_strips_quotes() {
        let tmp = tempfile::tempdir().unwrap();
        let wf = tmp.path().join("krew.yaml");
        std::fs::write(&wf, "          krew_template_file: \".krew.yaml\"\n").unwrap();
        assert_eq!(
            read_krew_template_file_input(&wf),
            Some(".krew.yaml".to_string())
        );

        std::fs::write(&wf, "          krew_template_file: '.krew/x.yaml'\n").unwrap();
        assert_eq!(
            read_krew_template_file_input(&wf),
            Some(".krew/x.yaml".to_string())
        );
    }

    /// Missing input line → None (caller falls back to defaults).
    #[test]
    fn read_krew_template_file_input_returns_none_when_absent() {
        let tmp = tempfile::tempdir().unwrap();
        let wf = tmp.path().join("krew.yaml");
        std::fs::write(&wf, "      - uses: rajatjindal/krew-release-bot@v0.0.46\n").unwrap();
        assert_eq!(read_krew_template_file_input(&wf), None);
    }

    /// Path resolution: custom input wins over both defaults.
    #[test]
    fn resolve_bot_template_path_honors_custom_input() {
        let tmp = tempfile::tempdir().unwrap();
        let wf = tmp.path().join("krew.yaml");
        std::fs::write(&wf, "          krew_template_file: my-template.yaml\n").unwrap();
        assert_eq!(
            resolve_bot_template_path(Some(tmp.path()), "anodizer", &wf),
            tmp.path().join("my-template.yaml")
        );
    }

    /// Path resolution: `.krew/` exists → `.krew/<name>.yaml`.
    #[test]
    fn resolve_bot_template_path_prefers_dot_krew_directory_when_present() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(tmp.path().join(".krew")).unwrap();
        let wf = tmp.path().join("krew.yaml");
        std::fs::write(&wf, "# no template-file input\n").unwrap();
        assert_eq!(
            resolve_bot_template_path(Some(tmp.path()), "anodizer", &wf),
            tmp.path().join(".krew").join("anodizer.yaml")
        );
    }

    /// Path resolution: no custom input + no `.krew/` → `.krew.yaml`.
    #[test]
    fn resolve_bot_template_path_falls_back_to_dot_krew_yaml() {
        let tmp = tempfile::tempdir().unwrap();
        let wf = tmp.path().join("krew.yaml");
        std::fs::write(&wf, "# no template-file input\n").unwrap();
        assert_eq!(
            resolve_bot_template_path(Some(tmp.path()), "anodizer", &wf),
            tmp.path().join(".krew.yaml")
        );
    }

    /// Bot template uses `{{ .TagName }}` (not the concrete version) so
    /// the file is version-independent — committed once, drives every
    /// release. `addURIAndSha` wraps every per-platform URL.
    #[test]
    fn generate_bot_template_emits_tag_placeholders_and_addurianadsha() {
        let template = generate_bot_template(&KrewManifestParams {
            name: "anodizer",
            version: "1.2.3", // ignored — placeholder rules
            homepage: "https://github.com/owner/anodizer",
            short_description: "Release tool",
            description: "Multi-line\ndescription.",
            caveats: "",
            platforms: &[KrewPlatform {
                os: "linux".to_string(),
                arch: "amd64".to_string(),
                url: "https://github.com/owner/anodizer/releases/download/{{ .TagName }}/anodizer-{{ .TagName }}-linux-amd64.tar.gz".to_string(),
                sha256: "ignored-in-template".to_string(),
                bin: "kubectl-anodizer".to_string(),
            }],
        })
        .unwrap();

        assert!(
            template.starts_with(
                "# This file was generated by anodizer for krew-release-bot. DO NOT EDIT.\n"
            ),
            "bot template missing header: {template}"
        );
        // Version uses `.TagName`, NOT the concrete `1.2.3`.
        assert!(
            template.contains("version: \"{{ .TagName }}\""),
            "got: {template}"
        );
        assert!(
            !template.contains("v1.2.3"),
            "concrete version leaked: {template}"
        );
        // Each platform has an `addURIAndSha` call (not a literal uri+sha256 pair).
        assert!(
            template.contains("{{addURIAndSha \"https://github.com/owner/anodizer/releases/download/{{ .TagName }}/anodizer-{{ .TagName }}-linux-amd64.tar.gz\" .TagName | indent 6}}"),
            "addURIAndSha invocation missing: {template}"
        );
        assert!(
            !template.contains("sha256: ignored-in-template"),
            "literal sha256 must be replaced: {template}"
        );
        // Description block scalar preserved.
        assert!(template.contains("description: |"), "got: {template}");
        assert!(template.contains("    Multi-line"), "got: {template}");
    }

    /// `platforms_with_tag_placeholders` swaps both `v<ver>` and bare
    /// `<ver>` forms so the template is fully tag-independent.
    #[test]
    fn platforms_with_tag_placeholders_replaces_both_version_forms() {
        let inputs = vec![KrewPlatform {
            os: "linux".to_string(),
            arch: "amd64".to_string(),
            url: "https://example.com/v1.2.3/tool-1.2.3-linux-amd64.tar.gz".to_string(),
            sha256: "deadbeef".to_string(),
            bin: "kubectl-tool".to_string(),
        }];
        let out = platforms_with_tag_placeholders(&inputs, "1.2.3");
        assert_eq!(
            out[0].url,
            "https://example.com/{{ .TagName }}/tool-{{ .TagName }}-linux-amd64.tar.gz"
        );
    }

    // -----------------------------------------------------------------------
    // generate_manifest tests
    // -----------------------------------------------------------------------

    #[test]
    fn test_generate_manifest_basic() {
        let manifest = generate_manifest(&KrewManifestParams {
            name: "kubectl-mytool",
            version: "1.0.0",
            homepage: "https://github.com/org/mytool",
            short_description: "A kubectl plugin",
            description: "A great kubectl plugin for managing things.",
            caveats: "",
            platforms: &[
                KrewPlatform {
                    os: "linux".to_string(),
                    arch: "amd64".to_string(),
                    url: "https://example.com/mytool-linux-amd64.tar.gz".to_string(),
                    sha256: "deadbeef".to_string(),
                    bin: "kubectl-mytool".to_string(),
                },
                KrewPlatform {
                    os: "darwin".to_string(),
                    arch: "amd64".to_string(),
                    url: "https://example.com/mytool-darwin-amd64.tar.gz".to_string(),
                    sha256: "cafebabe".to_string(),
                    bin: "kubectl-mytool".to_string(),
                },
            ],
        })
        .unwrap();

        // Header comment is present.
        assert!(manifest.starts_with("# This file was generated by anodizer. DO NOT EDIT.\n"));
        assert!(manifest.contains("apiVersion: krew.googlecontainertools.github.com/v1alpha2"));
        assert!(manifest.contains("kind: Plugin"));
        assert!(manifest.contains("  name: kubectl-mytool"));
        assert!(manifest.contains("version: v1.0.0"));
        assert!(manifest.contains("homepage: https://github.com/org/mytool"));
        assert!(manifest.contains("shortDescription: A kubectl plugin"));
        assert!(manifest.contains("A great kubectl plugin for managing things."));
        assert!(!manifest.contains("caveats:"));
        assert!(manifest.contains("platforms:"));
        assert!(manifest.contains("os: linux"));
        assert!(manifest.contains("arch: amd64"));
        assert!(manifest.contains("uri: https://example.com/mytool-linux-amd64.tar.gz"));
        assert!(manifest.contains("sha256: deadbeef"));
        assert!(manifest.contains("bin: kubectl-mytool"));
        assert!(manifest.contains("os: darwin"));
        assert!(manifest.contains("uri: https://example.com/mytool-darwin-amd64.tar.gz"));
        assert!(manifest.contains("sha256: cafebabe"));
    }

    #[test]
    fn test_generate_manifest_with_caveats() {
        let manifest = generate_manifest(&KrewManifestParams {
            name: "my-plugin",
            version: "2.0.0",
            homepage: "https://example.com",
            short_description: "Plugin",
            description: "A plugin",
            caveats: "Run 'kubectl my-plugin init' after installation.",
            platforms: &[KrewPlatform {
                os: "linux".to_string(),
                arch: "amd64".to_string(),
                url: "https://example.com/plugin.tar.gz".to_string(),
                sha256: "hash".to_string(),
                bin: "kubectl-my-plugin".to_string(),
            }],
        })
        .unwrap();

        assert!(manifest.contains("caveats:"));
        assert!(manifest.contains("Run 'kubectl my-plugin init' after installation."));
    }

    #[test]
    fn test_generate_manifest_no_homepage() {
        let manifest = generate_manifest(&KrewManifestParams {
            name: "tool",
            version: "1.0.0",
            homepage: "",
            short_description: "A tool",
            description: "desc",
            caveats: "",
            platforms: &[KrewPlatform {
                os: "linux".to_string(),
                arch: "amd64".to_string(),
                url: "https://example.com/tool.tar.gz".to_string(),
                sha256: "hash".to_string(),
                bin: "kubectl-tool".to_string(),
            }],
        })
        .unwrap();

        assert!(!manifest.contains("homepage:"));
    }

    #[test]
    fn test_generate_manifest_multi_platform() {
        let manifest = generate_manifest(&KrewManifestParams {
            name: "multi",
            version: "1.0.0",
            homepage: "https://example.com",
            short_description: "Multi-platform plugin",
            description: "A plugin for all platforms.",
            caveats: "",
            platforms: &[
                KrewPlatform {
                    os: "linux".to_string(),
                    arch: "amd64".to_string(),
                    url: "https://example.com/multi-linux-amd64.tar.gz".to_string(),
                    sha256: "hash_linux_amd64".to_string(),
                    bin: "kubectl-multi".to_string(),
                },
                KrewPlatform {
                    os: "linux".to_string(),
                    arch: "arm64".to_string(),
                    url: "https://example.com/multi-linux-arm64.tar.gz".to_string(),
                    sha256: "hash_linux_arm64".to_string(),
                    bin: "kubectl-multi".to_string(),
                },
                KrewPlatform {
                    os: "darwin".to_string(),
                    arch: "amd64".to_string(),
                    url: "https://example.com/multi-darwin-amd64.tar.gz".to_string(),
                    sha256: "hash_darwin_amd64".to_string(),
                    bin: "kubectl-multi".to_string(),
                },
                KrewPlatform {
                    os: "darwin".to_string(),
                    arch: "arm64".to_string(),
                    url: "https://example.com/multi-darwin-arm64.tar.gz".to_string(),
                    sha256: "hash_darwin_arm64".to_string(),
                    bin: "kubectl-multi".to_string(),
                },
                KrewPlatform {
                    os: "windows".to_string(),
                    arch: "amd64".to_string(),
                    url: "https://example.com/multi-windows-amd64.zip".to_string(),
                    sha256: "hash_windows_amd64".to_string(),
                    bin: "kubectl-multi".to_string(),
                },
            ],
        })
        .unwrap();

        // Count platform entries (each starts with "- selector:")
        let platform_count = manifest.matches("- selector:").count();
        assert_eq!(platform_count, 5);

        // Verify all platforms present
        assert!(manifest.contains("hash_linux_amd64"));
        assert!(manifest.contains("hash_linux_arm64"));
        assert!(manifest.contains("hash_darwin_amd64"));
        assert!(manifest.contains("hash_darwin_arm64"));
        assert!(manifest.contains("hash_windows_amd64"));
    }

    #[test]
    fn test_generate_manifest_complete_structure() {
        let manifest = generate_manifest(&KrewManifestParams {
            name: "kubectl-anodizer",
            version: "3.2.1",
            homepage: "https://github.com/tj-smith47/anodizer",
            short_description: "Release automation as a kubectl plugin",
            description: "A comprehensive release automation tool\nfor Kubernetes-based projects.",
            caveats: "Ensure kubectl is configured before use.",
            platforms: &[KrewPlatform {
                os: "linux".to_string(),
                arch: "amd64".to_string(),
                url: "https://github.com/tj-smith47/anodizer/releases/download/v3.2.1/anodizer-3.2.1-linux-amd64.tar.gz".to_string(),
                sha256: "aabbccdd".to_string(),
                bin: "kubectl-anodizer".to_string(),
            }],
        }).unwrap();

        // Starts with header comment
        assert!(manifest.starts_with("# This file was generated by anodizer. DO NOT EDIT.\n"));

        // Verify structure order (line 0 is the header comment)
        let lines: Vec<&str> = manifest.lines().collect();
        assert_eq!(
            lines[0],
            "# This file was generated by anodizer. DO NOT EDIT."
        );
        assert_eq!(
            lines[1],
            "apiVersion: krew.googlecontainertools.github.com/v1alpha2"
        );
        assert_eq!(lines[2], "kind: Plugin");
        assert_eq!(lines[3], "metadata:");
        assert_eq!(lines[4], "  name: kubectl-anodizer");
        assert_eq!(lines[5], "spec:");
        assert!(lines[6].contains("version: v3.2.1"));

        // Multi-line description
        assert!(manifest.contains("A comprehensive release automation tool"));
        assert!(manifest.contains("for Kubernetes-based projects."));

        // Caveats
        assert!(manifest.contains("Ensure kubectl is configured before use."));
    }

    // -----------------------------------------------------------------------
    // krew_arch / krew_os helper tests
    // -----------------------------------------------------------------------

    #[test]
    fn test_krew_arch_mapping() {
        assert_eq!(krew_arch("amd64"), "amd64");
        assert_eq!(krew_arch("x86_64"), "amd64");
        assert_eq!(krew_arch("arm64"), "arm64");
        assert_eq!(krew_arch("aarch64"), "arm64");
        assert_eq!(krew_arch("unknown"), "unknown");
    }

    #[test]
    fn test_krew_os_mapping() {
        assert_eq!(krew_os("darwin"), "darwin");
        assert_eq!(krew_os("macos"), "darwin");
        assert_eq!(krew_os("linux"), "linux");
        assert_eq!(krew_os("windows"), "windows");
        assert_eq!(krew_os("freebsd"), "freebsd");
    }

    // -----------------------------------------------------------------------
    // publish_to_krew dry-run tests
    // -----------------------------------------------------------------------

    #[test]
    fn test_publish_to_krew_missing_config() {
        use anodizer_core::config::{Config, CrateConfig, PublishConfig};
        use anodizer_core::context::{Context, ContextOptions};
        use anodizer_core::log::{StageLogger, Verbosity};

        let mut config = Config::default();
        config.crates = vec![CrateConfig {
            name: "mytool".to_string(),
            path: ".".to_string(),
            tag_template: "v{{ .Version }}".to_string(),
            publish: Some(PublishConfig::default()),
            ..Default::default()
        }];

        let mut ctx = Context::new(
            config,
            ContextOptions {
                dry_run: true,
                ..Default::default()
            },
        );
        let log = StageLogger::new("publish", Verbosity::Normal);

        assert!(publish_to_krew(&mut ctx, "mytool", &log).is_err());
    }

    #[test]
    fn test_publish_to_krew_missing_manifests_repo() {
        use anodizer_core::config::{Config, CrateConfig, KrewConfig, PublishConfig};
        use anodizer_core::context::{Context, ContextOptions};
        use anodizer_core::log::{StageLogger, Verbosity};

        let mut config = Config::default();
        config.crates = vec![CrateConfig {
            name: "mytool".to_string(),
            path: ".".to_string(),
            tag_template: "v{{ .Version }}".to_string(),
            publish: Some(PublishConfig {
                krew: Some(KrewConfig {
                    repository: None, // Missing
                    ..Default::default()
                }),
                ..Default::default()
            }),
            ..Default::default()
        }];

        let mut ctx = Context::new(
            config,
            ContextOptions {
                dry_run: true,
                ..Default::default()
            },
        );
        let log = StageLogger::new("publish", Verbosity::Normal);

        assert!(publish_to_krew(&mut ctx, "mytool", &log).is_err());
    }

    // -----------------------------------------------------------------------
    // artifacts_to_platforms .exe / binary-name-resolution tests
    // -----------------------------------------------------------------------

    fn make_os_artifact(os: &str, arch: &str, binary: Option<&str>) -> OsArtifact {
        OsArtifact {
            url: format!("https://example.com/{}-{}.tar.gz", os, arch),
            sha256: "deadbeef".into(),
            os: os.into(),
            arch: arch.into(),
            id: None,
            amd64_variant: None,
            arm_variant: None,
            binary: binary.map(|s| s.to_string()),
        }
    }

    #[test]
    fn test_artifacts_to_platforms_appends_exe_for_windows() {
        let arts = vec![
            make_os_artifact("linux", "amd64", Some("cfgd")),
            make_os_artifact("windows", "amd64", Some("cfgd")),
            make_os_artifact("darwin", "arm64", Some("cfgd")),
        ];
        let plats = artifacts_to_platforms(&arts, "cfgd");
        let by_os = |os: &str| plats.iter().find(|p| p.os == os).expect("missing platform");
        assert_eq!(by_os("linux").bin, "cfgd");
        assert_eq!(by_os("windows").bin, "cfgd.exe");
        assert_eq!(by_os("darwin").bin, "cfgd");
    }

    #[test]
    fn test_artifacts_to_platforms_does_not_double_suffix_exe() {
        let arts = vec![make_os_artifact("windows", "amd64", Some("cfgd.exe"))];
        let plats = artifacts_to_platforms(&arts, "cfgd");
        assert_eq!(plats[0].bin, "cfgd.exe");
    }

    #[test]
    fn test_artifacts_to_platforms_uses_archive_binary_name_over_default() {
        // Crate is `kubectl-cfgd` but ships binary `cfgd` — the manifest
        // must point at the in-archive name, not the crate name.
        let arts = vec![make_os_artifact("linux", "amd64", Some("cfgd"))];
        let plats = artifacts_to_platforms(&arts, "kubectl-cfgd");
        assert_eq!(plats[0].bin, "cfgd");
    }

    #[test]
    fn test_artifacts_to_platforms_falls_back_to_default_when_binary_unset() {
        let arts = vec![make_os_artifact("linux", "amd64", None)];
        let plats = artifacts_to_platforms(&arts, "cfgd");
        assert_eq!(plats[0].bin, "cfgd");
    }

    #[test]
    fn test_artifacts_to_platforms_arch_all_expands_with_correct_bin() {
        // arch=all should expand to amd64+arm64 with the same bin name on
        // both. Not a Windows test (krew doesn't use arch=all on windows
        // in practice) — just confirms the expansion path also flows
        // through resolve_bin.
        let arts = vec![make_os_artifact("darwin", "all", Some("cfgd"))];
        let plats = artifacts_to_platforms(&arts, "cfgd");
        assert_eq!(plats.len(), 2);
        assert!(plats.iter().all(|p| p.bin == "cfgd"));
        let arches: Vec<_> = plats.iter().map(|p| p.arch.as_str()).collect();
        assert!(arches.contains(&"amd64"));
        assert!(arches.contains(&"arm64"));
    }

    /// Regression for GoReleaser parity P9.1 (commit cba5b9f):
    /// `krew.skip_upload: "{{ .IsSnapshot }}"` must template-expand
    /// before its bool/auto/empty interpretation. On a snapshot run
    /// the rendered value is `"true"` and the publish path must
    /// short-circuit to `Ok(())` BEFORE the missing-repository check.
    #[test]
    fn krew_skip_upload_template_expands_to_true_on_snapshot() {
        use anodizer_core::config::{Config, CrateConfig, KrewConfig, PublishConfig, StringOrBool};
        use anodizer_core::context::{Context, ContextOptions};
        use anodizer_core::log::{StageLogger, Verbosity};

        let mut config = Config::default();
        config.project_name = "mytool".to_string();
        config.crates = vec![CrateConfig {
            name: "mytool".to_string(),
            path: ".".to_string(),
            tag_template: "v{{ .Version }}".to_string(),
            publish: Some(PublishConfig {
                krew: Some(KrewConfig {
                    // repository intentionally None — would normally
                    // hard-fail with "no repository config", but the
                    // skip_upload short-circuit must run BEFORE the
                    // repository-missing check.
                    repository: None,
                    skip_upload: Some(StringOrBool::String("{{ .IsSnapshot }}".to_string())),
                    ..Default::default()
                }),
                ..Default::default()
            }),
            ..Default::default()
        }];

        let mut ctx = Context::new(
            config,
            ContextOptions {
                snapshot: true,
                ..Default::default()
            },
        );
        ctx.template_vars_mut().set("IsSnapshot", "true");

        let log = StageLogger::new("publish", Verbosity::Normal);
        publish_to_krew(&mut ctx, "mytool", &log).expect(
            "skip_upload='{{ .IsSnapshot }}' on snapshot must short-circuit \
             to Ok(()) before the repository-missing check (GR cba5b9f)",
        );
    }
}

// ---------------------------------------------------------------------------
// KrewPublisher — Publisher trait wrapper (close-PR rollback)
// ---------------------------------------------------------------------------

/// Krew plugin-index publisher. Each successful per-crate publish opens a
/// PR against an upstream `krew-index`-style repo from a fork. The rollback
/// path closes those PRs via `PATCH /repos/<upstream>/pulls/<n>` with
/// `state=closed`.
///
/// PR-number discovery uses the **query-at-rollback-time** approach: at
/// publish time we only record the upstream coordinates, the fork owner,
/// and the branch name the publish path pushed to. At rollback time we
/// list open PRs filtered by `head=<fork_owner>:<branch>` and close each
/// match. This sidesteps modifying the unchanged `publish_to_krew` body
/// to surface the new PR number, and stays robust against a stale
/// evidence file stitched in from an older run.
///
/// CREDENTIAL HANDLING: [`KrewPrTarget`] stores `token_env_var` — the
/// NAME of the env var to consult at rollback time — not the resolved
/// token VALUE. Same rule applies to every PR-based publisher that
/// touches GitHub auth.
use serde::Deserialize;

simple_publisher!(
    KrewPublisher,
    "krew",
    anodizer_core::PublisherGroup::Manager,
    false,
    Some("GITHUB_TOKEN pull_request:write"),
);

/// Serialized shape of a recorded krew PR target. One entry per crate
/// whose publish path successfully pushed a branch to its fork. See
/// the module-level rustdoc for the query-at-rollback-time rationale.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
struct KrewPrTarget {
    /// Per-target label — the crate the manifest was generated for.
    /// Surfaces in log lines.
    target: String,
    /// Upstream owner — typically `kubernetes-sigs` (or whatever
    /// `repository.pull_request.base.owner` overrides to).
    upstream_owner: String,
    /// Upstream repo — typically `krew-index`.
    upstream_repo: String,
    /// Fork owner — the user/org the publish path pushed the branch to.
    fork_owner: String,
    /// Branch name on the fork — `{plugin_name}-v{version}`.
    branch: String,
    /// Env var name to consult for the rollback close-PR token.
    /// Captured at run-time so rollback uses the same env contract the
    /// publish path validated.
    token_env_var: Option<String>,
}

/// Decode the `krew_targets` array from
/// [`anodizer_core::PublishEvidence::extra`].
///
/// Returns an empty Vec on any of: missing key, wrong shape, empty
/// array. Rollback treats empty-decode the same as no-evidence and
/// emits the canonical empty-evidence warn.
fn decode_krew_targets(extra: &serde_json::Value) -> Vec<KrewPrTarget> {
    extra
        .get("krew_targets")
        .and_then(|v| serde_json::from_value::<Vec<KrewPrTarget>>(v.clone()).ok())
        .unwrap_or_default()
}

/// Resolve the upstream `<owner>/<repo>` slug for a krew target — mirrors
/// the dispatch logic in `publish_to_krew`: prefer
/// `repository.pull_request.base` when set, else fall back to the
/// canonical kubernetes-sigs/krew-index.
fn resolve_krew_upstream(krew_cfg: &anodizer_core::config::KrewConfig) -> (String, String) {
    if let Some(base) = krew_cfg
        .repository
        .as_ref()
        .and_then(|r| r.pull_request.as_ref())
        .and_then(|pr| pr.base.as_ref())
        && let (Some(o), Some(n)) = (base.owner.as_deref(), base.name.as_deref())
    {
        return (o.to_string(), n.to_string());
    }
    ("kubernetes-sigs".to_string(), "krew-index".to_string())
}

/// Build a [`KrewPrTarget`] for each crate the publisher would run on.
/// Reads config + the live process version so the branch name matches
/// what `publish_to_krew` will push.
fn collect_krew_run_targets(ctx: &Context) -> Vec<KrewPrTarget> {
    let mut out: Vec<KrewPrTarget> = Vec::new();
    let version = ctx.version();
    let selected = &ctx.options.selected_crates;
    for c in &ctx.config.crates {
        if !selected.is_empty() && !selected.contains(&c.name) {
            continue;
        }
        let Some(krew_cfg) = c.publish.as_ref().and_then(|p| p.krew.as_ref()) else {
            continue;
        };
        let Some((fork_owner_raw, _)) =
            crate::util::resolve_repo_owner_name(krew_cfg.repository.as_ref())
        else {
            continue;
        };
        let fork_owner = ctx
            .render_template(&fork_owner_raw)
            .unwrap_or(fork_owner_raw);
        // Plugin-name override mirrors `publish_to_krew`'s resolution.
        let plugin_name_raw = krew_cfg.name.as_deref().unwrap_or(&c.name);
        let plugin_name = ctx
            .render_template(plugin_name_raw)
            .unwrap_or_else(|_| plugin_name_raw.to_string());
        let branch = format!("{}-v{}", plugin_name, version);
        let (upstream_owner, upstream_repo) = resolve_krew_upstream(krew_cfg);
        out.push(KrewPrTarget {
            target: c.name.clone(),
            upstream_owner,
            upstream_repo,
            fork_owner,
            branch,
            token_env_var: Some("KREW_INDEX_TOKEN".to_string()),
        });
    }
    out
}

/// True when the crate has a `publish.krew` block — mirrors the
/// `per_crate!` predicate in `lib.rs` so the publisher iterates
/// exactly the same crate universe.
fn is_krew_per_crate_configured(ctx: &Context, crate_name: &str) -> bool {
    crate::util::all_crates(ctx)
        .into_iter()
        .any(|c| c.name == crate_name && c.publish.as_ref().is_some_and(|p| p.krew.is_some()))
}

/// Message emitted at publisher entry. Names how many crates the publisher
/// is iterating over. Factored into a helper so tests can pin the exact
/// substring an operator scans the log for.
pub(crate) fn run_start_message(selected_total: usize) -> String {
    format!(
        "krew: starting publish for {} selected crate(s)",
        selected_total
    )
}

/// Message emitted when a selected crate has no `publish.krew` block.
/// Replaces what used to be a silent `continue` — operators need to see
/// why a per-crate publish was a no-op rather than guess from a blank log.
pub(crate) fn run_skip_unconfigured_message(crate_name: &str) -> String {
    format!(
        "krew: skipping crate '{}' — no krew config block",
        crate_name
    )
}

/// Message emitted just before delegating to `publish_to_krew`. Anchors
/// the krew activity (plugin manifest render, fork clone, PR submission)
/// to a specific crate in the log so multi-crate workspaces are
/// disambiguatable.
pub(crate) fn run_per_crate_start_message(crate_name: &str) -> String {
    format!("krew: starting per-crate publish for '{}'", crate_name)
}

/// Final summary emitted at publisher exit. `processed` is the count of
/// crates the publisher actually invoked `publish_to_krew` on (not the
/// count of successful PRs — `publish_to_krew` has its own skip paths for
/// skip_upload/dry-run/etc., each of which logs its own status line).
pub(crate) fn run_done_message(processed: usize) -> String {
    format!("krew: completed — {} crate(s) processed", processed)
}

/// Decision predicate for the no-eligible-crates warning. True when the
/// publisher walked the selection but the configured-predicate filtered
/// every crate out — distinct from "ran successfully in dry-run mode".
///
/// `processed` is the count of crates whose `is_krew_per_crate_configured`
/// check passed and whose `publish_to_krew` invocation was reached.
/// `selected_len` is the size of the implicit-all-resolved selection.
pub(crate) fn should_warn_no_eligible(processed: usize, selected_len: usize) -> bool {
    processed == 0 && selected_len > 0
}

/// Warning emitted when the publisher was registered (at least one crate
/// has a `publish.krew` block at the config level) but the run path
/// processed zero crates.
///
/// With the implicit-all default in
/// [`crate::publisher_helpers::effective_publish_crates`], an empty
/// `selected_crates` resolves to every crate carrying a `publish.krew`
/// block — so a zero-processed run means `--crate`/`--all` matrix
/// selection was non-empty AND filtered every krew-configured crate out.
/// Operators must see this — otherwise the publisher's `succeeded` status
/// hides the fact that nothing was pushed.
pub(crate) fn run_no_eligible_crates_warning(selected_total: usize) -> String {
    format!(
        "krew: registered but 0 of {} effective crate(s) had a krew \
         config block — nothing pushed. Check that --crate / --all selects a \
         crate whose publish.krew block is set.",
        selected_total
    )
}

impl anodizer_core::Publisher for KrewPublisher {
    fn name(&self) -> &str {
        Self::PUBLISHER_NAME
    }
    fn group(&self) -> anodizer_core::PublisherGroup {
        Self::PUBLISHER_GROUP
    }
    fn required(&self) -> bool {
        Self::PUBLISHER_REQUIRED
    }
    fn rollback_scope_needed(&self) -> Option<&'static str> {
        Self::ROLLBACK_SCOPE
    }

    fn run(&self, ctx: &mut Context) -> anyhow::Result<anodizer_core::PublishEvidence> {
        let log = ctx.logger("publish");
        let selected =
            crate::publisher_helpers::effective_publish_crates(ctx, is_krew_per_crate_configured);
        log.status(&run_start_message(selected.len()));
        let mut processed = 0usize;
        let mut any_pushed = false;
        for crate_name in &selected {
            // Defensive guard for explicit `--crate=X` selection when X has no
            // publisher block; implicit-all is already filtered by effective_publish_crates above.
            if !is_krew_per_crate_configured(ctx, crate_name) {
                log.status(&run_skip_unconfigured_message(crate_name));
                continue;
            }
            processed += 1;
            log.status(&run_per_crate_start_message(crate_name));
            if publish_to_krew(ctx, crate_name, &log)? {
                any_pushed = true;
            }
        }
        if should_warn_no_eligible(processed, selected.len()) {
            log.warn(&run_no_eligible_crates_warning(selected.len()));
        } else {
            log.status(&run_done_message(processed));
        }
        let mut evidence = anodizer_core::PublishEvidence::new("krew");
        // Only record rollback targets when at least one branch push was made.
        // Phantom evidence causes rollback to close PRs that were never opened
        // (dry-run, skip_upload, no-op NoChanges, bot-template mode).
        if any_pushed {
            let targets = collect_krew_run_targets(ctx);
            evidence.extra = serde_json::json!({ "krew_targets": targets });
        }
        Ok(evidence)
    }

    fn rollback(
        &self,
        ctx: &mut Context,
        evidence: &anodizer_core::PublishEvidence,
    ) -> anyhow::Result<()> {
        let log = ctx.logger("publish");
        let targets = decode_krew_targets(&evidence.extra);
        if targets.is_empty() {
            log.warn(&crate::publisher_helpers::rollback_empty_warning_msg(
                "krew",
                "PR targets",
            ));
            return Ok(());
        }

        // Resolve token at rollback time — never persisted in evidence.
        // Falls back to ANODIZER_GITHUB_TOKEN then GITHUB_TOKEN, same as
        // every git-revert publisher.
        let env = ctx.env_source();
        let resolve_token = |t: &KrewPrTarget| -> Option<String> {
            t.token_env_var
                .as_deref()
                .and_then(|n| env.var(n))
                .or_else(|| env.var("ANODIZER_GITHUB_TOKEN"))
                .or_else(|| env.var("GITHUB_TOKEN"))
        };

        // Fan out at PR granularity, not target granularity: a single
        // krew target can map to multiple open PRs if the publish path
        // pushed the same branch twice (idempotent re-publish). We dedup
        // PR numbers per (upstream, n) so we don't try to close the same
        // PR twice when two targets share the same fork branch.
        struct CloseJob {
            upstream_owner: String,
            upstream_repo: String,
            pr_number: u64,
            token: String,
            target_label: String,
        }
        let mut jobs: Vec<CloseJob> = Vec::new();
        let mut seen: std::collections::BTreeSet<(String, String, u64)> =
            std::collections::BTreeSet::new();
        for t in &targets {
            let Some(token) = resolve_token(t) else {
                log.warn(&format!(
                    "krew: no token resolvable for {} (env var ${} / \
                     ANODIZER_GITHUB_TOKEN / GITHUB_TOKEN all unset); \
                     skipping rollback for this target",
                    t.target,
                    t.token_env_var.as_deref().unwrap_or("KREW_INDEX_TOKEN"),
                ));
                continue;
            };
            let env_hint_for_target = t.token_env_var.as_deref().unwrap_or("KREW_INDEX_TOKEN");
            let pr_numbers = match crate::util::find_open_pr_numbers_for_head(
                &t.upstream_owner,
                &t.upstream_repo,
                &t.fork_owner,
                &t.branch,
                Some(&token),
                env_hint_for_target,
            ) {
                Ok(v) => v,
                Err(e) => {
                    // Auth-failure / repo-not-found / transport problems
                    // surface as actionable warns naming the actual
                    // failure mode — not the misleading "no PR found,
                    // verify manually" that previously fired here.
                    log.warn(&format!(
                        "krew: failed to query upstream {}/{} for open PRs ({}); \
                         {} — manual cleanup required",
                        t.upstream_owner, t.upstream_repo, t.target, e
                    ));
                    continue;
                }
            };
            if pr_numbers.is_empty() {
                log.warn(&format!(
                    "krew: no open PRs found for head={}:{} against {}/{}; \
                     verify manually",
                    t.fork_owner, t.branch, t.upstream_owner, t.upstream_repo,
                ));
                continue;
            }
            for n in pr_numbers {
                let key = (t.upstream_owner.clone(), t.upstream_repo.clone(), n);
                if seen.insert(key) {
                    jobs.push(CloseJob {
                        upstream_owner: t.upstream_owner.clone(),
                        upstream_repo: t.upstream_repo.clone(),
                        pr_number: n,
                        token: token.clone(),
                        target_label: t.target.clone(),
                    });
                }
            }
        }

        let env_hint = targets
            .first()
            .and_then(|t| t.token_env_var.as_deref())
            .unwrap_or("KREW_INDEX_TOKEN");

        // Three-bucket count: (closed, already_closed, failed).
        // `already_closed` is a success bucket — 404 / 410 / 422 from
        // the PATCH means the desired end-state ("PR not open") is
        // already true (maintainer closed it, repo renamed, PR
        // deleted). Re-running --rollback-only after a partial
        // success must NOT surface those as failures.
        let counts = std::sync::Mutex::new((0usize, 0usize, 0usize));
        for chunk in jobs.chunks(crate::util::ROLLBACK_PARALLELISM) {
            std::thread::scope(|s| {
                let mut handles = Vec::with_capacity(chunk.len());
                for job in chunk {
                    let log = log.clone();
                    let counts = &counts;
                    handles.push(s.spawn(move || {
                        let pr_url = format!(
                            "https://github.com/{}/{}/pull/{}",
                            job.upstream_owner, job.upstream_repo, job.pr_number
                        );
                        log.status(&format!(
                            "krew: closing PR {} ({})",
                            job.target_label, pr_url
                        ));
                        let outcome = crate::util::close_pr_via_api(
                            &job.upstream_owner,
                            &job.upstream_repo,
                            job.pr_number,
                            &job.token,
                        );
                        match outcome {
                            crate::util::CloseOutcome::Closed => {
                                let mut c = crate::util::lock_recover(counts, &log, "krew");
                                c.0 += 1;
                            }
                            crate::util::CloseOutcome::AlreadyClosed => {
                                let mut c = crate::util::lock_recover(counts, &log, "krew");
                                c.1 += 1;
                                log.status(&format!(
                                    "krew: PR {} ({}) already closed/deleted upstream — \
                                     rollback noticed the existing state",
                                    job.target_label, pr_url
                                ));
                            }
                            crate::util::CloseOutcome::Failed(err) => {
                                let mut c = crate::util::lock_recover(counts, &log, "krew");
                                c.2 += 1;
                                log.warn(&crate::publisher_helpers::rollback_failure_warning_msg(
                                    "krew",
                                    &job.target_label,
                                    &pr_url,
                                    &err,
                                    Some(env_hint),
                                ));
                            }
                        }
                    }));
                }
                for h in handles {
                    crate::util::join_or_warn(h, &log, "krew");
                }
            });
        }
        // `into_inner` consumes the Mutex; poison here means a worker
        // panicked. Counter state is still valid (3-tuple of usize) so
        // recover and emit the summary rather than abandon the operator.
        let (closed, already_closed, failed) = match counts.into_inner() {
            Ok(c) => c,
            Err(poisoned) => {
                log.warn("krew: mutex poisoned by worker panic; reporting counters as-of poison");
                poisoned.into_inner()
            }
        };
        log.status(&format!(
            "krew: closed {}, already-closed {}, failed {}",
            closed, already_closed, failed
        ));
        Ok(())
    }

    fn preflight(&self, _ctx: &Context) -> anyhow::Result<anodizer_core::PreflightCheck> {
        Ok(anodizer_core::PreflightCheck::Pass)
    }
}

#[cfg(test)]
mod publisher_tests {
    use super::*;
    use anodizer_core::config::{
        CrateConfig, KrewConfig, PublishConfig, RepositoryConfig, StringOrBool,
    };
    use anodizer_core::test_helpers::TestContextBuilder;
    use anodizer_core::{PreflightCheck, PublishEvidence, Publisher, PublisherGroup};

    fn krew_crate(name: &str) -> CrateConfig {
        CrateConfig {
            name: name.to_string(),
            path: ".".to_string(),
            tag_template: "v{{ .Version }}".to_string(),
            publish: Some(PublishConfig {
                krew: Some(KrewConfig {
                    repository: Some(RepositoryConfig {
                        owner: Some("acme".to_string()),
                        name: Some("krew-index-fork".to_string()),
                        ..Default::default()
                    }),
                    short_description: Some("a kubectl plugin".to_string()),
                    description: Some("a kubectl plugin".to_string()),
                    ..Default::default()
                }),
                ..Default::default()
            }),
            ..Default::default()
        }
    }

    #[test]
    fn krew_publisher_classification() {
        let p = KrewPublisher::new();
        assert_eq!(p.name(), "krew");
        assert_eq!(p.group(), PublisherGroup::Manager);
        assert!(!p.required());
        assert_eq!(
            p.rollback_scope_needed(),
            Some("GITHUB_TOKEN pull_request:write")
        );
    }

    #[test]
    fn krew_preflight_defaults_to_pass() {
        let ctx = TestContextBuilder::new().build();
        let p = KrewPublisher::new();
        assert!(matches!(
            p.preflight(&ctx).expect("preflight ok"),
            PreflightCheck::Pass
        ));
    }

    #[test]
    fn krew_rollback_warns_when_no_targets_recorded() {
        let mut ctx = TestContextBuilder::new().build();
        let evidence = PublishEvidence::new("krew");
        let p = KrewPublisher::new();
        assert!(p.rollback(&mut ctx, &evidence).is_ok());

        let msg = crate::publisher_helpers::rollback_empty_warning_msg("krew", "PR targets");
        assert!(msg.starts_with("krew:"), "{msg}");
        assert!(msg.contains("PR targets"), "{msg}");
        assert!(msg.contains("verify"), "{msg}");
        assert!(msg.contains("manually"), "{msg}");
    }

    #[test]
    fn krew_target_extra_roundtrips() {
        let original = vec![KrewPrTarget {
            target: "demo".into(),
            upstream_owner: "kubernetes-sigs".into(),
            upstream_repo: "krew-index".into(),
            fork_owner: "acme".into(),
            branch: "demo-v1.2.3".into(),
            token_env_var: Some("KREW_INDEX_TOKEN".into()),
        }];
        let extra = serde_json::json!({ "krew_targets": original.clone() });
        let decoded = decode_krew_targets(&extra);
        assert_eq!(decoded, original);
    }

    #[test]
    fn krew_target_extra_carries_no_secret_material() {
        // Defense-in-depth: serialize a target and assert no field
        // names that could leak a token / pat are present. Mirrors
        // the credential-handling contract on `PublishEvidence::extra`.
        let t = KrewPrTarget {
            target: "demo".into(),
            upstream_owner: "kubernetes-sigs".into(),
            upstream_repo: "krew-index".into(),
            fork_owner: "acme".into(),
            branch: "demo-v1.2.3".into(),
            token_env_var: Some("KREW_INDEX_TOKEN".into()),
        };
        let s = serde_json::to_string(&t).expect("serialize");
        assert!(!s.contains("\"token\":"), "{s}");
        assert!(!s.contains("\"password\":"), "{s}");
        assert!(!s.contains("\"pat\":"), "{s}");
        // The env-var NAME is fine; values must never appear.
        assert!(s.contains("KREW_INDEX_TOKEN"), "{s}");
    }

    #[test]
    fn krew_effective_publish_crates_implicit_all_when_selection_empty() {
        // Regression pin for the `selected_crates = Vec::new()` failure
        // mode: the run path used to iterate the empty Vec and silently
        // skip every configured krew plugin. The helper now resolves to
        // implicit-all over `publish.krew`-carrying crates.
        let ctx = TestContextBuilder::new()
            .crates(vec![
                krew_crate("alpha"),
                krew_crate("beta"),
                CrateConfig {
                    name: "gamma".to_string(),
                    path: ".".to_string(),
                    tag_template: "v{{ .Version }}".to_string(),
                    publish: Some(PublishConfig::default()),
                    ..Default::default()
                },
            ])
            .build();
        let names =
            crate::publisher_helpers::effective_publish_crates(&ctx, is_krew_per_crate_configured);
        assert_eq!(names, vec!["alpha".to_string(), "beta".to_string()]);
    }

    #[test]
    fn krew_effective_publish_crates_honors_non_empty_selection() {
        let ctx = TestContextBuilder::new()
            .crates(vec![krew_crate("alpha"), krew_crate("beta")])
            .selected_crates(vec!["beta".to_string()])
            .build();
        let names =
            crate::publisher_helpers::effective_publish_crates(&ctx, is_krew_per_crate_configured);
        assert_eq!(names, vec!["beta".to_string()]);
    }

    #[test]
    fn krew_collect_run_targets_uses_default_upstream() {
        let ctx = TestContextBuilder::new()
            .crates(vec![krew_crate("demo")])
            .build();
        let targets = collect_krew_run_targets(&ctx);
        assert_eq!(targets.len(), 1);
        assert_eq!(targets[0].target, "demo");
        assert_eq!(targets[0].upstream_owner, "kubernetes-sigs");
        assert_eq!(targets[0].upstream_repo, "krew-index");
        assert_eq!(targets[0].fork_owner, "acme");
        assert!(
            targets[0].branch.starts_with("demo-v"),
            "branch: {}",
            targets[0].branch
        );
    }

    #[test]
    fn krew_collect_run_targets_honors_pull_request_base_override() {
        use anodizer_core::config::{PullRequestBaseConfig, PullRequestConfig};
        let mut c = krew_crate("demo");
        if let Some(p) = c.publish.as_mut()
            && let Some(k) = p.krew.as_mut()
            && let Some(r) = k.repository.as_mut()
        {
            r.pull_request = Some(PullRequestConfig {
                enabled: Some(true),
                base: Some(PullRequestBaseConfig {
                    owner: Some("custom-org".to_string()),
                    name: Some("custom-index".to_string()),
                    branch: None,
                }),
                draft: None,
                body: None,
            });
        }
        let ctx = TestContextBuilder::new().crates(vec![c]).build();
        let targets = collect_krew_run_targets(&ctx);
        assert_eq!(targets.len(), 1);
        assert_eq!(targets[0].upstream_owner, "custom-org");
        assert_eq!(targets[0].upstream_repo, "custom-index");
    }

    // -----------------------------------------------------------------------
    // Log-message helpers — the operator-facing log strings the publisher
    // emits at each boundary.

    #[test]
    fn run_start_message_names_selected_total() {
        let msg = run_start_message(3);
        assert!(msg.starts_with("krew:"), "{msg}");
        assert!(msg.contains("starting publish"), "{msg}");
        assert!(msg.contains("3 selected"), "{msg}");
    }

    #[test]
    fn run_skip_unconfigured_message_names_crate() {
        let msg = run_skip_unconfigured_message("demo");
        assert!(msg.starts_with("krew:"), "{msg}");
        assert!(msg.contains("skipping crate 'demo'"), "{msg}");
        assert!(msg.contains("no krew config block"), "{msg}");
    }

    #[test]
    fn run_per_crate_start_message_names_crate() {
        let msg = run_per_crate_start_message("demo");
        assert!(msg.starts_with("krew:"), "{msg}");
        assert!(msg.contains("starting per-crate publish"), "{msg}");
        assert!(msg.contains("'demo'"), "{msg}");
    }

    #[test]
    fn run_done_message_reports_processed_count() {
        let msg = run_done_message(2);
        assert!(msg.starts_with("krew:"), "{msg}");
        assert!(msg.contains("completed"), "{msg}");
        assert!(msg.contains("2 crate(s) processed"), "{msg}");
    }

    #[test]
    fn run_no_eligible_crates_warning_names_remediation() {
        let msg = run_no_eligible_crates_warning(5);
        assert!(msg.starts_with("krew:"), "{msg}");
        assert!(msg.contains("registered"), "{msg}");
        assert!(msg.contains("0 of 5 effective"), "{msg}");
        assert!(msg.contains("nothing pushed"), "{msg}");
        assert!(msg.contains("--crate"), "{msg}");
        assert!(msg.contains("--all"), "{msg}");
    }

    /// The no-eligible-crates warning must fire only when the iteration
    /// loop's configured-predicate filtered every selected crate out — not
    /// when the publish path was reached successfully.
    #[test]
    fn should_warn_no_eligible_only_fires_when_predicate_filtered_everything() {
        // One configured crate reached the publish path → no warning.
        assert!(!should_warn_no_eligible(1, 1));
        // True positive: none configured.
        assert!(should_warn_no_eligible(0, 3));
        // Empty selection → no warning.
        assert!(!should_warn_no_eligible(0, 0));
        // Partial-skip → no warning.
        assert!(!should_warn_no_eligible(1, 3));
    }

    /// Run the publisher end-to-end in dry-run mode against a context that
    /// selects a krew-configured crate. Verifies the run path is wired
    /// (returns Ok). The log lines are written to stderr and asserted
    /// indirectly via the helper-string tests above.
    #[test]
    fn krew_publisher_run_dry_run_returns_ok() {
        let mut ctx = TestContextBuilder::new()
            .crates(vec![krew_crate("demo")])
            .selected_crates(vec!["demo".to_string()])
            .dry_run(true)
            .build();
        let p = KrewPublisher::new();
        let evidence = p.run(&mut ctx).expect("dry-run publisher.run");
        // dry-run publish_to_krew short-circuits before branch push; no actual
        // push occurred so evidence.extra must be empty (no phantom targets).
        let targets = decode_krew_targets(&evidence.extra);
        assert!(
            targets.is_empty(),
            "dry-run must not record rollback targets: {targets:?}"
        );
    }

    /// When the publisher is registered (a crate has a krew block) but the
    /// selected-crates filter excludes every krew-configured crate, the run
    /// path must still return Ok and the processed count is zero.
    #[test]
    fn krew_publisher_run_no_eligible_crates_returns_ok() {
        let mut ctx = TestContextBuilder::new()
            .crates(vec![
                krew_crate("demo"),
                CrateConfig {
                    name: "other".to_string(),
                    path: ".".to_string(),
                    tag_template: "v{{ .Version }}".to_string(),
                    publish: Some(PublishConfig::default()),
                    ..Default::default()
                },
            ])
            // Select only the non-krew crate — publisher registered but
            // run path will iterate zero krew-configured crates.
            .selected_crates(vec!["other".to_string()])
            .dry_run(true)
            .build();
        let p = KrewPublisher::new();
        // Must return Ok even when no krew-configured crate is selected.
        p.run(&mut ctx).expect("publisher.run ok");
    }

    /// Implicit-all selection (empty `selected_crates`) + dry-run must
    /// produce empty evidence. The implicit-all path resolves through
    /// `effective_publish_crates` to every krew-configured crate, so this
    /// pins the gate where phantom rollback targets used to leak.
    #[test]
    fn test_publish_to_krew_dry_run_implicit_all_produces_empty_evidence() {
        let mut ctx = TestContextBuilder::new()
            .crates(vec![krew_crate("demo"), krew_crate("other")])
            // No selected_crates → implicit-all resolves to both krew crates.
            .dry_run(true)
            .build();
        let p = KrewPublisher::new();
        let evidence = p.run(&mut ctx).expect("dry-run implicit-all publisher.run");
        let targets = decode_krew_targets(&evidence.extra);
        assert!(
            targets.is_empty(),
            "dry-run + implicit-all must not record rollback targets: {targets:?}"
        );
    }

    /// skip_upload path must produce empty evidence — no branch push occurred.
    #[test]
    fn krew_publisher_run_skip_upload_produces_empty_evidence() {
        let mut crate_with_skip = krew_crate("demo");
        if let Some(ref mut publish) = crate_with_skip.publish
            && let Some(ref mut krew) = publish.krew
        {
            krew.skip_upload = Some(StringOrBool::Bool(true));
        }
        let mut ctx = TestContextBuilder::new()
            .crates(vec![crate_with_skip])
            .selected_crates(vec!["demo".to_string()])
            .build();
        let p = KrewPublisher::new();
        let evidence = p.run(&mut ctx).expect("skip_upload publisher.run");
        let targets = decode_krew_targets(&evidence.extra);
        assert!(
            targets.is_empty(),
            "skip_upload must not record rollback targets: {targets:?}"
        );
    }

    #[test]
    fn krew_publisher_visible_work_contract() {
        use crate::testing::assert_publisher_visible_work_contract;
        let mut ctx = TestContextBuilder::new()
            .crates(vec![krew_crate("demo")])
            .selected_crates(vec!["demo".to_string()])
            .dry_run(true)
            .build();
        let p = KrewPublisher::new();
        assert_publisher_visible_work_contract(&p, &mut ctx);
    }

    /// Building a krew plugin manifest for an artifact whose `sha256`
    /// metadata is empty must bail with an actionable error. Defaulting
    /// to `""` would embed an empty `sha256:` field in the rendered
    /// manifest, which krew's `addURIAndSha` validator rejects at
    /// install time. The bail message must name the publisher, the
    /// field, the offending artifact context, and a next-step hint.
    #[test]
    fn krew_sha256_empty_metadata_bails_with_actionable_error() {
        use anodizer_core::artifact::{Artifact, ArtifactKind};
        use anodizer_core::config::{
            Config, CrateConfig, KrewConfig, PublishConfig, RepositoryConfig,
        };
        use anodizer_core::context::{Context, ContextOptions};
        use anodizer_core::log::{StageLogger, Verbosity};
        let config = Config {
            crates: vec![CrateConfig {
                name: "mytool".to_string(),
                path: ".".to_string(),
                tag_template: "v{{ .Version }}".to_string(),
                publish: Some(PublishConfig {
                    krew: Some(KrewConfig {
                        repository: Some(RepositoryConfig {
                            owner: Some("acme".to_string()),
                            name: Some("krew-index-fork".to_string()),
                            ..Default::default()
                        }),
                        short_description: Some("a kubectl plugin".to_string()),
                        description: Some("a kubectl plugin".to_string()),
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
                ..Default::default()
            }],
            ..Default::default()
        };
        let mut ctx = Context::new(config, ContextOptions::default());
        ctx.artifacts.add(Artifact {
            kind: ArtifactKind::Archive,
            path: std::path::PathBuf::from("/tmp/mytool-linux-amd64.tar.gz"),
            name: "mytool-linux-amd64.tar.gz".to_string(),
            target: Some("x86_64-unknown-linux-gnu".to_string()),
            crate_name: "mytool".to_string(),
            metadata: {
                let mut m = std::collections::HashMap::new();
                m.insert(
                    "url".to_string(),
                    "https://example.com/mytool-linux-amd64.tar.gz".to_string(),
                );
                m.insert("binary".to_string(), "mytool".to_string());
                m
            },
            size: None,
        });
        let log = StageLogger::new("publish", Verbosity::Quiet);
        let err = publish_to_krew(&mut ctx, "mytool", &log).expect_err("missing sha256 must bail");
        let msg = format!("{err:#}");
        assert!(
            msg.contains("krew:") && msg.contains("sha256"),
            "error must name publisher + field; got: {msg}"
        );
        assert!(
            msg.contains("mytool"),
            "error must name the offending crate; got: {msg}"
        );
        assert!(
            msg.contains("dist/artifacts.json") || msg.contains("re-run"),
            "error must include a next-step hint; got: {msg}"
        );
    }
}
