#!/bin/sh
set -eu

# myapp — 
# 
#
# Installer for acme/tool — generated by anodizer.
#
# Usage:
#   curl -fsSL https://github.com/acme/tool/releases/download/<tag>/install.sh | sh
#   VERSION=v1.2.3 sh install.sh   # pin a specific release
#   INSTALL_DIR=~/bin sh install.sh           # override the install directory
#
# The script detects the host OS + architecture, downloads the matching
# release archive, verifies its sha256 checksum, and installs the binary.

REPO="acme/tool"
BASE_URL="https://github.com"
BINARIES="myapp"
INSTALL_DIR="${INSTALL_DIR:-/usr/local/bin}"
VERIFY_CHECKSUM="true"
VERSION="${VERSION:-}"

info() { printf '%s\n' "myapp-install: $*" >&2; }
die() { printf '%s\n' "myapp-install: error: $*" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

usage() {
	cat <<EOF
myapp installer — installs $BINARIES from $REPO releases.

Usage:
  sh ${0##*/} [--help]
  curl -fsSL $BASE_URL/$REPO/releases/latest/download/${0##*/} | sh

Environment:
  VERSION       release to install (default: the latest release);
                accepts a bare version or the full tag, e.g. v1.2.3
  INSTALL_DIR   directory to install into (default: $INSTALL_DIR);
                falls back to \$HOME/.local/bin when it is not writable

Supported platforms: darwin-amd64 darwin-arm64 linux-amd64 linux-arm64 windows-amd64 windows-arm64
EOF
}

# An unknown argument is a typo the user must see: this script has no flags
# beyond --help, and silently ignoring one would install something other than
# what was asked for. The empty arm keeps `curl … | sh` (no arguments) working.
case "${1:-}" in
	-h | --help) usage; exit 0 ;;
	"") ;;
	*) die "unknown argument: $1 (try --help)" ;;
esac

fetch() {
	# fetch <url> <dest>
	if have curl; then
		curl -fsSL "$1" -o "$2"
	elif have wget; then
		wget -qO "$2" "$1"
	else
		die "need curl or wget to download files"
	fi
}

fetch_stdout() {
	# fetch_stdout <url>
	if have curl; then
		curl -fsSL "$1"
	elif have wget; then
		wget -qO- "$1"
	else
		die "need curl or wget to download files"
	fi
}

detect_os() {
	case "$(uname -s)" in
        Linux*) echo "linux" ;;
        Darwin*) echo "darwin" ;;
        MINGW*|MSYS*|CYGWIN*) echo "windows" ;;
		*) echo "unsupported" ;;
	esac
}

detect_arch() {
	case "$(uname -m)" in
        x86_64|amd64) echo "amd64" ;;
        aarch64|arm64) echo "arm64" ;;
		*) echo "unsupported" ;;
	esac
}

install_binary() {
	# install_binary <src-path> <binary-name>
	_src="$1"
	_name="$2"
	dir="$INSTALL_DIR"
	if [ -w "$dir" ]; then
		install -m 0755 "$_src" "$dir/$_name"
	elif have sudo; then
		info "installing to $dir (requires sudo)"
		sudo install -m 0755 "$_src" "$dir/$_name"
	else
		dir="$HOME/.local/bin"
		info "no write access to $INSTALL_DIR and no sudo; installing to $dir"
		mkdir -p "$dir"
		install -m 0755 "$_src" "$dir/$_name"
	fi
	info "installed $_name $version to $dir/$_name"
	# Checked against the directory actually written to, not $INSTALL_DIR: a
	# writable INSTALL_DIR="$HOME/bin" is just as likely to be off PATH as the
	# fallback is.
	case ":$PATH:" in
		*":$dir:"*) ;;
		*) info "note: $dir is not in your PATH; add it to run $_name" ;;
	esac
}

# The GitHub REST API base: github.com is served from api.github.com; a
# GitHub Enterprise base is served from <base>/api/v3.
if [ "$BASE_URL" = "https://github.com" ]; then
	API_BASE="https://api.github.com"
else
	API_BASE="$BASE_URL/api/v3"
fi

if [ -z "$VERSION" ]; then
	info "resolving latest release of $REPO"
	body=$(fetch_stdout "$API_BASE/repos/$REPO/releases/latest") \
		|| die "failed to query the latest release of $REPO"
	VERSION=$(printf '%s\n' "$body" |
		grep -m1 '"tag_name"' |
		sed -e 's/.*"tag_name"[[:space:]]*:[[:space:]]*"//' -e 's/".*//')
	[ -n "$VERSION" ] || die "could not determine the latest release of $REPO"
fi

# The bare version (tag prefix stripped) names the asset; the tag names the
# release. Stripping the configured prefix accepts both `v1.2.3`
# and a bare `1.2.3` in VERSION.
version="${VERSION#v}"
tag="v${version}"

# Assigned here (not in the prologue) because the checksums filename embeds
# ${version}, which is only known after the version is resolved above.
CHECKSUMS="myapp_${version}_checksums.txt"

OS="$(detect_os)"
ARCH="$(detect_arch)"

# FORMAT is baked into each arm by the engine alongside the asset name, so the
# extraction step never has to re-derive a format from the filename — a
# `binary`-format asset carries no extension at all.
ARCHIVE=""
FORMAT=""
case "${OS}-${ARCH}" in
    darwin-amd64)
        ARCHIVE="myapp_${version}_darwin_amd64.tar.gz"
        FORMAT="tar.gz"
        ;;
    darwin-arm64)
        ARCHIVE="myapp_${version}_darwin_arm64.tar.gz"
        FORMAT="tar.gz"
        ;;
    linux-amd64)
        ARCHIVE="myapp_${version}_linux_amd64.tar.gz"
        FORMAT="tar.gz"
        ;;
    linux-arm64)
        ARCHIVE="myapp_${version}_linux_arm64.tar.gz"
        FORMAT="tar.gz"
        ;;
    windows-amd64)
        ARCHIVE="myapp_${version}_windows_amd64.zip"
        FORMAT="zip"
        ;;
    windows-arm64)
        ARCHIVE="myapp_${version}_windows_arm64.zip"
        FORMAT="zip"
        ;;
	*) die "no prebuilt binary for ${OS}-${ARCH} (supported: darwin-amd64 darwin-arm64 linux-amd64 linux-arm64 windows-amd64 windows-arm64)" ;;
esac

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT INT TERM

base="$BASE_URL/$REPO/releases/download/$tag"

info "downloading $ARCHIVE"
fetch "$base/$ARCHIVE" "$tmp/$ARCHIVE" || die "failed to download $ARCHIVE"

if [ "$VERIFY_CHECKSUM" = "true" ]; then
	# Prefer the combined checksums file; fall back to a per-asset .sha256 sidecar.
	expected=""
	if fetch "$base/$CHECKSUMS" "$tmp/$CHECKSUMS" 2>/dev/null; then
		expected=$(awk -v f="$ARCHIVE" '$2 == f { print $1 }' "$tmp/$CHECKSUMS" | head -n1)
	fi
	if [ -z "$expected" ] && fetch "$base/$ARCHIVE.sha256" "$tmp/$ARCHIVE.sha256" 2>/dev/null; then
		expected=$(awk '{ print $1 }' "$tmp/$ARCHIVE.sha256" | head -n1)
	fi
	[ -n "$expected" ] || die "no checksum published for $ARCHIVE"

	if have sha256sum; then
		actual=$(sha256sum "$tmp/$ARCHIVE" | awk '{ print $1 }')
	elif have shasum; then
		actual=$(shasum -a 256 "$tmp/$ARCHIVE" | awk '{ print $1 }')
	else
		die "need sha256sum or shasum to verify the download"
	fi

	[ "$expected" = "$actual" ] ||
		die "checksum mismatch for $ARCHIVE (expected $expected, got $actual)"
	info "checksum verified"
fi

info "extracting $ARCHIVE"
case "$FORMAT" in
	tar.gz | tgz) tar -xzf "$tmp/$ARCHIVE" -C "$tmp" ;;
	tar.xz | txz)
		have xz || die "need xz to extract $ARCHIVE"
		tar -xJf "$tmp/$ARCHIVE" -C "$tmp"
		;;
	tar.zst | tzst)
		# --use-compress-program, not --zstd: the latter is GNU-tar only.
		have zstd || die "need zstd to extract $ARCHIVE"
		tar --use-compress-program=zstd -xf "$tmp/$ARCHIVE" -C "$tmp"
		;;
	tar) tar -xf "$tmp/$ARCHIVE" -C "$tmp" ;;
	zip)
		have unzip || die "need unzip to extract $ARCHIVE"
		unzip -q "$tmp/$ARCHIVE" -d "$tmp"
		;;
	gz)
		# A single-file format holds the executable itself, so it is renamed to
		# the binary the loop below looks for. The generator refuses these
		# formats unless exactly one binary is installed, so $BINARIES is one word.
		have gunzip || die "need gunzip to extract $ARCHIVE"
		gunzip -c "$tmp/$ARCHIVE" > "$tmp/$BINARIES"
		;;
	xz)
		have xz || die "need xz to extract $ARCHIVE"
		xz -dc "$tmp/$ARCHIVE" > "$tmp/$BINARIES"
		;;
	# A name_template that names the binary makes the downloaded asset and the
	# install source one path, and cp refuses to copy a file onto itself.
	binary) [ "$ARCHIVE" = "$BINARIES" ] || cp "$tmp/$ARCHIVE" "$tmp/$BINARIES" ;;
	*) die "unknown archive format: $FORMAT ($ARCHIVE)" ;;
esac

for BINARY in $BINARIES; do
	bin=$(find "$tmp" -type f -name "$BINARY" | head -n1)
	[ -n "$bin" ] || die "binary $BINARY not found inside $ARCHIVE"
	chmod +x "$bin"
	install_binary "$bin" "$BINARY"
done
